#!/bin/sh

# socketrun.cc: Start a distributed process using socket connections
#
# @copyright (c) 2008 ASKAP, All Rights Reserved.
# @author Ger van Diepen <diepen AT astron nl>
#
# $Id$


# This script starts a distributed process to process a datasets.
# The processes will use sockets for communication.
#
# run as:  socketrun dry hfn port logfile program [arg1 arg2 ...]

dry=$1
shift
hfn=$1
shift
port=$1
shift
logfile=$1
shift
program=$1
shift

np=`wc -l $hfn | awk '{print $1}'`

# The first host is the master one.
masterhost=
pidlist=
rank=0
for inline in `cat $hfn`
do
  host=`echo $inline | sed -e 's%#.*%%'`
  part=`echo $inline | sed -e 's%.*#%%'`
  if test "$masterhost" = ""; then
    masterhost=$host
  fi
  echo "ssh $host $program socket $masterhost $port $np $rank $part" "$@"
  if test $dry = 0; then
    if test "$logfile" = ""; then
      ssh -x -n $host $program socket $masterhost $port $np $rank $part "$@" &
    else
      ssh -x -n $host $program socket $masterhost $port $np $rank $part "$@" > $logfile-$rank 2>&1 &
    fi
    pidlist="$pidlist $!"
  fi
  rank=`expr $rank + 1`
done

status=0
for pid in $pidlist
do
  if ! wait $pid; then
    status=1
  fi
done

exit $status
