#!/bin/bash

# lofar
[ -r ${INSTALLDIR}/lofar/lofarinit.sh ] && source ${INSTALLDIR}/lofar/lofarinit.sh
export PATH PYTHONPATH LD_LIBRARY_PATH LOFARROOT

# qpid
source ${INSTALLDIR}/qpid/.profile

# python-casacore
export PYTHONPATH=${PYTHONPATH}:${INSTALLDIR}/python-casacore/lib/python2.7/site-packages

# casacore
export PATH=${PATH}:${INSTALLDIR}/casacore/bin
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${INSTALLDIR}/casacore/lib
