#!/bin/sh

../../../../ParmDB/build/gnu_debug/src/parmdb <<EOF > /dev/null
 create tablename='tParmFacade_tmp.mep'
 add parm1 domain=[1,5,4,10],values=2
 add parm2 domain=[1,5,4,10],values=[2,0.1],nx=2
 adddef parm3 type='parmexpr',expr='parm1*parm2'
 adddef parm4 type='parmexpr',expr='parm2*parm3'
 quit
EOF
sleep 1
../../../../ParmDB/build/gnu_debug/src/parmdb <<EOF > /dev/null
 open tablename='tParmFacade_tmp.mep'
 add parm2 domain=[1,5,4,10],values=[2.1,0.15],nx=2,parentid=2
 add parm2 domain=[1,5,10,12],values=[-3,-0.01,0.02],ny=3,parentid=2
 quit
EOF

$LOFAR_CHECKTOOL tParmFacade tParmFacade_tmp.mep
$LOFAR_CHECKTOOL tParmFacade tParmFacade_tmp.mep '*' 0
