global HBtnColorBar_carte;
global HColorMap_carte5;
global HMainFig_carte5 ;
global HCarteFig5 ;
global HTimeFig5 ;
global HThreeDFig5 ;
global HSpecgramFig5;
global HistoFig5 ;
global HDspfig5;
global Contrl_donnee5;
global Contrl_seuil5
global Contrl_Actives5;
global numero_donnee5;
global echantillonnage;
global Fig_VarDonnee5;
global Contrl_freq5;
global NbClasse;
global proba;
global Action5;
global Contrl_donnee5;

%visua1=get(Contrl_freq,'string');
%selected = get(Contrl_freq,'Value');
%visua1=visua1(:,2);
%numero_donnee = visua1(selected)/echantillonnage;
%disp(['numero_donnee :' num2str(visua)']);
%global numero;
%==================================
%define general aspects
FrameWidth = 0.12; 

LeftBorder = 0.05; BottomBorder=0.05; 
TotalWidth = 1 - 3*LeftBorder-FrameWidth ; TotalHeight = 1-2*BottomBorder;
FigSpace = 0.05;
Col1Width = 0.3*TotalWidth;
Col2Width = TotalWidth-Col1Width-FigSpace;
Lin1Height = 0.3*TotalHeight;
Lin2Height= TotalHeight-Lin1Height-FigSpace;

FrameBorder = 0.01;
LeftFrameBorder = LeftBorder + Col1Width+Col2Width+2*FigSpace;
FrameHeight = TotalHeight;
CompBackGroundColor = [0.5 0.5 0.5];

arg_acpplan1=1;
arg_acpplan2=2;

%create figure 1 and set its attributs
MainFigPos_carte = [ 5 35 1017 663];
shh = get(0,'ShowHiddenHandles');
set(0,'ShowHiddenHandles','on')
%Figure principale
HMainFig_carte5 = figure(...
   'Name',['Carte dans le plan ' num2str(arg_acpplan1) '-' num2str(arg_acpplan2) ''], ...
   'handlevisibility','callback',...
   'IntegerHandle','off',...
   'NumberTitle','off',...
   'Tag','MainFig',...
   'position',MainFigPos_carte);

 %==================================
 % Set up main axes of MainFig
 axes( ...
    'Units','normalized', ...
    'Position',[LeftBorder BottomBorder TotalWidth TotalHeight]);
 
 set(HMainFig_carte5,'defaultaxesposition',[LeftBorder BottomBorder TotalWidth TotalHeight])
 
 %==================================
 % Define 3D subplot properties
 %Fig_VarDonnee5 = subplot(2,2,1);
 %set(gca, ...
 %   'Units','normalized', ...
 %   'Position',[LeftBorder BottomBorder+Lin2Height+FigSpace Col1Width Lin1Height]);

 %==================================
 
 % Define time plot

HTimeFig5 = subplot(2,2,2);
 set(gca, ...
    'Units','normalized', ...
    'Position',[0*LeftBorder+0*Col1Width+FigSpace BottomBorder+Lin2Height+FigSpace Col2Width*1.5 Lin1Height]);
%==================================
 % Define dsp plot
HSpecgramFig5 = subplot(2,2,3);
 set(gca, ...
    'Units','normalized', ...
    'Position',[LeftBorder BottomBorder Col1Width*1.4 Lin2Height]);
%==================================
 % Define specgram plot
HCarteFig5= subplot(2,2,4);
 set(gca, ...
    'Units','normalized', ...
    'Position',[2.5*LeftBorder+Col1Width+FigSpace  BottomBorder Col2Width*0.72 Lin2Height]);
 
 %====================================
 % Information for all buttons (and menus)
 CompHeight = 0.03;

 % Spacing between the button and the next command's label
 CompSpace = 0.02;
 
%====================================
% The CONSOLE frame

frmPos=[LeftFrameBorder BottomBorder FrameWidth*1.2 FrameHeight ];
h=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frmPos, ...
   'BackgroundColor',CompBackGroundColor );

% First Frame Component attributs

CompLeft = LeftFrameBorder + FrameBorder;
CompBottom = FrameHeight - FrameBorder - CompHeight;
CompWidth = FrameWidth - 2*FrameBorder;

% Affichage label 
CompPos = [CompLeft*0.07 CompBottom*0.735 CompWidth*1.3 CompHeight*0.75];
h = uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',CompPos, ...
   'Horiz','left', ...
   'String',['Carte acp plan : ' num2str(arg_acpplan1) '-' num2str(arg_acpplan2) ''], ...
   'Interruptible','off', ...
   'BackgroundColor',CompBackGroundColor , ...
   'ForegroundColor','white');

CompPos5 = [CompLeft*0.48 CompBottom*0.735 CompWidth*2.5 CompHeight*0.75];
h = uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',CompPos5, ...
   'Horiz','left', ...
   'String','Plan temps fréquence des données selectionnées', ...
   'Interruptible','off', ...
   'BackgroundColor',CompBackGroundColor , ...
   'ForegroundColor','white');

CompPos6 = [CompLeft*0.45 CompBottom*1.105 CompWidth*1.8 CompHeight*0.75];
h = uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',CompPos6, ...
   'Horiz','left', ...
   'String','Profil temporelle de la donnee :', ...
   'Interruptible','off', ...
   'BackgroundColor',CompBackGroundColor , ...
   'ForegroundColor','white');

CompPos7 = [CompLeft CompBottom CompWidth CompHeight];
h = uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',CompPos7, ...
   'Horiz','left', ...
   'String','Classe :', ...
   'Interruptible','off', ...
   'BackgroundColor',CompBackGroundColor , ...
   'ForegroundColor','white');

CompPos8 =[];
CompPos8 = [CompLeft 1.05*CompBottom CompWidth CompHeight];
h = uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',CompPos8, ...
   'Horiz','left', ...
   'String','Seuil Proba :', ...
   'Interruptible','off', ...
   'BackgroundColor',CompBackGroundColor , ...
   'ForegroundColor','white');

CompPos10 =[];
CompPos10 = [CompLeft 0.9*CompBottom CompWidth CompHeight];
h = uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',CompPos10, ...
   'Horiz','left', ...
   'String','Donnée :', ...
   'Interruptible','off', ...
   'BackgroundColor',CompBackGroundColor , ...
   'ForegroundColor','white');

ComPos11=[];
ComPos11=[CompLeft+0.5*FrameWidth-FrameBorder 0.91*CompBottom CompWidth*0.5 CompHeight*0.7];
Contrl_donnee5=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPos11, ...
   'String','1');
%'Min','0','Max','1');



CompPos4 = [CompLeft CompBottom*0.70 CompWidth CompHeight];
h = uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',CompPos4, ...
   'Horiz','left', ...
   'String','Probabilité :', ...
   'Interruptible','off', ...
   'BackgroundColor',CompBackGroundColor , ...
   'ForegroundColor','white');






% Action Btn
CompWidth = 0.5*FrameWidth - FrameBorder;
CompPos = [CompLeft+0.15*FrameWidth-FrameBorder CompBottom*0.8 CompWidth*1.5 CompHeight*2];
callbackStr='display_proba';
Action5=uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',CompPos, ...
   'String','Action', ...
   'Callback',callbackStr);

%==================================
%Appel pour la DSP


ComPos2=[];
ComPos2=[CompLeft+0.009*FrameWidth-FrameBorder 0.2*CompBottom CompWidth*2.8 CompHeight*14];
Contrl_Actives5=uicontrol( ...
   'Style','listbox', ...
   'Units','normalized', ...
   'Position',ComPos2, ...
   'String','bonjour','Callback','reader_freq5');

numero_donnee=2;
echantillonnage=10;
%Appel pour la DSP
ComPos3=[];
ComPos3=[CompLeft+0.5*FrameWidth-FrameBorder 1.*CompBottom CompWidth*0.8 CompHeight];
Contrl_Classe5=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',ComPos3, ...
   'String','1');
   %'Min','1','Max',NbClasse);

ComPos9=[];
ComPos9=[CompLeft+0.6*FrameWidth-FrameBorder 1.05*CompBottom CompWidth*0.8 CompHeight];
Contrl_seuil5=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',ComPos9, ...
   'String','0');
%'Min','0','Max','1');





%reader_Proba;