global HBtnColorBar_carte;
global HColorMap_carte;
global HMainFig_carte ;
global HCarteFig ;
global HTimeFig_Donnee ;
global HThreeDFig ;
global HistoFig ;
global Contrl_Donnee;
global Contrl_Actives;
global numero_donnee;
global echantillonnage;
global Fig_VarDonnee;
global range;
global fichier;
global Contrl_freq;


visua1=str2num(get(Contrl_freq,'string'));
selected = get(Contrl_freq,'Value');
visua1=visua1(:,2);
numero_donnee = visua1(selected)/echantillonnage;
%disp(['numero_donnee :' num2str(visua)']);
%global numero;
%==================================
%define general aspects
FrameWidth = 0.12; 

LeftBorder = 0.05; BottomBorder=0.05; 
TotalWidth = 1 - 3*LeftBorder-FrameWidth ; TotalHeight = 1-2*BottomBorder;
FigSpace = 0.05;
Col1Width = 0.3*TotalWidth;
Col2Width = TotalWidth-Col1Width-FigSpace;
Lin1Height = 0.3*TotalHeight;
Lin2Height= TotalHeight-Lin1Height-FigSpace;

FrameBorder = 0.01;
LeftFrameBorder = LeftBorder + Col1Width+Col2Width+2*FigSpace;
FrameHeight = TotalHeight;
CompBackGroundColor = [0.5 0.5 0.5];



%create figure 1 and set its attributs
MainFigPos_carte = [ 5 35 1017 663];
shh = get(0,'ShowHiddenHandles');
set(0,'ShowHiddenHandles','on')
%Figure principale
HMainFig_carte = figure(...
   'Name',['Carte dans le plan ' num2str(arg_acpplan1) '-' num2str(arg_acpplan2) ''], ...
   'handlevisibility','callback',...
   'IntegerHandle','off',...
   'NumberTitle','off',...
   'Tag','MainFig',...
   'position',MainFigPos_carte);

 %==================================
 % Set up main axes of MainFig
 axes( ...
    'Units','normalized', ...
    'Position',[LeftBorder BottomBorder TotalWidth TotalHeight]);
 
 set(HMainFig_carte,'defaultaxesposition',[LeftBorder BottomBorder TotalWidth TotalHeight])
 
 %==================================
 % Define 3D subplot properties
 Fig_VarDonnee = subplot(2,2,1);
 set(gca, ...
    'Units','normalized', ...
    'Position',[LeftBorder BottomBorder+Lin2Height+FigSpace Col1Width Lin1Height]);

 %==================================
% Define time plot

 HTimeFig_Donnee = subplot(2,2,2);
 set(gca, ...
    'Units','normalized', ...
    'Position',[LeftBorder+Col1Width+FigSpace BottomBorder+Lin2Height+FigSpace Col2Width Lin1Height]);
%==================================
 % Define dsp plot
 HistoFig = subplot(2,2,3);
 set(gca, ...
    'Units','normalized', ...
    'Position',[LeftBorder BottomBorder Col1Width Lin2Height]);
%==================================
 % Define specgram plot
 HCarteFig = subplot(2,2,4);
 set(gca, ...
    'Units','normalized', ...
    'Position',[LeftBorder+Col1Width+FigSpace  BottomBorder Col2Width Lin2Height]);
 
 %====================================
 % Information for all buttons (and menus)
 CompHeight = 0.03;

 % Spacing between the button and the next command's label
 CompSpace = 0.02;
 
%====================================
% The CONSOLE frame

frmPos=[LeftFrameBorder BottomBorder FrameWidth*1.2 FrameHeight ];
h=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frmPos, ...
   'BackgroundColor',CompBackGroundColor );

% First Frame Component attributs

CompLeft = LeftFrameBorder + FrameBorder;
CompBottom = FrameHeight - FrameBorder - CompHeight;
CompWidth = FrameWidth - 2*FrameBorder;

% Affichage label 
CompPos = [CompLeft*0.07 CompBottom*1.105 CompWidth*1.3 CompHeight*0.75];
h = uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',CompPos, ...
   'Horiz','left', ...
   'String','Variance des neurones :', ...
   'Interruptible','off', ...
   'BackgroundColor',CompBackGroundColor , ...
   'ForegroundColor','white');

CompPos5 = [CompLeft*0.07 CompBottom*0.735 CompWidth*1.3 CompHeight*0.75];
h = uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',CompPos5, ...
   'Horiz','left', ...
   'String','Activation des neurones :', ...
   'Interruptible','off', ...
   'BackgroundColor',CompBackGroundColor , ...
   'ForegroundColor','white');

CompPos6 = [CompLeft*0.45 CompBottom*1.105 CompWidth*1.8 CompHeight*0.75];
h = uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',CompPos6, ...
   'Horiz','left', ...
   'String','Profil temporelle de la donnee :', ...
   'Interruptible','off', ...
   'BackgroundColor',CompBackGroundColor , ...
   'ForegroundColor','white');

CompPos7 = [CompLeft CompBottom CompWidth CompHeight];
h = uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',CompPos7, ...
   'Horiz','left', ...
   'String','donnée :', ...
   'Interruptible','off', ...
   'BackgroundColor',CompBackGroundColor , ...
   'ForegroundColor','white');

% Environnement label
CompBottom = CompBottom - CompHeight - CompSpace;
CompPos = [CompLeft CompBottom CompWidth CompHeight];
h = uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',CompPos, ...
   'Horiz','left', ...
   'String','Environnement :', ...
   'Interruptible','off', ...
   'BackgroundColor',CompBackGroundColor , ...
   'ForegroundColor','white');


CompPos4 = [CompLeft CompBottom*0.85 CompWidth CompHeight];
h = uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',CompPos4, ...
   'Horiz','left', ...
   'String','Activation :', ...
   'Interruptible','off', ...
   'BackgroundColor',CompBackGroundColor , ...
   'ForegroundColor','white');






% Save Btn
CompWidth = 0.5*FrameWidth - FrameBorder;
CompPos = [CompLeft+0.5*FrameWidth-FrameBorder CompBottom*0.95 CompWidth CompHeight];
CompStr='Save';
callbackStr='reader1_save';
HBtnSave=uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',CompPos, ...
   'String',CompStr, ...
   'Callback',callbackStr);

%==================================
%Appel pour la DSP

ecrire={};
ecrire1=[];
range=[];
resultat_Activation1=[];
resultat_Activation=[];
A=fichier{numero_donnee};

A=str2num(A);
hep=2;
while(hep+1<=length(A))
resultat_Activation1=[numero_donnee,A(hep),A(hep+1)];    
resultat_Activation=[resultat_Activation;resultat_Activation1];
hep=hep+2;
end
    
range=sortrows(resultat_Activation,3);
range=flipud(range);

for i=1:length(range(:,3))
ecrire1=['N:' num2str(range(i,2)) ' - As :' num2str(range(i,3)) '']; 
ecrire{i}=ecrire1;
end

ComPos2=[];
ComPos2=[CompLeft+0.009*FrameWidth-FrameBorder 0.32*CompBottom CompWidth*2.8 CompHeight*14];
Contrl_Actives=uicontrol( ...
   'Style','listbox', ...
   'Units','normalized', ...
   'Position',ComPos2, ...
   'String',ecrire);

%Appel pour la DSP
ComPos3=[];
ComPos3=[CompLeft+0.5*FrameWidth-FrameBorder 1.07*CompBottom CompWidth*0.8 CompHeight*0.7];
Contrl_Donnee=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPos3, ...
   'String',num2str(numero_donnee*echantillonnage));

reader_Carte;