#!/bin/bash
# 
# Start an OTB Server instance
#
# The default portnumbers for clients is 12500; provide another port
# by using commandline switch -p
# The default host for OTDB postgres server is sas001; change with 
# commandline switch -s
#

function info()
{
  echo "Usage: $0 [-p portnumber] [-s OTDBserver]"
  echo "  portnumber: port that the server listens to. The default "
  echo "              portnumbers for clients is 12500"
  echo "  OTDBserver: hostname of server where OTDB postgresql server runs"
  echo "              Default is sas001"
}

OTDB_host=sas001
port=12500
while getopts  "p:s:h" flag
do
   case "$flag" in
   p)
   port=$OPTARG
   ;;
   s)
   OTDB_host=$OPTARG
   ;;
   h) 
   info
   exit 0
   ;;
   *)
   info
   exit 0
   ;;
   esac
done

OTB_DIR=/opt/sas/otb/server
export JAVA_HOME=/usr/java/jdk1.7.0_02

echo
echo --- Starting OTB Server using: ---
echo --- OTDB Host: $OTDB_host  
echo --- Server port: $port

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${OTB_DIR}/lib
OTB_APP=$OTB_DIR/`basename $OTB_DIR/jOTDB3*.jar`
export CLASSPATH=$OTB_APP

serverpid=0
ps -ef | grep -v grep | grep java | grep server | grep $port 2>&1 1>/dev/null
if [ $? -ne 0 ]; then
    echo
    echo --- Starting OTB Server

    for JAR_DEPENDENCY in $OTB_DIR/lib/*.jar
    do
	echo -- Adding `basename $JAR_DEPENDENCY` dependency to Java Classpath
	export CLASSPATH=$CLASSPATH:$JAR_DEPENDENCY
    done
    let oport=$port+1
    curdate=`date +%Y%m%dT%H%M%S`
    $JAVA_HOME/bin/java -cp $CLASSPATH nl.astron.lofar.sas.otb.jotdb3.jOTDBserver -s $OTDB_host -d $OTDB_host -p $port -o $oport 1>/localhome/log/OTBServer_${curdate}.log 2>&1 & 
    serverpid=$!
    echo OTB Server started [${serverpid}]. Logfile is /localhome/log/OTBServer_${curdate}.log
else
    serverpid=`ps -ef | grep -v grep | grep java | grep server | grep $port | awk '{print $2}'`
    echo OTB server already running [$serverpid]
    exit 0
fi

exit $serverpid
