#!/bin/sh

# rundist-part: The rundist part run in a distributed way
#
# Copyright (C) 2009
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$

# This script is sarted by rundist by means of startdistproc/socketrun.
# It setups the environment for the distributed process and sets working directory.
# Thereafter the program is started with arguments:
# 1.  rank (0-relative)
# 2.  name of dataset part to process
# >2 extra arguments given


if test $# -lt 11; then
  echo "run as:  rundist-part 'socket' masterhost masterport nproc rank"
  echo "                      img-part filesys img-part-vds envfile"
  echo "                      prog wd [arg]"
  exit 1
fi

shift
shift
shift
shift
rank=$1
shift
dataset=$1
shift
shift
shift
envfile=$1
shift
prog=$1
shift
wd=$1
shift


# Initialize environment.
if test "$envfile" != ""; then
  . $envfile
fi

# Set the working directory.
test "$wd" = ""  ||  wd=`dirname dataset`
cd $wd

# Start the program with its arguments.
$prog $rank $dataset "$@"
