#!/bin/sh

STATIONS="4 6 16 24"
NR_SUBBAND_SAMPLES="196608"

for NR_STATIONS in $STATIONS; do
  ( 
    mkdir -p CS1_BGLProc/build/xlc_bgl
    cd CS1_BGLProc/build/xlc_bgl
    make clean
    make check EXTRA_CPPFLAGS="-DNR_STATIONS=$NR_STATIONS -DNR_SUBBAND_SAMPLES=$NR_SUBBAND_SAMPLES"
    cp src/CS1_BGL_Processing ../../../../../../installed/xlc_bgl/bin/CS1_BGL_Processing.$NR_STATIONS
  )

done
