# -- DataProducts --
#
# $Id: DataProducts.comp 9343 2006-09-28 13:10:40Z blaakmeer $
#
# --DataProducts Global--
#
#      name              vers   qual        constr.            descr.
#--------------------------------------------------------------------------------------------------------
node   DataProducts        	 4.0.0  development 'node constraint'  "DataProducts"

#    name                    dir. type   unit   prun. vm   value         constr.  descr.
#--------------------------------------------------------------------------------------------------------
par  measurementSets         IO    vtext   -      10    0  '[]'		 -        'Names of the measurement sets'
