#! /bin/bash
#
# chkconfig: 2345 90 10
# description: foremand is a daemon that is part of the LOFAR system health management system. it takes \
#              care of starting/stopping/killing jobs on client nodes.
# processname: foremand
# config: /etc/lofar-shm/client.conf
# pidfile: /var/run/foremand.pid

# TODO: need to make sure start-up is after network and pgsql (and stop before).
# see /usr/share/doc/initscripts-[..]/sysvinitfiles for more info on red hat init scripts.

# source the function library
. /etc/init.d/functions

prog="foremand"

start() {
	echo -n $"Starting $prog: "
	daemon $prog -d -v
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	killproc $prog
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
	return $RETVAL
}	

stat() {
	status $prog
}	

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		start
		;;
	status)
		stat
		;;
	condrestart)
		[ -f /var/lock/subsys/$prog ] && stop && start || :
		;;
	*)
		echo $"Usage: $0 {start|stop|condrestart|restart|reload|status}"
		exit 1
		;;
esac
