#!/bin/sh

# Add . to PATH.
PATH=.:$PATH
export PATH

# Set srcdir if undefined (if run outside 'make check')
if test "$srcdir" = ""; then
  srcdir=../../../src
fi

# Create directories to create the parmdb-s in.
# They must match the FileName in in_ms*.vds.
rm -rf tsetupparmdb_tmp.ms0
rm -rf tsetupparmdb_tmp.ms1
rm -rf tsetupparmdb_tmp.ms2
mkdir tsetupparmdb_tmp.ms0
mkdir tsetupparmdb_tmp.ms1
mkdir tsetupparmdb_tmp.ms2

# Enclose output in angle brackets to exclude it from the assay diff.
echo ">>>"
$srcdir/../src/setupparmdb tsetupparmdb.in_vd sourcecat "" tsetupparmdb.in_cd `pwd` tsetupparmdb_tmp.log dry tsetupparmdb_tmp.hfn
echo "<<<"

# Append the three log files to the output.
# Wait for the subprocesses to finish.
sleep 5
grep -v 'log4cxx:' tsetupparmdb_tmp.log-0
grep -v 'log4cxx:' tsetupparmdb_tmp.log-1
grep -v 'log4cxx:' tsetupparmdb_tmp.log-2

# Remove the temporary parset part files.
rm -f tsetupparmdb.parset.part*
