#!/bin/sh

# Set srcdir if undefined (if run outside 'make check')
if test "$srcdir" = ""; then
  srcdir=../../../src
fi

# Create directories to create the parmdb-s in.
# They must match the FileName in in_ms*.vds.
rm -rf tsetupparmdb_tmp.ms0
rm -rf tsetupparmdb_tmp.ms1
rm -rf tsetupparmdb_tmp.ms2
mkdir tsetupparmdb_tmp.ms0
mkdir tsetupparmdb_tmp.ms1
mkdir tsetupparmdb_tmp.ms2

# Combine the vds files.
combinevds tsetupparmdb_tmp.vd tsetupparmdb.in_ms{0,1,2}.vds

# Enclose output in angle brackets to exclude it from the assay diff.
echo ">>>"
$srcdir/../src/setupparmdb -overwrite tsetupparmdb_tmp.vd "" "" "" tsetupparmdb_tmp.log 0 tsetupparmdb_tmp.hfn `pwd`
echo "<<<"

# Append the three log files to the output.
# Wait for the subprocesses to finish.
sleep 5
grep -v 'log4cxx:' tsetupparmdb_tmp.log-0
grep -v 'log4cxx:' tsetupparmdb_tmp.log-1
grep -v 'log4cxx:' tsetupparmdb_tmp.log-2

# Check if the three parmdbs and overall VDS exist.
test -d tsetupparmdb_tmp.ms0/instrument  ||  exit 1
test -d tsetupparmdb_tmp.ms1/instrument  ||  exit 1
test -d tsetupparmdb_tmp.ms2/instrument  ||  exit 1
test -e tsetupparmdb_tmp.instrument  ||  exit 1
