/*
 * BBSStepOperationPanelSolveImpl.java
 *
 * Created on August 18, 2006, 12:25 PM
 */

package nl.astron.lofar.sas.otbcomponents.bbs.stepmanagement.operations;

import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import nl.astron.lofar.sas.otbcomponents.bbs.stepmanagement.BBSStepData;

/**
 *
 * @author  pompert
 */
public class BBSStepOperationPanelSolveImpl extends javax.swing.JPanel implements IBBSStepOperationPanel{
    
    /** Creates new form BBSStepOperationPanelSolveImpl */
    public BBSStepOperationPanelSolveImpl() {
        initComponents();
    }
    
    public void setBBSStepContent(BBSStepData stepData,BBSStepData inheritedData){
        if(stepData!=null){
            String operationName = stepData.getOperationName();
            
        }
    }
    
    
    public HashMap<String,String> getBBSStepOperationAttributes(){
        return null;
    }
    
    public boolean validateInput(){
        return true;
    }
    
    private String createList(JList aListComponent,boolean createQuotes) {
        String aList="[";
        if (aListComponent.getModel().getSize() > 0) {
            if(createQuotes){
                aList += "\"";
            }
            aList += (String)aListComponent.getModel().getElementAt(0);
            if(createQuotes){
                aList += "\"";
            }
            for (int i=1; i < aListComponent.getModel().getSize();i++) {
                aList+= ",";
                if(createQuotes){
                    aList += "\"";
                }
                aList += aListComponent.getModel().getElementAt(i);
                if(createQuotes){
                    aList += "\"";
                }
            }
            
        }
        aList+="]";
        return aList;
    }
    private void fillList(JList aListComponent,String theList,boolean removeQuotes) {
        DefaultListModel itsModel = new DefaultListModel();
        aListComponent.setModel(itsModel);
        String aList = theList;
        if (aList.startsWith("[")) {
            aList = aList.substring(1,aList.length());
        }
        if (aList.endsWith("]")) {
            aList = aList.substring(0,aList.length()-1);
        }
        if(!aList.equals("")){
            String[] aS=aList.split(",");
            for (int i=0; i< aS.length;i++) {
                if(removeQuotes){
                    itsModel.addElement(aS[i].substring(1,aS[i].length()-1));
                }else{
                    itsModel.addElement(aS[i]);
                }
            }
            aListComponent.setModel(itsModel);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        seOperationAttributesInputPanel = new javax.swing.JPanel();
        maxIterationsLabel = new javax.swing.JLabel();
        maxIterationsText = new javax.swing.JTextField();
        epsilonText = new javax.swing.JTextField();
        epsilonLabel = new javax.swing.JLabel();
        minConvergedText = new javax.swing.JTextField();
        minConvergedLabel = new javax.swing.JLabel();
        domainSizeGroupPanel = new javax.swing.JPanel();
        dsFrequencyLabel = new javax.swing.JLabel();
        dsTimeLabel = new javax.swing.JLabel();
        dsFrequencyText = new javax.swing.JTextField();
        dsTimeText = new javax.swing.JTextField();
        dsFrequencyUnitLabel = new javax.swing.JLabel();
        dsTimeUnitLabel = new javax.swing.JLabel();
        parametersGroupPanel = new javax.swing.JPanel();
        excludedParametersGroupPanel = new javax.swing.JPanel();
        excludedParmsModPanel = new javax.swing.JPanel();
        addExcludedParmButton = new javax.swing.JButton();
        deleteExcludedParmButton = new javax.swing.JButton();
        excludedParmsScrollPane = new javax.swing.JScrollPane();
        excludedParmsList = new javax.swing.JList();
        solvableParametersGroupPanel = new javax.swing.JPanel();
        solvableParmsModPanel = new javax.swing.JPanel();
        addSolvableParmButton = new javax.swing.JButton();
        deleteSolvableParmButton = new javax.swing.JButton();
        solvableParmsScrollPane = new javax.swing.JScrollPane();
        solvableParmsList = new javax.swing.JList();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setMaximumSize(new java.awt.Dimension(540, 180));
        setMinimumSize(new java.awt.Dimension(540, 180));
        setPreferredSize(new java.awt.Dimension(540, 180));
        seOperationAttributesInputPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maxIterationsLabel.setText("Max. iterations :");
        seOperationAttributesInputPanel.add(maxIterationsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        seOperationAttributesInputPanel.add(maxIterationsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 60, -1));

        seOperationAttributesInputPanel.add(epsilonText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 60, -1));

        epsilonLabel.setText("Epsilon :");
        seOperationAttributesInputPanel.add(epsilonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        seOperationAttributesInputPanel.add(minConvergedText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 60, -1));

        minConvergedLabel.setText("Min. converged :");
        seOperationAttributesInputPanel.add(minConvergedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        domainSizeGroupPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        domainSizeGroupPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Domain Size"));
        dsFrequencyLabel.setText("Frequency :");
        domainSizeGroupPanel.add(dsFrequencyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        dsTimeLabel.setText("Time :");
        domainSizeGroupPanel.add(dsTimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        domainSizeGroupPanel.add(dsFrequencyText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 60, -1));

        domainSizeGroupPanel.add(dsTimeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 60, -1));

        dsFrequencyUnitLabel.setText("Hz");
        domainSizeGroupPanel.add(dsFrequencyUnitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, 20));

        dsTimeUnitLabel.setText("s");
        domainSizeGroupPanel.add(dsTimeUnitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 20, 20));

        seOperationAttributesInputPanel.add(domainSizeGroupPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, 70));

        parametersGroupPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parametersGroupPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));
        excludedParametersGroupPanel.setLayout(new java.awt.BorderLayout());

        excludedParametersGroupPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Excluded"));
        excludedParmsModPanel.setLayout(new java.awt.GridBagLayout());

        addExcludedParmButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nl/astron/lofar/sas/otbcomponents/bbs/icons/general/Add16.gif")));
        addExcludedParmButton.setMaximumSize(new java.awt.Dimension(30, 25));
        addExcludedParmButton.setMinimumSize(new java.awt.Dimension(30, 25));
        addExcludedParmButton.setPreferredSize(new java.awt.Dimension(30, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        excludedParmsModPanel.add(addExcludedParmButton, gridBagConstraints);

        deleteExcludedParmButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nl/astron/lofar/sas/otbcomponents/bbs/icons/general/Delete16.gif")));
        deleteExcludedParmButton.setMaximumSize(new java.awt.Dimension(30, 25));
        deleteExcludedParmButton.setMinimumSize(new java.awt.Dimension(30, 25));
        deleteExcludedParmButton.setPreferredSize(new java.awt.Dimension(30, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        excludedParmsModPanel.add(deleteExcludedParmButton, gridBagConstraints);

        excludedParametersGroupPanel.add(excludedParmsModPanel, java.awt.BorderLayout.SOUTH);

        excludedParmsScrollPane.setViewportView(excludedParmsList);

        excludedParametersGroupPanel.add(excludedParmsScrollPane, java.awt.BorderLayout.CENTER);

        parametersGroupPanel.add(excludedParametersGroupPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 160, 140));

        solvableParametersGroupPanel.setLayout(new java.awt.BorderLayout());

        solvableParametersGroupPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Solvable"));
        solvableParmsModPanel.setLayout(new java.awt.GridBagLayout());

        addSolvableParmButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nl/astron/lofar/sas/otbcomponents/bbs/icons/general/Add16.gif")));
        addSolvableParmButton.setMaximumSize(new java.awt.Dimension(30, 25));
        addSolvableParmButton.setMinimumSize(new java.awt.Dimension(30, 25));
        addSolvableParmButton.setPreferredSize(new java.awt.Dimension(30, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        solvableParmsModPanel.add(addSolvableParmButton, gridBagConstraints);

        deleteSolvableParmButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nl/astron/lofar/sas/otbcomponents/bbs/icons/general/Delete16.gif")));
        deleteSolvableParmButton.setMaximumSize(new java.awt.Dimension(30, 25));
        deleteSolvableParmButton.setMinimumSize(new java.awt.Dimension(30, 25));
        deleteSolvableParmButton.setPreferredSize(new java.awt.Dimension(30, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        solvableParmsModPanel.add(deleteSolvableParmButton, gridBagConstraints);

        solvableParametersGroupPanel.add(solvableParmsModPanel, java.awt.BorderLayout.SOUTH);

        solvableParmsScrollPane.setViewportView(solvableParmsList);

        solvableParametersGroupPanel.add(solvableParmsScrollPane, java.awt.BorderLayout.CENTER);

        parametersGroupPanel.add(solvableParametersGroupPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 140));

        seOperationAttributesInputPanel.add(parametersGroupPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 350, 170));

        add(seOperationAttributesInputPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExcludedParmButton;
    private javax.swing.JButton addSolvableParmButton;
    private javax.swing.JButton deleteExcludedParmButton;
    private javax.swing.JButton deleteSolvableParmButton;
    private javax.swing.JPanel domainSizeGroupPanel;
    private javax.swing.JLabel dsFrequencyLabel;
    private javax.swing.JTextField dsFrequencyText;
    private javax.swing.JLabel dsFrequencyUnitLabel;
    private javax.swing.JLabel dsTimeLabel;
    private javax.swing.JTextField dsTimeText;
    private javax.swing.JLabel dsTimeUnitLabel;
    private javax.swing.JLabel epsilonLabel;
    private javax.swing.JTextField epsilonText;
    private javax.swing.JPanel excludedParametersGroupPanel;
    private javax.swing.JList excludedParmsList;
    private javax.swing.JPanel excludedParmsModPanel;
    private javax.swing.JScrollPane excludedParmsScrollPane;
    private javax.swing.JLabel maxIterationsLabel;
    private javax.swing.JTextField maxIterationsText;
    private javax.swing.JLabel minConvergedLabel;
    private javax.swing.JTextField minConvergedText;
    private javax.swing.JPanel parametersGroupPanel;
    private javax.swing.JPanel seOperationAttributesInputPanel;
    private javax.swing.JPanel solvableParametersGroupPanel;
    private javax.swing.JList solvableParmsList;
    private javax.swing.JPanel solvableParmsModPanel;
    private javax.swing.JScrollPane solvableParmsScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
