answer2={};
answer3={};
matrix_noise=[];
matrix=[];
count_file2=0;
count_file3=0;
final_matrix=[];
set(listbox_load,'String',answer2);
set(listbox2_load,'String',answer3);
set(0,'CurrentFigure',HMainFig_gene)
subplot(PolyphasePlot)
cla