MainFigPos_Perio = [ 5 35 150 150];
shh = get(0,'ShowHiddenHandles');
set(0,'ShowHiddenHandles','on')
%Figure principale
HMainFig_Perio = figure(...
   'Name','Periodogram', ...
   'handlevisibility','callback',...
   'IntegerHandle','off',...
   'NumberTitle','off',...
   'Tag','MainFig2',...
   'position',MainFigPos_Perio);

frm1PosPerio=[LeftFrameBorder*0.008 BottomBorder FrameWidth*8 FrameHeight ];
frm1Perio=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frm1PosPerio, ...
   'BackgroundColor',CompBackGroundColor );

frm1PosPerio=[LeftFrameBorder*0.045 BottomBorder*2 FrameWidth*7.5 FrameHeight*0.9 ];
frm1Perio=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frm1PosPerio, ...
   'BackgroundColor',[0.6 0.5 0.5] );

ComPos50=[];
ComPos50=[LeftFrameBorder*0.40 CompBottom*0.7 CompWidth*7 CompHeight*6];
Freq_Res_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPos50, ...
   'String','Frequency resolution');

ComPos51=[];
ComPos51=[LeftFrameBorder*0.4 CompBottom*0.52 CompWidth*7 CompHeight*5];
Freq_Res=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',ComPos51, ...
   'String','1000');

ComPos52=[];
ComPos52=[LeftFrameBorder*0.38 CompBottom*0.25 CompWidth*8 CompHeight*5.3];
Apply_Freq_Res=uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',ComPos52, ...
   'String','Apply','Callback','Apply_perio');

ComPos53=[];
ComPos53=[LeftFrameBorder*0.30 CompBottom*1.06 CompWidth*10 CompHeight*3];
Apply_Freq_Res=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPos53, ...
   'String','Periodogram','BackgroundColor',CompBackGroundColor);

