#!/bin/sh

# makedoc builds the doxygen documentation in the subdirectory doc of the
# current directory. It builds the documentation for all header files, etc.
# at the current package and below.
# E.g. if in directory LOFAR, all LOFAR documentation is built in LOFAR/doc.
#      If in LOFAR/LCS/Common/build/gnu_debug, all LCS/Common documentation
#        is built in LOFAR/LCS/Common/build/gnu_debug/doc.
#
# doxygen must be found in your PATH.
# If the dot program is found in your path, doxygen is told to generate
# graphical class info as well.

  srcdir=`pwd | sed -e "s%/build/.*%%" -e "s%/build$%%"`;
  lfrdir=`echo $srcdir | sed -e "s%/LOFAR/.*%/LOFAR%"` ;
  projnm=`echo $srcdir | sed -e "s%.*/LOFAR/%%" -e "s%.*/LOFAR$%LOFAR%"` ;
  if [ ! -d $lfrdir/autoconf_share ]; then
    echo "Error: the autoconf_share directory could not be found."
    echo "Check your working directory is somewhere in the LOFAR tree."
    exit 1
  fi

  \rm -rf doc
  mkdir doc
  cd doc
  touch doxygen.cfg

  echo "OUTPUT_DIRECTORY        = ." >> doxygen.cfg
  echo "EXTRACT_ALL             = YES" >> doxygen.cfg
  echo "EXTRACT_PRIVATE         = YES" >> doxygen.cfg
  echo "EXTRACT_STATIC          = YES" >> doxygen.cfg
  echo "ALWAYS_DETAILED_SEC     = YES" >> doxygen.cfg
  echo "CASE_SENSE_NAMES        = YES" >> doxygen.cfg
  echo "JAVADOC_AUTOBRIEF       = YES" >> doxygen.cfg
  echo "DETAILS_AT_TOP          = YES" >> doxygen.cfg
  echo "DISTRIBUTE_GROUP_DOC    = YES" >> doxygen.cfg
  echo "ALIASES                 = \"template=\par Template requirements:\n\"" >> doxygen.cfg
  echo "MAX_INITIALIZER_LINES   = 0" >> doxygen.cfg
  echo "WARNINGS                = YES" >> doxygen.cfg
  echo "WARN_IF_UNDOCUMENTED    = NO" >> doxygen.cfg
  echo "FILE_PATTERNS           = *.h *.idl *.doc" >> doxygen.cfg
  echo "FILTER_SOURCE_FILES     = YES" >> doxygen.cfg
  echo "INPUT_FILTER            = $lfrdir/autoconf_share/slash2spanning.pl" >> doxygen.cfg
  echo "SOURCE_BROWSER          = YES" >> doxygen.cfg
  echo "REFERENCED_BY_RELATION  = YES" >> doxygen.cfg
  echo "REFERENCES_RELATION     = YES" >> doxygen.cfg
  echo "ALPHABETICAL_INDEX      = YES" >> doxygen.cfg
  echo "COLS_IN_ALPHA_INDEX     = 3" >> doxygen.cfg
  echo "ENUM_VALUES_PER_LINE    = 1" >> doxygen.cfg
  echo "GENERATE_TREEVIEW       = YES" >> doxygen.cfg
  echo "GENERATE_LATEX          = NO" >> doxygen.cfg
  echo "ALLEXTERNALS            = YES" >> doxygen.cfg
  echo "" >> doxygen.cfg
  echo "SEARCHENGINE            = NO" >> doxygen.cfg
    
  DOXYGENDOT=`which dot 2>&1`
  if [ -f "$DOXYGENDOT" ]; then
    DOXYGENDOT=`dirname $DOXYGENDOT`
    echo 'HAVE_DOT = YES' >> doxygen.cfg
    echo 'CLASS_GRAPH = YES' >> doxygen.cfg
    echo 'COLLABORATION_GRAPH = YES' >> doxygen.cfg
    echo "DOT_PATH = $DOXYGENDOT" >> doxygen.cfg
    echo 'DOT_CLEANUP = YES' >> doxygen.cfg
    echo '' >> doxygen.cfg
  fi

  echo "PROJECT_NAME = $projnm" >> doxygen.cfg ;
  echo "INPUT = $srcdir" >> doxygen.cfg ;
  echo "RECURSIVE = YES" >> doxygen.cfg ;
  echo "HTML_OUTPUT = ." >> doxygen.cfg ;
  echo "EXCLUDE = $srcdir/build $srcdir/test $srcdir/demo $srcdir/installed" >> doxygen.cfg;
  echo "GENERATE_TAGFILE = `basename -$projnm`.tag" >> doxygen.cfg ;
  doxygen doxygen.cfg ;

  echo ""
  echo "Doxygen output generated in ./doc"
