package nl.astron.lofar.mac.apl.gui.jrsp.panels.subbandstats;

import javax.swing.JPanel;
import nl.astron.lofar.mac.apl.gui.jrsp.panels.ITabPanel;
import nl.astron.lofar.mac.apl.gui.jrsp.panels.MainPanel;
import org.apache.log4j.Logger;

public class SubbandStatsPanel extends JPanel implements ITabPanel 
{
    private Logger log;
    
    private MainPanel mainPanel;
    
    /**
     * Default Constructor.
     */
    public SubbandStatsPanel()
    {
        log = Logger.getLogger(SubbandStatsPanel.class);
        
        initComponents();
        
        /*
         * Initialization of subpanels.
         */
        plotLeft.init(this);
        plotRight.init(this);
        settingsPanel.init(this);    
    }

    /**
     * Used to initialize the ITabPanel and give it a refrence to the main panel.
     * 
     * @param mainPanel   The MainPanel.
     */
    public void init(MainPanel mainPanel)
    {
        this.mainPanel = mainPanel;
    }
    
    /**
     * Method that can be called by the main panel to update this panel.
     */
    public void update()
    {
        /*
         * Update subpanels
         */
        plotLeft.update();
        plotRight.update();
        settingsPanel.update();
    }
    
    /**
     * Returns the main panel that the children can use.
     * (Default access specifier: only accesible within this package)
     */
    MainPanel getMainPanel()
    {
        return mainPanel;
    }
    
    /**
     * Return the left plot. Default access!
     */
    SubbandStatsPlotPanel getPlotLeft()
    {
        return plotLeft;
    }
    
    /**
     * Return the right plot. Default access!
     */
    SubbandStatsPlotPanel getPlotRight()
    {
        return plotRight;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        plotRight = new nl.astron.lofar.mac.apl.gui.jrsp.panels.subbandstats.SubbandStatsPlotPanel();
        plotLeft = new nl.astron.lofar.mac.apl.gui.jrsp.panels.subbandstats.SubbandStatsPlotPanel();
        settingsPanel = new nl.astron.lofar.mac.apl.gui.jrsp.panels.subbandstats.WaveformSettingsPanel();

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                .add(org.jdesktop.layout.GroupLayout.LEADING, settingsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                    .add(plotLeft, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(plotRight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(plotLeft, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(plotRight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(settingsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nl.astron.lofar.mac.apl.gui.jrsp.panels.subbandstats.SubbandStatsPlotPanel plotLeft;
    private nl.astron.lofar.mac.apl.gui.jrsp.panels.subbandstats.SubbandStatsPlotPanel plotRight;
    private nl.astron.lofar.mac.apl.gui.jrsp.panels.subbandstats.WaveformSettingsPanel settingsPanel;
    // End of variables declaration//GEN-END:variables
}