#!/bin/sh

../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format=","
../src/parmdb_main <<EOF
open tablename='tmakesourcedb_tmp.sdb'
showdef
EOF

echo ""
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="category='1',Name,Type,Ra,Dec,I,Q,U,V,SpInx,Major,Minor,Phi"
../src/parmdb_main <<EOF
open tablename='tmakesourcedb_tmp.sdb'
showdef
EOF

echo ""
../src/makesourcedb in=tmakesourcedb.in_2 out=tmakesourcedb_tmp.sdb append=0 format="category='3', patch='patch1' Name Type Rah ram ras Decd decm decs I, Q, U, V, SpInx='1.5', Major, Minor, Phi"
../src/parmdb_main <<EOF
open tablename='tmakesourcedb_tmp.sdb'
showdef
EOF

echo ">>>"
if test "$1" != ""; then
python<<EOF
from pyrap.tables import *
t=table("tmakesourcedb_tmp.sdb/SOURCES/PATCHES")
print "patch nrow =",t.nrows()
for col in ["PATCHNAME", "CATEGORY", "APPARENT_BRIGHTNESS", "RA", "DEC"]:
  print col, "=", t.getcol(col);
t=table("tmakesourcedb_tmp.sdb/SOURCES")
print "source nrow =",t.nrows()
for col in ["SOURCENAME", "PATCHID", "SOURCETYPE"]:
  print col, "=", t.getcol(col);
EOF
fi
echo "<<<"

# Select using a cone
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="," center="" center="23deg,45.0.0.00" radius="1arcsec"
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="," center="" center="23deg,45.0.2.00" radius="1.9arcsec"
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="," center="" center="23deg,45.0.0.00" width="1arcsec"
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="," center="" center="23deg,45.0.2.00" width="10arcmin,4.1arcsec"
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="," center="" center="23deg,45.0.2.00" width="10arcmin,3.9arcsec"

