#!/bin/bash

webserv=`ps -o pid -C QPIDWebserverJSON |wc | awk '{ print $1 }'`

if [ "$webserv" == "1" ]; then
   echo -n QPID status webserver not running, starting up...
   sudo -u qpid sh -c "ulimit -s 1024; /opt/lofar/bin/QPIDWebserverJSON 1>> /opt/lofar/var/log//QPIDwebserverJSON.log 2>&1 &"
else
   echo QPID status webserver already running
   exit
fi

sleep 1
# Check if running
webserv=`ps -o pid -C QPIDWebserverJSON |wc | awk '{ print $1 }'`
if [ "$webserv" == "1" ]; then 
  echo "    FAILED"
else 
  echo "    OK"
fi
