#!/bin/sh

# clearBB: clear BB (workorders and solutions) for BlackBoardDemo
#
#  Copyright (C) 2004
#  ASTRON (Netherlands Foundation for Research in Astronomy)
#  P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#  $Id$

# the following options can be given:
# -host    Host (default = dop50, this is the Postgres host uses)
# -user    User

BBHOST="dop50.astron.nl"
BBUSER=`whoami`
PTABLENAME='bbs3parmsolutions'

while [ 1 = 1 ]
do
  if [ "$1" = "-host" ]; then
    shift
    BBHOST="$1"
    shift
  elif [ "$1" = "-user" ]; then
    shift
    BBUSER="$1"
    shift
  elif [ "$1" = "-tablename" ]; then
    shift
    PTABLENAME="$1"
    shift
  else
    break;
  fi
done

SQLCLIENT="psql -h $BBHOST -U postgres $BBUSER"

#create the bb tables
echo " " > sql_create
echo " DROP TABLE bbs3solutions;" >> sql_create
echo " DROP TABLE bbs3woprediffer;" >> sql_create
echo " DROP TABLE bbs3wosolver;" >> sql_create
echo " DROP TABLE $PTABLENAME;" >> sql_create
echo " CREATE TABLE bbs3woprediffer (
       DATA TEXT NOT NULL, 
       WOID INTEGER PRIMARY KEY,
       SCID INTEGER, 
       STATUS INTEGER, 
       KSTYPE TEXT,
       DONOTHING INTEGER, 
       NEWBASELINES INTEGER, 
       NEWDOMAIN INTEGER,
       NEWSOURCES INTEGER,
       SUBTRACTSOURCES INTEGER, 
       WRITEPREDDATA INTEGER,
       WRITEINDATACOL INTEGER,
       MAXITERATIONS INTEGER,
       STARTFREQ DOUBLE PRECISION,
       FREQLENGTH DOUBLE PRECISION,
       STARTTIME DOUBLE PRECISION,
       TIMELENGTH DOUBLE PRECISION,
       CLEANUP INTEGER,
       UPDATEPARMS INTEGER,
       SOLUTIONID INTEGER);" >> sql_create
echo " CREATE INDEX bbs3woprediffer_status_idx ON bbs3woprediffer(status); " >> sql_create
#echo " CREATE INDEX bbs3woprediffer_kstype_idx ON bbs3woprediffer(kstype); " >> sql_create
echo " CREATE TABLE bbs3wosolver (
       DATA TEXT NOT NULL, 
       WOID INTEGER PRIMARY KEY,
       SCID INTEGER, 
       STATUS INTEGER, 
       KSTYPE TEXT,
       ITERATION INTEGER,
       DONOTHING INTEGER,
       NEWDOMAIN INTEGER,
       MAXITERATIONS INTEGER, 
       FITCRITERION DOUBLE PRECISION,
       USESVD INTEGER,
       CLEANUP INTEGER);" >> sql_create
#echo " CREATE INDEX bbs3wosolver_kstype_idx ON bbs3wosolver(kstype); " >> sql_create
echo " CREATE INDEX bbs3wosolver_status_idx ON bbs3wosolver(status); " >> sql_create
echo "create table bbs3solutions (
      DATA TEXT NOT NULL, 
      WOID INTEGER, 
      ITERATION INTEGER,
      FIT DOUBLE PRECISION, 
      MU DOUBLE PRECISION, 
      STDDEV DOUBLE PRECISION, 
      CHI DOUBLE PRECISION,
      STARTFREQ DOUBLE PRECISION,
      ENDFREQ DOUBLE PRECISION,
      STARTTIME DOUBLE PRECISION,
      ENDTIME DOUBLE PRECISION,
      HASCONVERGED INTEGER,
      PRIMARY KEY (WOID, ITERATION));" >> sql_create
echo "create table $PTABLENAME (
      SEQNR SERIAL PRIMARY KEY, 
      WOID INTEGER NOT NULL,
      ITERATION INTEGER, 
      PARMNAME TEXT,
      NX INTEGER,
      NY INTEGER, 
      COEFF DOUBLE PRECISION[]);" >> sql_create
$SQLCLIENT < sql_create
