#!/bin/sh

# clearBB: clear BB (workorders and solutions) for BlackBoardDemo
#
#  Copyright (C) 2004
#  ASTRON (Netherlands Foundation for Research in Astronomy)
#  P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#  $Id$

# the following options can be given:
# -host    Host (default = dop50, this is the host PL uses)
# -user    User

BBHOST="dop50"
BBUSER=`whoami`

while [ 1 = 1 ]
do
  if [ "$1" = "-host" ]; then
    shift
    BBHOST="$1"
    shift
  elif [ "$1" = "-user" ]; then
    shift
    BBUSER="$1"
    shift
  else
    break;
  fi
done

SQLCLIENT="psql -h $BBHOST -U postgres $BBUSER"

#create the bb tables
echo " " > sql_create
echo " DROP TABLE bbs3solutions;" >> sql_create
echo " DROP TABLE bbs3woprediffer;" >> sql_create
echo " DROP TABLE bbs3wosolver;" >> sql_create
echo " CREATE TABLE bbs3woprediffer (
       ObjId BIGINT NOT NULL UNIQUE PRIMARY KEY, 
       Owner BIGINT NOT NULL, 
       VersionNr INTEGER NOT NULL, 
       ID INTEGER, 
       TAG INTEGER, 
       SEQNR BIGINT, 
       DATA TEXT, 
       WOID INTEGER,
       SCID INTEGER, 
       STATUS INTEGER, 
       KSTYPE TEXT, 
       NEWBASELINES INTEGER, 
       NEWDOMAIN INTEGER,
       NEWSOURCES INTEGER,
       SUBTRACTSOURCES INTEGER, 
       STARTFREQ INTEGER,
       FREQLENGTH INTEGER,
       STARTTIME INTEGER,
       TIMELENGTH INTEGER,
       CLEANUP INTEGER);" >> sql_create
echo " CREATE TABLE bbs3wosolver (
       ObjId BIGINT NOT NULL UNIQUE PRIMARY KEY, 
       Owner BIGINT NOT NULL, 
       VersionNr INTEGER NOT NULL, 
       ID INTEGER, 
       TAG INTEGER, 
       SEQNR BIGINT, 
       DATA TEXT, 
       WOID INTEGER,
       SCID INTEGER, 
       STATUS INTEGER, 
       KSTYPE TEXT, 
       NEWDOMAIN INTEGER, 
       USESVD INTEGER,
       CLEANUP INTEGER);" >> sql_create
echo "create table bbs3solutions (
      ObjId BIGINT NOT NULL UNIQUE PRIMARY KEY, 
      Owner BIGINT NOT NULL, 
      VersionNr INTEGER NOT NULL, 
      ID INTEGER, 
      TAG INTEGER, 
      SEQNR BIGINT, 
      DATA TEXT, 
      WOID INTEGER, 
      FIT DOUBLE PRECISION, 
      MU DOUBLE PRECISION, 
      STDDEV DOUBLE PRECISION, 
      CHI DOUBLE PRECISION);" >> sql_create
$SQLCLIENT < sql_create
