#!/usr/bin/python
# $Id: radbservice 33373 2016-01-22 11:01:15Z schaap $

'''
runs the resourceassignment database service
'''
import logging
from lofar.sas.resourceassignment.resourceassignmentservice import service

logger = logging.getLogger(__name__)

if __name__ == '__main__':
    service.main()
