#!/bin/sh

# Parsets to use
PARSETS="
FIR_FilterTest.parset.77_Stations
FIR_FilterTest.parset.AARTFAAC
FIR_FilterTest.parset.small-test
"
cp ${srcdir}/../../src/cuda/FIR_Filter.cu .

# Check for GPU
if ! lspci | grep -E "VGA|3D" | grep -E "ATI|NVIDIA"
then
  echo "No ATI/NVIDIA graphics cards detected on host `hostname`" \
       "-- aborting test." >&2
  exit 3
fi

STATUS=0
for PARSET in $PARSETS
do
  echo "Running ./FIR_FilterTest $PARSET" >&2
  ./FIR_FilterTest $PARSET >&1
  if [ $? != 0 ]
  then
    STATUS=1
    echo "FAILED: ./FIR_FilterTest $PARSET" >&2
	exit $STATUS #exit for now.
  fi
done

exit $STATUS
