//#  ABSBeamletStatsPSet.h: Property set for the beamlet statistics.
//#
//#  Copyright (C) 2002-2004
//#  ASTRON (Netherlands Foundation for Research in Astronomy)
//#  P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
//#
//#  This program is free software; you can redistribute it and/or modify
//#  it under the terms of the GNU General Public License as published by
//#  the Free Software Foundation; either version 2 of the License, or
//#  (at your option) any later version.
//#
//#  This program is distributed in the hope that it will be useful,
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//#  GNU General Public License for more details.
//#
//#  You should have received a copy of the GNU General Public License
//#  along with this program; if not, write to the Free Software
//#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//#
//#  $Id$

#ifndef ABSBEAMLETSTATSPSET_H_
#define ABSBEAMLETSTATSPSET_H_

#include <GCF/GCF_Defines.h>
#include <GCF/GCF_PValue.h>

namespace ABS
{

  const TProperty BeamServerProps[] =
    {
      {"power000_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power000_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power001_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power001_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power002_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power002_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power003_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power003_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power004_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power004_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power005_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power005_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power006_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power006_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power007_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power007_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power008_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power008_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power009_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power009_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power010_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power010_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power011_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power011_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power012_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power012_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power013_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power013_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power014_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power014_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power015_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power015_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power016_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power016_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power017_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power017_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power018_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power018_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power019_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power019_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power020_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power020_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power021_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power021_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power022_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power022_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power023_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power023_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power024_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power024_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power025_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power025_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power026_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power026_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power027_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power027_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power028_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power028_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power029_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power029_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power030_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power030_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power031_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power031_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power032_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power032_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power033_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power033_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power034_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power034_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power035_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power035_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power036_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power036_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power037_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power037_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power038_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power038_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power039_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power039_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power040_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power040_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power041_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power041_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power042_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power042_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power043_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power043_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power044_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power044_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power045_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power045_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power046_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power046_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power047_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power047_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power048_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power048_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power049_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power049_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power050_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power050_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power051_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power051_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power052_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power052_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power053_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power053_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power054_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power054_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power055_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power055_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power056_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power056_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power057_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power057_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power058_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power058_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power059_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power059_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power060_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power060_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power061_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power061_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power062_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power062_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power063_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power063_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power064_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power064_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power065_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power065_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power066_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power066_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power067_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power067_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power068_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power068_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power069_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power069_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power070_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power070_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power071_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power071_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power072_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power072_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power073_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power073_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power074_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power074_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power075_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power075_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power076_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power076_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power077_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power077_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power078_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power078_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power079_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power079_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power080_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power080_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power081_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power081_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power082_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power082_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power083_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power083_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power084_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power084_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power085_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power085_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power086_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power086_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power087_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power087_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power088_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power088_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power089_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power089_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power090_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power090_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power091_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power091_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power092_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power092_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power093_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power093_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power094_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power094_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power095_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power095_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power096_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power096_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power097_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power097_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power098_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power098_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power099_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power099_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power100_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power100_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power101_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power101_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power102_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power102_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power103_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power103_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power104_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power104_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power105_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power105_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power106_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power106_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power107_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power107_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power108_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power108_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power109_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power109_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power110_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power110_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power111_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power111_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power112_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power112_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power113_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power113_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power114_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power114_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power115_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power115_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power116_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power116_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power117_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power117_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power118_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power118_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power119_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power119_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power120_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power120_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power121_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power121_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power122_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power122_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power123_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power123_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power124_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power124_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power125_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power125_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power126_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power126_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power127_x", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},
      {"power127_y", GCFPValue::LPT_DOUBLE, GCF_WRITABLE_PROP, "0"},

      // seqnr of the last statistics package included in the stats
      {"seqnr", GCFPValue::LPT_UNSIGNED, GCF_READABLE_PROP, "0"},
    };

  const TPropertySet BeamServerPSet = 
    {
	(sizeof(BeamServerProps)/sizeof(TProperty)), "BeamServer", BeamServerProps
    };

};

#endif

