#!/bin/sh

# mwimager-part.cc: A distributed part of mwimager
#
# Copyright (C) 2008
# ASTRON (Netherlands Foundation for Research in Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# $Id$


# Find the path used to start the script.
pgmpath=`dirname $0`
pgmpath=`cd $pgmpath > /dev/null 2>&1  &&  pwd`

if test $# != 10; then
  echo "run as:   mwimager-part dummy dummy dummy dummy rank ms-part"
  echo "                        lofarroot parset-file wd dry"
  exit 1
fi

shift
shift
shift
shift
seqnr=$1
msn=$2
lroot=$3
psn=$4
wd=$5
dry=$6

# Initialize lofar environment.
. $lroot/lofarinit.sh
# Set to working directory.
cd $wd

# Add channel info to the parset file.
cp $psn $psn.part$seqnr
schan=`getparsetvalue $psn.part$seqnr firstchan 2>/dev/null` || schan=0
echan=`getparsetvalue $psn.part$seqnr lastchan  2>/dev/null` || echan=-1
sfreq=`getparsetvalue $msn.vds StartFreqs schan` || exit 1
efreq=`getparsetvalue $msn.vds EndFreqs   echan` || exit 1
dname=`getparsetvalue $msn.vds Name` || exit 1
echo "Images.frequency = [$sfreq, $efreq]" >> $psn.part$seqnr
sed -e "s/^ *dataset * =.*/dataset = $dname/" $psn.part$seqnr > $psn.part$seqnr-tmp
mv $psn.part$seqnr-tmp $psn.part$seqnr

# Convert parset file from SAS format to cimager format.
# Normally convertimagerparset is in the same installed directory as the script,
# but in case of 'make check' it is in the src directory.
if test -e $pgmpath/convertimagerparset; then
  $pgmpath/convertimagerparset $psn.part$seqnr $psn.part$seqnr.cvt
else
  ../src/convertimagerparset $psn.part$seqnr $psn.part$seqnr.cvt
fi

if test "$dry" = dry; then
  cat $psn.part$seqnr.cvt
  exit 0
fi

# Run the imager.
~/askapsoft/Code/Components/Synthesis/synthesis/trunk/apps/cimager.sh -inputs $psn.part$seqnr.cvt

# Convert to FITS.
## image2fits 
