#!/bin/sh

# makemsdistr-part.cc: A distributed part of makemsdistr
#
# Copyright (C) 2009
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$


# Find the path used to start the script.
pgmpath=`dirname $0`
pgmpath=`cd $pgmpath > /dev/null 2>&1  &&  pwd`

if test $# != 13; then
  echo "run as:   makemsdistr-part dummy dummy dummy dummy rank"
  echo "                           msname dummy dummy envfile"
  echo "                           parset-file vdspath vdsout cdn"
  exit 1
fi

shift
shift
shift
shift
seqnr=$1
msn=$2
envfile=$5
psn=$6
vdspath=$7
vdsout=$8
cdn=$9

# Initialize environment.
if test "$envfile" != ""; then
  . $envfile
fi

# Create the MS.
# Grep the VDSname from the result.
echo "$pgmpath/makems $psn $seqnr $msn $vdspath $cdn > ${vdsout}_$seqnr"
$pgmpath/makems $psn $seqnr $msn $vdspath $cdn | grep "vds=" | sed -e 's/vds=//' > ${vdsout}_$seqnr 
