#!/bin/bash

. $srcdir/testFuncs.sh

# The code we need to test doesn't use a GPU,
# but we need to pass a list of gpu devices to create a BF Pipeline obj.
haveGPU || exit 3

# remove any output files from prev runs
rm -f tMultiPartTABOutput-L123881_SAP000_B000_P00?_bf.{h5,raw}

obsID=123881
rank=0
"$LOFARROOT/bin/outputProc" $obsID $rank &
outPid=$!

trap 'kill -9 $outPid' SIGTERM SIGINT SIGQUIT SIGHUP  # don't linger on e.g. Ctrl-C

./tMultiPartTABOutput
testStatus=$?
[ $testStatus -eq 0 ] || echo "Error: Test exited with status $testStatus"

wait $outPid
outputProcStatus=$?
[ $outputProcStatus -eq 0 ] || echo "Error: outputProc exited with status $outputProcStatus"

# check output files (195328 float values per file (1 block))
dataStatus=0
diff -q tMultiPartTABOutput.in_P000.raw tMultiPartTABOutput-L123881_SAP000_B000_P000_bf.raw || dataStatus=1
diff -q tMultiPartTABOutput.in_P001.raw tMultiPartTABOutput-L123881_SAP000_B000_P001_bf.raw || dataStatus=1

# final verdict
# outputProc crashes on final meta data. Ignore. We checked the output files.
exit $testStatus && $dataStatus #&& $outputProcStatus
