      #ifndef AID_VisAgent_h
      #define AID_VisAgent_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
      #include "DMI/AtomicID.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_VisAgent ();

#ifndef _defined_id_AidAgent
#define _defined_id_AidAgent 1
const AtomicID AidAgent(-1249);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/VisAgent/src/VisAgent.aidlist:1
const int AidAgent_int = -1249;
#endif
#ifndef _defined_id_AidData
#define _defined_id_AidData 1
const AtomicID AidData(-1107);                    // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOPUSSY/test/Testing.aidlist:2
const int AidData_int = -1107;
#endif
#ifndef _defined_id_AidFooter
#define _defined_id_AidFooter 1
const AtomicID AidFooter(-1202);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/VisCube/src/VisCube.aidlist:27
const int AidFooter_int = -1202;
#endif
#ifndef _defined_id_AidHeader
#define _defined_id_AidHeader 1
const AtomicID AidHeader(-1133);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/VisCube/src/VisCube.aidlist:30
const int AidHeader_int = -1133;
#endif
#ifndef _defined_id_AidInput
#define _defined_id_AidInput 1
const AtomicID AidInput(-1075);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOPUSSY/src/OCTOPUSSY.aidlist:42
const int AidInput_int = -1075;
#endif
#ifndef _defined_id_AidOutput
#define _defined_id_AidOutput 1
const AtomicID AidOutput(-1130);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/VisAgent/src/VisAgent.aidlist:6
const int AidOutput_int = -1130;
#endif
#ifndef _defined_id_AidParameters
#define _defined_id_AidParameters 1
const AtomicID AidParameters(-1282);              // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOPUSSY/src/OCTOPUSSY.aidlist:53
const int AidParameters_int = -1282;
#endif
#ifndef _defined_id_AidResume
#define _defined_id_AidResume 1
const AtomicID AidResume(-1251);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/VisAgent/src/VisAgent.aidlist:8
const int AidResume_int = -1251;
#endif
#ifndef _defined_id_AidSuspend
#define _defined_id_AidSuspend 1
const AtomicID AidSuspend(-1252);                 // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/VisAgent/src/VisAgent.aidlist:9
const int AidSuspend_int = -1252;
#endif
#ifndef _defined_id_AidTile
#define _defined_id_AidTile 1
const AtomicID AidTile(-1123);                    // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/VisAgent/src/VisAgent.aidlist:10
const int AidTile_int = -1123;
#endif
#ifndef _defined_id_AidVis
#define _defined_id_AidVis 1
const AtomicID AidVis(-1116);                     // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/VisAgent/src/VisAgent.aidlist:11
const int AidVis_int = -1116;
#endif


#endif
