#!/usr/bin/ksh
#
# genDBcode
#
# Generates DTL code for storing/saving an object to a database
# Uses a .map file to lookup the references and a .fun file
# for looking up the routines that should be generated
#
# Syntax: genDBcode mapfile functionfile R|P [class]
#
# $Id$
#
VERSION="v2.3"

#
# RECaddBCA class
#
RECaddBCA()
{
	Class=$1
	
	echo "// The ${Class}_BCA structure 'binds' the database columns"
	echo "// to the members of the ${Class} class."
	echo "class ${Class}_BCA {"
	echo "public:"
	echo "	void operator()(BoundIOs& cols, ${Class}& rowbuf) {"
	# get all 'basic' members of the class
	grep ^$Class ${MAPWRKFILE} | grep "::" | while read line
	do
		ColName=`echo $line | cut -d":" -f5`
		Member=`echo $line | cut -d":" -f4`
		echo "		cols[\"${ColName}\"]	== rowbuf.${Member};"
	done
	echo "	}"
	echo "};\n"
}

#
# RECaddInsertRoutine class 
#
RECaddInsertRoutine()
{
	Class=$1
	Table=`grep ^$Class ${MAPWRKFILE} | head -1 | cut -d":" -f2`

	echo "//"
	echo "// Routine for insert this ${Class} object in the database."
	echo "//"
	echo "void insert_${Class}(${Class}&	insRec) {"
	echo "	DBView<${Class}>	insView(\"${Table}\", ${Class}_BCA());"
	echo "	DBView<${Class}>::insert_iterator	insIter = insView;\n"

	echo "	*insIter = *insRec;"
	echo "}\n"
}

#
# RECaddSearchRoutine class clause
#
RECaddSearchRoutine()
{
	Class=$1
	Clause=$2
	Table=`grep ^$Class ${MAPWRKFILE} | head -1 | cut -d":" -f2`

	echo "vector<${Class}> read_${Class}() {"
	echo "	vector<${Class}> 		results;"
	echo "	DBView<${Class}>			view(\"${Table}\", ${Class}_BCA(),"
	echo "								\"${Clause}\");"
	echo "	DBView<${Class}>::select_iterator	readIter = view.begin();\n"
	echo "	for ( ; readIter != view.end(); ++readIter) {"
	echo "		results.push_back(*readIter);"
	echo "	}"
	echo "	return results;"
	echo "}\n"
}

#
# RECaddUpdateRoutine class clause
#
RECaddUpdateRoutine()
{
	Class=$1
	Clause=$2
	Table=`grep ^$Class ${MAPWRKFILE} | head -1 | cut -d":" -f2`

	echo "//"
	echo "// Routine for updating this ${Class} object in the database."
	echo "//"
	echo "void update_${Class}(${Class}&	theRecord) {"
	echo "	DBView<${Class}>			view(\"${Table}\", ${Class}_BCA(),"
	echo "								\"${Clause}\");"
	echo "	DBView<${Class}>::update_iterator	updIter = view;"
	echo ""
	echo "	// update the database"
	echo "	*updIter=*theRecord;"
	echo "}\n"
}

#---------------------- Persistency layer routines ----------------------------

#
# TPOopenNamespace
#
TPOopenNamespace()
{
	echo "namespace LOFAR {"
	echo "	namespace PL {"
	echo ""
}

#
# TPOcloseNamespace
#
TPOcloseNamespace()
{
	echo "	} // close namespace PL"
	echo "}	// close namespace LOFAR"
	echo ""
}

#
# TPOaddDTLstruct class
#
TPOaddDTLstruct()
{
	Class=$1
	
	echo ""
	echo "// The DBRep<${Class}> structure is a contigious representation of"
	echo "// all fields that should be stored to the database"

	# define a struct with the PO fields and the DataObj fields
	echo "template <>"
	echo "struct DBRep<${Class}> {"
	
	# every structs needs a bindCols functor.
	echo "	void bindCols(dtl::BoundIOs& cols);"

	# add all 'basic' members of the DataObj
	grep ^$Class ${MAPWRKFILE} | grep "::" | while read line
	do
		MemType=`echo $line | cut -d":" -f3 | sed "s/!/::/"`
		Member=`echo $line | cut -d":" -f4`
		echo "	${MemType}			${Member};"
	done

	echo "};"
	echo ""
}

#
# TPOaddBCA class
#
TPOaddBCA()
{
	Class=$1
	
	echo "// vindCols() 'binds' the database columns represented by \a cols"
	echo "// to the members of the DBRep<${Class}> class."
	echo "void DBRep<${Class}>::bindCols(BoundIOs& cols) {"

	# add all 'basic' members of the class
	grep ^$Class ${MAPWRKFILE} | grep "::" | while read line
	do
		ColName=`echo $line | cut -d":" -f5`
		Member=`echo $line | cut -d":" -f4`
		echo "	cols[\"${ColName}\"]	== ${Member};"
	done

	echo "}"
	echo ""
}

#
# TPOaddToDatabaseRep class 
#
# Adds code that copies the values from the real data-objects and the
# persistency object to a local DBRep<xxx> class.
#
TPOaddToDatabaseRep() 
{
	Class=$1

	echo ""
	echo "// toDBRep copies the fields of the ${Class} class to the"
	echo "// DBRep<${Class}> structure"
	echo "void TPersistentObject<${Class}>::toDBRep(DBRep<${Class}>& dest) const"
	echo "{"

	# add all 'basic' members of the Dataobj
	grep ^$Class ${MAPWRKFILE} | grep "::" | while read line
	do
		Member=`echo $line | cut -d":" -f4`
		echo "	dest.${Member}	= data().${Member};"
	done
	echo "}\n"
}

#
# TPOaddFromDatabaseRep class
#
# Adds code that copies the values from the local DBRep<xxx> class to the
# real data-objects and the persistency object.
#
TPOaddFromDatabaseRep() 
{
	Class=$1
	Action=$2

	echo ""
	echo "// fromDBRep copies the fields of the DBRep<${Class}> structure"
	echo "// to the ${Class} class."
	echo "void TPersistentObject<${Class}>::fromDBRep(const DBRep<${Class}>& src)"
	echo "{"

	# add all 'basic' members of the Dataobj
	grep ^$Class ${MAPWRKFILE} | grep "::" | while read line
	do
		Member=`echo $line | cut -d":" -f4`
		echo "	data().${Member}	= src.${Member};"
	done
	echo "}\n"
}

#
# TPOaddInitRoutine class
#
# Adds code that initializes the internals of a TPersistentObject
#
TPOaddInitRoutine() 
{
	Class=$1
	Action=$2

	echo ""
	echo "// Initialize the internals of TPersistentObject<${Class}>"
	echo "void TPersistentObject<${Class}>::init()"
	echo "{"

	# generate initialization code for all classes and base classes.
	grep ^$Class ${MAPWRKFILE} | grep -v "::" | while read line
	do
		Table=`echo $line | cut -d':' -f2`
		Member=`echo $line | cut -d':' -f4`
		Relation=`echo $line | cut -d':' -f5`
		RelClass=`echo $line | cut -d':' -f6`

		echo "	{"
		echo "	// create new TPersistentObject for ${Relation} ${RelClass}"
		if [ "${Relation}" == "BaseClass" ]; then
			echo "	Pointer p(new TPersistentObject<${RelClass}>(data()));"
		else
			echo "	Pointer p(new TPersistentObject<${RelClass}>(data().${Member}));"
		fi
		echo "	// associate ${RelClass}'s owner object-id with ${Class}'s objectid"
		echo "	p->metaData().ownerOid() = metaData().oid();"
		echo "	// add newly created TPersistentObject to container of ownedPOs."
		echo "	ownedPOs().push_back(p);"
		echo "	}"
	done

	echo "	// set the correct database table name"
	echo "	tableName(\"${Class}\");"
	echo "}"
	echo ""
}

#
# TPOaddAttributemap class
#
# Adds code that copies initializes the attribute map from TPO<x>
#
TPOaddAttributemap() 
{
	Class=$1

	echo ""
	echo "// Initialize the attribute map for TPersistenObject<${Class}>"
	echo "template<>"
	echo "void TPersistentObject<${Class}>::initAttribMap()"
	echo "{"

	# add all 'basic' members of the Dataobj
	grep ^$Class ${MAPWRKFILE} | grep "::" | while read line
	do
		Member=`echo $line | cut -d":" -f4`
		Colname=`echo $line | cut -d":" -f5`
		echo "	theirAttribMap[\"${Member}\"]	= \"${Colname}\";"
	done

	# add code for all classes and base classes.
	grep ^$Class ${MAPWRKFILE} | grep -v "::" | while read line
	do
		Member=`echo $line | cut -d":" -f4`
		RelType=`echo $line | cut -d":" -f5`
		SubClass=`echo $line | cut -d':' -f6`
		if [ "${RelType}" == "BaseClass" ]; then
			echo "	theirAttribMap[\"${SubClass}::\"]	="
			echo "		\"@\" + string(typeid(TPersistentObject<${SubClass}>).name());"
		else
			echo "	theirAttribMap[\"${Member}\"]	="
			echo "		\"@\" + string(typeid(TPersistentObject<${SubClass}>).name());"
		fi
	done
	echo "}\n"
}

#---------------------------- Global routines ---------------------------------
#
# initTmpfile
#
# Writes an informational header to the tempfile in case the file was not
# removed by this script.
#
initTmpfile()
{
	echo "#This temporarely file was generated by genDBcode"
	echo "#It should have been cleaned up by genDBcode, please remove it"
	echo "#ClassName:TableName:Ctype:MemberName:ColumnName:SubclassName:DBtype"
}

#
# initSrcfile filetype class
#
# Adds an informational header to the C++ source- of headerfile.
#
initSrcfile()
{
	FileType=$1
	Class=$2

	echo -n "//# This file was generated by genDBcode ${VERSION} on " ; date
	echo "//# with the command: genDBcode ${MAPFILE} ${FUNFILE} ${LAYER} ${CLASS}"
	echo -n "//# from the directory: " ; pwd
	echo "//#"
	echo "//# EDITING THIS FILE MANUALLY IS AT YOUR OWN RISK"
	echo "//# IT MIGHT BE OVERWRITTEN BY THE NEXT MAKE OF YOUR PROJECT"
	echo "//#"

	# include the headerfiles in the C++ sourcefile
	if [ "${FileType}" == "cc" ]; then
		echo "#include \"${FILEPREFIX}${Class}.h\""
		# Grep all subclasses of this class and include those headerfiles also.
		grep ^${Class} ${MAPWRKFILE} | grep -v "::" | while read line
		do
			subClass=`echo $line | cut -d':' -f6`
			echo "#include \"${FILEPREFIX}${subClass}.h\""
		done
		echo "#include <PL/TPersistentObject.h>"
		echo ""
		echo "using namespace dtl;"
		echo ""
	else	# its a headerfile
		TimeStamp=`date +%y%m%d%H%M%S`
		typeset -u FileLabel=${TimeStamp}_${FILEPREFIX}${Class}_H
		echo "//# only include this file once"
		echo "#if !defined(${FileLabel})"
		echo "#define ${FileLabel}"
		echo ""
		echo "#include \"${Class}.h\""
		echo "#include <PL/DBRep.h>"
		echo ""
	fi
}

#
# closeHeaderfile class
#
# write the last '#endif' to the headerfile
#
closeHeaderfile()
{
	Class=$1

	echo "#include \"${FILEPREFIX}${Class}.tcc\"	// Include template code"
	echo ""
	echo "#endif"
}

#
# cleanupWorkFiles
#
# Removes all temporary workfiles
#
cleanupWorkFiles()
{
	rm -f ${MAPWRKFILE} ${ALLCLASSESWRKFILE}
}

#
# cleanlist filename
#
# Removes all (partial) comment lines from the file
#
cleanlist()
{
	cut -d"#" -f1 $1 | awk '{ if (NF > 0) print $0 }'
}

#
# convertMapfile mapfile
#
# Convert the user format from the mapfile into something more convenient
# and store this in the tempfile.
#
# Allowed linesyntax of  the mapfile:
#	Class	<ClassName>
#	Table	<TableName>
#	File	<Filename>
#	<Ctype>	<MemberName>	<ColumnName>	<DBtype>
#	<Ctype>	<MemberName>	class			<ClassName>
#
# Syntax of the constructed temp-file:
# ClassName:TableName:Ctype:MemberName:ColumnName:SubclassName:DBtype
#
# NOTE: THIS ROUTINE ALSO EXISTS IN genDBsql
#
convertMapfile()
{
	Mapfile=$1

	cleanlist ${Mapfile} | while read label name dbname fldtype
	do
		# comment is stripped off, check rest of line
		if [ -z "$label" -o -z "$name" ]; then		# need two fields
			continue
		fi

		case $label in
		Class|class|CLASS)				# Class keyword
			CurClass=$name
			;;
		Table|table|TABLE)				# Table keyword
			CurTable=$name
			;;
		File|file|FILE)					# File keyword
			CurFile=$name
			;;
		*)								# no keyword, assume fieldname
			# label (=c_type) may be xxx::yyy, change it to xxx!yyy
			ctype=`echo $label | sed "s/::/!/"`
			typeset -l SubClass=`echo $dbname | cut -d" " -f1`
			# what kind of field is this?
			if [ "${SubClass}" == "class" -o "${SubClass}" == "baseclass" ]; then
				# it's a (sub)class, get its name.
				SubClassName=`echo $fldtype | cut -d" " -f1`
				echo "$CurClass:$CurTable:$ctype:$name:$dbname:$SubClassName:BIGINT"
			else
				echo "$CurClass:$CurTable:$ctype:$name:$dbname::$fldtype"
			fi
			;;
		esac
	done
}

# hasSubClasses class
#
# Routine that figures out if the given class has subclasses.
# Returns true or false
#
hasSubClasses()
{
	Class=$1

	# Note: grep returns 0 if something found, 1 or -1 if not.
	grep ^$Class ${MAPWRKFILE} | grep -v "::" >>/dev/null
	GrepOk=`echo $?`
	
	if [ ${GrepOk} == "0" ]; then			# something found?
		echo true
	else
		echo false
	fi

}
#------------------------------- MAIN program ---------------------------------
#
# Check invocation syntax: [-d destdir] genDBcode mapfile cmdfile layer [class]
#

# Check option argument
DESTDIR="./"						# assume no destination directory
eval set argv=`getopt "d:" $*`		# reformat arguments
shift
case "$1" in
	-d)	DESTDIR=$2
		if [ ! -d ${DESTDIR} ]; then
			echo "Destination directory >${DESTDIR}< does not exist"
			exit 1
		fi
		shift 2
		;;
esac
shift								# remove --

# Check other arguments
case $# in
	3)	MAPFILE=$1					# genDBcode mapfile funfile layer
		FUNFILE=$2
		typeset -u LAYER=$3
		GREPMASK=""
		CLASS=""
		;;
	4)	MAPFILE=$1					# genDBcode mapfile funfile layer classname
		FUNFILE=$2
		typeset -u LAYER=$3
		GREPMASK=" | grep ^$4"
		CLASS=$4
		;;
	*)	echo "Syntax: $0 mapfile functionfile layer [class]"
		echo "        where layer is R(ecord) or P(ersistency)"
		exit 0
		;;
esac

# Mapfile must exist
#
if [ ! -s ${MAPFILE} ]; then
	echo "File ${MAPFILE} doesn't exist\n"
	exit 1
fi

# Functionfile must exist
#
if [ ! -s ${FUNFILE} ]; then
	echo "File ${FUNFILE} doesn't exist\n"
	exit 1
fi

# Check Layer type
#
case "${LAYER}" in
R)		FILEPREFIX="Rec"		;;
P)		FILEPREFIX="PO_"		;;
*)		echo "Layer should be R(ecord) or P(ersistency), not >${LAYER}<\n"
		exit 1
esac

# All arguments seem ok, continue processing

# Initialize some variables
#
ROLLBACKCODE=false				# whether or not generate rollback code
LCSBASEFILE=${DESTDIR}/LCS_base.h
MAPWRKFILE=/tmp/mapinfo.LCS.$$
ALLCLASSESWRKFILE=/tmp/created.LCS.$$

# Make sure there are no old workfiles left
cleanupWorkFiles

# Set trap handler before we create anything
trap "cleanupWorkFiles ; exit" 1 2 3 13 15

# convert the human readable format of the mapfile into something
# more convenient for shell-programming
echo "Analysing mapfile"
initTmpfile					> ${MAPWRKFILE}
convertMapfile ${MAPFILE}	>>${MAPWRKFILE}

# Scan the functionfile to determine what code should be generated
#
PrevClass="Unknown"
eval "cleanlist $FUNFILE $GREPMASK" | \
while read class action clause
do
	# minimal check on layout of line
	if [ -z "$class" -o -z "$action" ]; then
		continue
	fi

	# New class? generate the necc. structures in the new sourcefile.
	# generate exacly one BCA for each class
	if [ "${PrevClass}" != "${class}" ]; then
		case ${LAYER} in
		R) 	SOURCEFILE=${DESTDIR}/${FILEPREFIX}${class}.tcc
			HEADERFILE=${DESTDIR}/${FILEPREFIX}${class}.h
			initSrcfile "cc" ${class}  > ${SOURCEFILE}
			RECaddBCA 	     ${class}  >>${SOURCEFILE}
			;;
		P) 	# start a new headerfile and sourcefile
			SOURCEFILE=${DESTDIR}/${FILEPREFIX}${class}.tcc
			HEADERFILE=${DESTDIR}/${FILEPREFIX}${class}.h
			echo ${class}	 							>>${ALLCLASSESWRKFILE}
			echo "Creating code for class ${class}"
			initSrcfile "cc"				${class} 	> ${SOURCEFILE}
			TPOopenNamespace							>>${SOURCEFILE}
			TPOaddBCA 						${class} 	>>${SOURCEFILE}
			TPOaddToDatabaseRep				${class} 	>>${SOURCEFILE} 
			TPOaddFromDatabaseRep			${class} 	>>${SOURCEFILE} 
			TPOaddInitRoutine				${class} 	>>${SOURCEFILE} 
			TPOaddAttributemap				${class} 	>>${SOURCEFILE} 
			initSrcfile "h"					${class} 	> ${HEADERFILE}
			TPOopenNamespace							>>${HEADERFILE}
			TPOaddDTLstruct					${class} 	>>${HEADERFILE}
			TPOcloseNamespace							>>${HEADERFILE}
			closeHeaderfile					${class}	>>${HEADERFILE}
			;;
		esac
		PrevClass=${class}
	fi

	# dispatch the action
	typeset -u action=${action}						# to uppercase
	case ${LAYER} in
	R)
		case $action in
		I) RECaddInsertRoutine $class 			>>${SOURCEFILE}		;;
		U) RECaddUpdateRoutine $class "$clause"	>>${SOURCEFILE}		;;
		D) RECaddDeleteRoutine $class "$clause"	>>${SOURCEFILE}		;;
		S) RECaddSearchRoutine $class "$clause"	>>${SOURCEFILE}		;;
		*) echo "ERROR:Unknown function >$action< for class >$class< in file >$FUNFILE<"
		   ;;
		esac
		;;
	esac
done

# Finish all created .tcc files
if [ "${LAYER}" == "P" ]; then
	cat ${ALLCLASSESWRKFILE} | while read Class
	do
		TPOcloseNamespace >>${DESTDIR}/${FILEPREFIX}${Class}.tcc
	done
fi

# Finally cleanup our mess
cleanupWorkFiles
