#########################################################################
#	Makefile for the Base simulation environment.			#
#	Use MPI=1 if you want to compile with MPI support.		#
#########################################################################

EXES	= routetest
LIBNAME = routesim
LIBS    = $(DIRPREFIX)../BaseSim/$(ALIBDIR)/libbasesim.a

include $(DIRPREFIX)../BaseSim/Makedefs
