#!/bin/csh -f

set BASE = $1

##set DIRORIG = '/usr4/neurosat2/com/yacoub/prog/src'
set DIRORIG = '/usr4/neurosat3/com/dfr/psomamb/src'

set DIRDEST = '.'

set NOMORIG = ${BASE}.c
set NOMDEST = ${BASE}.c

if ( !( -f ${DIRORIG}/${NOMORIG} ) ) then
	echo " ***  fichier ORIG ${DIRORIG}/${NOMORIG} inexistent ***"
	exit 1
endif


if ( !( -f ${DIRDEST}/${NOMDEST} ) ) then
	echo " ***  fichier DEST ${DIRDEST}/${NOMDEST} inexistent ***"
	exit 1
endif

set INDENT_OPTIONS = '-npro -nbad  -bap -cdb -d2 -br -nbc -bl -bli2 -c33 -cd33 -ncdb -ce -cli0 -cp1 -di1 -nfc1 -fca -i2 -ci3 -ip5 -lp -pcs -psl -nsc -sob -ss -ts8 -cs -bs'

indent ${INDENT_OPTIONS} ${DIRORIG}/${NOMORIG} -o XXX${NOMORIG}
indent ${INDENT_OPTIONS} ${DIRDEST}/${NOMDEST} -o YYY${NOMDEST}

diff XXX${NOMORIG} YYY${NOMDEST}

#\rm  XXX${NOMORIG} YYY${NOMDEST}
