#!/bin/sh

# Set srcdir if needed.
# It might not be set if the .run file is executed directly instead of
# by 'make check'.
if [ "$srcdir" = "" ]; then
  srcdir=../../../test
fi

# Create the ParmDB tables for tPredSolv.
$srcdir/makeDemoParmDB tPredSolv
if [ $? != 0 ]; then
  exit 1
fi

if [ ! -d $LOFARDATAROOT/BBS2/demo3.MS_p1 ]; then
  exit 3
fi

$LOFAR_CHECKTOOL ./tPredSolv $USER $LOFARDATAROOT/BBS2/demo3.MS_p1 tPredSolv_tmp.demo_instr tPredSolv_tmp.demo_sky
status=$?
exit $status

