clear answer;
clear Signal_modulation;
Signal_modulation=[];
clear resampler;
clear s;
resol=16384;
fs=0;
Filename_reference='no file';
Filename_reference=[];
mat=[];
Filter1Coef=[];
Filter2Coef=[];
resu_poly=[];
I=[];
global I;
Threshold_reference=-150;
Threshold_modu=1;
global indice_reference;
indice=0;
Filename_load2=[];
Signal_modulation_noisy=[];
count_file=0;
count_file2=0;
answer=cell(25,1);
answer2=cell(3,1);
answer3=cell(3,1);
count_file3=0;
FrameWidth = 0.12; 
CompBottom=0.86;
CompWidth=0.05;
CompHeight=0.03;
LeftBorder = 0.05; 
BottomBorder=0.05; 
TotalWidth = 1 - 3*LeftBorder-FrameWidth ; TotalHeight = 1-2*BottomBorder;
FigSpace = 0.05;
Col1Width = 0.3*TotalWidth;
Col2Width = TotalWidth-Col1Width-FigSpace;
Lin1Height = 0.3*TotalHeight;
Lin2Height= TotalHeight-Lin1Height-FigSpace;
Modulated_signal=struct('Modula_signal',{},'feature_modulat',{});
feature_mod=struct('name',{},'Carrier_freq',{},'modulation_param',{},'modulation_Ampl',{});
FrameBorder = 0.01;
LeftFrameBorder = LeftBorder + Col1Width+Col2Width+2*FigSpace;
FrameHeight = TotalHeight;
CompBackGroundColor = [0.5 0.5 0.5];

MainFigPos_gene = [ 5 35 1017 663];
shh = get(0,'ShowHiddenHandles');
set(0,'ShowHiddenHandles','on')
%Figure principale
HMainFig_gene = figure(...
   'Name','DataGenerator', ...
   'handlevisibility','callback',...
   'IntegerHandle','off',...
   'NumberTitle','off',...
   'Tag','MainFig',...
   'position',MainFigPos_gene);

 %=================================
 
frm1Pos=[LeftFrameBorder*0.008 BottomBorder+FrameHeight/2.5 FrameWidth*4.1 FrameHeight/1.665 ];
frm1=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frm1Pos, ...
   'BackgroundColor',CompBackGroundColor );

frm2Pos=[LeftFrameBorder*0.606 16.75*BottomBorder FrameWidth*4.1 FrameHeight/8 ];
frm2=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frm2Pos, ...
   'BackgroundColor',CompBackGroundColor );

frm6Pos=[LeftFrameBorder*0.615 17.1*BottomBorder FrameWidth*3.99 FrameHeight/12 ];
frm6=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frm6Pos, ...
  'BackgroundColor',[0.6 0.5 0.5]);


frm4Pos=[LeftFrameBorder*0.008+0.006 14.93*BottomBorder FrameWidth*4 FrameHeight/4.9];
frm4=uicontrol( ...
   'Style','frame', ...
  'Units','normalized', ...
  'Position',frm4Pos, ...
   'BackgroundColor', [0.6 0.5 0.5]);

ComPos20=[];
ComPos20=[LeftFrameBorder*0.095 CompBottom*1.02 CompWidth*1.2 CompHeight*1.3];
Load_button=uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',ComPos20, ...
   'String','Load','Callback','load_file');

ComPos201=[];
ComPos201=[LeftFrameBorder*0.17 CompBottom*1.02 CompWidth*1.2 CompHeight*1.3];
Load_button=uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',ComPos201, ...
   'String','Clear','Callback','Clear_file');



ComPos40=[];
ComPos40=[LeftFrameBorder*0.095 CompBottom*0.97 CompWidth*1.2 CompHeight*1.3];
Visu_button=uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',ComPos40, ...
   'String','See','Callback','Visu_file');

ComPos41=[];
ComPos41=[LeftFrameBorder*0.02 CompBottom*0.915 CompWidth*1.2 CompHeight*1.3];
Visu_Fs_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPos41, ...
   'String','Sampling Frequency');


ComPos42=[];
ComPos42=[LeftFrameBorder*0.02 CompBottom*0.88 CompWidth*1.2 CompHeight];
Visu_Fs=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',ComPos42, ...
   'String','0');

ComPos421=[];
ComPos421=[LeftFrameBorder*0.095 CompBottom*0.915 CompWidth*1.2 CompHeight*1.3];
Visu_Time_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPos421, ...
   'String','Total Time');

ComPos422=[];
ComPos422=[LeftFrameBorder*0.095 CompBottom*0.88 CompWidth*1.2 CompHeight];
Visu_Time=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',ComPos422, ...
   'String','0');

ComPos423=[];
ComPos423=[LeftFrameBorder*0.17 CompBottom*0.915 CompWidth*1.2 CompHeight*1.3];
Visu_Size_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPos423, ...
   'String','Size(Bytes)');

ComPos424=[];
ComPos424=[LeftFrameBorder*0.17 CompBottom*0.88 CompWidth*1.2 CompHeight];
Visu_Size=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',ComPos424, ...
   'String','0');

ComPos21=[];
ComPos21=[LeftFrameBorder*0.25 CompBottom-0.09 CompWidth*5.3 CompHeight*5];
Load_listbox=uicontrol( ...
   'Style','listbox', ...
   'Units','normalized', ...
   'Position',ComPos21, ...
   'String','');

modulation_name=cell(8,1);
modulation_name={'Am';'Amdsb-tc';'Amssb';'FM';'PM';'Pwm'};
CompLeft =0.8400;
tm=0;

frm9Pos=[LeftFrameBorder*0.008+0.006 12.5*BottomBorder FrameWidth*4 FrameHeight/8];
frm9=uicontrol( ...
   'Style','frame', ...
  'Units','normalized', ...
  'Position',frm9Pos, ...
   'BackgroundColor', [0.6 0.5 0.5]);


ModPos=[LeftFrameBorder*0.008+0.018 0.77*CompBottom CompWidth*1.1 CompHeight];
Modulation=uicontrol( ...
   'Style','text', ...
  'Units','normalized', ...
  'Position',ModPos, ...
   'string','Modulation:');


for i=1:3
    for j=1:2
        tm=tm+1;
p_btn1 = uicontrol(gcf,...
                 'style', 'pushbutton',...
                 'Position',[15+i*75 CompBottom*555-23*j 70 20 ],...
                 'String', modulation_name{tm},'Callback',[ 'modulation_func (' num2str(tm) ')']);
end
end


Noise_TextPos=[LeftFrameBorder*0.63 17.9*BottomBorder CompWidth*1.1 CompHeight];
Noise_Text=uicontrol(...
   'Style','text', ...
  'Units','normalized', ...
  'Position',Noise_TextPos, ...
  'string','Noise :');

Noise_Pos=[LeftFrameBorder*0.63 17.5*BottomBorder CompWidth*1.1 CompHeight];
Noise_minValue=uicontrol(...
   'Style','text', ...
  'Units','normalized', ...
  'Position',Noise_Pos, ...
  'string','Noise :','String',num2str(20*log10(Threshold_modu)));


Noise_Var_textPos=[LeftFrameBorder*0.75 17.9*BottomBorder CompWidth*1.1 CompHeight];
Noise_Var_text=uicontrol( ...
   'Style','text', ...
  'Units','normalized', ...
  'Position',Noise_Var_textPos, ...
   'string','Power level(dB)');

Noise_VarPos=[LeftFrameBorder*0.75 17.5*BottomBorder CompWidth*1.1 CompHeight];
Noise_Var=uicontrol( ...
   'Style','edit', ...
  'Units','normalized', ...
  'Position',Noise_VarPos, ...
   'string',num2str(20*log10(Threshold_modu)));


buttonaddPos=[LeftFrameBorder*0.85 17.5*BottomBorder CompWidth*1.1 CompHeight*1.5];
buttonadd=uicontrol( ...
   'Style','pushbutton', ...
  'Units','normalized', ...
  'Position',buttonaddPos, ...
   'string','+ vision','callback','Noise_addition');

FFTButton_Pos=[LeftFrameBorder*0.92 17.5*BottomBorder CompWidth*1.1 CompHeight*1.5];
FFTButton=uicontrol( ...
   'Style','pushbutton', ...
  'Units','normalized', ...
  'Position',FFTButton_Pos, ...
   'string','FFT','callback','TFP_FFT');


buttonPolyPos=[LeftFrameBorder*0.99 17.5*BottomBorder CompWidth*1.9 CompHeight*1.5];
buttonPoly=uicontrol( ...
   'Style','pushbutton', ...
  'Units','normalized', ...
  'Position',buttonPolyPos, ...
   'string','Polyphase Filter','Callback','Polyphase');

buttonSavePos=[LeftFrameBorder*1.11 17.9*BottomBorder CompWidth*1.3 CompHeight];
buttonSave=uicontrol( ...
   'Style','pushbutton', ...
  'Units','normalized', ...
  'Position',buttonSavePos, ...
   'string','Save_temp','Callback','Save_modulation');

buttonSave2Pos=[LeftFrameBorder*1.11 17.2*BottomBorder CompWidth*1.3 CompHeight];
buttonSave2=uicontrol( ...
   'Style','pushbutton', ...
  'Units','normalized', ...
  'Position',buttonSave2Pos, ...
   'string','Save_Matrix','Callback','Save_matrix');

frm2Pos=[LeftFrameBorder*0.606 14.3*BottomBorder FrameWidth*4.1 FrameHeight/8 ];
frm2=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frm2Pos, ...
   'BackgroundColor',CompBackGroundColor );

frm8Pos=[LeftFrameBorder*0.615 14.63*BottomBorder FrameWidth*4 FrameHeight/11];
frm8=uicontrol( ...
   'Style','frame', ...
  'Units','normalized', ...
  'Position',frm8Pos, ...
   'BackgroundColor', [0.6 0.5 0.5]);

Data_TextPos=[LeftFrameBorder*0.62 15.7*BottomBorder CompWidth*0.8 CompHeight*0.7];
Data=uicontrol(...
   'Style','text', ...
  'Units','normalized', ...
  'Position',Data_TextPos, ...
  'string',' Data :');

Add_NoisePos=[LeftFrameBorder*0.62 14.8*BottomBorder CompWidth*0.9 CompHeight*1.2];
Add_Noise=uicontrol(...
   'Style','pushbutton', ...
  'Units','normalized', ...
  'Position',Add_NoisePos, ...
  'string','+','callback','Matirx_noise_add');

clear_listPos=[LeftFrameBorder*0.603 13.75*BottomBorder CompWidth*0.8 CompHeight*0.8];
clear_list=uicontrol(...
   'Style','pushbutton', ...
  'Units','normalized', ...
  'Position',clear_listPos, ...
  'string','Clear','callback','Clear_list');

fs2_TextPos=[LeftFrameBorder*0.8 13.3*BottomBorder CompWidth*0.5 CompHeight*0.7];
fs2_text=uicontrol(...
   'Style','text', ...
  'Units','normalized', ...
  'Position',fs2_TextPos, ...
  'string',' fs :');

fs2_Pos=[LeftFrameBorder*0.84 13.3*BottomBorder CompWidth*1.5 CompHeight*0.8];
fs2=uicontrol(...
   'Style','text', ...
  'Units','normalized', ...
  'Position',fs2_Pos, ...
  'string','0');

NoisePower_TextPos=[LeftFrameBorder*0.61 13.3*BottomBorder CompWidth*1.3 CompHeight*0.7];
NoisePower_Text=uicontrol(...
   'Style','text', ...
  'Units','normalized', ...
  'Position',NoisePower_TextPos, ...
  'string',' Noise_level:');

NoisePower_Pos=[LeftFrameBorder*0.7 13.3*BottomBorder CompWidth*1.2 CompHeight*0.8];
NoisePower=uicontrol(...
   'Style','edit', ...
  'Units','normalized', ...
  'Position',NoisePower_Pos, ...
  'string','0');


real_time_textPos=[LeftFrameBorder*0.93 13.8*BottomBorder CompWidth*3 CompHeight*0.7];
real_time_text=uicontrol(...
   'Style','text', ...
  'Units','normalized', ...
  'Position',real_time_textPos, ...
  'string',' Real Integration Time (s) :');

real_time_Pos=[LeftFrameBorder*1.096 13.8*BottomBorder CompWidth*1.7 CompHeight*0.8];
real_time=uicontrol(...
   'Style','text', ...
  'Units','normalized', ...
  'Position',real_time_Pos, ...
  'string','0');

Total_time_textPos=[LeftFrameBorder*0.93 13.3*BottomBorder CompWidth*3 CompHeight*0.7];
Total_time_text=uicontrol(...
   'Style','text', ...
  'Units','normalized', ...
  'Position',Total_time_textPos, ...
  'string',' Total Time (s) :');

Total_time_Pos=[LeftFrameBorder*1.096 13.3*BottomBorder CompWidth*1.7 CompHeight*0.8];
Total_time=uicontrol(...
   'Style','text', ...
  'Units','normalized', ...
  'Position',Total_time_Pos, ...
  'string','0');

Occupancy_textPos=[LeftFrameBorder*0.93 12.85*BottomBorder CompWidth*3 CompHeight*0.7];
Total_time_text=uicontrol(...
   'Style','text', ...
  'Units','normalized', ...
  'Position',Occupancy_textPos, ...
  'string',' Occupancy (%) :');

Occupancy_Pos=[LeftFrameBorder*1.096 12.85*BottomBorder CompWidth*1.7 CompHeight*0.8];
Occupancy=uicontrol(...
   'Style','text', ...
  'Units','normalized', ...
  'Position',Occupancy_Pos, ...
  'string','0');


List_modulation_Postext=[LeftFrameBorder*0.38 BottomBorder*14.1 CompWidth*3.2 CompHeight];
List_modulation_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',List_modulation_Postext, ...
   'String','Modulation - Fs - Ampl - Feature','FontSize',8,'BackgroundColor',[0.6 0.5 0.5]);

List_modulation_Pos=[LeftFrameBorder*0.385 BottomBorder*12.7 CompWidth*3.2 CompHeight*2.6];
List_modulation=uicontrol( ...
   'Style','listbox', ...
   'Units','normalized', ...
   'Position',List_modulation_Pos, ...
   'String','');


real_fr_textPos=[LeftFrameBorder*0.65 13.8*BottomBorder CompWidth*3 CompHeight*0.7];
real_fr_text=uicontrol(...
   'Style','text', ...
  'Units','normalized', ...
  'Position',real_fr_textPos, ...
  'string',' Real frequency Resolution(Hz):');

real_fr_Pos=[LeftFrameBorder*0.84 13.8*BottomBorder CompWidth*1.5 CompHeight*0.8];
real_fr=uicontrol(...
   'Style','text', ...
  'Units','normalized', ...
  'Position',real_fr_Pos, ...
  'string','0');


Data_loadPos=[LeftFrameBorder*0.68 15.5*BottomBorder CompWidth*1.3 CompHeight];
Data_load=uicontrol(...
   'Style','pushbutton', ...
  'Units','normalized', ...
  'Position',Data_loadPos, ...
  'string',' Load_File ','Callback','load_matrix');

Data_load2Pos=[LeftFrameBorder*0.68 14.8*BottomBorder CompWidth*1.3 CompHeight];
Data_load2=uicontrol(...
   'Style','pushbutton', ...
  'Units','normalized', ...
  'Position',Data_load2Pos, ...
  'string',' Load_noise ','Callback','load_matrix2');


listbox_loadPos=[LeftFrameBorder*0.76 15.5*BottomBorder CompWidth*2.1 CompHeight*1.1];
listbox_load=uicontrol(...
   'Style','listbox', ...
  'Units','normalized', ...
  'Position',listbox_loadPos, ...
  'string','');

listbox2_loadPos=[LeftFrameBorder*0.76 14.8*BottomBorder CompWidth*2.1 CompHeight*1.1];
listbox2_load=uicontrol(...
   'Style','listbox', ...
  'Units','normalized', ...
  'Position',listbox2_loadPos, ...
  'string','');

Data_loadPos=[LeftFrameBorder*1.025 15*BottomBorder CompWidth*1.6 CompHeight*1.5];
Data_Poly=uicontrol(...
   'Style','pushbutton', ...
  'Units','normalized', ...
  'Position',Data_loadPos, ...
  'string','Polyphase Filter','Callback','Polyphase');

Data_loadPos=[LeftFrameBorder*0.982 15*BottomBorder CompWidth*0.6 CompHeight*1.5];
Data_FFT=uicontrol(...
   'Style','pushbutton', ...
  'Units','normalized', ...
  'Position',Data_loadPos, ...
  'string','FFT','Callback','TFP_FFT');

Exit_Pos=[LeftFrameBorder*1.11 19.05*BottomBorder CompWidth*1.3 CompHeight*1.5];
Exit_Button=uicontrol(...
  'Style','pushbutton', ...
  'Units','normalized', ...
  'Position',Exit_Pos, ...
  'string','Exit','Callback','clear_gui_load');

Matrix_SavePos=[LeftFrameBorder*1.13 15*BottomBorder CompWidth*0.8 CompHeight*1.5];
Matrix_Save=uicontrol(...
   'Style','pushbutton', ...
  'Units','normalized', ...
  'Position',Matrix_SavePos, ...
  'string','Save','Callback','Save_Matrix2');

Data_loadPos=[LeftFrameBorder*0.897 15*BottomBorder CompWidth*1.3 CompHeight*1.5];
Data_FFT=uicontrol(...
   'Style','pushbutton', ...
  'Units','normalized', ...
  'Position',Data_loadPos, ...
  'string','Periodogram','Callback','Periodogramme');

HPerioMod = subplot(4,1,2);
 set(gca, ...
    'Units','normalized', ...
    'Position',[LeftFrameBorder*0.008+0.023 CompBottom*0.05 0.467 0.33]);
%==================================

PolyphasePlot= subplot(4,3,4);
 set(gca, ...
  'Units','normalized', ...
    'Position',[LeftFrameBorder*0.65  CompBottom*0.05 0.45 0.6]);
%==================================


