#########################################################################
#	Makefile for the Base simulation environment.			#
#	Use MPI=1 if you want to compile with MPI support.		#
#########################################################################

EXES	= routetest
LIBNAME = routesim
LIBS    = ../BaseSim/$(LIBDIR)/libbasesim.a

include ../BaseSim/Makedefs
