#!/bin/sh

# Convert an LSM text file (e.g. from NVSS) to a ParmDB file.
#
# Run as:
#   lsm2db in out [maxnrsrc [dbtype [usernm]]]

if [ $# -lt 2 ]; then
  echo "Run as:  lsm2db in out [maxnrsrc [dbtype [usernm]]]"
  exit 1
fi
if [ $# -lt 3 ]; then
  maxnrsrc=100000000
else
  maxnrsrc=$3
fi
if [ $# -lt 4 ]; then
  dbtype=aips
else
  dbtype=$4
fi
usernm=$5

# Convert LSM text file to a file suitable for tablefromascii.
echo "Cat Name RAh RAm RAs eRA Decd Decm Decs eDEC Freq Flux" > lsm.fil-tmp
echo " A   A    I   I   D   D   I    I    D    D    D    D  " >> lsm.fil-tmp
grep -v '#' $1 >> lsm.fil-tmp

# Create a glish script making commands for creating and fill the table.
echo "include 'lsm2db.g'" > lsm.fil-glish
echo "lsm2db ('lsm.fil-tmp', 'lsm.fil-tab', $maxnrsrc)" >> lsm.fil-glish
echo "exit" >> lsm.fil-glish
glish lsm.fil-glish > /dev/null

# Execute the commands created by the glish script.
source lsm.fil-scr
beginParmdbInputFile "dbtype='$dbtype', user='$usernm', tablename='$2'"
makeLsm
applyfile > /dev/null
echo "Wrote ParmDB $dbtype table $2"
\rm -rf lsm.fil-{tmp,glish,tab,scr}
