#!/bin/sh

PROJ_PATH=`grep '^proj_path' ${PVSS_II} | sed 's/^.*proj_path *= * "//' | sed 's/".*//'| sed -n '$p' | tail -n 1`
echo PropertyAgent: Current running PVSS project has been found in $PROJ_PATH
cp -Rf ../share/pvss/* $PROJ_PATH >> /dev/null

runningPVSS00ctrl=`ps -ef | grep PVSS00ctrl | grep gcfpa-cwd.ctl | awk '{ print $1 }'`
if [ "a$runningPVSS00ctrl" != "a" ]; then
  echo "PropertyAgent: An old PA watchdog is still running. Will be stopped first!!!"
  kill -9 $runningPVSS00ctrl
fi

#echo PropertyAgent: Prepare DB
#PVSS00ctrl -script libs/gcfpa-prep.ctl -currentproj
echo PropertyAgent: Start watch-dog in the background
PVSS00ctrl -script libs/gcfpa-cwd.ctl -currentproj &

if [ -r customPrepPVSSDB.ctl ]; then
	echo PropertyAgent: Start custom prepare DB
	cp *.ctl $PROJ_PATH/scripts
	PVSS00ctrl -script customPrepPVSSDB.ctl -currentproj
#	rm -f $PROJ_PATH/scripts/customPrepPVSSDB.ctl
fi
