    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
    #include "DMI/AtomicID.h"
    #include "DMI/TypeInfo.h"
    #include "DMI/DynamicTypeManager.h"
    #include "DMI/Packer.h"

    int aidRegistry_Solver ()
    {
      return 1;
    }

static AtomicID::Register aid_reg_Domain(-1144,"Domain");
static AtomicID::Register aid_reg_Parameter(-1232,"Parameter");
static AtomicID::Register aid_reg_Step(-1142,"Step");
static AtomicID::Register aid_reg_Convergence(-1143,"Convergence");
static AtomicID::Register aid_reg_Size(-1127,"Size");
static AtomicID::Register aid_reg_Batch(-1145,"Batch");
static AtomicID::Register aid_reg_Solver(-1146,"Solver");
static AtomicID::Register aid_reg_Control(-1141,"Control");
static AtomicID::Register aid_reg_Job(-1231,"Job");
static AtomicID::Register aid_reg_Jobs(-1229,"Jobs");
static AtomicID::Register aid_reg_SolvableParm(-1362,"SolvableParm");
static AtomicID::Register aid_reg_SolvableFlag(-1366,"SolvableFlag");
static AtomicID::Register aid_reg_PeelNrs(-1363,"PeelNrs");
static AtomicID::Register aid_reg_PredNrs(-1357,"PredNrs");
static AtomicID::Register aid_reg_Ant1(-1367,"Ant1");
static AtomicID::Register aid_reg_Ant2(-1368,"Ant2");
static AtomicID::Register aid_reg_AntMode(-1355,"AntMode");
static AtomicID::Register aid_reg_CorrSel(-1359,"CorrSel");
static AtomicID::Register aid_reg_Niter(-1356,"Niter");
static AtomicID::Register aid_reg_UseSVD(-1361,"UseSVD");
static AtomicID::Register aid_reg_CalcUVW(-1360,"CalcUVW");
static AtomicID::Register aid_reg_ModelType(-1364,"ModelType");
static AtomicID::Register aid_reg_MEP(-1358,"MEP");
static AtomicID::Register aid_reg_GSM(-1365,"GSM");
static AtomicID::Register aid_reg_Save(-1369,"Save");
static AtomicID::Register aid_reg_Parms(-1370,"Parms");
static AtomicID::Register aid_reg_Residuals(-1257,"Residuals");
static AtomicID::Register aid_reg_SolvParams(-1378,"SolvParams");
static AtomicID::Register aid_reg_Rank(-1372,"Rank");
static AtomicID::Register aid_reg_Fit(-1373,"Fit");
static AtomicID::Register aid_reg_Errors(-1374,"Errors");
static AtomicID::Register aid_reg_CoVar(-1376,"CoVar");
static AtomicID::Register aid_reg_Flag(-1207,"Flag");
static AtomicID::Register aid_reg_Mu(-1377,"Mu");
static AtomicID::Register aid_reg_StdDev(-1375,"StdDev");
static AtomicID::Register aid_reg_Chi(-1371,"Chi");
static AtomicID::Register aid_reg_Peel(-1333,"Peel");
static AtomicID::Register aid_reg_Solve(-1384,"Solve");
static AtomicID::Register aid_reg_Iter(-1334,"Iter");
static AtomicID::Register aid_reg_Num(-1140,"Num");
static AtomicID::Register aid_reg_Intermediate(-1386,"Intermediate");
static AtomicID::Register aid_reg_Final(-1385,"Final");
static AtomicID::Register aid_reg_Current(-1390,"Current");
static AtomicID::Register aid_reg_Start(-1134,"Start");
static AtomicID::Register aid_reg_End(-1131,"End");
static AtomicID::Register aid_reg_Time(-1218,"Time");
static AtomicID::Register aid_reg_Tile(-1123,"Tile");
static AtomicID::Register aid_reg_Count(-1108,"Count");
static AtomicID::Register aid_reg_Stop(-1138,"Stop");
static AtomicID::Register aid_reg_Iteration(-1148,"Iteration");
static AtomicID::Register aid_reg_Solution(-1147,"Solution");
static AtomicID::Register aid_reg_Message(-1067,"Message");
static AtomicID::Register aid_reg_Next(-1150,"Next");
static AtomicID::Register aid_reg_Data(-1107,"Data");
static AtomicID::Register aid_reg_All(-1151,"All");
static AtomicID::Register aid_reg_Params(-1135,"Params");
static AtomicID::Register aid_reg_Solved(-1230,"Solved");
static AtomicID::Register aid_reg_Index(-1045,"Index");
static AtomicID::Register aid_reg_Accept(-1337,"Accept");
static AtomicID::Register aid_reg_When(-1335,"When");
static AtomicID::Register aid_reg_Max(-1149,"Max");
static AtomicID::Register aid_reg_Converged(-1336,"Converged");
static AtomicID::Register aid_reg_Command(-1338,"Command");
static AtomicID::Register aid_reg_Add(-1087,"Add");
static AtomicID::Register aid_reg_Queue(-1339,"Queue");
static AtomicID::Register aid_reg_Single(-1354,"Single");
static AtomicID::Register aid_reg_Defer(-1389,"Defer");
static AtomicID::Register aid_reg_IDLE(-1340,"IDLE");
static AtomicID::Register aid_reg_ENDSOLVE(-1341,"ENDSOLVE");
static AtomicID::Register aid_reg_NEXT_DOMAIN(-1342,"NEXT_DOMAIN");

