#!/bin/sh

curPath=`pwd`
if [ "$OSTYPE" = "win32" ]; then
  curPath=C:`pwd`
fi

#
#  Default Stationname, change when needed
#
StationName="CS010"


#
# Set DBSynchronisation to DB number (can be found in list later)
#
PVSStoolSyncTypes -system 10 $StationName -project $1


#
# set distributed system on in the project
#
cp config/config config/config.orig
cp ../LOFAR/MAC/Navigator/config/config.station config/config

export PVSS_II=$curPath/config/config
cp config/progs config/progs.orig
cp ../LOFAR/MAC/Navigator/config/progs.station config/progs


mkdir scripts/libs/nav_fw
cp ../LOFAR/MAC/Navigator/scripts/libs/nav_fw/gcf_util.ctl scripts/libs/nav_fw
cp ../LOFAR/MAC/Navigator/scripts/libs/monitorStateChanges.ctl scripts/libs

#
# Start project in background
#
PVSS00pmon -proj $1 &

#
# Wait  some time untill pmon is running
#
echo -n "Taking some time to give the pmon a chance to start..."
sleep 60
echo "(done)"
#
# empty the database from demo stuff (this has catastrofal results for now, 
# allthough it does the right thing, it renders the database useless, so ETM 
# is working on a solution for this. Conclusion is:
# Keep ANALOG2 (used in poowerconfigs) and ExampleDP_Float (used as default point in sumalert lists)
# even after this there seem to happen some strange things. So for now let's keep them in the system.
#
#echo -n "empty the database from demo stuff"
#PVSS00ctrl -script emptyDatabase.ctl -currentproj; echo "(done)"


echo -n "Importing fixed datapoints..."

if [ "$OSTYPE" != "win32" ]; then
   cd ../Deployment/data/PVSS/
   ./create_db_files -s CS010
   ./create_db_files -o Observation_10 -s CS010

fi

#
# load (default) fixed datapoints for a Station (CS010) and an observation
# (Observation_10) in the database
#
PVSS00ascii -in ../LOFAR/MAC/Navigator/CS010Datapointtypes.dpl -currentproj; echo "(done)"
PVSS00ascii -in ../LOFAR/MAC/Navigator/CS010PermDatapoints.dpl -currentproj; echo "(done)"
PVSS00ascii -in ../LOFAR/MAC/Navigator/CS010ObsDatapoints.dpl -currentproj; echo "(done)"
cd $curPath

cp ../LOFAR/MAC/Navigator/scripts/libs/nav_fw/gcfpa-prep.ctl scripts
#
# prepare project to enable use of GCF based MAC controllers
#
echo -n "Prepare project to enable use of GCF based MAC controllers..."
PVSS00ctrl -script gcfpa-prep.ctl -currentproj; echo "(done)"

#
#shut down project
#
PVSS00pmon -currentproj -stopWait






