#!/bin/sh

# makeCombinedImage-part: The distributed part of makeCombinedImage*
#
# Copyright (C) 2009
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$

# Find the path used to start the script.
pgmpath=`dirname $0`
pgmpath=`cd $pgmpath > /dev/null 2>&1  &&  pwd`

if test $# != 5; then
  echo "run as:  makeCombinedImages-part rank ms-part parsetfile imageext dry"
  exit 1
fi

# Get the arguments.
rank=$1
ms=$2
parset=$3
imgext=$4
dry=$5

# Combine the facets.
if test "$dry" = dry; then
  # In dry mode sleep to make sure the output is in the correct order.
  sleep $rank
  echo "combineFacets $parset $ms $imgext"
  cat $parset
else
  echo "combineFacets $parset $ms $imgext"
  combineFacets $parset $ms "$imgext"
fi
