/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class otb_navigatorRMIImpl */

#ifndef _Included_otb_navigatorRMIImpl
#define _Included_otb_navigatorRMIImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef otb_navigatorRMIImpl_serialVersionUID
#define otb_navigatorRMIImpl_serialVersionUID -3215090123894869218LL
#undef otb_navigatorRMIImpl_serialVersionUID
#define otb_navigatorRMIImpl_serialVersionUID -4100238210092549637LL
#undef otb_navigatorRMIImpl_serialVersionUID
#define otb_navigatorRMIImpl_serialVersionUID 4974527148936298033LL
/*
 * Class:     otb_navigatorRMIImpl
 * Method:    getDBList
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_otb_navigatorRMIImpl_getDBList
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
