#!/usr/bin/env python

import lofar.mstools as lmt
import sys

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print ''
        print 'Insufficient arguments; run as:'
        print '    expandimageps parsetin parsetout [nsubbands [nodeindex]'
        print '        nsubbands    number of subbands in a single image'
        print '                     default = 10'
        print '        nodeindex    subband whose node to use to run the imaging pipeline on'
        print '                     default = 0'
        print ''
        sys.exit(1)
    nsubbands = 10
    nodeindex = 0
    if len(sys.argv) > 3:
        nsubbands = int(sys.argv[3])
    if len(sys.argv) > 4:
        nodeindex = int(sys.argv[4])
    # See if the MS pattern is given.
    msname = 'msin'
    if len(sys.argv) > 3  and  len(sys.argv[3]) > 0:
        msname = [sys.argv[3]]
    # See if the ParmDB pattern is given.
    pdbname = 'pdbin'
    if len(sys.argv) > 4  and  len(sys.argv[4]) > 0:
        pdbname = [sys.argv[4]]
    # See if the MS output name is given.
    outname = 'msout'
    if len(sys.argv) > 5  and  len(sys.argv[45]) > 0:
        outname = [sys.argv[5]]
    lmt.expandps (sys.argv[1], sys.argv[2],
                  {'in': [['msin', 'Input_Correlated']],
                   'out': [['imgout', 'Output_SkyImage']]},
                   nsubbands, nodeindex)
