#!/usr/bin/python
# $Id: radbservice 33373 2016-01-22 11:01:15Z schaap $

'''
runs the resourceassignment postgres database listener and sends EventMessages to the lofar bus
'''
import logging

logging.basicConfig(format='%(asctime)s %(levelname)s %(message)s', level=logging.INFO)
logger = logging.getLogger(__name__)

from optparse import OptionParser
from lofar.sas.resourceassignment.database import radbpglistener
from lofar.sas.resourceassignment.database.config import DEFAULT_BUSNAME

if __name__ == '__main__':
    # Check the invocation arguments
    parser = OptionParser("%prog [options]",
                          description='runs the resourceassignment postgres database listener and sends EventMessages to the lofar bus')
    parser.add_option("-b", "--busname", dest="busname", type="string", default=DEFAULT_BUSNAME, help="Name of the bus exchange on the qpid broker, default: %s" % DEFAULT_BUSNAME)
    (options, args) = parser.parse_args()

    radbpglistener.main(busname=options.busname)
