#!/bin/csh -f

### ################################################################################
### Substitier 'MonFichierDeDonnees', 'PrefixDeSorties' et 'MapWeights.map' par des
### valeurs a vous:
###
###   - 'MonFichierDeDonnees' est le nom du foichier de donnees au
###     format Spoutnik.
###
###   - 'MapWeights.map' est le fichier de la MAP calcule prealablement par SOM.
###
###   - 'PrefixDeSorties' est le prefix qui auront les fichiers crees
###     par PRSOM. Voir commentaires plus bas.
### ################################################################################

# Chemin d'acces aux executables
set BINDIR   = /mesiow0/jdromer/spoutnik/Spoutnik/src

# \rm ${PRSOM_CASE}_PRSOM_* >& /dev/null

### ################################################################################
### APPEL AU PROGRAMME
### ################################################################################
### Changer ici les arguments du programme:

${BINDIR}/prsom -overwrite -map-size 2 9 9         \
                 -cycles-mean 6500 100     \
                 -smooth-dist-mean 1 0.08 \
                 sauvegardecont2.txt holcont2__SOM_Wei.map prholcont2_ 

################################################################################
### 
### Calling program 'prsom':
### 	prsom [options] <LearnFile> <MapFile> <FilePrefix>
### 
### Arguments:
###         <LearnFile> ....... fichier de formes a classer.
###         <MapFile> ......... fichier des poids issue de SOM.
###         <FilePrefix> ...... prefix des fichiers de sortie qui seront :
###              - <FilePrefix>_PRSOM_Wei.map ........ poids de la carte.
###              - <FilePrefix>_PRSOM_WeiCard.map .... poids + cardinalite pour Sammon.
###              - <FilePrefix>_PRSOM_WeiVar.map ..... poids + variance pour Sammon.
###              - <FilePrefix>_PRSOM_Card.res ....... cardinalite chaque neurone.
###              - <FilePrefix>_PRSOM_Var.res ........ variance de chaque neurone.
###              - <FilePrefix>_PRSOM_WFEP.res ....... neurone gagnant par forme.
###              - <FilePrefix>_PRSOM_Acti.res ....... activation de chaque exemple
###                dans la fonction densite de chaque neurone.
### 
### List of options:
###                 -test-file <TestSetFileName> :
###                                  to indicate the name of the
###                                  file to test. Default = NULL.
###                 -var-file <VariancesFileName> :
###                                  to indicate the name of the variances
###                                  map file to test. Default = NULL.
###                 -map-size <MapDim> <MapSize1> .. <MapSizeN> :
###                                  Map dimension and size.
###                                  Default = 2 dimensions, 10x10
###                 -map-min-val <MapMinValue> :
###                                  Real value with min map value. This will be
###                                  the same for all dimensions of input data.
###                                  Default = -1.000000
###                 -map-min <MapMinString> :
###                                  string with min map value. Give as many
###                                  values as dimensions of input data.
###                                  Default is related to <MapMinValue> default value.
###                 -map-max-val <MapMaxValue> :
###                                  Real value with max map value. This will be
###                                  the same for all dimensions of input data.
###                                  Default = 1.000000
###                 -map-max <MapMaxString> :
###                                  string with max map value. Give as many
###                                  values as dimensions of input data
###                                  Default is related to <MapMaxValue> default value.
###                 -cycles-var <NbCyclesVar> <FrequenceTestsVar> :
###                                  Number of learning cycles and test frequency (in cycles)
###                                  for Variance computation. Default = [50, 1].
###                 -smooth-dist-var <SmoothDistanceValVar> :
###                                  Value of smooth distance for Variance
###                                  computation. Default = 3.0.
###                 -cycles-mean <NbCyclesMean> <FrequenceTestsMean> :
###                                  Number of learning cycles and test frequency (in cycles)
###                                  for Mean computation. Default = [200, 10].
###                 -smooth-dist-mean <SmoothDistanceMeanMaximum> <SmoothDistanceMeanMinimum> :
###                                  Maximal and minimal value of smooth
###                                  distance for Mean computation. Default = [1.0, 0.1].
###                 -threshold-neigh-var <SomThresholdNeighborVar> :
###                 -threshold-neigh-mean <SomThresholdNeighborMean> :
###                                  indicates, for Variance and MEAN cycles,
###                                  the threshold, farther than that,
###                                  neighborhood doesnt counts.
###                                  Default <SomThresholdNeighborVar> = 0.001000
###                                  Default <SomThresholdNeighborMean> = 0.001000
###                 -best-contrast <Frequency> :
###                                  Activates flag to allow to save weights if
###                                  best contrast. Default = 0.
###                 -best-rms <Frequency> :
###                                  Activates flag to allow to save weights if
###                                  best RMS. Default = 0.
###                 -trace-map <Frequency> :
###                                  Activates flag to allow to save weights at
###                                  each <Frequency> iterations. Default = 0.
###                 -overwrite :
###                                  Flag to allow overwriting all output files if already
###                                  exists. Default = OFF.
### 
################################################################################
