#!/bin/csh -f

### ################################################################################

# Chemin d'acces aux executables
set BINDIR   = /usr/local/Spoutnik/Lnx86/bin/

# \rm ${CASE}_SOM_* >& /dev/null

### ################################################################################
### APPEL AU PROGRAMME
### ################################################################################
### Changer ici les arguments du programme:

${BINDIR}/CAH  <ARGUMENTS> ...


### ################################################################################
### Calling program './Lnx86/bin/CAH':
###         ./Lnx86/bin/CAH [options] <SomIndexFile> <CardFile> <OutIndexMapFile> <OutIndexSaMapFile>
### or after 'prsom':
###         ./Lnx86/bin/CAH [options] <SomIndexFile> <CardFile> <VarFile> <OutIndexMapFile> <OutIndexSaMapFile>
### 
### Arguments:
###         <SomIndexFile> ....... neurones partiellement indexes par somindex.
###         <CardFile> ........... cardinalite des neurones (som).
###         <VarFile> ............ variance des neurones (uniquement si prsom).
###         <OutIndexMapFile> .... sortie : neurones entierement indexes par CAH pour somlabel.
###         <OutIndexSaMapFile> .. sortie : neurones entierement indexes pour sammon.
### 
### List of options:
###                 -topol <MapTopology> :
###                                  to indicate the topology of the
###                                  map {'hexa', 'rect'}. Default = 'hexa'.
###                 -iopt <ClusterIndex> :
###                                  to indicate the clustering index
###                                  used to compute distances. Default = 1.
###                                  Use 8 in case of 'prsom' input.
### ################################################################################
