#!/bin/csh -f

#\rm ${CASE}.res >& /dev/null

# Chemin d'acces aux executables
set BINDIR   = /mesiow0/jdromer/spoutnik/Spoutnik/src

### ################################################################################
### APPEL AU PROGRAMME
### ################################################################################
### Changer ici les arguments du programme:

${BINDIR}/somproba -n-class 10 -n-choice 3 prholcont2_IndexMap.map prholcont2__PRSOM_Card.res prholcont2__PRSOM_Acti.res label.res Probaholcont2.res 


################################################################################
### 
### Calling program 'somproba':
###         somproba [options]  <MapFile> <CardFile> <ActFile> <ResFile> <OutFile>
### 
### Arguments:
###         <MapFile> ........ la carte des neurones labellises par la CAH.
###         <CardFile> ....... cardinalite des neurones.
###         <ActFile> ........ activation de la forme x dans les lois normales
###                            des referents.
###         <ResFile> ........ numero de la classe a laquelle est associe chaque
###                            forme.
###         <OutFile> ........ sortie : les N-CHOICE classes de plus grande probabilite
###                            pour chaque forme.
### 
### List of options:
###                 -n-class <nClass> :
###                                  Number of true classes.
###                                  Default = 12.
###                 -n-choice <nChoice> :
###                                  number of choices for classes of greatest
###                                  probability. Default = 3.
###                 -threshold <Treshold> :
###                                  Treshold of minimal probability for consider
###                                  a class. Default = 0.1.
### 
################################################################################
