#!/bin/csh -f

### ################################################################################
### Substitier 'MonFichierDeDonnees', 'PrefixDeSorties' et 'MapWeights.map' par des
### valeurs a vous:
###
###   - 'MonFichierDeDonnees' est le nom du foichier de donnees au
###     format Spoutnik.
###
###   - 'MapWeights.map' est le fichier de la MAP calcule prealablement par SOM ou PRSOM.
###
###   - 'FicVariance' est le fichier de la MAP calcule prealablement par SOM ou PRSOM.
###
###   - 'PrefixDeSorties' est le prefix qui auront les fichiers crees
###     par TEST_PSOM. Voir commentaires plus bas.
### ################################################################################

# Chemin d'acces aux executables
set BINDIR   = /usr/local/Spoutnik/Lnx86/bin/

# \rm ${PRSOM_CASE}_PRSOM_* >& /dev/null

### ################################################################################
### APPEL AU PROGRAMME
### ################################################################################
### Changer ici les arguments du programme:

${BINDIR}/test_psom \
                 MonFichierDeDonnees MapWeights.map FicVariance PrefixDeSorties

################################################################################
### 
### Calling program './test_psom':
###         ./test_psom [options] <TestSetFile> <MapFile> <VarFile> <FilePrefix>
### 
### Arguments:
###         <TestFile> ........ fichier de formes a tester.
###         <MapFile> ......... fichier des poids issue de SOM ou PRSOM.
###         <VarFile> ......... fichier des variances a reprendre.
###         <FilePrefix> ...... prefix des fichiers de sortie qui seront :
###           - <FilePrefix>_TPSOM_Wei.map ........ poids de la carte.
###           - <FilePrefix>_TPSOM_WeiCard.map .... poids + cardinalite pour Sammon.
###           - <FilePrefix>_TPSOM_WFEP.res ....... neurone gagnant par forme.
###           - <FilePrefix>_TPSOM_Card.res ....... cardinalite chaque neurone.
###           - <FilePrefix>_TPSOM_Acti.res ....... activation de chaque exemple
###             dans la fonction densite de chaque neurone.
### 
### List of options:
###                 -overwrite :
###                                  Flag to allow overwriting all output files if already
###                                  exists. Default = OFF.
### 
################################################################################
