#!/bin/bash
#
# Script to start the OTB (on sas001)
# Change the first lines when an update is done 
#

export serverDir=/opt/sas/server_Version21
export clientDir=/opt/sas/client_Version21
export JAVAHOME=/usr/java/jdk1.6.0_07

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$serverDir


serverpid=0
ps -ef | grep -v grep | grep java | grep 13599    2>&1 1>/dev/null
if [ $? -ne 0 ]; then
        $JAVAHOME/bin/java -jar $serverDir/jOTDB2.jar paulus boskabouter LOFAR20 sas001 sas001 13599 13600 &
    serverpid=$!
fi

$JAVAHOME/bin/java -jar $clientDir/OTB.jar -p 13599


if [ $serverpid -ne 0 ]; then
   echo "Stopping server"
   kill $serverpid
   sleep 1
fi
