#!/bin/sh

# fillParamTables: fill parameter database for BlackBoardDemo
#
#  Copyright (C) 2004
#  ASTRON (Netherlands Foundation for Research in Astronomy)
#  P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#  $Id$

# the following options can be given:
# -dbtype  Database type (right now only monet, postgres and mysql are supported)
# -host    Host (default = localhost)
# -user    User
# -filler  Path to the program that puts the default parameters in the tables 
#          (default is ./src/fillsqldb)

TABLEFILLER="src/fillsqldb"

DBTYPE="mysql"
HOST="localhost"
USER="zwart"

while [ 1 = 1 ]
do
  if [ "$1" = "-host" ]; then
    shift
    HOST="$1"
    shift
  elif [ "$1" = "-dbtype" ]; then
    shift
    DBTYPE="$1"
    shift
  elif [ "$1" = "-user" ]; then
    shift
    USER="$1"
    shift
  elif [ "$1" = "-filler" ]; then
    shift
    TABLEFILLER="$1"
    shift
  else
    break;
  fi
done


PARMDBCONNECT="connect db='$USER', dbtype='$DBTYPE', host='$HOST', user ='$USER'"
if [ "$DBTYPE" = "monet" ]; then
# for monet the user needs to monetdb (for now):
    PARMDBCONNECT="connect db='$USER', dbtype='$DBTYPE', host='$HOST', user ='monetdb'"
fi

for n in 1 2 3 4 5 6 ; do
    tablename=meqmodel$n
    echo $PARMDBCONNECT ",  tablename='${tablename}'" > fill.parmdb
    for name in a b c d e f g h i j k l m n o p q r s t u v w x y ; do
	number=0
#	while [ $number -le 40 ] ; do
	while [ $number -le 400 ] ; do
	    echo "add ${name}dummy${number} values=0" >> fill.parmdb
#	    echo "add ${name}dummy${number} values=0 domain='[ 0.1 0.9 0.1 0.9 ]'" >> fill.parmdb
	    number=$(($number+1))
	done
    done
    echo "quit" >> fill.parmdb
    $TABLEFILLER < fill.parmdb
    
    tablename=skymodel$n
    echo $PARMDBCONNECT ", tablename='${tablename}'" > fill.parmdb
    for name in a b c d e f g h i j k l m n o p q r s t u v w x y ; do
	number=0
#	while [ $number -le 4 ] ; do
	while [ $number -le 40 ] ; do
	    echo "add ${name}dummy${number} values=0" >> fill.parmdb
	    number=$(($number+1))
	done
    done
#      echo "add RA.CP1 values=10:26:35.0" >> fill.parmdb
    echo "quit" >> fill.parmdb
    $TABLEFILLER < fill.parmdb
done
