#!/bin/sh

# fillDefaultTables: fill database for BlackBoardDemo
#
#  Copyright (C) 2004
#  ASTRON (Netherlands Foundation for Research in Astronomy)
#  P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#  $Id$

# the following options can be given:
# -dbtype  Database type (right now only monet, postgres and mysql are supported)
# -host    Host (default = localhost)
# -user    User
# -filler  Path to the program that puts the default parameters in the tables 
#          (default is ./src/fillsqldb)

TABLEFILLER="src/fillsqldb"

DBTYPE="mysql"
HOST="localhost"
USER=`whoami`

while [ 1 = 1 ]
do
  if [ "$1" = "-host" ]; then
    shift
    HOST="$1"
    shift
  elif [ "$1" = "-dbtype" ]; then
    shift
    DBTYPE="$1"
    shift
  elif [ "$1" = "-user" ]; then
    shift
    USER="$1"
    shift
  elif [ "$1" = "-filler" ]; then
    shift
    TABLEFILLER="$1"
    shift
  else
    break;
  fi
done


PARMDBCONNECT="connect db='$USER', dbtype='$DBTYPE', host='$HOST', user ='$USER'"
if [ "$DBTYPE" = "monet" ]; then
# for monet the user needs to monetdb (for now):
    PARMDBCONNECT="connect db='$USER', dbtype='$DBTYPE', host='$HOST', user ='monetdb'"
fi

for n in 1 2 3 4 5 6 ; do
    tablename=meqmodel$n
    echo $PARMDBCONNECT ",  tablename='${tablename}'" > fill.parmdb
    echo "adddef frot values=0" >> fill.parmdb
    echo "adddef drot values=0" >> fill.parmdb
    echo "adddef dell values=0" >> fill.parmdb
    echo "adddef gain.11 values=1" >> fill.parmdb
    echo "adddef gain.22 values=1" >> fill.parmdb
    echo "adddef EJ11.real.SR1.CP1 values=1" >> fill.parmdb
    echo "adddef EJ11.real.SR1.CP2 values=1" >> fill.parmdb
    echo "adddef EJ11.real.SR1.CP3 values=1" >> fill.parmdb
    echo "adddef EJ11.real.SR2.CP1 values=1" >> fill.parmdb
    echo "adddef EJ11.real.SR2.CP2 values=1" >> fill.parmdb
    echo "adddef EJ11.real.SR2.CP3 values=1" >> fill.parmdb
    echo "adddef EJ11.real.SR5.CP1 values=1" >> fill.parmdb
    echo "adddef EJ11.real.SR5.CP2 values=1" >> fill.parmdb
    echo "adddef EJ11.real.SR5.CP3 values=1" >> fill.parmdb
    echo "adddef EJ11.real.SR9.CP1 values=1" >> fill.parmdb
    echo "adddef EJ11.real.SR9.CP2 values=1" >> fill.parmdb
    echo "adddef EJ11.real.SR9.CP3 values=1" >> fill.parmdb
    echo "adddef EJ11.real values=1" >> fill.parmdb
    echo "adddef EJ12.real values=0" >> fill.parmdb
    echo "adddef EJ21.real values=0" >> fill.parmdb
    echo "adddef EJ22.real values=1" >> fill.parmdb
    echo "adddef EJ11.imag values=1" >> fill.parmdb
    echo "adddef EJ12.imag values=0" >> fill.parmdb
    echo "adddef EJ21.imag values=0" >> fill.parmdb
    echo "adddef EJ22.imag values=1" >> fill.parmdb
    echo "quit" >> fill.parmdb
    $TABLEFILLER < fill.parmdb
    
    tablename=skymodel$n
    echo $PARMDBCONNECT ", tablename='${tablename}'" > fill.parmdb
    echo "adddef RA.CP1 values=10:26:35.0" >> fill.parmdb
    echo "adddef DEC.CP1 values=26.0.0.0" >> fill.parmdb
    echo "adddef StokesI.CP1 values=1.0" >> fill.parmdb
    echo "adddef StokesQ.CP1 values=0 " >> fill.parmdb
    echo "adddef StokesU.CP1 values=0 " >> fill.parmdb
    echo "adddef StokesV.CP1 values=0" >> fill.parmdb
    echo "adddef RA.CP2 values=10:26:35.4" >> fill.parmdb
    echo "adddef DEC.CP2 values=26.0.21.0" >> fill.parmdb
    echo "adddef StokesI.CP2 values=1.0" >> fill.parmdb
    echo "adddef StokesQ.CP2 values=0 " >> fill.parmdb
    echo "adddef StokesU.CP2 values=0 " >> fill.parmdb
    echo "adddef StokesV.CP2 values=0" >> fill.parmdb
    echo "adddef RA.CP3 values=10:26:37.1" >> fill.parmdb
    echo "adddef DEC.CP3 values=25.59.49.0" >> fill.parmdb
    echo "adddef StokesI.CP3 values=1.0" >> fill.parmdb
    echo "adddef StokesQ.CP3 values=0 " >> fill.parmdb
    echo "adddef StokesU.CP3 values=0 " >> fill.parmdb
    echo "adddef StokesV.CP3 values=0" >> fill.parmdb
    
    echo "adddef RA.CP4 values=10:26:34.8" >> fill.parmdb
    echo "adddef DEC.CP4 values=25.59.39.0" >> fill.parmdb
    echo "adddef StokesI.CP4 values=1.0" >> fill.parmdb
    echo "adddef StokesQ.CP4 values=0 " >> fill.parmdb
    echo "adddef StokesU.CP4 values=0 " >> fill.parmdb
    echo "adddef StokesV.CP4 values=0" >> fill.parmdb
    
    echo "adddef RA.CP5 values=10:26:36.3" >> fill.parmdb
    echo "adddef DEC.CP5 values=26.0.11.0" >> fill.parmdb
    echo "adddef StokesI.CP5 values=1.0" >> fill.parmdb
    echo "adddef StokesQ.CP5 values=0 " >> fill.parmdb
    echo "adddef StokesU.CP5 values=0 " >> fill.parmdb
    echo "adddef StokesV.CP5 values=0" >> fill.parmdb
    
    echo "adddef RA.CP6 values=10:26:36.1" >> fill.parmdb
    echo "adddef DEC.CP6 values=25.59.59.0" >> fill.parmdb
    echo "adddef StokesI.CP6 values=1.0" >> fill.parmdb
    echo "adddef StokesQ.CP6 values=0 " >> fill.parmdb
    echo "adddef StokesU.CP6 values=0 " >> fill.parmdb
    echo "adddef StokesV.CP6 values=0" >> fill.parmdb
    
    echo "adddef RA.CP7 values=10:26:37.6" >> fill.parmdb
    echo "adddef DEC.CP7 values=25.59.56.0" >> fill.parmdb
    echo "adddef StokesI.CP7 values=1.0" >> fill.parmdb
    echo "adddef StokesQ.CP7 values=0 " >> fill.parmdb
    echo "adddef StokesU.CP7 values=0 " >> fill.parmdb
    echo "adddef StokesV.CP7 values=0" >> fill.parmdb

    echo "adddef RA.CP8 values=10:26:34.5" >> fill.parmdb
    echo "adddef DEC.CP8 values=25.59.51." >> fill.parmdb
    echo "adddef StokesI.CP8 values=1.0" >> fill.parmdb
    echo "adddef StokesQ.CP8 values=0 " >> fill.parmdb
    echo "adddef StokesU.CP8 values=0 " >> fill.parmdb
    echo "adddef StokesV.CP8 values=0" >> fill.parmdb

    echo "adddef RA.CP9 values=10:26:36.6" >> fill.parmdb
    echo "adddef DEC.CP9 values=26.0.15.5" >> fill.parmdb
    echo "adddef StokesI.CP9 values=1.0" >> fill.parmdb
    echo "adddef StokesQ.CP9 values=0 " >> fill.parmdb
    echo "adddef StokesU.CP9 values=0 " >> fill.parmdb
    echo "adddef StokesV.CP9 values=0" >> fill.parmdb

    echo "adddef RA.CP10 values=10:26:35.6" >> fill.parmdb
    echo "adddef DEC.CP10 values=26.0.0.0" >> fill.parmdb
    echo "adddef StokesI.CP10 values=1.0" >> fill.parmdb
    echo "adddef StokesQ.CP10 values=0 " >> fill.parmdb
    echo "adddef StokesU.CP10 values=0 " >> fill.parmdb
    echo "adddef StokesV.CP10 values=0" >> fill.parmdb
    echo "quit" >> fill.parmdb
    $TABLEFILLER < fill.parmdb

done
