#!/bin/sh

# Run the ExamplePL4 test program.
# First an empty database table is created.
# Thereafter the test program is run.
# If an argument is given to the script, the test program is not run
# making it possible to run the test program separately (e.g. to debug it).

# Create the database table.
psql -h dop50.astron.nl -U postgres test << _EOF_ > ExamplePL4_tmp.psql_out 2>&1
\i ../../../test/ExamplePL2.sql
\q
_EOF_

# Run the test program if no first argument is given.
if [ "$1" = "" ]; then
#  ~/bin/valgrind --tool=memcheck --num-callers=50 --workaround-gcc296-bugs=yes --leak-check=yes --track-fds=yes ./ExamplePL4
  ./ExamplePL4
  STATUS=$?
  if [ $STATUS != 0 ]; then
    exit $STATUS
  fi
fi

# Show the contents of the database.
psql -h dop50.astron.nl -U postgres test << _EOF_
select tag,seqnr,counter from ExamplePL2
\q
_EOF_
