package nl.astron.lofar.mac.apl.gui.jrsp.panels;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import nl.astron.lofar.mac.apl.gui.jrsp.Board;

/**
 * This is the main panel for the WaveformSettings.
 * @author  balken
 */
public class WaveformSettingsPanel extends JPanel implements ActionListener
{
    /** Board instance */
    private Board board;
    
    /** 
     * Creates new form WaveformSettingsPanel.
     */
    public WaveformSettingsPanel() 
    {
        board = null;
        
        initComponents();
        
        inputPanel.addActionListener(this);
    }
    
    /**
     * Get board.
     * @return  board
     */
    public Board getBoard()
    {
        return board;
    }
    
    /**
     * Set board.
     * @param   board
     */
    public void setBoard(Board board)
    {
        this.board = board;
    }
    
    /**
     * Invoked when a action occured; btnSumbit on the inputpanel pressed.
     * Note: board has to be set.
     * @TODO: Set RCUMask
     */
    public void actionPerformed(ActionEvent e)
    {
        if(board == null)
        {
            return;
        }
        
        int rcuMask = 0;
        int mode = 0;
        int frequency = 0;
        int amplitude = 0;
        try
        {
            mode = Integer.parseInt(inputPanel.getMode());
            frequency = Integer.parseInt(inputPanel.getFrequency());
            amplitude = Integer.parseInt(inputPanel.getAmplitude());
        }
        catch(NumberFormatException nfe)
        {
            JOptionPane.showMessageDialog(null, "Incorrect value discovered. All fields should contain a positive value.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        board.setWaveformSettings(rcuMask, mode, frequency, amplitude);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        inputPanel = new nl.astron.lofar.mac.apl.gui.jrsp.panels.WaveformSettingsInputPanel();

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(inputPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .add(inputPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nl.astron.lofar.mac.apl.gui.jrsp.panels.WaveformSettingsInputPanel inputPanel;
    // End of variables declaration//GEN-END:variables
}