#!/bin/sh
RUNDEMOPATH=`echo $0 | sed 's/\/rundemo$//'`
cd $RUNDEMOPATH

AIPSROOT=%AIPSROOT%
if test "$AIPSROOT" = "%AIPSROOT%"; then
	AIPSROOT=/aips++/weekly
fi
MEQ_PATH=../../CPA/CAL/build/gnu_opt/src
PATH=$PATH:$MEQ_PATH:.
echo -n Using:
which meqcalibrater
if test ! $?; then
	echo "Please compile LOFAR/CEP/CPA/CAL to produce LOFAR/CEP/CPA/CAL/build/gnu_opt/src/meqcalibrater"
	exit
fi
tar zxvf pss1.demo.tgz && \
ln -sf ../../CPA/CAL/src/*.g . && \
. $AIPSROOT/aipsinit.sh && \
glish -l rundemo.glish
