#!/bin/sh

# tmakesourcedb.run: Script to test makesourcedb
#
# Copyright (C) 2008
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$

# Remove the Version line from the output because it is system dependent.
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="< " | grep -v ' Version '
../src/parmdb_main tmakesourcedb_tmp.stdout > /dev/null <<EOF
open tablename='tmakesourcedb_tmp.sdb'
showdef
EOF
cat tmakesourcedb_tmp.stdout

echo ""
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="category=fixed'1',Name,Type,Ra,Dec,I,Q,U,V,SpInx='0.5',Major,Minor,Phi" | grep -v ' Version '
../src/parmdb_main tmakesourcedb_tmp.stdout > /dev/null <<EOF
open tablename='tmakesourcedb_tmp.sdb'
showdef
EOF
cat tmakesourcedb_tmp.stdout

echo ""
../src/makesourcedb in=tmakesourcedb.in_2 out=tmakesourcedb_tmp.sdb append=0 format="category=fixed'3', patch=fixed'patch1' Name Type Rah ram ras Decd decm decs I, Q, U, V, SpInx=fixed'1.5', Major, Minor, Phi, a0:b=fixed'3.0'" | grep -v ' Version '
../src/parmdb_main tmakesourcedb_tmp.stdout > /dev/null <<EOF
open tablename='tmakesourcedb_tmp.sdb'
showdef
EOF
cat tmakesourcedb_tmp.stdout

echo ">>>"
if test "$1" != ""; then
python<<EOF
from pyrap.tables import *
t=table("tmakesourcedb_tmp.sdb/SOURCES/PATCHES")
print "patch nrow =",t.nrows()
for col in ["PATCHNAME", "CATEGORY", "APPARENT_BRIGHTNESS", "RA", "DEC"]:
  print col, "=", t.getcol(col);
t=table("tmakesourcedb_tmp.sdb/SOURCES")
print "source nrow =",t.nrows()
for col in ["SOURCENAME", "PATCHID", "SOURCETYPE"]:
  print col, "=", t.getcol(col);
EOF
fi
echo "<<<"

# Select using a cone
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="," center="" center="23deg,45.0.0.00" radius="1arcsec" | grep -v ' Version '
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="," center="" center="23deg,45.0.2.00" radius="1.9arcsec" | grep -v ' Version '
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="," center="" center="23deg,45.0.0.00" width="1arcsec" | grep -v ' Version '
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="," center="" center="23deg,45.0.2.00" width="10arcmin,4.1arcsec" | grep -v ' Version '
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="," center="" center="23deg,45.0.2.00" width="10arcmin,3.9arcsec" | grep -v ' Version '

