#!/usr/bin/env python

import lofar.mstools as lmt
import sys

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print ''
        print 'Insufficient arguments; run as:'
        print '  expandcalps parsetin parsetout nsubbands [mspattern, [instrname]]'
        print ''
        print ' If an mspattern is given, it must be the name of a directory'
        print ' containing the MeasurementSets or a glob-pattern matching the'
        print ' MeasurementSets to process. If a directory name is given,'
        print ' *.MS will be added to make it a glob pattern.'
        print ' If no or an empty mspattern is given, it means that the msin'
        print ' parameter in the input parset defines the glob-pattern for'
        print ' the MeasurementSets to process.'
        print ''
        print ' If an instrname is given, it must define the names of the'
        print ' output instrument model tables. It can contain the placeholders'
        print ' <DN>, <BN>, <BN.>, <.BN>, <SEQ>, <OBSID>, <SAP>, <SB>, <TYPE>.'
        print ' If no or an empty instrname is given, the instrout parameter in'
        print ' the input parset defines the output names'
        print ''
        print 'For example:'
        print '  expandcalps  in.parset  out.parset  80  /data/L45318'
        print '    /data/scratch/pipeline/L46175/L46175_<SAP>_<SB>_instr.instr'
        print ''
        if len(sys.argv) == 2  and  sys.argv[1] == '-h':
            help(lmt.expandps)
        sys.exit(1)

    # See if the MS pattern is given.
    inname = 'msin'
    if len(sys.argv) > 4  and  len(sys.argv[4]) > 0:
        # Add *.MS if no glob pattern given. Turn it into a list.
        inname = [lmt.addfileglob (sys.argv[4], '*.MS')]
    # See if the ParmDB name is given.
    outname = 'instrout'
    if len(sys.argv) > 5  and  len(sys.argv[5]) > 0:
        outname = [sys.argv[5]]
    # Expand the parset.
    lmt.expandps (sys.argv[1], sys.argv[2],
                  {'in': [(inname, 'Input_Correlated')],
                   'out': [(outname, 'Output_InstrumentModel')]},
                  int(sys.argv[3]))
