#!/bin/csh -f

### ################################################################################
### Substitier 'MonFichierDeDonnees' et 'PrefixDeSorties' par des
### valeurs a vous:
###
###   - 'MonFichierMAP' est le nom du fichier de la carte au
###     format Spoutnik.
###
###   - 'MonFicCard' est le nom du fichier de cardinalite.
###
###   - 'FicSortieIndexMap' est nom du fichie de sortie.
### ################################################################################

# Chemin d'acces aux executables
set BINDIR   = /mesiow0/jdromer/spoutnik/Spoutnik/src

### ################################################################################
### APPEL AU PROGRAMME
### ################################################################################
### Changer ici les arguments du programme:

${BINDIR}/CAHclass -iopt 8 -rewrite 2 10 prholcont2__PRSOM_Wei.map prholcont2__PRSOM_Card.res prholcont2__PRSOM_Var.res prholcont2_IndexMap 
   

### ################################################################################
### Calling program 'CAHclass':
###         CAHclass [options] <WhichClassifier> <NbOfClasses> <SomMapFile> <CardFile>  <OutIndexMapFile>
### 
### or:
###         CAHclass [options] <WhichClassifier> <NbOfClasses> <SomMapFile> <CardFile> <VarFile>  <OutIndexMapFile>
### 
### Arguments:
###         <WhichClassifier> .... 1 for SOM classiffier, 2 for PRSOM.
###         <NbOfClasses> ........ number of classes or number of clusters in largest partition.
###         <SomMapFile> ......... fichier de neurones partiellement issue de SOM/PRSOM.
###         <CardFile> ........... fichier de cardinalite des neurones (som).
###         <VarFile> ............ [Parameter ONLY for iopt=8] Fichier de variances (prsom).
###         <OutIndexMapFile> .... sortie : neurones entierement indexes par CAH pour somlabel.
### 
### List of options:
###                 -iopt <ClusterIndex> :
###                                  to indicate the clustering index
###                                  used to compute distances. Default = 1.
###                                  Use 8 in case of 'prsom' input.
###                 -rewrite :
###                                  to allows existing file rewriting for
###                                  output files. Default = <DISABLED>.
### 
### ################################################################################
