#!/bin/csh -f

###
### Exemple SOM de phase de convergence (il faut apporter l'ancien MAP)
###

# Chemin d'acces aux executables
set BINDIR   = /mesiow0/jdromer/spoutnik/Spoutnik/src/

# Si vous voulez effacer les fichiers
# \rm ${CASE}_SOM_* >& /dev/null

${BINDIR}/som -map-size 2 10 10       \
              -temp 0.8 0.08           \
              -learn-rate 0.037 0.001 \
              -cycles 6500 100        \
              -old-map holcont4__SOM_Wei.map \
	      sauvegardecont2.txt holcont5conv_
 
