function modulation_type(modulation_choice)

frm7Pos=[0.509 BottomBorder FrameWidth*4 FrameHeight/7 ];
frm7=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frm7Pos, ...
   'BackgroundColor', [0.6 0.5 0.5]);