function [s]=signal_func(hello);
global Time;
global Frequency;
global Time_signal;
global Band;
global Ampl;
global signal_name;
global signal_choice;
global Width;
global listbox_signal;
global res;
global s;
global rad1;
global rad2;
global rad3;
global rad4;
global freq2;
global Power_noise;

signal_choice=0;
signal_choice=hello;
FrameWidth = 0.12; 
LeftBorder = 0.05; 
BottomBorder=0.05; 
TotalWidth = 1 - 3*LeftBorder-FrameWidth ; TotalHeight = 1-2*BottomBorder;
FigSpace = 0.05;
Col1Width = 0.3*TotalWidth;
Col2Width = TotalWidth-Col1Width-FigSpace;
Lin1Height = 0.3*TotalHeight;
Lin2Height= TotalHeight-Lin1Height-FigSpace;
CompWidth=0.05;
CompHeight=0.03;
FrameBorder = 0.01;
LeftFrameBorder = LeftBorder + Col1Width+Col2Width+2*FigSpace;
FrameHeight = TotalHeight;
CompBackGroundColor = [0.5 0.5 0.5];


frm6Pos=[LeftFrameBorder*0.008+0.006 BottomBorder*8.4 FrameWidth*4 FrameHeight/4];
frm6=uicontrol(gcf,...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frm6Pos, ...
   'BackgroundColor', [0.6 0.5 0.5]);

if (signal_choice~=6 & signal_choice~=8 )
ComPos7=[];
ComPos7=[LeftFrameBorder*0.008+0.1 BottomBorder*11.6 CompWidth*1.3 CompHeight];
Frequency=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',ComPos7, ...
   'String','1000');

ComPos9=[];
ComPos9=[LeftFrameBorder*0.008+0.1 BottomBorder*12.3  CompWidth*1.3 CompHeight*0.8];
Frequency_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPos9, ...
   'String','Frequency');
end

if signal_choice~=8 
ComPos8=[];
ComPos8=[LeftFrameBorder*0.22 BottomBorder*11.6 CompWidth*1.3 CompHeight];
Ampl=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',ComPos8, ...
   'String','1');

ComPos10=[];
ComPos10=[LeftFrameBorder*0.22 BottomBorder*12.3  CompWidth*1.3 CompHeight*0.8];
Ampl_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPos10, ...
   'String','Ampl');
end

disp(['signal: ' num2str(signal_choice) '']);
ComPos11=[];
ComPos11=[LeftFrameBorder*0.03 BottomBorder*11.6  CompWidth*1.3 CompHeight*1.5];
Var_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPos11, ...
   'String',signal_name(signal_choice));

ComPos12=[];
ComPos12=[LeftFrameBorder*0.008+0.1 BottomBorder*10 CompWidth*1.3 CompHeight];
Time=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',ComPos12, ...
   'String',get(Time_signal,'String'));

ComPos13=[];
ComPos13=[LeftFrameBorder*0.008+0.1 BottomBorder*10.7 CompWidth*1.3 CompHeight*0.8];
time_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPos13, ...
   'String','Time(s)');


ComPos16=[];
ComPos16=[LeftFrameBorder*0.008+0.0175 BottomBorder*9.9 CompWidth*1.35 CompHeight*2.1];
Valide=uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',ComPos16, ...
   'String','Vision','Callback','Vision');

ComPos17=[];
ComPos17=[LeftFrameBorder*0.49 BottomBorder*11.5 CompWidth*1.5 CompHeight*2];
Addition=uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',ComPos17, ...
   'String','+','FontSize',18,'Callback',['Addition(' num2str(signal_choice) ')']);

Width=0;

if (signal_choice>2&signal_choice<7)
ComPos18=[];
ComPos18=[LeftFrameBorder*0.22 BottomBorder*10.7  CompWidth*1.3 CompHeight*0.8];
Width_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPos18, ...
   'String','Width');

ComPos14=[];
ComPos14=[LeftFrameBorder*0.22 BottomBorder*10 CompWidth*1.3 CompHeight];
Width=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',ComPos14, ...
   'String','0.01');
end

freq2=0;
if (signal_choice==7) 
ComPos9=[];
ComPos9=[LeftFrameBorder*0.008+0.1 BottomBorder*12.3  CompWidth*1.3 CompHeight*0.8];
Frequency_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPos9, ...
   'String','Frequency 1');    

ComPos18=[];
ComPos18=[LeftFrameBorder*0.22 BottomBorder*10.7  CompWidth*1.3 CompHeight*0.8];
freq2_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPos18, ...
   'String','Frequency 2');
    
ComPos14=[];
ComPos14=[LeftFrameBorder*0.22 BottomBorder*10 CompWidth*1.3 CompHeight];
freq2=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',ComPos14, ...
   'String','2000');

ComPos140=[];
ComPos140=[LeftFrameBorder*0.33 BottomBorder*12 CompWidth*1.5 CompHeight];
rad1=uicontrol( ...
   'Style','radiobutton', ...
   'Units','normalized', ...
   'Position',ComPos140, ...
   'value',1,'String','Linear','BackgroundColor',[0.6 0.5 0.5],'Callback','radio_button1');

ComPos141=[];
ComPos141=[LeftFrameBorder*0.33 BottomBorder*11.4 CompWidth*1.5 CompHeight];
rad2=uicontrol( ...
   'Style','radiobutton', ...
   'Units','normalized', ...
   'Position',ComPos141, ...
   'value',0,'String','Exponentiel','BackgroundColor', [0.6 0.5 0.5],'Callback','radio_button2');

ComPos142=[];
ComPos142=[LeftFrameBorder*0.33 BottomBorder*10.8 CompWidth*1.5 CompHeight];
rad3=uicontrol( ...
   'Style','radiobutton', ...
   'Units','normalized', ...
   'Position',ComPos142, ...
   'value',0,'String','Quadra Convexe','BackgroundColor', [0.6 0.5 0.5],'Callback','radio_button3');

ComPos143=[];
ComPos143=[LeftFrameBorder*0.33 BottomBorder*10.2 CompWidth*1.5 CompHeight];
rad4=uicontrol( ...
   'Style','radiobutton', ...
   'Units','normalized', ...
   'Position',ComPos143, ...
   'value',0,'String','Quadra Concave','BackgroundColor', [0.6 0.5 0.5],'Callback','radio_button4');
end

if (signal_choice==8)
ComPos18=[];
ComPos18=[LeftFrameBorder*0.22 BottomBorder*10.7  CompWidth*1.6 CompHeight*0.8];
Power_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPos18, ...
   'String','Noise Power :');

ComPos14=[];
ComPos14=[LeftFrameBorder*0.22 BottomBorder*10 CompWidth*1.3 CompHeight];
Power_noise=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',ComPos14, ...
   'String','0');
end




ComPos20=[];
ComPos20=[LeftFrameBorder*0.49 BottomBorder*9.9 CompWidth*1.5 CompHeight*2.1];
Valide=uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',ComPos20, ...
   'String','-','fontsize',18,'Callback','minus_signal');



