#!/usr/bin/env python

import lofar.mstools as lmt
import sys

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print ''
        print 'Insufficient arguments; run as:'
        print '    expandtargetps parsetin parsetout'
        print ''
        sys.exit(1)
    lmt.expandps (sys.argv[1], sys.argv[2],
                  {'in': [['msin', 'Input_Correlated'],
                          ['pbin', 'Input_InstrumentModel']],
                   'out': [['msout', 'Output_Correlated']]})
