/*
 * TablePanel.java
 *
 * Created on January 13, 2006, 4:47 PM
 */

package nl.astron.lofar.sas.otbcomponents;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author  blaakmeer/coolen
 */
public class TablePanel extends javax.swing.JPanel {
    
    /** Creates new form BeanForm */
    public TablePanel() {
        initComponents();

    }
    
    /** Set the Model for this Table
     *
     * @param   tableModel    The Model to be used
     */
    public void setTableModel(AbstractTableModel tableModel) {
        jTable1.setModel(tableModel);
        jTable1.updateUI();
    }
    
    /** Return the model from this table
     *
     * @return The abstract TableModel
     */
    public AbstractTableModel getTableModel() {
        return (AbstractTableModel)jTable1.getModel();
    }
    
    /** get the selected Row
     *
     * @return the seledcted Row
     */
    public int getSelectedRow() {
        return jTable1.getSelectedRow();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
    
}
