#!/bin/sh

declare -i i=0;
while [ $i -lt 10 ]; do
	./beamctl \
		--array=CS010C-HALF \
		--rcus=$i \
		--subbands=$i \
		--beamlets=$i \
		--rcumode=3 \
		--direction=0,0,LOFAR_LMN > /dev/null 2>&1 &
	i=$i+1
done
