#!/bin/sh

# tmwimager.run: Script to test mwimager
#
# Copyright (C) 2008
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$


# Set srcdir if undefined (if run outside 'make check')
if test "$srcdir" = ""; then
  srcdir=../../../test
fi
srcdir=`cd $srcdir/../src > /dev/null && pwd`
exedir=`cd ../test > /dev/null && pwd`

# Extend PATH.
PATH=`pwd`:$srcdir:$exedir:$PATH
export PATH

# Do a test using the askap imager.
# Enclose output in angle brackets to exclude it from the assay diff.
echo ">>>"
$srcdir/../src/mwimager tmwimager.parset tmwimager.in_cd `pwd` tmwimager_tmp.log dry tmwimager_tmp.hfn
echo "<<<"
# Append the three log files to the output.
# Wait for the subprocesses to finish.
# Remove disturbing log4cxx lines
sleep 5
grep -v 'log4cxx:' tmwimager_tmp.log-0 | grep -v 'Debug: '
grep -v 'log4cxx:' tmwimager_tmp.log-1 | grep -v 'Debug: '
grep -v 'log4cxx:' tmwimager_tmp.log-2 | grep -v 'Debug: '
# Remove the temporary parset part files.
rm -f tmwimager.parset.part*

# Do a test using the casa imager.
# Enclose output in angle brackets to exclude it from the assay diff.
echo ">>>"
$srcdir/../src/mwimager -casa tmwimager.parset tmwimager.in_cd `pwd` tmwimager_tmp.log dry tmwimager_tmp.hfn
echo "<<<"
# Append the three log files to the output.
# Wait for the subprocesses to finish.
# Remove disturbing log4cxx lines
sleep 5
echo ""
grep -v 'log4cxx:' tmwimager_tmp.log-0 | grep -v 'Debug: '
grep -v 'log4cxx:' tmwimager_tmp.log-1 | grep -v 'Debug: '
grep -v 'log4cxx:' tmwimager_tmp.log-2 | grep -v 'Debug: '

# Do a test using the casa imager with clean parameters.
# Enclose output in angle brackets to exclude it from the assay diff.
echo ">>>"
$srcdir/../src/mwimager -casa tmwimager.in_parset2 tmwimager.in_cd `pwd` tmwimager_tmp.log dry tmwimager_tmp.hfn
echo "<<<"
# Append the three log files to the output.
# Wait for the subprocesses to finish.
# Remove disturbing log4cxx lines
sleep 5
echo ""
grep -v 'log4cxx:' tmwimager_tmp.log-0 | grep -v 'Debug: '
grep -v 'log4cxx:' tmwimager_tmp.log-1 | grep -v 'Debug: '
grep -v 'log4cxx:' tmwimager_tmp.log-2 | grep -v 'Debug: '
