#!/bin/sh

# tMSSplit.run: Script to run tMSSplit
#
# Copyright (C) 2008
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$

# Exit with UNTESTED if the MS does not exist.
if [ ! -d $1/tMSSplit.MS ]; then
  echo "Test not executed; $1/tMSSplit.MS could not be found"
  exit 3
fi
# Do the split and check it thereafter.
../src/MSSplit $1/tMSSplit.MS tMSSplit_tmp  &&  \
      $LOFAR_CHECKTOOL tMSSplit $1/tMSSplit.MS tMSSplit_tmp
