#!/bin/sh

cwd=`pwd`
echo "tVdsMaker ..."
./tVdsMaker || exit 1
# Remove system specific work directory from output.
sed -e "s%$cwd/%%" tVdsMaker_tmp.ms1.vds
echo ""
sed -e "s%$cwd/%%" tVdsMaker_tmp.ms2.vds

echo ""
echo "combinevds ..."
../src/combinevds tVdsMaker_tmp.ms.gds tVdsMaker_tmp.ms1.vds tVdsMaker_tmp.ms2.vds || exit 1
# Remove system specific work directory from output.
sed -e "s%$cwd/%%" tVdsMaker_tmp.ms.gds
exit 0
