#!/bin/sh

# initparms: fill default parameter tables for bbstest
#
#  Copyright (C) 2004
#  ASTRON (Netherlands Foundation for Research in Astronomy)
#  P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#  $Id$

# functions for writing the input file for parmdb
beginParmdbInputFile () {
  rm fill.parmdb
  add2file "create $*"
  add2file "connect $*"
  add2file "clear"
}
add2file () {
  echo $* >> fill.parmdb
}
applyfile () {
  add2file  "quit" 
  ./parmdb < fill.parmdb
#  rm fill.parmdb
}

# functions for creating the correct meq models
makeMeq () {
  diff="1e-6" 
  if [ "$#" -eq "1" ]; then
    diff=$1 
  fi
  add2file  "adddef frot      values=0, diff=${diff}" 
  add2file  "adddef drot      values=0, diff=${diff}" 
  add2file  "adddef dell      values=0, diff=${diff}" 
  add2file  "adddef gain.11   values=1, diff=${diff}" 
  add2file  "adddef gain.22   values=1, diff=${diff}" 
  add2file  "adddef EJ11.real values=1, diff=${diff}" 
  add2file  "adddef EJ12.real values=0, diff=${diff}" 
  add2file  "adddef EJ21.real values=0, diff=${diff}" 
  add2file  "adddef EJ22.real values=1, diff=${diff}" 
  add2file  "adddef EJ11.imag values=1, diff=${diff}" 
  add2file  "adddef EJ12.imag values=0, diff=${diff}" 
  add2file  "adddef EJ21.imag values=0, diff=${diff}" 
  add2file  "adddef EJ22.imag values=1, diff=${diff}" 
}
perturbEJ11real () {
  diff="1e-6" 
  if [ "$#" -eq "1" ]; then
    diff=$1 
  fi
  add2file  "updatedef EJ11.real values=1, absPertValues=0.5, diff=${diff}"
}
perturbEJ11realPolyn () {
  diff="1e-6" 
  if [ "$#" -eq "1" ]; then
    diff=$1 
  fi
  add2file  "updatedef EJ11.real nx=2, values=[1.0, 0.01], absPertValues=[0.5, 0.5], diff=${diff}, time0=2352088832"
  #exit
}
makeEJ11Poly () {
  diff="1e-6" 
  if [ "$#" -eq "1" ]; then
    diff=$1 
  fi
  add2file  "updatedef EJ11.real nx=2, values=[1.0, 0.01], diff=${diff}, time0=2352088832"
}

# functions for creating the correct gsm models
makeGsm () {
  diff="1e-6" 
  if [ "$#" -eq "1" ]; then
    diff=$1 
  fi
  add2file  "adddef RA.CP1      values=2.734,   srcnr=0, diff=${diff}, diff_rel=F" 
  add2file  "adddef DEC.CP1     values=0.45379, srcnr=0, diff=${diff}, diff_rel=F" 
  add2file  "adddef StokesI.CP1 values=1.0,     srcnr=0, diff=${diff} " 
  add2file  "adddef StokesQ.CP1 values=0,       srcnr=0, diff=${diff} " 
  add2file  "adddef StokesU.CP1 values=0,       srcnr=0, diff=${diff} " 
  add2file  "adddef StokesV.CP1 values=0,       srcnr=0, diff=${diff} " 
  add2file  "adddef RA.CP2      values=2.73402, srcnr=1, diff=${diff}, diff_rel=F" 
  add2file  "adddef DEC.CP2     values=0.45369, srcnr=1, diff=${diff}, diff_rel=F" 
  add2file  "adddef StokesI.CP2 values=0.5,     srcnr=1, diff=${diff} " 
  add2file  "adddef StokesQ.CP2 values=0,       srcnr=1, diff=${diff} " 
  add2file  "adddef StokesU.CP2 values=0,       srcnr=1, diff=${diff} " 
  add2file  "adddef StokesV.CP2 values=0,       srcnr=1, diff=${diff} " 
  add2file  "adddef RA.CP3      values=2.73398, srcnr=2, diff=${diff}, diff_rel=F" 
  add2file  "adddef DEC.CP3     values=0.45375, srcnr=2, diff=${diff}, diff_rel=F" 
  add2file  "adddef StokesI.CP3 values=0.3,     srcnr=2, diff=${diff} " 
  add2file  "adddef StokesQ.CP3 values=0,       srcnr=2, diff=${diff} " 
  add2file  "adddef StokesU.CP3 values=0,       srcnr=2, diff=${diff} " 
  add2file  "adddef StokesV.CP3 values=0,       srcnr=2, diff=${diff} " 
}
perturbGsm () {
  diff="1e-6" 
  if [ "$#" -eq "1" ]; then
    diff=$1 
  fi
  add2file  "updatedef RA.CP1      values=2.734,   srcnr=0, diff=${diff}, absPertValues=0.000003, diff_rel=F" 
  add2file  "updatedef DEC.CP1     values=0.45379, srcnr=0, diff=${diff}, absPertValues=-0.0000005, diff_rel=F" 
  add2file  "updatedef StokesI.CP1 values=1.0,     srcnr=0, diff=${diff}, absPertValues=0.0" 
  add2file  "updatedef RA.CP2      values=2.73402, srcnr=1, diff=${diff}, absPertValues=0.0000005, diff_rel=F" 
  add2file  "updatedef DEC.CP2     values=0.45369, srcnr=1, diff=${diff}, absPertValues=-0.00000025, diff_rel=F" 
  add2file  "updatedef StokesI.CP2 values=0.5,     srcnr=1, diff=${diff}, absPertValues=0.5" 
  add2file  "updatedef RA.CP3      values=2.73398, srcnr=2, diff=${diff}, absPertValues=0.000001, diff_rel=F" 
  add2file  "updatedef DEC.CP3     values=0.45375, srcnr=2, diff=${diff}, absPertValues=0.00000025, diff_rel=F" 
  add2file  "updatedef StokesI.CP3 values=0.3,     srcnr=2, diff=${diff}, absPertValues=0.7" 
}
makePertGsm10 () {
  diff="1e-6" 
  if [ "$#" -eq "1" ]; then
    diff=$1 
  fi
  add2file  "adddef RA.CP1      values=10:26:35.2, srcnr=0, diff=${diff}, absPertValues=0.0000005 ,diff_rel=F" 
  add2file  "adddef DEC.CP1     values=26.0.0.87 , srcnr=0, diff=${diff}, absPertValues=-0.0000005 , diff_rel=F" 
  add2file  "adddef StokesI.CP1 values=1.5    , srcnr=0, diff=${diff}, absPertValues=0.1 " 
  add2file  "adddef StokesQ.CP1 values=0,       srcnr=0, diff=${diff} " 
  add2file  "adddef StokesU.CP1 values=0,       srcnr=0, diff=${diff} " 
  add2file  "adddef StokesV.CP1 values=0,       srcnr=0, diff=${diff} " 
  add2file  "adddef RA.CP2      values=10:26:35.2, srcnr=1, diff=${diff}, absPertValues=0.0000005 ,diff_rel=F" 
  add2file  "adddef DEC.CP2     values=26.0.22.0 , srcnr=1, diff=${diff}, absPertValues=-0.0000005 , diff_rel=F" 
  add2file  "adddef StokesI.CP2 values=1.0    , srcnr=1, diff=${diff}, absPertValues=0.1 " 
  add2file  "adddef StokesQ.CP2 values=0,       srcnr=1, diff=${diff} " 
  add2file  "adddef StokesU.CP2 values=0,       srcnr=1, diff=${diff} " 
  add2file  "adddef StokesV.CP2 values=0,       srcnr=1, diff=${diff} " 
  add2file  "adddef RA.CP3      values=10:26:37.2, srcnr=2, diff=${diff}, absPertValues=0.0000005 ,diff_rel=F" 
  add2file  "adddef DEC.CP3     values=25.59.50.0, srcnr=2, diff=${diff}, absPertValues=-0.0000005 , diff_rel=F" 
  add2file  "adddef StokesI.CP3 values=0.7    , srcnr=2, diff=${diff}, absPertValues=0.1 " 
  add2file  "adddef StokesQ.CP3 values=0,       srcnr=2, diff=${diff} " 
  add2file  "adddef StokesU.CP3 values=0,       srcnr=2, diff=${diff} " 
  add2file  "adddef StokesV.CP3 values=0,       srcnr=2, diff=${diff} " 
  add2file  "adddef RA.CP4      values=10:26:35.0, srcnr=3, diff=${diff}, absPertValues=0.0000005 ,diff_rel=F" 
  add2file  "adddef DEC.CP4     values=25.59.40.0 , srcnr=3, diff=${diff}, absPertValues=-0.0000005 , diff_rel=F" 
  add2file  "adddef StokesI.CP4 values=0.5    , srcnr=3, diff=${diff}, absPertValues=0.1 " 
  add2file  "adddef StokesQ.CP4 values=0,       srcnr=3, diff=${diff} " 
  add2file  "adddef StokesU.CP4 values=0,       srcnr=3, diff=${diff} " 
  add2file  "adddef StokesV.CP4 values=0,       srcnr=3, diff=${diff} " 
  add2file  "adddef RA.CP5      values=10:26:36.1       , srcnr=4, diff=${diff}, absPertValues=0.0000005 ,diff_rel=F" 
  add2file  "adddef DEC.CP5     values=26.0.10.0       , srcnr=4, diff=${diff}, absPertValues=-0.0000005 , diff_rel=F" 
  add2file  "adddef StokesI.CP5 values=0.3    , srcnr=4, diff=${diff}, absPertValues=0.1 " 
  add2file  "adddef StokesQ.CP5 values=0,       srcnr=4, diff=${diff} " 
  add2file  "adddef StokesU.CP5 values=0,       srcnr=4, diff=${diff} " 
  add2file  "adddef StokesV.CP5 values=0,       srcnr=4, diff=${diff} " 
  add2file  "adddef RA.CP6      values=10:26:36.0       , srcnr=5, diff=${diff}, absPertValues=0.0000005 ,diff_rel=F" 
  add2file  "adddef DEC.CP6     values=26.0.0.00       , srcnr=5, diff=${diff}, absPertValues=-0.0000005 , diff_rel=F" 
  add2file  "adddef StokesI.CP6 values=0.3    , srcnr=5, diff=${diff}, absPertValues=0.1 " 
  add2file  "adddef StokesQ.CP6 values=0,       srcnr=5, diff=${diff} " 
  add2file  "adddef StokesU.CP6 values=0,       srcnr=5, diff=${diff} " 
  add2file  "adddef StokesV.CP6 values=0,       srcnr=5, diff=${diff} " 
  add2file  "adddef RA.CP7      values=10:26:37.5       , srcnr=6, diff=${diff}, absPertValues=0.0000005 ,diff_rel=F" 
  add2file  "adddef DEC.CP7     values=25.59.55.0       , srcnr=6, diff=${diff}, absPertValues=-0.0000005 , diff_rel=F" 
  add2file  "adddef StokesI.CP7 values=0.2    , srcnr=6, diff=${diff}, absPertValues=0.1 " 
  add2file  "adddef StokesQ.CP7 values=0,       srcnr=6, diff=${diff} " 
  add2file  "adddef StokesU.CP7 values=0,       srcnr=6, diff=${diff} " 
  add2file  "adddef StokesV.CP7 values=0,       srcnr=6, diff=${diff} " 
  add2file  "adddef RA.CP8      values=10:26:34.7       , srcnr=7, diff=${diff}, absPertValues=0.0000005 ,diff_rel=F" 
  add2file  "adddef DEC.CP8     values=25.59.50.0       , srcnr=7, diff=${diff}, absPertValues=-0.0000005 , diff_rel=F" 
  add2file  "adddef StokesI.CP8 values=0.1    , srcnr=7, diff=${diff}, absPertValues=0.1 " 
  add2file  "adddef StokesQ.CP8 values=0,       srcnr=7, diff=${diff} " 
  add2file  "adddef StokesU.CP8 values=0,       srcnr=7, diff=${diff} " 
  add2file  "adddef StokesV.CP8 values=0,       srcnr=7, diff=${diff} " 
  add2file  "adddef RA.CP9      values=10:26:37.0       , srcnr=8, diff=${diff}, absPertValues=0.0000005 ,diff_rel=F" 
  add2file  "adddef DEC.CP9     values=26.0.15.0       , srcnr=8, diff=${diff}, absPertValues=-0.0000005 , diff_rel=F" 
  add2file  "adddef StokesI.CP9 values=0.1    , srcnr=8, diff=${diff}, absPertValues=0.1 " 
  add2file  "adddef StokesQ.CP9 values=0,       srcnr=8, diff=${diff} " 
  add2file  "adddef StokesU.CP9 values=0,       srcnr=8, diff=${diff} " 
  add2file  "adddef StokesV.CP9 values=0,       srcnr=8, diff=${diff} " 
  add2file  "adddef RA.CP10      values=10:26:35.7       , srcnr=9, diff=${diff}, absPertValues=0.0000005 ,diff_rel=F" 
  add2file  "adddef DEC.CP10     values=26.0.0.80       , srcnr=9, diff=${diff}, absPertValues=-0.0000005 , diff_rel=F" 
  add2file  "adddef StokesI.CP10 values=0.08   , srcnr=9, diff=${diff}, absPertValues=0.1 " 
  add2file  "adddef StokesQ.CP10 values=0,       srcnr=9, diff=${diff} " 
  add2file  "adddef StokesU.CP10 values=0,       srcnr=9, diff=${diff} " 
  add2file  "adddef StokesV.CP10 values=0,       srcnr=9, diff=${diff} " 
}


