#!/bin/sh

MSDIR=/data/PSS3/diepen/BBS2

rm -rf tBBS3_tmp
mkdir tBBS3_tmp
cd tBBS3_tmp
# ln -s ../../../../test/tBBS3.sh .
ln -s ../../../../test/tBBS3.runTest.sh .
ln -s ../../../../test/tBBS3.test* .
ln -s ../../../../src/clearBB .
ln -s ../../../../src/initparms .
ln -s ../../../../test/run.test* .
ln -s ../../src/BBS3 tBBS3 
ln -s ../../src/parmdb . 
ln -s ../../../../test/generalinfo.sh .
ln -s ../../../../test/cp2web.sh .
ln -s ../../../../test/tBBS3.machinefile tBBS3_tmp.machinefile
# remove (links to) emacs backup files
rm -f ./*~

rm -f demo{3,3p,10}-1.MS.{dat,des,uvw}

ln -s $MSDIR/demo3.MS_p1 demo3.MS_p1
ln -s $MSDIR/demo3p.MS_p1 demo3p.MS_p1
ln -s $MSDIR/demo3n.MS_p1 demo3n.MS_p1
ln -s $MSDIR/demo10.MS_p1 demo10.MS_p1
