#!/bin/sh

rm -rf tBBS3_tmp
mkdir tBBS3_tmp
cd tBBS3_tmp
ln -s ../../../../test/tBBS3.sh .
ln -s ../../../../test/tBBS3.test* .
ln -s ../../../../src/clearBB .
ln -s ../../../../test/initparms .
ln -s ../../../../test/run.test* .
ln -s ../tBBS3 . 
ln -s ../../src/parmdb . 
ln -s ../../../../test/generalinfo.sh .
ln -s ../../../../test/cp2web.sh .
# remove (links to) emacs backup files
rm -f ./*~

rm -f demo{3,3p,10}-1.MS.{dat,des,uvw}
ln -s /data/PSS3/diepen/BBS2/demo3/demo.dat demo3-1.MS.dat
ln -s /data/PSS3/diepen/BBS2/demo3/demo.des demo3-1.MS.des
ln -s /data/PSS3/diepen/BBS2/demo3/demo.uvw demo3-1.MS.uvw
ln -s /data/PSS3/diepen/BBS2/demo3p/demo.dat demo3p-1.MS.dat
ln -s /data/PSS3/diepen/BBS2/demo3p/demo.des demo3p-1.MS.des
ln -s /data/PSS3/diepen/BBS2/demo3p/demo.uvw demo3p-1.MS.uvw
ln -s /data/PSS3/diepen/BBS2/demo3n/demo.dat demo3n-1.MS.dat
ln -s /data/PSS3/diepen/BBS2/demo3n/demo.des demo3n-1.MS.des
ln -s /data/PSS3/diepen/BBS2/demo3n/demo.uvw demo3n-1.MS.uvw
ln -s /data/PSS3/diepen/BBS2/demo10/demo.dat demo10-1.MS.dat
ln -s /data/PSS3/diepen/BBS2/demo10/demo.des demo10-1.MS.des
ln -s /data/PSS3/diepen/BBS2/demo10/demo.uvw demo10-1.MS.uvw
