close all
%global numero;
global arg_acpplan1;
global arg_acpplan2;
global echantillonnage;
global NbClasse;
global R;
global count;
global HBtnColorBar;
global HMainFig ;
global HDspFig ;
global HColorMap;
global freq;
global HTimeFig ;
global HTimeFig2 ;
global HThreeDFig ;
global HSpecgramFig ;
global HBtnColorBar2;
global HMainFig2 ;
global HDspFig2 ;
global HColorMap2;
global donnee_ben;
global HTimeFig ;
global HThreeDFig ;
global HSpecgramFig ;
global numero;
global numero_classe;
global DSP;
global sizeMap;
R=cell(10,1);
count=0;
fichier={};
DSP=evalin('base','DSP');
interface1;
