global MyData3;
global NbClasse;
fid=fopen(file_name,'r');
MyData3=[];
disp(['here: ' file_name ' ']);
tline2=fgetl(fid);
MyData3=fscanf(fid,'%e');
esp=strfind(tline2,' '); 
NbClasse=str2num(tline2(esp(1):esp(2)));
U=colormap(hsv(NbClasse));
fclose(fid);