#!/bin/sh -x
# constants
DBHOST=sas099.control.lofar

#cleanup on normal exit and on SIGHUP, SIGINT, SIGQUIT, and SIGTERM
trap 'qpid-config del exchange --force $queue ; kill ${SERVICE_PID}' 0 1 2 3 15

# Generate randome queue name
queue=$(< /dev/urandom tr -dc [:alnum:] | head -c16)

# Create the queue
qpid-config add exchange topic $queue

# Setup a clean database with predefined content
dropdb -U postgres -h ${DBHOST} unittest_db
gzip -dc $srcdir/unittest_db.dump.gz | psql -U postgres -h ${DBHOST} -f -
TreeStatusEvents.py -B $queue -D unittest_db -H ${DBHOST} -U postgres &
SERVICE_PID=$!
# Starting up takes a while
sleep 3

# Run the unit test
source python-coverage.sh
python_coverage_test "Messaging/python" t_TreeStatusEvents.py -D unittest_db -H ${DBHOST} -B $queue
