#!/usr/bin/python
# $Id$

DEFAULT_OTDB_SERVICE_BUSNAME = 'lofar.otdb.specification'
DEFAULT_OTDB_SERVICENAME = 'OTDBService'

DEFAULT_OTDB_NOTIFICATION_BUSNAME='lofar.otdb.status'
DEFAULT_OTDB_NOTIFICATION_SUBJECT='TaskStatus'
