#!/usr/bin/python
# $Id$

DEFAULT_OTDB_SERVICE_BUSNAME = 'lofar.otdb.command'
DEFAULT_OTDB_SERVICENAME = 'OTDBService'

DEFAULT_OTDB_NOTIFICATION_BUSNAME='lofar.otdb.notification'
DEFAULT_OTDB_NOTIFICATION_SUBJECT='TaskStatus'
