#!/bin/bash -e

# Run the unit test
# either with or without code coverage measurements,
# depending wheter coverage has been installed

if type "coverage" > /dev/null; then
    #run test using python coverage tool

    #erase previous results
    coverage erase

    #setup coverage config file
    printf "[report]\nexclude_lines = \n  if __name__ == .__main__.\n  def main\n" > .coveragerc

    coverage run --branch --include=*Messaging/python* t_messages.py
    RESULT=$?
    if [ $RESULT -eq 0 ]; then
        echo " *** Code coverage results *** "
        coverage report -m
        echo " *** End coverage results *** "
    fi
    exit $RESULT
else
    #coverage not available
    echo "Please run: 'pip install coverage' to enable code coverage reporting of the unit tests"
    #run plain test script
    python t_messages.py
fi
