#!/bin/sh

cwd=`pwd -P`
echo "tVdsMaker ..."
./tVdsMaker > tVdsMaker_tmp.out1 || exit 1
# Remove system specific work directory from output.
sed -e "s%$cwd/%%" tVdsMaker_tmp.ms1.vds
echo ""
sed -e "s%$cwd/%%" tVdsMaker_tmp.ms2.vds

echo ""
echo "combinevds ..."
../src/combinevds tVdsMaker_tmp.ms.gds tVdsMaker_tmp.ms1.vds tVdsMaker_tmp.ms2.vds > tVdsMaker_tmp.out1 || exit 1
grep -v "INFO " tVdsMaker_tmp.out1
# Remove system specific work directory from output.
sed -e "s%$cwd/%%" tVdsMaker_tmp.ms.gds
exit 0
