#!/bin/bash
#
# Script to (re)create a OTDB database from scratch, using the sql statements
#
# Usage: fresh_database <DBNAME>
#
# Requires all sql-commands to be present in /opt/lofar/sbin/sql
# If existing, DROPS the current database
#
if [ -z $1 ]; then
  echo "Usage: fresh_database <DBNAME>"
  exit 0
fi

if [  "$1" == "-h" ]; then 
  echo "Usage: fresh_database <DBNAME>"
  exit 0
fi

DBNAME=$1
DBUSER=postgres
DBHOST=localhost
DBPORT=5432

# The following commands assume that the user has super user privileges.
#
# Access to PostgreSQL databases is managed via the 'pg_hba.conf' file. 
#
# Postgres should be told to listen to external TCP ports. 
# Edit /sasdb/data/postgresq.conf
# to have the following stanzas:
#
#     Listen_addresses = '*'
#     Port = 5432
#
# Don't forget to restart Postgres after altering these files, 
# as follows (Debian):
#
#  pg_ctl start -D /sasdb/data -l /sasdb/data/pg_log/logfile
#
# Drop DB & USER. User DBUSER owns DBNAME, so we have to remove the database 
# first!
# Note the '|| true' at the end. This ensures that the commands succeed, 
# even if the database is not found.

echo " == Dropping database $DBNAME =="
echo dropdb   --host $DBHOST --port $DBPORT --user postgres --echo $DBNAME || true
dropdb   --host $DBHOST --port $DBPORT --user postgres --echo $DBNAME || true
# Create USER, DB, and add the 'plpgsql' language for stored procedures.

echo " == Creating new database $DBNAME =="
echo createdb   --host $DBHOST --port $DBPORT --user postgres --owner $DBUSER --echo $DBNAME
createdb   --host $DBHOST --port $DBPORT --user postgres --owner $DBUSER --echo $DBNAME
echo createlang --host $DBHOST --port $DBPORT --user postgres --dbname $DBNAME  --echo "plpgsql"
createlang --host $DBHOST --port $DBPORT --user postgres --dbname $DBNAME  --echo "plpgsql"

echo " == Creating new tables in $DBNAME =="
if [ -e /opt/lofar/sbin/sql/create_OTDB.sql ]; then 
  cd /opt/lofar/sbin/sql
  echo psql -f create_OTDB.sql --host $DBHOST --port $DBPORT --user $DBUSER $DBNAME 2>&1 | grep ERROR | grep -v "does not exist"
  psql -f create_OTDB.sql --host $DBHOST --port $DBPORT --user $DBUSER $DBNAME 2>&1 | grep ERROR | grep -v "does not exist"
else
  echo "Cannot find /opt/lofar/sbin/sql/create_OTDB.sql; did you install this?"
fi
echo " == Done =="
