#!/bin/sh

# tparmexportcal.run: Script to test program parmexportcal
#
# Copyright (C) 2011
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$

showparms()
{
  ../src/parmdbm tparmexportcal_tmp.stdout > /dev/null << EOF
   open tablename='tparmexportcal_tmp.pdb2'
   showdef
   show
   close
   quit
EOF
  grep -v ": Version " tparmexportcal_tmp.stdout
}

# Create the ParmDB to be exported.
../src/parmdbm tparmexportcal_tmp.stdout > /dev/null << EOF
 create tablename='tparmexportcal_tmp.pdb'
 add Gain:S1:Real:1 nx=2,ny=1,values=[0.1, 0.2], domain=[1,3,2,4]
 add Gain:S1:Imag:1 nx=2,ny=1,values=[  1,   2], domain=[1,3,2,4]
 close
 quit
EOF
grep -v ": Version " tparmexportcal_tmp.stdout

# Export in standard way and show result.
echo ""
../src/parmexportcal in=tparmexportcal_tmp.pdb out=tparmexportcal_tmp.pdb2 | grep -v ": Version " | grep -v "INFO "
showparms

# Export in as ampl/phase way and show result.
echo ""
../src/parmexportcal in=tparmexportcal_tmp.pdb out=tparmexportcal_tmp.pdb2 type=polar | grep -v ": Version " | grep -v "INFO "
showparms

# Create another ParmDB to be exported.
echo ""
../src/parmdbm tparmexportcal_tmp.stdout > /dev/null << EOF
 create tablename='tparmexportcal_tmp.pdb'
 add Gain:S1:Phase:1 ny=2,values=[0.1, 0.2], domain=[1,3,2,4]
 add Gain:S1:Ampl:1 ny=2,values=[  1,   2], domain=[1,3,2,4]
 close
 quit
EOF
grep -v ": Version " tparmexportcal_tmp.stdout

# Export in standard way and show result.
echo ""
../src/parmexportcal in=tparmexportcal_tmp.pdb out=tparmexportcal_tmp.pdb2 | grep -v ": Version " | grep -v "INFO "
showparms

# Export in as ampl/phase way and show result.
echo ""
../src/parmexportcal in=tparmexportcal_tmp.pdb out=tparmexportcal_tmp.pdb2 type=complex | grep -v ": Version " | grep -v "INFO "
showparms

