#!/bin/bash
#
# Start OTB Gui
#
# The default portnumbers for clients to connect with server is 12500; 
# provide another port by using commandline switch -p
# The default host for OTDB server is sas001; change with commandline switch -s
#

function info()
{
  echo "Usage: $0 [-p portnumber] [-s OTBserver] [-d DBName]"
  echo "  portnumber: port to connect to server. The default "
  echo "              portnumber for clients is 12500"
  echo "  OTBserver : hostname of server where OTB server runs"
  echo "              Default is sas001"
  echo "  DBName    : Name of Database to connect to. Default is LOFAR_4"
}

OTB_host=sas001
port=12500
DB_name=LOFAR_4

while getopts  "p:s:d:h" flag
do
   case "$flag" in
   p)
   port=$OPTARG
   ;;
   s)
   OTB_host=$OPTARG
   ;;
   d)
   DB_name=$OPTARG
   ;;
   h)
   info
   exit 0
   ;;
   *)
   info
   exit 0
   ;;
   esac
done

# Start server first (if not running already)
serverpid=0
if [ "$OTB_host" == "sas001" ]; then  
  ./startServerOTB -p $port 
  serverpid=$? # not real pid, but suffices to trigger kill of process
else
  echo "Assuming OTB server is already running on system $OTB_host"
fi

export OTB_DIR=/opt/sas/otb/client
export JAVA_HOME=/usr/java/jdk1.7.0_02

echo
echo --- Starting OTB Client using: ---
echo --- OTB Host: $OTB_host
echo --- Server port: $port

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OTB_DIR/lib
export OTB_APP=$OTB_DIR/`basename $OTB_DIR/OTB*.jar`
export CLASSPATH=$OTB_APP

for JAR_DEPENDENCY in $OTB_DIR/lib/*.jar
do
	echo -- Adding `basename $JAR_DEPENDENCY` dependency to Java Classpath
	export CLASSPATH=$CLASSPATH:$JAR_DEPENDENCY
done

echo Starting up ...
$JAVA_HOME/bin/java -cp $CLASSPATH nl.astron.lofar.sas.otb.Main -s $OTB_host -p $port -d $DB_name -u busyman

if [ $serverpid -ne 0 ]; then
   echo "Stopping server"
   serverpid=`ps -ef | grep -v grep | grep java | grep server | grep $port | awk '{print $2}'`
   kill $serverpid
   sleep 1
fi

