/*
 * WaveformSettingsSelectPanel.java
 *
 * Created on April 18, 2006, 1:55 PM
 */

package nl.astron.lofar.mac.apl.gui.jrsp.panels.waveformsettings;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import nl.astron.lofar.mac.apl.gui.jrsp.panels.*;

/**
 *
 * @author  balken
 */
public class WaveformSettingsSelectPanel extends JPanel implements ActionListener
{   
    // the parent class
    private WaveformSettingsPanel parent;
    
    /**
     * 
     * Creates new form WaveformSettingsSelectPanel
     */
    public WaveformSettingsSelectPanel() 
    {
        initComponents();
        
        cmbBoard1.addActionListener(this);
        chkBoard1Antenna1.addActionListener(this);
    }

    public void init(WaveformSettingsPanel parent)
    {
        this.parent = parent;
        
        if(parent.getMainPanel().getBoard().isConnected())
        {
            int nofBoards = parent.getMainPanel().getBoard().getNofBoards();
            
            cmbBoard1.removeAllItems();
            cmbBoard2.removeAllItems();
            
            for (int i = 0; i < nofBoards; i++)
            {
                cmbBoard1.addItem(Integer.toString(i));
                cmbBoard2.addItem(Integer.toString(i));
            }
        }
    }
    
    public void actionPerformed(ActionEvent event)
    {
        // @TODO: implement
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        cmbBoard1 = new javax.swing.JComboBox();
        chkBoard1Antenna1 = new javax.swing.JCheckBox();
        chkBoard1Antenna2 = new javax.swing.JCheckBox();
        chkBoard1Antenna3 = new javax.swing.JCheckBox();
        chkBoard1Antenna4 = new javax.swing.JCheckBox();
        chkBoard1Antenna5 = new javax.swing.JCheckBox();
        chkBoard1Antenna6 = new javax.swing.JCheckBox();
        chkBoard1Antenna7 = new javax.swing.JCheckBox();
        chkBoard1Antenna8 = new javax.swing.JCheckBox();
        cmbBoard2 = new javax.swing.JComboBox();
        chkBoard2Antenna1 = new javax.swing.JCheckBox();
        chkBoard2Antenna2 = new javax.swing.JCheckBox();
        chkBoard2Antenna3 = new javax.swing.JCheckBox();
        chkBoard2Antenna4 = new javax.swing.JCheckBox();
        chkBoard2Antenna5 = new javax.swing.JCheckBox();
        chkBoard2Antenna6 = new javax.swing.JCheckBox();
        chkBoard2Antenna7 = new javax.swing.JCheckBox();
        chkBoard2Antenna8 = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Selection"));

        chkBoard1Antenna1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoard1Antenna1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkBoard1Antenna2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoard1Antenna2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkBoard1Antenna3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoard1Antenna3.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkBoard1Antenna4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoard1Antenna4.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkBoard1Antenna5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoard1Antenna5.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkBoard1Antenna6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoard1Antenna6.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkBoard1Antenna7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoard1Antenna7.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkBoard1Antenna8.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoard1Antenna8.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkBoard2Antenna1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoard2Antenna1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkBoard2Antenna2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoard2Antenna2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkBoard2Antenna3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoard2Antenna3.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkBoard2Antenna4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoard2Antenna4.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkBoard2Antenna5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoard2Antenna5.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkBoard2Antenna6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoard2Antenna6.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkBoard2Antenna7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoard2Antenna7.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkBoard2Antenna8.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoard2Antenna8.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(chkBoard1Antenna1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkBoard1Antenna2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkBoard1Antenna3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkBoard1Antenna4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkBoard1Antenna5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkBoard1Antenna6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkBoard1Antenna7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkBoard1Antenna8))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cmbBoard1, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 71, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(layout.createSequentialGroup()
                        .add(chkBoard2Antenna1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkBoard2Antenna2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkBoard2Antenna3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkBoard2Antenna4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkBoard2Antenna5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkBoard2Antenna6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkBoard2Antenna7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkBoard2Antenna8))
                    .add(cmbBoard2, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cmbBoard1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cmbBoard2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(chkBoard1Antenna1)
                    .add(chkBoard1Antenna2)
                    .add(chkBoard1Antenna3)
                    .add(chkBoard1Antenna4)
                    .add(chkBoard1Antenna5)
                    .add(chkBoard1Antenna6)
                    .add(chkBoard1Antenna7)
                    .add(chkBoard1Antenna8)
                    .add(chkBoard2Antenna8)
                    .add(chkBoard2Antenna7)
                    .add(chkBoard2Antenna6)
                    .add(chkBoard2Antenna5)
                    .add(chkBoard2Antenna4)
                    .add(chkBoard2Antenna3)
                    .add(chkBoard2Antenna2)
                    .add(chkBoard2Antenna1))
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkBoard1Antenna1;
    private javax.swing.JCheckBox chkBoard1Antenna2;
    private javax.swing.JCheckBox chkBoard1Antenna3;
    private javax.swing.JCheckBox chkBoard1Antenna4;
    private javax.swing.JCheckBox chkBoard1Antenna5;
    private javax.swing.JCheckBox chkBoard1Antenna6;
    private javax.swing.JCheckBox chkBoard1Antenna7;
    private javax.swing.JCheckBox chkBoard1Antenna8;
    private javax.swing.JCheckBox chkBoard2Antenna1;
    private javax.swing.JCheckBox chkBoard2Antenna2;
    private javax.swing.JCheckBox chkBoard2Antenna3;
    private javax.swing.JCheckBox chkBoard2Antenna4;
    private javax.swing.JCheckBox chkBoard2Antenna5;
    private javax.swing.JCheckBox chkBoard2Antenna6;
    private javax.swing.JCheckBox chkBoard2Antenna7;
    private javax.swing.JCheckBox chkBoard2Antenna8;
    private javax.swing.JComboBox cmbBoard1;
    private javax.swing.JComboBox cmbBoard2;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox jComboBox2;
    // End of variables declaration//GEN-END:variables
    
}
