#!/bin/sh
# This script must be called from the "..build/<variant>" directory
# with input argument: usernm

if [ "$#" != "1" ]; then
 echo "This script should be called with user name as input argument"
 exit 1
fi

usernm=$1

ln -s src/parmdb .

. ../../src/initparms
\rm -rf /tmp/$USER.demo*
cp -r /data/PSS3/diepen/BBS2/demo3.MEP /tmp/$USER.demo.MEP
cp -r /data/PSS3/diepen/BBS2/demo3_gsm.MEP /tmp/$USER.demo_gsm.MEP


# Do testDefault
echo ""
echo "Doing testDefault"

echo "  Generating parm tables ..."
# use functions in initparms to initialize parmtables
beginParmdbInputFile "dbtype='aips', user='$usernm', tablename='demo3-1'"
makeMeq
applyfile

beginParmdbInputFile "dbtype='aips', user='$usernm', tablename='demo3_gsm-1'"
makeGsm
perturbGsm
applyfile

echo "  Preparing BlackBoard ..."
../../src/clearBB -user $usernm


