#!/bin/bash

. ./testFuncs.sh

PARSET=$PWD/tMACfeedback.in_parset

# Add the connection information for this test
echo "Cobalt.Feedback.host=localhost" >> $PARSET
echo "Cobalt.Feedback.remotePath=$LOFARROOT/var/run" >> $PARSET
echo "Cobalt.FinalMetaDataGatherer.host=localhost" >> $PARSET

# Start a mock OnlineControl to verify the communications of runObservation.sh
$srcdir/MockOnlineControl.sh $PARSET &
ONLINECONTROL_PID=$!

# Run the observation
runObservation.sh -C -l 1 $PARSET
OBSRESULT=$?

# Wait for OnlineControl to finish
wait $ONLINECONTROL_PID
ONLINECONTROLRESULT=$?

if [ $OBSRESULT -gt 0 ]; then
  echo "runObservation.sh failed (status: $OBSRESULT)"
  exit $OBSRESULT
fi

if [ $ONLINECONTROLRESULT -gt 0 ]; then
  echo "MockOnlineControl.sh failed (status: $ONLINECONTROLRESULT)"
  exit $ONLINECONTROLRESULT
fi

# Everything went ok
exit 0

