#!/bin/sh

# Set srcdir if needed.
# It might not be set if the .run file is executed directly instead of
# by 'make check'.
if [ "$srcdir" = "" ]; then
  srcdir=../../../test
fi

# Create the ParmDB tables for tPredict.
$srcdir/makeDemoParmDBPred tPredict

\rm -rf tPredict_tmp.MS1
cp -r /data/PSS3/diepen/BBS2/demo3.MS_p1 tPredict_tmp.MS1

$LOFAR_CHECKTOOL ./tPredict $USER tPredict_tmp.MS1 tPredict_tmp.demo_instr tPredict_tmp.demo_sky
status=$?
exit $status

