#!/bin/sh

# Add . to PATH.
PATH=.:$PATH
export PATH

# Set srcdir if undefined (if run outside 'make check')
if test "$srcdir" = ""; then
  srcdir=../../../src
fi

# Create directories to create the sourcedb-s in.
# They must match the FileName in in_ms*.vds.
rm -rf tsetupsourcedb_tmp.ms0
rm -rf tsetupsourcedb_tmp.ms1
rm -rf tsetupsourcedb_tmp.ms2
mkdir tsetupsourcedb_tmp.ms0
mkdir tsetupsourcedb_tmp.ms1
mkdir tsetupsourcedb_tmp.ms2

# Enclose output in angle brackets to exclude it from the assay diff.
# Use _tmp name for the gds, so the resulting sourcedb also gets a _tmp name.
cp tsetupsourcedb.in_gds tsetupsourcedb_tmp.gds
echo ">>>"
$srcdir/../src/setupsourcedb -overwrite tsetupsourcedb_tmp.gds tsetupsourcedb.in "" "" tsetupsourcedb_tmp.log 0 tsetupsourcedb_tmp.hfn `pwd`
echo "<<<"

# Append the three log files to the output.
# Wait for the subprocesses to finish.
sleep 5
grep -v 'log4cxx:' tsetupsourcedb_tmp.log-0
grep -v 'log4cxx:' tsetupsourcedb_tmp.log-1
grep -v 'log4cxx:' tsetupsourcedb_tmp.log-2

# Check if the three sourcedbs and overall VDS exist.
test -d tsetupsourcedb_tmp.ms0/sky  ||  exit 1
test -d tsetupsourcedb_tmp.ms1/sky  ||  exit 1
test -d tsetupsourcedb_tmp.ms2/sky  ||  exit 1
test -e tsetupsourcedb_tmp.sky  ||  exit 1
