/* Generated by lofar_init.m4 */

#ifndef LOFAR_CONFIG_H
#define LOFAR_CONFIG_H

#if defined(HAVE_CONFIG_H)
#include <config.h>
#endif

#define HAVE_LOFAR_TOOLS 1

#define LOFARLOGGER_PACKAGE "LCS.Tools"

#endif
