# -- Cluster--
#
# $Id$
#
#      name        vers   qual        constr.            descr.
#--------------------------------------------------------------------------------------------------------
node   Cluster     4.0.0  development 'node constraint'  "Cluster Settings"

#      name        		  vers   qual        constr.            descr.
#--------------------------------------------------------------------------------------------------------
#uses   BGLSection         4.0.0  development 1                  "BGL Nodes"
#uses   StorageSection     4.0.0  development 1                  "Storage Nodes"
#uses   ImagingSection     4.0.0  development 1                  "Imaging Nodes"

