# -- ConnectionSection --
#
# $Id$
#
#      name        vers   qual        constr.            descr.
#--------------------------------------------------------------------------------------------------------
node   Connection         1.0.1  development 'node constraint'  "Connections between hosts"

#      name             	vers   qual        constr.            descr.
#--------------------------------------------------------------------------------------------------------
uses   BGL-Storage			1.0.0  development -                  "Connection between BGL and storage node"
uses   Storage-Imaging 		1.0.1  development -                  "Connection between storage and imaging node"
