#!/bin/sh -x

trap 'cleanup; trap - 0; exit' 0 1 2 3 15

# Kill the background process (if it's still running)
cleanup()
{
  if kill -0 $! 2>/dev/null; then 
    kill -9 $! 2>/dev/null
  fi
}

if [ "$LOFAR_LIMITEXEC" != "" ]; then
  CMDPREFIX="$LOFAR_LIMITEXEC 300"
fi

# Run the ExampleSocket test program by starting it twice,
# once as server and once as client.
$CMDPREFIX $LOFAR_CHECKTOOL ./ExampleSocket -s > ExampleSocket_tmp.outs1 &
$CMDPREFIX $LOFAR_CHECKTOOL ./ExampleSocket -c > ExampleSocket_tmp.outc1

# Exit if something went wrong.
STATUS=$?
if [ $STATUS != 0 ]; then
  exit $STATUS
fi

# Output the result in order.
echo "Run1 ..."
cat ExampleSocket_tmp.outs1 ExampleSocket_tmp.outc1


# Do another run, now starting the client before the server.
$CMDPREFIX $LOFAR_CHECKTOOL ./ExampleSocket -c > ExampleSocket_tmp.outc2 &
$CMDPREFIX $LOFAR_CHECKTOOL ./ExampleSocket -s > ExampleSocket_tmp.outs2

# Exit if something went wrong.
STATUS=$?
if [ $STATUS != 0 ]; then 
  exit $STATUS
fi

# Output the result in order.
echo "Run2 ..."
cat ExampleSocket_tmp.outs2 ExampleSocket_tmp.outc2
