# -- Cluster--
#
# $Id$
#
#      name        vers   qual        constr.            descr.
#--------------------------------------------------------------------------------------------------------
node   Cluster     1.0.1  development 'node constraint'  "Cluster Settings"

#      name        		  vers   qual        constr.            descr.
#--------------------------------------------------------------------------------------------------------
#uses   BGLSection         1.0.0  development 1                  "BGL Nodes"
#uses   StorageSection     1.0.1  development 1                  "Storage Nodes"
#uses   ImagingSection     1.0.0  development 1                  "Imaging Nodes"

