#!/bin/bash 
#
# For reasons beyond my comprehesion 'trap' is not executed if I replace
# /bin/bash with /bin/sh; so I surrendered and used /bin/bash.
#
# $Id$

# Kill all background jobs we've created
trap 'for pid in $(jobs -p); do kill $pid; done' 0 1 2 3 15

# Fake a display if envvar DISPLAY is not set.
if [ -z "$DISPLAY" ]
then
  Xvfb :99 -ac & 
  export DISPLAY=:99
  sleep 0.1  # Give Xvfb time to start
fi

# Run the test
./testqstring
