#!/bin/sh

# parmdbremote_scr: Script to invoke a distributed parmdbremote process
#
# Copyright (C) 2009
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$

if test $# != 10; then
  echo "run as:   parmdbremote-src 'socket' host port np rank"
  echo "                           pdb-part filesys ms-part-vds envfile"
  echo "                           wd"
  exit 1
fi
envfile=$9
wd=${10}

# Initialize environment.
if test "$envfile" != ""; then
  . $envfile
fi

# cd to work directory and add . to PATH for test purposes (make check).
if test -d $wd; then
  cd $wd
  PATH=.:$PATH
  export PATH
fi

parmdbremote $2 $3 $6    # host,port,parmdb-part
