#!/bin/sh

pert="1e-6"

echo "creating instrument_model (aips++)..."
parmdb << EOF
create db='$USER', dbtype='aips', tablename='demo'
adddef EJ11.real values=1, perturbation=${pert}
adddef EJ12.real values=0, perturbation=${pert}
adddef EJ21.real values=0, perturbation=${pert}
adddef EJ22.real values=1, perturbation=${pert}
adddef EJ11.imag values=1, perturbation=${pert}
adddef EJ12.imag values=0, perturbation=${pert}
adddef EJ21.imag values=0, perturbation=${pert}
adddef EJ22.imag values=1, perturbation=${pert}
adddef EJ11.ampl values=1, perturbation=${pert}
adddef EJ12.ampl values=0, perturbation=${pert}
adddef EJ21.ampl values=0, perturbation=${pert}
adddef EJ22.ampl values=0, perturbation=${pert}
adddef EJ11.phase values=0, perturbation=${pert}
adddef EJ12.phase values=0, perturbation=${pert}
adddef EJ21.phase values=0, perturbation=${pert}
adddef EJ22.phase values=0, perturbation=${pert}
adddef frot values=0, perturbation=${pert}
adddef drot values=0, perturbation=${pert}
adddef dell values=0, perturbation=${pert}
adddef gain.11 values=1, perturbation=${pert}
adddef gain.22 values=1, perturbation=${pert}
quit
EOF

echo "creating sky_model (aips++)..."
parmdb << EOF
create db='$USER', dbtype='aips', tablename='demo_gsm'
adddef RA.CP1  values=2.734, perturbation=${pert}, pert_rel=F
adddef DEC.CP1 values=0.45379, perturbation=${pert}, pert_rel=F
adddef StokesI.CP1 values=1, perturbation=${pert}
adddef StokesQ.CP1 values=0, perturbation=${pert}
adddef StokesU.CP1 values=0, perturbation=${pert}
adddef StokesV.CP1 values=0, perturbation=${pert}
adddef RA.CP2  values=2.73402, perturbation=${pert}, pert_rel=F
adddef DEC.CP2 values=0.45369, perturbation=${pert}, pert_rel=F
adddef StokesI.CP2 values=1, perturbation=${pert} 
adddef StokesQ.CP2 values=0, perturbation=${pert} 
adddef StokesU.CP2 values=0, perturbation=${pert}
adddef StokesV.CP2 values=0, perturbation=${pert}
adddef RA.CP3  values=2.73398, perturbation=${pert}, pert_rel=F
adddef DEC.CP3 values=0.45375, perturbation=${pert}, pert_rel=F
adddef StokesI.CP3 values=1, perturbation=${pert} 
adddef StokesQ.CP3 values=0, perturbation=${pert} 
adddef StokesU.CP3 values=0, perturbation=${pert}
adddef StokesV.CP3 values=0, perturbation=${pert}
quit
EOF
