#!/bin/sh

\rm -rf /tmp/$USER.demo*
cp -r /opt/lofar/data/BBS2/demo3.MEP /tmp/$USER.demo.MEP
cp -r /opt/lofar/data/BBS2/demo3_gsm.MEP /tmp/$USER.demo_gsm.MEP

ln -s /opt/lofar/data/BBS2/demo3.MS_p1 /tmp/$USER.demo
$LOFAR_CHECKTOOL ./tMSData /opt/lofar/data/BBS2/demo3.MS $USER /tmp/$USER.demo /tmp/$USER.demo.MEP /tmp/$USER.demo_gsm.MEP 100 MODEL_DATA
status=$?

\rm -rf /tmp/$USER.demo
ln -s /opt/lofar/data/BBS2/3C343/10008336.MS_p1 /tmp/$USER.demo
$LOFAR_CHECKTOOL ./tMSData /opt/lofar/data/BBS2/3C343/10008336.MS $USER /tmp/$USER.demo /tmp/$USER.demo.MEP /tmp/$USER.demo_gsm.MEP 14 DATA

#\rm -rf /tmp/$USER.demo*
exit $status
