# -- ConnectionSection --
#
# $Id$
#
#      name        vers   qual        constr.            descr.
#--------------------------------------------------------------------------------------------------------
node   Connection         4.0.0  development 'node constraint'  "Connections between hosts"

#      name             	vers   qual        constr.            descr.
#--------------------------------------------------------------------------------------------------------
#uses   Storage-Imaging 	4.0.0  development -                  "Connection between storage and imaging node"
