#!/bin/sh

# Run the TestBidirectional test program.
# First an empty database table is created.
# Thereafter the test program is run.
# If an argument is given to the script, the test program is not run
# making it possible to run the test program separately (e.g. to debug it).

# Create the database table.
psql -h dop50.astron.nl -U postgres test << _EOF_ > TestBidirectional_tmp.psql_out 2>&1
\i ../../../test/TestBidirectional.sql
\q
_EOF_

# Run the test program if no first argument is given.
if [ "$1" != "" ]; then
  exit 0;
fi
./TestBidirectional
STATUS=$?
if [ $STATUS != 0 ]; then
  exit $STATUS
fi


