#!/bin/sh

export OTB_DIR=/opt/sas/otb/server
export JAVA_HOME=/usr/java/jdk1.7.0_02

echo
echo --- Starting OTB Server ---

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OTB_DIR
export OTB_APP=$OTB_DIR/`basename $OTB_DIR/jOTDB3*.jar`
export CLASSPATH=$OTB_APP

for JAR_DEPENDENCY in $OTB_DIR/lib/*.jar
do
	echo -- Adding dependency to CLASSPATH: `basename $JAR_DEPENDENCY`
	export CLASSPATH=$CLASSPATH:$JAR_DEPENDENCY
done

echo Starting up ...

serverpid=0
ps -ef | grep -v grep | grep java | grep 12500 2>&1 1>/dev/null
if [ $? -ne 0 ]; then
    $JAVA_HOME/bin/java -cp $CLASSPATH nl.astron.lofar.sas.otb.jotdb3.jOTDBserver -s sas001 -d sas001 -p 12500 -o 12501 &
    serverpid=$!
fi

echo OTB Server stopped.
