#!/bin/sh

# tsetupparmdb.run: Script to test setupparmdb
#
# Copyright (C) 2008
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$


# Set srcdir if undefined (if run outside 'make check')
if test "$srcdir" = ""; then
  srcdir=../../../src
fi

# Add src directory to PATH (to find parmdb).
PATH=../src:$PATH
export PATH
which parmdb_main

# Create directories to create the parmdb-s in.
# They must match the FileName in in_ms*.vds.
rm -rf tsetupparmdb_tmp.ms0
rm -rf tsetupparmdb_tmp.ms1
rm -rf tsetupparmdb_tmp.ms2
mkdir tsetupparmdb_tmp.ms0
mkdir tsetupparmdb_tmp.ms1
mkdir tsetupparmdb_tmp.ms2

# Enclose output in angle brackets to exclude it from the assay diff.
# Use _tmp name for the gds, so the resulting parmdb also gets a _tmp name.
cp tsetupparmdb.in_gds tsetupparmdb_tmp.gds
echo ">>>"
$srcdir/../src/setupparmdb -overwrite tsetupparmdb_tmp.gds "" "" "" tsetupparmdb_tmp.log 0 tsetupparmdb_tmp.hfn `pwd`  ||  exit 1
echo "<<<"

# Append the three log files to the output.
# Wait for the subprocesses to finish.
sleep 5
grep -v 'log4cxx:' tsetupparmdb_tmp.log-0
grep -v 'log4cxx:' tsetupparmdb_tmp.log-1
grep -v 'log4cxx:' tsetupparmdb_tmp.log-2

# Check if the three parmdbs and overall VDS exist.
test -d tsetupparmdb_tmp.ms0/instrument  ||  exit 1
test -d tsetupparmdb_tmp.ms1/instrument  ||  exit 1
test -d tsetupparmdb_tmp.ms2/instrument  ||  exit 1
test -e tsetupparmdb_tmp.instrument  ||  exit 1
