#!/bin/bash

. ./testFuncs.sh

# See if the generateStationStreams.sh script works as we use it for the
# live test system, and check if it generates the file we have in the repos.

"$LOFARROOT/sbin/generateStationStreams.sh" > StationStreams.parset.out || exit

echo "Generated output. Comparing against installed (reference)."

diff "$LOFARROOT/etc/parset-additions.d/default/StationStreams.parset" StationStreams.parset.out
