#!/bin/bash
#
# loadPICtree : loads all components in an OTDB database
#
# Copyright (C) 2006
# ASTRON (Netherlands Foundation for Research in Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# Syntax: loadPICtree databasename
#
# $Id$
#
VERSION="v1.0"

# SyntaxError msg
#
SyntaxError()
{
	Msg=$1

	[ -z "${Msg}" ] || echo "ERROR: ${Msg}"
	echo ""
	echo "Syntax: $(basename $0) -D databasename [-H databaseserver] [-D directory]"
	echo "        - databasename is always needed"
        echo "        - directory is path to executables PVSS2SAS and load_PICtree [/opt/lofar/bin]"
	echo
}

DATABASE=
HOST=`hostname -s`
DIR="/opt/lofar/bin"

while getopts "hD:v:q:H:d:" OPTION
do
     case $OPTION in

         h)
             SyntaxError
             exit 1
             ;;
	 D)
	     DATABASE=$OPTARG
	     ;;
	 H)
	     HOST=$OPTARG
	     ;;
	 d)
	     DIR=$OPTARG
	     ;;
	 ?)
             SyntaxError
             exit 1
             ;;
       esac
done

if [[ -z $DATABASE ]]; then 
  echo "Please provide a database name!"
  SyntaxError
  exit
fi

#
# MAIN
#

if [[ -e $DIR/PVSS2SAS ]] && [[ -e $DIR/load_PICtree ]]; then 
  RESULTFILE=OTDBDatapoints.out
  rm -f ${RESULTFILE}
  echo "Creating PIC file..."
  ./createPICfile | $DIR/PVSS2SAS >${RESULTFILE}
  # create commandline for load_PICtree
  arguments=$DATABASE
  arguments=$arguments" "$HOST
  echo "Executing: $DIR/load_PICtree $arguments ${RESULTFILE} 2>&1 | tee loadPICtree.log"
  $DIR/load_PICtree $arguments ${RESULTFILE} 2>&1 | tee loadPICtree.log
  echo "Done; Logfile is loadPICtree.log"
else
  echo "Cannot find or execute $DIR/PVSS2SAS or $DIR/load_PICtree"
fi
