/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection */

#ifndef _Included_nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection
#define _Included_nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection
 * Method:    initOTDBconnection
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT void JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection_initOTDBconnection
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection
 * Method:    isConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection_isConnected
  (JNIEnv *, jobject);

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection
 * Method:    connect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection_connect
  (JNIEnv *, jobject);

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection
 * Method:    disconnect
 * Signature: ()Z
 */
JNIEXPORT void JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection
 * Method:    getTreeInfo
 * Signature: (IZ)Lnl/astron/lofar/sas/otb/jotdb3/jOTDBtree;
 */
JNIEXPORT jobject JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection_getTreeInfo
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection
 * Method:    getStateList
 * Signature: (IZLjava/lang/String;Ljava/lang/String;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection_getStateList
  (JNIEnv *, jobject, jint, jboolean, jstring, jstring);

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection
 * Method:    getTreeList
 * Signature: (SS)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection_getTreeList
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection
 * Method:    getDefaultTemplates
 * Signature: ()Ljava/util/Vector
 */
JNIEXPORT jobject JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection_getDefaultTemplates
  (JNIEnv *, jobject);

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection
 * Method:    getExecutableTrees
 * Signature: (S)Ljava/util/Vector
 */
JNIEXPORT jobject JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection_getExecutableTrees
(JNIEnv *, jobject, jshort);

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection
 * Method:    getTreeGroup
 * Signature: (II)Ljava/util/Vector
 */
JNIEXPORT jobject JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection_getTreeGroup
(JNIEnv *, jobject, jint, jint); 

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection
 * Method:    getTreesInPeriod
 * Signature: (SLjava/lang/String;Ljava/lang/String;)Ljava/util/Vector
 */
JNIEXPORT jobject JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection_getTreesInPeriod
(JNIEnv *, jobject, jshort, jstring, jstring );

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection
 * Method:    errorMsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection_errorMsg
  (JNIEnv *, jobject);

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection
 * Method:    getAuthToken
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection_getAuthToken
  (JNIEnv *, jobject);

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection
 * Method:    getDBName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jOTDBconnection_getDBName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
