#!/bin/sh

# Run the ExampleShMem test program using mpirun on 2 nodes.

if [ -f $MPIBIN/mpirun ]; then
  echo "localhost" > ExampleShMem_tmp.machinefile
  $MPIBIN/mpirun -np 2 -machinefile ExampleShMem_tmp.machinefile ExampleShMem 1
  $MPIBIN/mpirun -np 2 -machinefile ExampleShMem_tmp.machinefile ExampleShMem 2
  $MPIBIN/mpirun -np 2 -machinefile ExampleShMem_tmp.machinefile ExampleShMem 3
else
  echo "ExampleShMem.run skipped: probably MPI is not configured in"
  exit 3
fi
