# Source:  https://svn.astron.nl/LOFAR/trunk/SubSystems/Online_Cobalt/postinstall/lofarsys/bashrc

# Sample .bashrc for SuSE Linux
# Copyright (c) SuSE GmbH Nuernberg

# There are 3 different types of shells in bash: the login shell, normal shell
# and interactive shell. Login shells read ~/.profile and interactive shells
# read ~/.bashrc; in our setup, /etc/profile sources ~/.bashrc - thus all
# settings made here will also take effect in a login shell.
#
# NOTE: It is recommended to make language settings in ~/.profile rather than
# here, since multilingual X sessions would not work properly if LANG is over-
# ridden in every subshell.

# Some applications read the EDITOR variable to determine your favourite text
# editor. So uncomment the line below and enter the editor of your choice :-)
#export EDITOR=/usr/bin/vim
#export EDITOR=/usr/bin/mcedit

# enable core dumps!
ulimit -c unlimited

# unlimited stack space
ulimit -s unlimited

# do not generate alarms in Cobalt (for testing)
#export COBALT_NO_ALARM=1

# add casacore bin dir to PATH
export PATH=$PATH:/localhome/lofar/casacore-1.7.0/bin

# set up environment for 'current' Cobalt version
source /opt/lofar/lofarinit.sh
if [ $? -ne 0 ] && [ ! -d $HOME/lofar/current ]; then
  echo "Likely cause: $HOME/lofar/current does not refer to an installed LOFAR/Cobalt root directory (e.g. under $HOME/lofar/lofar_versions/ )."
fi

