#!/bin/sh

# tstartdproc: Test script startdistproc in various ways
#
# Copyright (C) 2008
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# @author Ger van Diepen <diepen AT astron nl>
#
# $Id$


# Set srcdir if not set.
if test "$srcdir" = ""; then
  srcdir=../../../test
fi
curdir=`pwd`
# Set the src and make it absolute.
ssdir=`cd $srcdir/../src > /dev/null 2>&1; pwd`
sedir=`cd ../src > /dev/null 2>&1; pwd`

# Add srcdir to PATH, so runlogpid can be found.
# Add ../src to PATH, so finddproc can be found
# Add test to PATH, so tstartdproc can be found.
PATH=$ssdir:$sedir:$curdir:$PATH
export PATH

startdistproc -dsn tstartdproc.in_vd -cdn tstartdproc.in_cd \
-mode single -dry -hfn tstartdproc_tmp.out0 -fdp ../src prog1 -arg "a b"
echo "status=$?"
cat tstartdproc_tmp.out0

echo ''
startdistproc -dsn tstartdproc.in_vd -cdn tstartdproc.in_cd \
-mode mpi -dry -hfn tstartdproc_tmp.out1 -fdp ../src prog1 -arg "a b"
echo "status=$?"
cat tstartdproc_tmp.out1

echo ''
startdistproc -useenv $curdir/tstartdproc_tmp.out2.envfile \
-dsn tstartdproc.in_vd -cdn tstartdproc.in_cd \
-mode 3851 -dry -hfn tstartdproc_tmp.out2 -fdp ../src prog1 -arg "a b" \
> tstartdproc_tmp.log2
echo "status=$?"
cat tstartdproc_tmp.out2
# Remove absolute directory path from logfile.
sed -e "s%$curdir%%g" tstartdproc_tmp.log2

echo ''
startdistproc -killonfail -useenv $curdir/tstartdproc_tmp.out3.envfile \
-logfile $curdir/tstartdproc_tmp.log3b \
-dsn tstartdproc.in_vd -cdn tstartdproc.in_cd1 -nostartmaster \
-mode 3851 -hfn tstartdproc_tmp.out3 -fdp ../src `pwd`/tstartdproc.in_run \
> tstartdproc_tmp.log3a
echo "status=$?"
cat tstartdproc_tmp.out3
# Print log file without lines containing directory path and pids.
# Outcomment lines with kill which contain pids.
# Remove other lines containing Killed: some systems print them, some don't.
# Also remove lines containing "Debug: registered context" which are written
# when not using log4cplus/cxx.
sed -e "s%$curdir%%g" -e 's/pid=[0-9]*/pid=nn/' -e 's/kill -9 .*/kill -9 /' tstartdproc_tmp.log3a
for i in 0 1 2
do
  sed -e "s%$curdir%%g" tstartdproc_tmp.log3b-$i | grep -v "^Debug: registered context"
  sed -e 's/pid=[0-9]*/pid=nn/' tstartdproc_tmp.out3.envfile.pid-$i | grep -v " Killed "
done
