#!/bin/sh

# mwimager-askap: mwimager-part using askap's cimager
#
# Copyright (C) 2008
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# @author Ger van Diepen <diepen AT astron nl>
#
# $Id$


# Find the path used to start the script.
pgmpath=`dirname $0`
pgmpath=`cd $pgmpath > /dev/null 2>&1  &&  pwd`

if test $# != 5; then
  echo "run as:   mwimager-askap parset-file seqnr ms-part ms-part-vds dry"
  exit 1
fi

psn=$1
seqnr=$2
msn=$3
vds=$4
dry=$5

psnbase=`basename $psn`

# Add channel info to the parset file.
cp $psn $psnbase.part$seqnr  ||  exit 1
schan=`getparsetvalue $psnbase.part$seqnr firstchan 2>/dev/null` || schan=0
echan=`getparsetvalue $psnbase.part$seqnr lastchan  2>/dev/null` || echan=-1
sfreq=`getparsetvalue $vds StartFreqs schan` || exit 1
efreq=`getparsetvalue $vds EndFreqs   echan` || exit 1
echo "Images.frequency = [$sfreq, $efreq]" >> $psnbase.part$seqnr
msdRa=`getparsetvalue $vds Extra.FieldDirectionRa 0 2>/dev/null` || extraRa=
msdDec=`getparsetvalue $vds Extra.FieldDirectionDec 0 2>/dev/null` || extraDec=
msdType=`getparsetvalue $vds Extra.FieldDirectionType 0 2>/dev/null` || extraType=
if test "$msdRa" != "" -a "$msdDec" != "" -a "$msdType" != ""; then
  echo "msDirRa = $msdRa" >> $psnbase.part$seqnr
  echo "msDirDec = $msdDec" >> $psnbase.part$seqnr
  echo "msDirType = $msdType" >> $psnbase.part$seqnr
fi
sed -e "s%^ *dataset *=.*%dataset = $msn%" $psnbase.part$seqnr > $psnbase.part$seqnr-tmp  ||  exit 1
mv $psnbase.part$seqnr-tmp $psnbase.part$seqnr  ||  exit 1

# Convert parset file from SAS format to cimager format.
convertimagerparset $psnbase.part$seqnr $psnbase.part$seqnr.cvt  ||  exit 1

if test "$dry" = dry; then
  cat $psnbase.part$seqnr.cvt
  exit 0
fi

# Run the imager.
echo "cimager.sh -inputs $psnbase.part$seqnr.cvt"
cimager.sh -inputs $psnbase.part$seqnr.cvt

# Create a symlink using the same name as cimager would create.
imgname=`getparsetvalue $psnbase.part$seqnr.cvt Cimager.Images.Names`
newname=`getparsetvalue $psnbase.part$seqnr.cvt imgname`
# Do not do it if it already exists as a directory without table.dat.
# Thus an already existing regular .img is overwritten.
makelink=1;
if ! test -L $newname  -a  -d $newname; then
  if test ! -e $newname/table.dat; then
    makelink=0
  fi
fi
nm=
if test -e $imgname.restored; then
  nm=$imgname.restored
  if test -e $imgname  -a  $imgname -nt $nm; then
    nm=$imgname
  fi
elif test -d $imgname; then
  nm=$imgname
fi
if test $makelink = 1  -a  "$nm" != ""; then
  echo "ln -s $nm $newname"
  rm -rf $newname
  ln -s $nm $newname
fi

# Convert to FITS.
## image2fits 
