#!/bin/sh

if test $# != 10; then
  echo "run as:   parmdbremote-src 'socket' host port np rank"
  echo "                           pdb-part filesys ms-part-vds"
  echo "                           lofarroot wd"
  exit 1
fi
lroot=$9
wd=${10}

# Source lofarinit to find parmdbremote in production environment.
if test -e  $lroot/lofarinit.sh; then
  sh $lroot/lofarinit.sh
fi
# cd to work directory and add . to PATH for test purposes (make check).
if test -d $wd; then
  cd $wd
  PATH=.:$PATH
  export PATH
fi

parmdbremote $2 $3 $6    # host,port,parmdb-part
