#!/bin/sh

# setupsourcedb-part: The distributed part of setupsourcedb
#
# Copyright (C) 2009
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$

# Find the path used to start the script.
pgmpath=`dirname $0`
pgmpath=`cd $pgmpath > /dev/null 2>&1  &&  pwd`

if test $# != 17; then
  echo "run as:  setupsourcedb-part dummy dummy dummy dummy rank"
  echo "                            ms-part filesys ms-part-vds envfile"
  echo "                            wd srccat makeopt pdbname overwrite dry"
  echo "                            stepfreq steptime"
  exit 1
fi

shift
shift
shift
shift
seqnr=$1
msn=$2
envfile=$5
wd=$6
srccat=$7
makeopt=$8
pdb=$9
overwrite=${10}
dry=${11}
stepfreq=${12}
steptime=${13}


# Initialize environment.
if test "$envfile" != ""; then
  . $envfile
fi

# Check if a sourcedb name is given.
if test "$pdb" = ""; then
  echo "setupsourcedb-part:empty pdb name given"
  exit 1
fi

# For 'make check' we need to qualify where makesourcedb is.
#case "$wd" in
#*/test)
#  pgmpath=../src/
#  ;;
#esac

# Set the working directory; derive it if needed.
if test "$wd" = ""  -o  "$wd" = "..."; then
  wd=`dirname "$msn"`
fi
cd $wd  ||  exit 1

# Enclose all options in quotes.
sdbopt=
for opt in $makeopt
do
  sdbopt="$sdbopt '$opt'"
done

# Append to the SourceDB. Delete it first if overwrite is given.
echo "makesourcedb $sdbopt in=$srccat out=$msn/$pdb"
if test "$dry" != dry; then
  if test $overwrite = 1; then
    rm -rf $msn/$pdb
  fi
  # Use eval to avoid problems with quotes in sdbopt.
  eval makesourcedb $sdbopt in=$srccat out=$msn/$pdb || exit 1

  if test "$stepfreq" != "."  -a  "$steptime" != "."; then
    # Put default steps into the sourcedb.
    parmdb_main <<EOF
open tablename="$msn/$pdb"
set stepx=$stepfreq, stepy=$steptime
EOF
  fi
fi
