#!/bin/sh

# setupparmdb-part: The distributed part of setupparmdb
#
# Copyright (C) 2009
# ASTRON (Netherlands Foundation for Research in Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# $Id$

# Find the path used to start the script.
pgmpath=`dirname $0`
pgmpath=`cd $pgmpath > /dev/null 2>&1  &&  pwd`

if test $# != 12; then
  echo "run as:  setupparmdb-part dummy dummy dummy dummy rank"
  "                               ms-part filesys ms-part-vds"
  echo "                          lofarroot pdbfile pdbname dry"
  exit 1
fi

shift
shift
shift
shift
seqnr=$1
msn=$4
lroot=$5
pdbfile=$6
pdb=$7
dry=$8


# Initialize lofar environment.
. $lroot/lofarinit.sh

# Check if a parmdb name is given (if empty, the MS gets deleted hereafter).
if test "$pdb" = ""; then
  echo "setupparmdb-part: empty pdb name given"
  exit 1
fi

# Get the MS name from the VDS file.
# If an MS name is given, use that.
if test ! -d "$msn"; then
  msn=`getparsetvalue $msn FileName`
fi

# Create the instrument ParmDB.
# Insert defaults for non-zero parameters.
echo "Create $msn/$pdb (copy of $pdbfile)"
if test "$dry" != dry; then
  rm -rf $msn/$pdb           # this is safe because $pdb is not empty
  cp -r $pdbfile $msn/$pdb
fi
