#!/bin/sh

# startparmdbdistr: Script to start the distributed parmdbremote processes
#
# Copyright (C) 2009
# ASTRON (Netherlands Foundation for Research in Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# $Id$

# Find the path used to start the script.
pgmpath=`dirname $0`
pgmpath=`cd $pgmpath > /dev/null 2>&1  &&  pwd`

# Determine the host name to be used. Default is result of hostname.
# Try if a connection can be made. If not, set it to localhost.
# This is merely to run the test tParmFacadeDistr.run on all possible systems.
host=`hostname`
ssh -o "ConnectTimeout=10" $host date > /dev/null 2>&1
if test $? != 0; then
  echo "localhost is used because $host is unreachable"
  host=localhost
fi
  
# Start parmdbremote for each part.
startdistproc -mode "$1" -nowait -masterhost $host -nostartmaster \
              -cdn "$2" -dsn "$3" $pgmpath/parmdbremote-scr "$LOFARROOT" `pwd`
