#!/bin/bash -ev

source MessageFuncs.sh

unset LOFARROOT # Make sure MessageRouter reads ./MessageRouter.conf

# Allow timeouts on commands. Use: alarm <timeout> <cmd> <args>
alarm() { perl -e 'alarm shift; exec @ARGV' "$@"; }

#
# ---- TEST: normal configuration -----
#

# Create a routing configuration
create_queue in1
create_queue in2
create_queue out1
create_queue out2
create_queue out3

echo '
[multicast]
in1: out1, out2
in2: out3
' > MessageRouter.conf

# Start MessageRouter
alarm 60 python $srcdir/../src/MessageRouter >&2 &
PID=$!

# Inject messages into all input queues
send_msg in1 "test1"
send_msg in2 "test2"

# Check output queues, we only want ONE message in each!
[ "`wait_msg 1 out1`" == "test1" ]
wait_msg 0 out1 && exit 1
[ "`wait_msg 1 out2`" == "test1" ]
wait_msg 0 out2 && exit 1
[ "`wait_msg 1 out3`" == "test2" ]
wait_msg 0 out3 && exit 1

# Check whether input queues have been emptied
wait_msg 0 in1 && exit 1
wait_msg 0 in2 && exit 1

# Stop MessageRouter
send_msg messagerouter.command "stop"
wait $PID

#
# ---- TEST: non-existing input queue ----
#

echo '
[multicast]
in.notexist: out1
' > MessageRouter.conf

# Start MessageRouter -- should crash
python $srcdir/../src/MessageRouter >&2 || true

#
# ---- TEST: non-existing output queue ----
#

echo '
[multicast]
in1: out.notexist
' > MessageRouter.conf

# Start MessageRouter -- should crash
python $srcdir/../src/MessageRouter >&2 || true

#
# ---- TEST: fowarding to dump.<inputqueue> topic -----
#

echo '
[multicast]
in1: out1
' > MessageRouter.conf

# Start MessageRouter
python $srcdir/../src/MessageRouter >&2 &
PID=$!

# Wait for topic to become available
sleep 1

# Start listening already, since topics are not persistent!
wait_msg 3 dump.in1 > tMessageRouter.out &
MSGPID=$!

# Wait for listener to attach to topic
sleep 1

# Inject a message
send_msg in1 "test1"

# Receive the message and verify the content
wait $MSGPID
diff <(echo "test1") tMessageRouter.out

# Stop MessageRouter
send_msg messagerouter.command "stop"
wait $PID

# Technically unnecessary with "bash -e"
exit 0

