#!/bin/sh

# Set srcdir if needed.
# It might not be set if the .run file is executed directly instead of
# by 'make check'.
if [ "$srcdir" = "" ]; then
  srcdir=../../../test
fi

# Create the ParmDB tables for tCorrect.
$srcdir/makeDemoParmDBCorr tCorrect
if [ $? != 0 ]; then
  exit 1
fi

\rm -rf tCorrect_tmp.MS1
if [ ! -d $LOFARDATAROOT/BBS2/demo3.MS_p1 ]; then
  exit 3
fi
cp -r $LOFARDATAROOT/BBS2/demo3.MS_p1 tCorrect_tmp.MS1

$LOFAR_CHECKTOOL ./tCorrect $USER tCorrect_tmp.MS1 tCorrect_tmp.demo_instr tCorrect_tmp.demo_sky
status=$?
exit $status
