#!/bin/sh

# Run the ExampleSocket test program by starting it twice.
# Once as server and once as client.

echo "Run1 (takes about 30 seconds, longer if checktool is used) ..."
rm -f tTH_Socket_tmp.result
($LOFAR_CHECKTOOL ./tTH_Socket -s 1>tTH_Socket_tmp.outs1 2>&1 ; echo $? >>tTH_Socket_tmp.result )&
echo "CLIENT OUTPUT"
 $LOFAR_CHECKTOOL ./tTH_Socket -c ; echo $? >>tTH_Socket_tmp.result
sleep 1
echo "SERVER OUTPUT"
cat tTH_Socket_tmp.outs1
grep "1" tTH_Socket_tmp.result
if [ $? -ne 1 ]; then
	echo "test failed!"
	exit 1
fi

# Do another run with starting the client before the server.
echo "Run2 (takes about 30 seconds, longer if checktool is used) ..."
rm -f tTH_Socket_tmp.result
($LOFAR_CHECKTOOL ./tTH_Socket -c 1>tTH_Socket_tmp.outc2 2>&1 ; echo $? >>tTH_Socket_tmp.result )&
echo "SERVER OUTPUT"
 $LOFAR_CHECKTOOL ./tTH_Socket -s ; echo $? >>tTH_Socket_tmp.result
sleep 1
echo "CLIENT OUTPUT"
cat tTH_Socket_tmp.outc2
grep "1" tTH_Socket_tmp.result
if [ $? -ne 1 ]; then
	echo "test failed!"
	exit 1
fi
echo "test succesful"
exit 0
