/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CampaignInfo.java
 *
 * Created on 28-feb-2010, 19:42:09
 */

package nl.astron.lofar.sas.otbcomponents;

import java.rmi.RemoteException;
import nl.astron.lofar.sas.otb.MainFrame;
import nl.astron.lofar.sas.otb.jotdb2.jCampaignInfo;
import nl.astron.lofar.sas.otb.jotdb2.jOTDBtree;
import nl.astron.lofar.sas.otb.util.OtdbRmi;
import nl.astron.lofar.sas.otb.util.UserAccount;
import org.apache.log4j.Logger;


/**
 *
 * @author Coolen
 */
public class CampaignInfo extends javax.swing.JPanel {

    static Logger logger = Logger.getLogger(CampaignInfo.class);
    static String name = "CampaignInfo";

    /** Creates new form BeanForm */
    public CampaignInfo() {
        initComponents();
        itsMainFrame=null;
    }

         /** Creates new form BeanForm with mainFrame info
     *
     * @params  aNode   node to obtain the info from
     *
     */
    public CampaignInfo(MainFrame aMainFrame) {
        initComponents();
        itsMainFrame = aMainFrame;
        initPanel();
    }

    public void setMainFrame(MainFrame aMainFrame) {
        if (aMainFrame != null) {
            itsMainFrame=aMainFrame;
            initPanel();
        } else {
            logger.debug("No Mainframe supplied");
        }
    }

    private void initPanel() {

        itsMainFrame.setHourglassCursor();


        this.inputName.setText("");
        this.inputTitle.setText("");
        this.inputPI.setText("");
        this.inputCO_I.setText("");
        this.inputContact.setText("");

        // check access
        UserAccount userAccount = itsMainFrame.getUserAccount();


        if(userAccount.isAdministrator()) {
            // enable/disable certain controls
        }
        if(userAccount.isAstronomer()) {
            // enable/disable certain controls
        }
        if(userAccount.isInstrumentScientist()) {
            // enable/disable certain controls
        }


         if (itsMainFrame != null) {
            try {
                itsTree=OtdbRmi.getRemoteOTDB().getTreeInfo(itsMainFrame.getSharedVars().getTreeID(),false);
                //get the CampaignName from the tree
                itsCampaignName=itsTree.campaign;

                // get the CampaignInfo from the tree
                itsCampaignInfo = OtdbRmi.getRemoteCampaign().getCampaign(itsCampaignName);
                if  (itsCampaignInfo != null) {
                   this.inputName.setText(itsCampaignInfo.itsName);
                    this.inputTitle.setText(itsCampaignInfo.itsTitle);
                    this.inputPI.setText(itsCampaignInfo.itsPI);
                    this.inputCO_I.setText(itsCampaignInfo.itsCO_I);
                    this.inputContact.setText(itsCampaignInfo.itsContact);
                } else {
                    this.inputName.setText("");
                    this.inputTitle.setText("");
                    this.inputPI.setText("");
                    this.inputCO_I.setText("");
                    this.inputContact.setText("");
                }
            } catch (RemoteException ex) {
                logger.debug("ObservationPanel: Error getting treeInfo/campaignInfo" + ex);
                this.inputName.setText("");
                this.inputTitle.setText("");
                this.inputPI.setText("");
                this.inputCO_I.setText("");
                this.inputContact.setText("");
            }
         } else {
            logger.debug("ERROR:  no MainFrame given");
        }
        itsMainFrame.setNormalCursor();

    }

    private MainFrame       itsMainFrame    = null;
    private String          itsCampaignName = "";
    private jOTDBtree       itsTree=null;
    private jCampaignInfo   itsCampaignInfo = null;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        inputTitle = new javax.swing.JTextField();
        inputPI = new javax.swing.JTextField();
        inputCO_I = new javax.swing.JTextField();
        inputContact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("Name");

        jLabel2.setText("Title");

        jLabel3.setText("Principal Investigator(s)");

        jLabel4.setText("Co Investigator(s)");

        jLabel5.setText("Contact");

        inputName.setEditable(false);

        inputTitle.setEditable(false);

        inputPI.setEditable(false);

        inputCO_I.setEditable(false);

        inputContact.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setText("Campaign Info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputName, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                            .addComponent(inputContact, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                            .addComponent(inputCO_I, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                            .addComponent(inputPI, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                            .addComponent(inputTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCO_I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputCO_I;
    private javax.swing.JTextField inputContact;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputPI;
    private javax.swing.JTextField inputTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
