#!/bin/sh -x
# constants
DBHOST=sas099.control.lofar

# This test requires Python 2.7+
python -c 'import sys, os; sys.exit(1 - int(sys.version >= "2.7"))' || exit 3

# This test requires access to DBHOST
ping -w 1 -c 1 $DBHOST || exit 3

# This test requires PostGres tooling
which dropdb || exit 3
which psql   || exit 3

# Setup a clean database with predefined content
dropdb -U postgres -h ${DBHOST} unittest_db
gzip -dc $srcdir/unittest_db.dump.gz | psql -U postgres -h ${DBHOST} -f -

# Run the unit test
# either with or without code coverage measurements,
# depending wheter coverage has been installed

if type "coverage" > /dev/null; then
    #run test using python coverage tool

    #erase previous results
    coverage erase

    #setup coverage config file
    printf "[report]\nexclude_lines = \n  if __name__ == .__main__.\n  def main\n" > .coveragerc

    coverage run --branch python t_getTreeGroup.py postgres ${DBHOST} unittest_db
    RESULT=$?
    if [ $RESULT -eq 0 ]; then
        echo " *** Code coverage results *** "
        coverage report -m
        echo " *** End coverage results *** "
    fi
    exit $RESULT
else
    #coverage not available
    echo "Please run: 'pip install coverage' to enable code coverage reporting of the unit tests"
    #run plain test script
    python t_getTreeGroup.py postgres ${DBHOST} unittest_db
fi

