# -- Calibration--
#
# $Id: Calibration.comp 20298 2012-03-02 13:41:04Z loose $
#
#      name        vers   qual        constr.            descr.
#--------------------------------------------------------------------------------------------------------
node  Calibration  4.0.0  development 'node constraint'  "Calibration pipeline"

#    name                    dir. type   unit   prun. vm   value                constr.  descr.
#--------------------------------------------------------------------------------------------------------
par  CalibratorSource        I    text   -	    100   0    ''                   -        "Calibrator source for generation of instrument model"

