#!/bin/sh

PROJ_PATH=`grep '^proj_path' ${PVSS_II} | sed 's/^.*proj_path *= * "//' | sed 's/".*//'| sed -n '$p' | tail -n 1`
cp -Rf pvss/* $PROJ_PATH
PVSS00ctrl -script libs/gcfpa-prep.ctl -currentproj
PVSS00ctrl -script libs/gcfpa-cwd.ctl -currentproj &
if [ -r customPrepPVSSDB.ctl ]; then
	cp *.ctl $PROJ_PATH/scripts
	PVSS00ctrl -script customPrepPVSSDB.ctl -currentproj
	rm -f $PROJ_PATH/scripts/customPrepPVSSDB.ctl
fi