#!/bin/sh

curPath=`pwd`
if [ "$OSTYPE" = "win32" ]; then
  curPath=C:`pwd`
fi


#
# set local remoteDriver on in the project
#
cp config/config config/config.orig
cp config/config.nav config/config

cp config/progs config/progs.orig
cp config/progs.nav config/progs










