#!/bin/sh

# prepareBBDone: run the scripts that need to be run once for BlackBoardDemo
#
#  Copyright (C) 2004
#  ASTRON (Netherlands Foundation for Research in Astronomy)
#  P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#  $Id$

# the following options can be given:
# -dbtype  Database type (right now only monet, postgres and mysql are supported)
# -host    Host (default = localhost)
# -user    User

DBTYPE="mysql"
HOST="lofar6.astron.nl"
BBHOST="dop50.astron.nl"
USER=`whoami`

while [ 1 = 1 ]
do
  if [ "$1" = "-host" ]; then
    shift
    HOST="$1"
    shift
  elif [ "$1" = "-bbhost" ]; then
    shift
    BBHOST="$1"
    shift
  elif [ "$1" = "-dbtype" ]; then
    shift
    DBTYPE="$1"
    shift
  elif [ "$1" = "-user" ]; then
    shift
    USER="$1"
    shift
  else
    break;
  fi
done

../../src/createParamTables -host $HOST -user $USER -dbtype $DBTYPE
../../src/fillDefaultTables -host $HOST -user $USER -dbtype $DBTYPE
../../src/prepareBBD        -host $HOST -user $USER -dbtype $DBTYPE -bbhost $BBHOST
