#!/bin/sh

# mwimager.cc: Script to start a distributed cimager process
#
# Copyright (C) 2008
# ASTRON (Netherlands Foundation for Research in Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# $Id$


# Find the path used to start the script.
pgmpath=`dirname $0`
pgmpath=`cd $pgmpath > /dev/null 2>&1  &&  pwd`

# Check if LOFARROOT is set.
if test "$LOFARROOT" = ""; then
  echo "LOFARROT is undefined; source lofarinit.(c)sh first"
  exit 1
fi

# First argument must be ms-name.
# Second one is optional clusterdesc name.
# Third one is optional dry run (0=normal, 1=dry).
if test $# = 0; then
  echo "run as:   mwimager parset-file [clusterdesc] [wd] [logfile] [dry] [hfn]"
  echo "       parset-file   name of parset file"
  echo "       clusterdesc   name of clusterdesc file"
  echo "                     default is $HOME/CEP.cl;usterdesc"
  echo "       wd            working directory in subprocesses"
  echo "       logfile       root name of logfile of each subprocess"
  echo "                     A sequence number gets appended to it"
  echo "                     default is mwimager.log"
  echo "       dry           dry = do a dry run, i.e. only print commands"
  echo "       hfn           name of the hostfile (machinefile) created"
  echo "                     by startdistproc"
  echo "                     Only needed for test purposes"
  exit 1
else
  psn=$1
  shift
fi
cdn=$HOME/CEP.clusterdesc
if test $# != 0; then
  cdn=$1
  shift
fi
wd=0
if test $# != 0; then
  wd=$1
  shift
fi
logfile=
if test $# != 0; then
  logfile=$1
  shift
fi
dry=0
if test $# != 0; then
  dry=$1
  shift
fi
hfn=
if test $# != 0; then
  hfn=$1
  shift
fi

# Prepend parset with pwd if it has a relative file name.
case "$psn" in
    /*)
	;;
    *)
	psn=$wd/$psn
	;;
esac

# Get dataset name from the parset.
msname=`getparsetvalue $psn dataset` || exit 1

# Start the imager processes on the various machines.
echo "startdistproc -mode 0 -nomasterhost -dsn $msname -hfn "$hfn" -cdn $cdn -logfile "$logfile" $pgmpath/mwimager-part $LOFARROOT $psn $wd $dry"
startdistproc -mode 0 -nomasterhost -dsn $msname -hfn "$hfn" -cdn $cdn -logfile "$logfile" $pgmpath/mwimager-part $LOFARROOT $psn $wd $dry
