#!/bin/sh

# clearParamTables: clear previously computed parameters from tables
#
#  Copyright (C) 2004
#  ASTRON (Netherlands Foundation for Research in Astronomy)
#  P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#  $Id$

# the following options can be given:
# -dbtype  Database type (right now only monet, postgres and mysql are supported)
# -host    Host (default = localhost)
# -user    User

DBTYPE="mysql"
HOST="localhost"
USER="zwart"
AIPSTABLECREATOR="glish -l /lofarbuild/weekly/LOFAR/CEP/CPA/PSS3/CAL/src/parmtable.g"

# read commandline options
while [ 1 = 1 ]
do
  if [ "$1" = "-host" ]; then
    shift
    HOST="$1"
    shift
  elif [ "$1" = "-dbtype" ]; then
    shift
    DBTYPE="$1"
    shift
  elif [ "$1" = "-user" ]; then
    shift
    USER="$1"
    shift
  else
    break;
  fi
done


# set sqlclient options
if [ "$DBTYPE" = "mysql" ]; then
# for mysql
    SQLCLIENT="mysql -h $HOST -u mysql $USER"
elif [ "$DBTYPE" = "postgres" ]; then
# for postgres
    SQLCLIENT="psql -h $HOST -U postgres $USER"
elif [ "$DBTYPE" = "monet" ]; then
# for monet:
    SQLCLIENT="MapiClient -h $HOST -l sql -u monetdb -P monetdb"
elif [ "$DBTYPE" = "aips" ]; then
# for aips:
    SQLCLIENT=""
else
    echo "Unkown dbtype"
    exit 1
fi


if [ "$DBTYPE" = "aips" ]; then
# for aips, simply delete tables and recreate them
    echo " " > aipscreate
    for n in 1 2 3 4 5 6 ; do
      tablename=meqmodel${n}.MEP
      rm -rf $tablename
      echo "parmtable(\"${tablename}\", T)" >> aipscreate
      tablename=skymodel${n}.MEP
      rm -rf $tablename
      echo "parmtable(\"${tablename}\", T)" >> aipscreate
    done
    echo "exit" >> aipscreate
    $AIPSTABLECREATOR < aipscreate
else
# for sql databases: clear tables
    echo " " > sql_clear
    for n in 1 2 3 4 5 6 ; do
	tablename=meqmodel$n
	echo " DELETE FROM ${tablename} ; " >> sql_clear
	tablename=skymodel$n
	echo " DELETE FROM ${tablename} ; " >> sql_clear
    done
    $SQLCLIENT < sql_clear
fi
