#!/bin/sh

# this script can be used to fill the database before running the blackboard demo
# you can change the SQLCLIENT and PARMDBCONNECT to match your database type (postgres or mysql)
# and you database name



# change this to your database/username
# for postgres:
#SQLCLIENT="psql -h dop50 -U postgres zwart"
# for mysql:
SQLCLIENT="mysql -h dop50 -u mysql zwart"

PARMDBCONNECT="connect db='zwart', dbtype='mysql' "

TABLEFILLER="src/fillsqldb"

for n in 1 2 3 4 5 6 
  do
    	tablename=meqmodel$n
    	echo ${tablename}
	echo " " > sql_create

	echo " DROP TABLE ${tablename}; " >> sql_create
	echo " DROP TABLE ${tablename}def; " >> sql_create
        echo " CREATE TABLE ${tablename}def (
        	Coeff		text,
		SimCoeff	text,
		PertSimCoeff	text,
		pertvalue	double precision,
		isrelpert	int4,
		t0		double precision,
		f0		double precision,
		normalized	int4,
		name		text,
		srcnr		int8,
		statnr		int8
		);" >> sql_create
#	echo " CREATE INDEX ${tablename}def_name_idx ON ${tablename}def (name);" >> sql_create
        echo " CREATE TABLE ${tablename} (
        	Coeff		text,
		SimCoeff	text,
		PertSimCoeff	text,
		pertvalue	double precision,
		isrelpert	int4,
		t0		double precision,
		f0		double precision,
		normalized	int4,
		tb		double precision,
		te		double precision,
		fb		double precision,
		fe		double precision,
		name		text,
		srcnr		int8,
		statnr		int8
		);" >> sql_create
#	echo " CREATE INDEX ${tablename}_name_idx ON ${tablename} (name);" >> sql_create

	$SQLCLIENT < sql_create

	echo $PARMDBCONNECT ",  tablename='${tablename}'" > fill.parmdb
	echo "adddef frot values=0" >> fill.parmdb
	echo "adddef drot values=0" >> fill.parmdb
	echo "adddef dell values=0" >> fill.parmdb
	echo "adddef gain.11 values=1" >> fill.parmdb
	echo "adddef gain.22 values=1" >> fill.parmdb
	echo "adddef EJ11.real.SR1.CP1 values=1" >> fill.parmdb
	echo "adddef EJ11.real.SR1.CP2 values=1" >> fill.parmdb
	echo "adddef EJ11.real.SR1.CP3 values=1" >> fill.parmdb
	echo "adddef EJ11.real.SR2.CP1 values=1" >> fill.parmdb
	echo "adddef EJ11.real.SR2.CP2 values=1" >> fill.parmdb
	echo "adddef EJ11.real.SR2.CP3 values=1" >> fill.parmdb
	echo "adddef EJ11.real.SR5.CP1 values=1" >> fill.parmdb
	echo "adddef EJ11.real.SR5.CP2 values=1" >> fill.parmdb
	echo "adddef EJ11.real.SR5.CP3 values=1" >> fill.parmdb
	echo "adddef EJ11.real.SR9.CP1 values=1" >> fill.parmdb
	echo "adddef EJ11.real.SR9.CP2 values=1" >> fill.parmdb
	echo "adddef EJ11.real.SR9.CP3 values=1" >> fill.parmdb
	echo "adddef EJ11.real values=1" >> fill.parmdb
	echo "adddef EJ12.real values=0" >> fill.parmdb
	echo "adddef EJ21.real values=0" >> fill.parmdb
	echo "adddef EJ22.real values=1" >> fill.parmdb
	echo "adddef EJ11.imag values=1" >> fill.parmdb
	echo "adddef EJ12.imag values=0" >> fill.parmdb
	echo "adddef EJ21.imag values=0" >> fill.parmdb
	echo "adddef EJ22.imag values=1" >> fill.parmdb
	echo "quit" >> fill.parmdb
	$TABLEFILLER < fill.parmdb

    	tablename=skymodel$n
    	echo ${tablename}

	echo " " > sql_create
	echo "drop table ${tablename};" >> sql_create
	echo "drop table ${tablename}def;" >> sql_create
        echo " CREATE TABLE ${tablename}def (
        	Coeff		text,
		SimCoeff	text,
		PertSimCoeff	text,
		pertvalue	double precision,
		isrelpert	int4,
		t0		double precision,
		f0		double precision,
		normalized	int4,
		name		text,
		srcnr		int8,
		statnr		int8
		);" >> sql_create
#	echo " CREATE INDEX ${tablename}def_name_idx ON ${tablename}def (name);" >> sql_create
        echo " CREATE TABLE ${tablename} (
        	Coeff		text,
		SimCoeff	text,
		PertSimCoeff	text,
		pertvalue	double precision,
		isrelpert	int4,
		t0		double precision,
		f0		double precision,
		normalized	int4,
		tb		double precision,
		te		double precision,
		fb		double precision,
		fe		double precision,
		name		text,
		srcnr		int8,
		statnr		int8
		);" >> sql_create
#	echo " CREATE INDEX ${tablename}_name_idx ON ${tablename} (name);" >> sql_create
	$SQLCLIENT < sql_create

	echo $PARMDBCONNECT ", tablename='${tablename}'" > fill.parmdb
    	echo "adddef RA.CP1 values=10:26:35.0" >> fill.parmdb
    	echo "adddef DEC.CP1 values=26.0.0.0" >> fill.parmdb
    	echo "adddef StokesI.CP1 values=1.0" >> fill.parmdb
    	echo "adddef StokesQ.CP1 values=0 " >> fill.parmdb
    	echo "adddef StokesU.CP1 values=0 " >> fill.parmdb
    	echo "adddef StokesV.CP1 values=0" >> fill.parmdb
    	echo "adddef RA.CP2 values=10:26:35.4" >> fill.parmdb
    	echo "adddef DEC.CP2 values=26.0.21.0" >> fill.parmdb
    	echo "adddef StokesI.CP2 values=1.0" >> fill.parmdb
    	echo "adddef StokesQ.CP2 values=0 " >> fill.parmdb
    	echo "adddef StokesU.CP2 values=0 " >> fill.parmdb
    	echo "adddef StokesV.CP2 values=0" >> fill.parmdb
    	echo "adddef RA.CP3 values=10:26:37.1" >> fill.parmdb
    	echo "adddef DEC.CP3 values=25.59.49.0" >> fill.parmdb
    	echo "adddef StokesI.CP3 values=1.0" >> fill.parmdb
    	echo "adddef StokesQ.CP3 values=0 " >> fill.parmdb
    	echo "adddef StokesU.CP3 values=0 " >> fill.parmdb
    	echo "adddef StokesV.CP3 values=0" >> fill.parmdb

    	echo "adddef RA.CP4 values=10:26:34.8" >> fill.parmdb
    	echo "adddef DEC.CP4 values=25.59.39.0" >> fill.parmdb
    	echo "adddef StokesI.CP4 values=1.0" >> fill.parmdb
    	echo "adddef StokesQ.CP4 values=0 " >> fill.parmdb
    	echo "adddef StokesU.CP4 values=0 " >> fill.parmdb
    	echo "adddef StokesV.CP4 values=0" >> fill.parmdb

    	echo "adddef RA.CP5 values=10:26:36.3" >> fill.parmdb
    	echo "adddef DEC.CP5 values=26.0.11.0" >> fill.parmdb
    	echo "adddef StokesI.CP5 values=1.0" >> fill.parmdb
    	echo "adddef StokesQ.CP5 values=0 " >> fill.parmdb
    	echo "adddef StokesU.CP5 values=0 " >> fill.parmdb
    	echo "adddef StokesV.CP5 values=0" >> fill.parmdb

    	echo "adddef RA.CP6 values=10:26:36.1" >> fill.parmdb
    	echo "adddef DEC.CP6 values=25.59.59.0" >> fill.parmdb
    	echo "adddef StokesI.CP6 values=1.0" >> fill.parmdb
    	echo "adddef StokesQ.CP6 values=0 " >> fill.parmdb
    	echo "adddef StokesU.CP6 values=0 " >> fill.parmdb
    	echo "adddef StokesV.CP6 values=0" >> fill.parmdb

    	echo "adddef RA.CP7 values=10:26:37.6" >> fill.parmdb
    	echo "adddef DEC.CP7 values=25.59.56.0" >> fill.parmdb
    	echo "adddef StokesI.CP7 values=1.0" >> fill.parmdb
    	echo "adddef StokesQ.CP7 values=0 " >> fill.parmdb
    	echo "adddef StokesU.CP7 values=0 " >> fill.parmdb
    	echo "adddef StokesV.CP7 values=0" >> fill.parmdb

    	echo "adddef RA.CP8 values=10:26:34.5" >> fill.parmdb
    	echo "adddef DEC.CP8 values=25.59.51." >> fill.parmdb
    	echo "adddef StokesI.CP8 values=1.0" >> fill.parmdb
    	echo "adddef StokesQ.CP8 values=0 " >> fill.parmdb
    	echo "adddef StokesU.CP8 values=0 " >> fill.parmdb
    	echo "adddef StokesV.CP8 values=0" >> fill.parmdb

    	echo "adddef RA.CP9 values=10:26:36.6" >> fill.parmdb
    	echo "adddef DEC.CP9 values=26.0.15.5" >> fill.parmdb
    	echo "adddef StokesI.CP9 values=1.0" >> fill.parmdb
    	echo "adddef StokesQ.CP9 values=0 " >> fill.parmdb
    	echo "adddef StokesU.CP9 values=0 " >> fill.parmdb
    	echo "adddef StokesV.CP9 values=0" >> fill.parmdb

    	echo "adddef RA.CP10 values=10:26:35.6" >> fill.parmdb
    	echo "adddef DEC.CP10 values=26.0.0.0" >> fill.parmdb
    	echo "adddef StokesI.CP10 values=1.0" >> fill.parmdb
    	echo "adddef StokesQ.CP10 values=0 " >> fill.parmdb
    	echo "adddef StokesU.CP10 values=0 " >> fill.parmdb
    	echo "adddef StokesV.CP10 values=0" >> fill.parmdb
	echo "quit" >> fill.parmdb
	$TABLEFILLER < fill.parmdb

done

#create the bb tables
echo " " > sql_create
echo " DROP TABLE bbsolutions;" >> sql_create
echo " DROP TABLE bbworkorders;" >> sql_create
echo " CREATE TABLE bbworkorders (
       ObjId BIGINT NOT NULL UNIQUE PRIMARY KEY, 
       Owner BIGINT NOT NULL, 
       VersionNr INTEGER NOT NULL, 
       ID INTEGER, 
       TAG INTEGER, 
       SEQNR BIGINT, 
       DATA TEXT, 
       WOID INTEGER, 
       STATUS INTEGER, 
       KSTYPE TEXT, 
       STRATEGYNO INTEGER, 
       NOSTARTSOLS INTEGER, 
       ARGSSIZE INTEGER, 
       NUMBEROFPARAM INTEGER);" >> sql_create
echo "create table bbsolutions (
      ObjId BIGINT NOT NULL UNIQUE PRIMARY KEY, 
      Owner BIGINT NOT NULL, 
      VersionNr INTEGER NOT NULL, 
      ID INTEGER, 
      TAG INTEGER, 
      SEQNR BIGINT, 
      DATA TEXT, 
      BBID INTEGER, 
      WOID INTEGER, 
      ITERATION INTEGER, 
      FIT DOUBLE PRECISION, 
      MU DOUBLE PRECISION, 
      STDDEV DOUBLE PRECISION, 
      CHI DOUBLE PRECISION, 
      NUMBEROFPARAM INTEGER);" >> sql_create
echo "\q" >> sql_create
$SQLCLIENT < sql_create
