#!/bin/sh

cp ${srcdir}/PO_tAttr1.sql .

# Define exit and interrupt handler to clean up files.
trap 'rm -f PO_tAttr1.sql tAtrr1_tmp.psql_out ; \
      trap 0 ; \
      exit $STATUS' 0 1 2 3 15

psql -h dop50.astron.nl -U postgres test << _EOF_ > tAtrr1_tmp.psql_out 2>&1
\i PO_tAttr1.sql
\q
_EOF_

# Let tAttr1 fill the db.

# LOFAR_CHECKTOOL can define a command (like valgrind) for the executable.
$LOFAR_CHECKTOOL ./tAttr1 1
