    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
    #include "DMI/AtomicID.h"
    #include "DMI/TypeInfo.h"
    #include "DMI/DynamicTypeManager.h"
    #include "DMI/Packer.h"

    int aidRegistry_MSVisAgent ()
    {
      return 1;
    }

static AtomicID::Register aid_reg_MS(-1120,"MS");
static AtomicID::Register aid_reg_MSVisInputAgent(-1119,"MSVisInputAgent");
static AtomicID::Register aid_reg_MSVisOutputAgent(-1118,"MSVisOutputAgent");
static AtomicID::Register aid_reg_DDID(-1122,"DDID");
static AtomicID::Register aid_reg_VDSID(-1121,"VDSID");
static AtomicID::Register aid_reg_Selection(-1124,"Selection");
static AtomicID::Register aid_reg_Tile(-1123,"Tile");
static AtomicID::Register aid_reg_String(-1128,"String");
static AtomicID::Register aid_reg_Column(-1125,"Column");
static AtomicID::Register aid_reg_Size(-1127,"Size");
static AtomicID::Register aid_reg_Format(-1126,"Format");
static AtomicID::Register aid_reg_Vis(-1116,"Vis");
static AtomicID::Register aid_reg_Input(-1075,"Input");
static AtomicID::Register aid_reg_Params(-1135,"Params");
static AtomicID::Register aid_reg_Start(-1134,"Start");
static AtomicID::Register aid_reg_End(-1131,"End");

