      #ifndef AID_MSVisAgent_h
      #define AID_MSVisAgent_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
      #include "DMI/AtomicID.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_MSVisAgent ();

#ifndef _defined_id_AidColumn
#define _defined_id_AidColumn 1
const AtomicID AidColumn(-1125);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgent.aidlist:1
const int AidColumn_int = -1125;
#endif
#ifndef _defined_id_AidDDID
#define _defined_id_AidDDID 1
const AtomicID AidDDID(-1122);                    // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgent.aidlist:2
const int AidDDID_int = -1122;
#endif
#ifndef _defined_id_AidEnd
#define _defined_id_AidEnd 1
const AtomicID AidEnd(-1131);                     // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/VisAgent/src/VisAgent.aidlist:2
const int AidEnd_int = -1131;
#endif
#ifndef _defined_id_AidFormat
#define _defined_id_AidFormat 1
const AtomicID AidFormat(-1126);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgent.aidlist:4
const int AidFormat_int = -1126;
#endif
#ifndef _defined_id_AidInput
#define _defined_id_AidInput 1
const AtomicID AidInput(-1075);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOPUSSY/src/OCTOPUSSY.aidlist:34
const int AidInput_int = -1075;
#endif
#ifndef _defined_id_AidMS
#define _defined_id_AidMS 1
const AtomicID AidMS(-1120);                      // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/VisCube/src/VisCube.aidlist:40
const int AidMS_int = -1120;
#endif
#ifndef _defined_id_AidMSVisInputAgent
#define _defined_id_AidMSVisInputAgent 1
const AtomicID AidMSVisInputAgent(-1119);         // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgent.aidlist:7
const int AidMSVisInputAgent_int = -1119;
#endif
#ifndef _defined_id_AidMSVisOutputAgent
#define _defined_id_AidMSVisOutputAgent 1
const AtomicID AidMSVisOutputAgent(-1118);        // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgent.aidlist:8
const int AidMSVisOutputAgent_int = -1118;
#endif
#ifndef _defined_id_AidParams
#define _defined_id_AidParams 1
const AtomicID AidParams(-1135);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgent.aidlist:9
const int AidParams_int = -1135;
#endif
#ifndef _defined_id_AidSelection
#define _defined_id_AidSelection 1
const AtomicID AidSelection(-1124);               // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgent.aidlist:10
const int AidSelection_int = -1124;
#endif
#ifndef _defined_id_AidSize
#define _defined_id_AidSize 1
const AtomicID AidSize(-1127);                    // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgent.aidlist:11
const int AidSize_int = -1127;
#endif
#ifndef _defined_id_AidStart
#define _defined_id_AidStart 1
const AtomicID AidStart(-1134);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgent.aidlist:12
const int AidStart_int = -1134;
#endif
#ifndef _defined_id_AidString
#define _defined_id_AidString 1
const AtomicID AidString(-1128);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgent.aidlist:13
const int AidString_int = -1128;
#endif
#ifndef _defined_id_AidTile
#define _defined_id_AidTile 1
const AtomicID AidTile(-1123);                    // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgent.aidlist:14
const int AidTile_int = -1123;
#endif
#ifndef _defined_id_AidVDSID
#define _defined_id_AidVDSID 1
const AtomicID AidVDSID(-1121);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgent.aidlist:15
const int AidVDSID_int = -1121;
#endif
#ifndef _defined_id_AidVis
#define _defined_id_AidVis 1
const AtomicID AidVis(-1116);                     // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/VisAgent/src/VisAgent.aidlist:10
const int AidVis_int = -1116;
#endif


#endif
