#!/bin/bash

. ./testFuncs.sh

# Replace PVSSGatewayStub's path where it outputs events with stdout,
# such that the test framework can check against the .stdout ref output.
cp "$LOFARROOT/etc/PVSSGatewayStub.conf" "$LOFARROOT/etc/PVSSGatewayStub.conf.backup"
sed -i -e '/outputFile[[:blank:]]*=/d' "$LOFARROOT/etc/PVSSGatewayStub.conf"
echo "outputFile = /dev/stdout" >> "$LOFARROOT/etc/PVSSGatewayStub.conf"

gwPid=none
sbPid=none
trap "kill -9 $gwPid $sbPid; mv $LOFARROOT/etc/PVSSGatewayStub.conf.backup $LOFARROOT/etc/PVSSGatewayStub.conf" \
  SIGTERM SIGINT SIGQUIT SIGHUP

# Start ServiceBroker and PVSSGatewayStub.
# They need time to (re)connect, but the necessary sleep time is in ~RTmetadata().
ServiceBroker &
sbPid=$!

PVSSGatewayStub &
gwPid=$!

../../../MAC/MACIO/test/tRTmetadata > /dev/null  # logging disrupts output verif

testStatus=$?
[ $testStatus -eq 0 ] || echo "Error: Test exited with status $testStatus"

kill $gwPid
wait $gwPid
gwStatus=$?
[ $gwStatus -eq 0 ] || echo "Error: PVSSGatewayStub exited with status $gwStatus"

kill $sbPid
wait $sbPid
sbStatus=$?
[ $sbStatus -eq 0 ] || echo "Error: ServiceBroker exited with status $sbStatus"

mv "$LOFARROOT/etc/PVSSGatewayStub.conf.backup" "$LOFARROOT/etc/PVSSGatewayStub.conf"

[ $testStatus -eq 0 -a $gwStatus -eq 0 -a $sbStatus -eq 0 ]
