/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_astron_lofar_sas_otb_jotdb3_jTreeValue */

#ifndef _Included_nl_astron_lofar_sas_otb_jotdb3_jTreeValue
#define _Included_nl_astron_lofar_sas_otb_jotdb3_jTreeValue
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jTreeValue
 * Method:    addKVT
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jTreeValue_addKVT__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jTreeValue
 * Method:    addKVT
 * Signature: (Lnl/astron/lofar/sas/otb/jotdb3/jOTDBvalue;)Z
 */
JNIEXPORT jboolean JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jTreeValue_addKVT__Lnl_astron_lofar_sas_otb_jotdb3_jOTDBvalue_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jTreeValue
 * Method:    addKVTlist
 * Signature: (Ljava/util/Vector;)Z
 */
JNIEXPORT jboolean JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jTreeValue_addKVTlist
  (JNIEnv *, jobject, jobject);

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jTreeValue
 * Method:    searchInPeriod
 * Signature: (IILjava/lang/String;Ljava/lang/String;Z)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jTreeValue_searchInPeriod
  (JNIEnv *, jobject, jint, jint, jstring, jstring, jboolean);

/*
 * Class:     nl_astron_lofar_sas_otb_jotdb3_jTreeValue
 * Method:    getSchedulableItems
 * Signature: (I)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_nl_astron_lofar_sas_otb_jotdb3_jTreeValue_getSchedulableItems
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
