/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jOTDB_jTreeMaintenance */

#ifndef _Included_jOTDB_jTreeMaintenance
#define _Included_jOTDB_jTreeMaintenance
#ifdef __cplusplus
extern "C" {
#endif

   namespace LOFAR 
     {
	namespace jOTDB 
	  {
	     
   
   /*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    initTreeMaintenance
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jOTDB_jTreeMaintenance_initTreeMaintenance
  (JNIEnv *, jobject);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    getNode
 * Signature: (I)LjOTDB/jVICnodeDef;
 */
JNIEXPORT jobject JNICALL Java_jOTDB_jTreeMaintenance_getNode__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    buildTemplateTree
 * Signature: (IS)I
 */
JNIEXPORT jint JNICALL Java_jOTDB_jTreeMaintenance_buildTemplateTree
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    copyTemplateTree
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jOTDB_jTreeMaintenance_copyTemplateTree
  (JNIEnv *, jobject, jint);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    getNode
 * Signature: (II)LjOTDB/jOTDBnode;
 */
JNIEXPORT jobject JNICALL Java_jOTDB_jTreeMaintenance_getNode__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    getItemList
 * Signature: (III)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_jOTDB_jTreeMaintenance_getItemList__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    getItemList
 * Signature: (ILjava/lang/String;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_jOTDB_jTreeMaintenance_getItemList__ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    dupNode
 * Signature: (IIS)I
 */
JNIEXPORT jint JNICALL Java_jOTDB_jTreeMaintenance_dupNode
  (JNIEnv *, jobject, jint, jint, jshort);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    saveNode
 * Signature: (LjOTDB/jOTDBnode;)Z
 */
JNIEXPORT jboolean JNICALL Java_jOTDB_jTreeMaintenance_saveNode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    saveNodeList
 * Signature: (Ljava/util/Vector;)Z
 */
JNIEXPORT jboolean JNICALL Java_jOTDB_jTreeMaintenance_saveNodeList
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    deleteNode
 * Signature: (LjOTDB/jOTDBnode;)Z
 */
JNIEXPORT jboolean JNICALL Java_jOTDB_jTreeMaintenance_deleteNode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    deleteNodeList
 * Signature: (Ljava/util/Vector;)Z
 */
JNIEXPORT jboolean JNICALL Java_jOTDB_jTreeMaintenance_deleteNodeList
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    checkTreeConstraints
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jOTDB_jTreeMaintenance_checkTreeConstraints
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    instanciateTree
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jOTDB_jTreeMaintenance_instanciateTree
  (JNIEnv *, jobject, jint);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    pruneTree
 * Signature: (IS)Z
 */
JNIEXPORT jboolean JNICALL Java_jOTDB_jTreeMaintenance_pruneTree
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    deleteTree
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jOTDB_jTreeMaintenance_deleteTree
  (JNIEnv *, jobject, jint);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    getTopNode
 * Signature: (I)LjOTDB/jOTDBnode;
 */
JNIEXPORT jobject JNICALL Java_jOTDB_jTreeMaintenance_getTopNode
  (JNIEnv *, jobject, jint);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    setClassification
 * Signature: (IS)Z
 */
JNIEXPORT jboolean JNICALL Java_jOTDB_jTreeMaintenance_setClassification
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    setTreeState
 * Signature: (IS)Z
 */
JNIEXPORT jboolean JNICALL Java_jOTDB_jTreeMaintenance_setTreeState
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     jOTDB_jTreeMaintenance
 * Method:    errorMsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jOTDB_jTreeMaintenance_errorMsg
  (JNIEnv *, jobject);
	  }
     }
   
#ifdef __cplusplus
}
#endif
#endif
