#include <jni.h>
#include "otb_navigatorRMIImpl.h"


JNIEXPORT jobjectArray JNICALL 
Java_otb_navigatorRMIImpl_getDBList (JNIEnv *env, jobject obj) {

 jobjectArray ret;
 int i;

 char *DBList[105]= { 
   "Departments.Administration.Cees_Boon.Salary=\"1500\"",
   "Departments.Administration.Cees_Boon.Address=\"Randervoordestraat 6\"",
   "Departments.Administration.Cees_Boon.PostalCode=\"7906HM\"",
   "Departments.Administration.Cees_Boon.City=\"Hoogeveen\"",
   "Departments.Administration.Cees_Boon.WorkPhone=\"0521-595117\"",
   "Departments.Administration.Cees_Boon.PrivatePhone=\"0528-268049\"",
   "Departments.Administration.Cees_Boon.Email=\"boon@astron.nl\"",
   "Departments.Administration.Jaap_van_de_Spreng.Salary=\"1600\"",
   "Departments.Administration.Jaap_van_de_Spreng.Address=\"Veenwijksweg 17\"",
   "Departments.Administration.Jaap_van_de_Spreng.PostalCode=\"8427RS\"",
   "Departments.Administration.Jaap_van_de_Spreng.City=\"Ravenswoud\"",
   "Departments.Administration.Jaap_van_de_Spreng.WorkPhone=\"0521-595130\"",
   "Departments.Administration.Jaap_van_de_Spreng.PrivatePhone=\"0516-433364\"",
   "Departments.Administration.Jaap_van_de_Spreng.Email=\"spreng@astron.nl\"",
   "Departments.Administration.Thijs_Zanders.Salary=\"1600\"",
   "Departments.Administration.Thijs_Zanders.Address=\"Alexander Dubcekweg 49\"",
   "Departments.Administration.Thijs_Zanders.PostalCode=\"9403XB\"",
   "Departments.Administration.Thijs_Zanders.City=\"Assen\"",
   "Departments.Administration.Thijs_Zanders.WorkPhone=\"0521-595148\"",
   "Departments.Administration.Thijs_Zanders.PrivatePhone=\"06-55707136\"",
   "Departments.Administration.Thijs_Zanders.Email=\"zanders@astron.nl\"",
   "Departments.ICT.Chris_Broekema.Salary=\"2000\"",
   "Departments.ICT.Chris_Broekema.Address=\"Aquamarijnstraat 309\"",
   "Departments.ICT.Chris_Broekema.PostalCode=\"9743PH\"",
   "Departments.ICT.Chris_Broekema.City=\"Groningen\"",
   "Departments.ICT.Chris_Broekema.WorkPhone=\"0521-595215\"",
   "Departments.ICT.Chris_Broekema.PrivatePhone=\"050-5714258\"",
   "Departments.ICT.Chris_Broekema.Email=\"broekema@astron.nl\"",
   "Departments.ICT.Arthur_Coolen.Salary=\"1900\"",
   "Departments.ICT.Arthur_Coolen.Address=\"Hoofdstraat 78\"",
   "Departments.ICT.Arthur_Coolen.PostalCode=\"9635AW\"",
   "Departments.ICT.Arthur_Coolen.City=\"Noordbroek\"",
   "Departments.ICT.Arthur_Coolen.WorkPhone=\"0521-595292\"",
   "Departments.ICT.Arthur_Coolen.PrivatePhone=\"0598-451712\"",
   "Departments.ICT.Arthur_Coolen.Email=\"coolen@astron.nl\"",
   "Departments.ICT.Ger_van_Diepen.Salary=\"2200\"",
   "Departments.ICT.Ger_van_Diepen.Address=\"Moleneinde 25\"",
   "Departments.ICT.Ger_van_Diepen.PostalCode=\"7981AM\"",
   "Departments.ICT.Ger_van_Diepen.City=\"Diever\"",
   "Departments.ICT.Ger_van_Diepen.WorkPhone=\"0521-595241\"",
   "Departments.ICT.Ger_van_Diepen.PrivatePhone=\"0521-592729\"",
   "Departments.ICT.Ger_van_Diepen.Email=\"diepen@astron.nl\"",
   "Departments.ICT.Alex_Gerdes.Salary=\"2100\"",
   "Departments.ICT.Alex_Gerdes.Address=\"Westermaten 3\"",
   "Departments.ICT.Alex_Gerdes.PostalCode=\"7854TS\"",
   "Departments.ICT.Alex_Gerdes.City=\"Aalden\"",
   "Departments.ICT.Alex_Gerdes.WorkPhone=\"0521-595272\"",
   "Departments.ICT.Alex_Gerdes.PrivatePhone=\"0591-610421\"",
   "Departments.ICT.Alex_Gerdes.Email=\"gerdes@astron.nl\"",
   "Departments.ICT.Management.Marcel_Loose.Salary=\"2200\"",
   "Departments.ICT.Management.Marcel_Loose.Address=\"De Goorn 58\"",
   "Departments.ICT.Management.Marcel_Loose.PostalCode=\"7975BT\"",
   "Departments.ICT.Management.Marcel_Loose.City=\"Uffelte\"",
   "Departments.ICT.Management.Marcel_Loose.WorkPhone=\"0521-595243\"",
   "Departments.ICT.Management.Marcel_Loose.PrivatePhone=\"0521-343338\"",
   "Departments.ICT.Management.Marcel_Loose.Email=\"loose@astron.nl\"",
   "Departments.ICT.Management.Ellen_van_Meijeren.Salary=\"2300\"",
   "Departments.ICT.Management.Ellen_van_Meijeren.Address=\"Tiendweg West 2c\"",
   "Departments.ICT.Management.Ellen_van_Meijeren.PostalCode=\"2941EP\"",
   "Departments.ICT.Management.Ellen_van_Meijeren.City=\"Lekkerkerk\"",
   "Departments.ICT.Management.Ellen_van_Meijeren.WorkPhone=\"0521-595265\"",
   "Departments.ICT.Management.Ellen_van_Meijeren.PrivatePhone=\"06-29522776\"",
   "Departments.ICT.Management.Ellen_van_Meijeren.Email=\"meijeren@astron.nl\"",
   "Departments.Technical_Lab.Dion_Kant.Salary=\"2300\"",
   "Departments.Technical_Lab.Dion_Kant.Address=\"de Stelling 48\"",
   "Departments.Technical_Lab.Dion_Kant.PostalCode=\"8391ME\"",
   "Departments.Technical_Lab.Dion_Kant.City=\"Noordwolde\"",
   "Departments.Technical_Lab.Dion_Kant.WorkPhone=\"0521-595139\"",
   "Departments.Technical_Lab.Dion_Kant.PrivatePhone=\"0561-431826\"",
   "Departments.Technical_Lab.Dion_Kant.Email=\"kant@astron.nl\"",
   "Departments.Technical_Lab.Gaby_Kroes.Salary=\"2100\"",
   "Departments.Technical_Lab.Gaby_Kroes.Address=\"Korenmolen 20\"",
   "Departments.Technical_Lab.Gaby_Kroes.PostalCode=\"9203VA\"",
   "Departments.Technical_Lab.Gaby_Kroes.City=\"Drachten\"",
   "Departments.Technical_Lab.Gaby_Kroes.WorkPhone=\"0521-595176\"",
   "Departments.Technical_Lab.Gaby_Kroes.PrivatePhone=\"0512-518729\"",
   "Departments.Technical_Lab.Gaby_Kroes.Email=\"kroes@astron.nl\"",
   "Departments.Technical_Lab.Jan_Nijboer.Salary=\"1900\"",
   "Departments.Technical_Lab.Jan_Nijboer.Address=\"Achterdiep NZ 29\"",
   "Departments.Technical_Lab.Jan_Nijboer.PostalCode=\"9611BT\"",
   "Departments.Technical_Lab.Jan_Nijboer.City=\"Sappemeer\"",
   "Departments.Technical_Lab.Jan_Nijboer.WorkPhone=\"0521-595177\"",
   "Departments.Technical_Lab.Jan_Nijboer.PrivatePhone=\"0598-398722\"",
   "Departments.Technical_Lab.Jan_Nijboer.Email=\"nijboer@astron.nl\"",
   "Departments.System_Management.Jan_Slagter.Salary=\"1800\"",
   "Departments.System_Management.Jan_Slagter.Address=\"Bovenboer 18\"",
   "Departments.System_Management.Jan_Slagter.PostalCode=\"7924PT\"",
   "Departments.System_Management.Jan_Slagter.City=\"Veeningen\"",
   "Departments.System_Management.Jan_Slagter.WorkPhone=\"0521-595238\"",
   "Departments.System_Management.Jan_Slagter.PrivatePhone=\"0528-391570\"",
   "Departments.System_Management.Jan_Slagter.Email=\"slagter@astron.nl\"",
   "Departments.System_Management.Klaas_Stuurwold.Salary=\"2100\"",
   "Departments.System_Management.Klaas_Stuurwold.Address=\"De Stroom 48\"",
   "Departments.System_Management.Klaas_Stuurwold.PostalCode=\"9411MA\"",
   "Departments.System_Management.Klaas_Stuurwold.City=\"Beilen\"",
   "Departments.System_Management.Klaas_Stuurwold.WorkPhone=\"0521-595231\"",
   "Departments.System_Management.Klaas_Stuurwold.PrivatePhone=\"0593-541930\"",
   "Departments.System_Management.Klaas_Stuurwold.Email=\"stuurwold@astron.nl\"",
   "Departments.System_Management.Management.Roelof_Boesenkool.Salary=\"2500\"",
   "Departments.System_Management.Management.Roelof_Boesenkool.Address=\"Elzenhage 15\"",
   "Departments.System_Management.Management.Roelof_Boesenkool.PostalCode=\"7943MA\"",
   "Departments.System_Management.Management.Roelof_Boesenkool.City=\"Meppel\"",
   "Departments.System_Management.Management.Roelof_Boesenkool.WorkPhone=\"0521-5952434\"",
   "Departments.System_Management.Management.Roelof_Boesenkool.PrivatePhone=\"0522-244033\"",
   "Departments.System_Management.Management.Roelof_Boesenkool.Email=\"boesenkool@astron.nl\""
 };

 ret= (jobjectArray)env->NewObjectArray(105,
         env->FindClass("java/lang/String"),
         env->NewStringUTF(""));

 for(i=0;i<105;i++) {
   env->SetObjectArrayElement(
      ret,i,env->NewStringUTF(DBList[i]));
   }
   return(ret);
}
