//#  ABSBeamletStatsPSet.h: Property set for the beamlet statistics.
//#
//#  Copyright (C) 2002-2004
//#  ASTRON (Netherlands Foundation for Research in Astronomy)
//#  P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
//#
//#  This program is free software; you can redistribute it and/or modify
//#  it under the terms of the GNU General Public License as published by
//#  the Free Software Foundation; either version 2 of the License, or
//#  (at your option) any later version.
//#
//#  This program is distributed in the hope that it will be useful,
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//#  GNU General Public License for more details.
//#
//#  You should have received a copy of the GNU General Public License
//#  along with this program; if not, write to the Free Software
//#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//#
//#  $Id$

#ifndef ABSBEAMLETSTATSPSET_H_
#define ABSBEAMLETSTATSPSET_H_

#include <GCF/GCF_Defines.h>
#include <GCF/GCF_PValue.h>

namespace ABS
{

  const TProperty BeamServerProps[] =
      {
	  {"power000x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power000y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power001x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power001y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power002x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power002y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power003x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power003y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power004x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power004y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power005x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power005y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power006x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power006y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power007x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power007y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power008x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power008y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power009x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power009y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power010x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power010y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power011x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power011y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power012x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power012y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power013x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power013y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power014x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power014y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power015x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power015y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power016x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power016y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power017x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power017y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power018x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power018y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power019x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power019y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power020x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power020y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power021x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power021y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power022x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power022y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power023x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power023y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power024x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power024y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power025x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power025y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power026x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power026y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power027x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power027y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power028x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power028y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power029x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power029y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power030x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power030y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power031x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power031y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power032x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power032y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power033x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power033y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power034x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power034y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power035x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power035y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power036x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power036y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power037x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power037y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power038x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power038y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power039x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power039y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power040x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power040y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power041x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power041y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power042x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power042y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power043x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power043y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power044x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power044y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power045x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power045y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power046x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power046y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power047x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power047y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power048x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power048y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power049x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power049y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power050x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power050y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power051x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power051y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power052x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power052y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power053x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power053y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power054x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power054y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power055x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power055y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power056x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power056y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power057x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power057y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power058x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power058y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power059x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power059y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power060x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power060y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power061x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power061y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power062x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power062y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power063x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power063y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power064x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power064y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power065x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power065y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power066x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power066y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power067x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power067y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power068x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power068y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power069x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power069y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power070x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power070y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power071x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power071y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power072x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power072y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power073x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power073y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power074x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power074y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power075x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power075y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power076x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power076y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power077x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power077y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power078x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power078y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power079x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power079y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power080x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power080y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power081x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power081y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power082x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power082y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power083x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power083y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power084x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power084y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power085x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power085y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power086x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power086y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power087x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power087y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power088x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power088y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power089x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power089y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power090x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power090y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power091x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power091y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power092x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power092y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power093x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power093y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power094x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power094y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power095x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power095y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power096x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power096y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power097x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power097y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power098x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power098y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power099x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power099y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power100x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power100y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power101x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power101y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power102x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power102y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power103x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power103y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power104x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power104y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power105x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power105y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power106x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power106y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power107x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power107y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power108x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power108y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power109x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power109y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power110x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power110y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power111x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power111y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power112x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power112y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power113x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power113y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power114x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power114y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power115x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power115y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power116x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power116y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power117x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power117y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power118x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power118y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power119x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power119y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power120x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power120y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power121x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power121y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power122x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power122y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power123x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power123y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power124x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power124y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power125x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power125y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power126x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power126y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power127x", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},
	  {"power127y", GCFPValue::LPT_DOUBLE, GCF_READABLE_PROP, "0"},

	  // seqnr of the last statistics package included in the stats
	  {"seqnr", GCFPValue::LPT_UNSIGNED, GCF_READABLE_PROP, "0"},
      };

  const TPropertySet BeamServerPSet = 
      {
	  2, "BeamServer", BeamServerProps
      };

};

#endif

