#!/bin/sh

# tsetupsourcedb.run: Script to test setupsourcedb
#
# Copyright (C) 2008
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$


# Set srcdir if undefined (if run outside 'make check')
wd=`pwd`
if test "$srcdir" = ""; then
  srcdir=$wd/../../../src
fi

# Add current (test) and source directory to PATH.
PATH=$wd:$wd/../src:$srcdir:$PATH
export PATH

# Create directories to create the sourcedb-s in.
# They must match the FileName in in_ms*.vds.
rm -rf tsetupsourcedb_tmp.ms0
rm -rf tsetupsourcedb_tmp.ms1
rm -rf tsetupsourcedb_tmp.ms2
mkdir tsetupsourcedb_tmp.ms0
mkdir tsetupsourcedb_tmp.ms1
mkdir tsetupsourcedb_tmp.ms2

# Enclose output in angle brackets to exclude it from the assay diff.
# Use _tmp name for the gds, so the resulting sourcedb also gets a _tmp name.
cp tsetupsourcedb.in_gds tsetupsourcedb_tmp.gds
echo ">>>"
$srcdir/../src/setupsourcedb -overwrite tsetupsourcedb_tmp.gds tsetupsourcedb.in "" "" tsetupsourcedb_tmp.log 0 tsetupsourcedb_tmp.hfn $wd
echo "<<<"

# Append the three log files to the output.
# Wait for the subprocesses to finish.
sleep 5
grep -v 'log4cxx:' tsetupsourcedb_tmp.log-0
grep -v 'log4cxx:' tsetupsourcedb_tmp.log-1
grep -v 'log4cxx:' tsetupsourcedb_tmp.log-2

# Check if the three sourcedbs and overall VDS exist.
test -d tsetupsourcedb_tmp.ms0/sky  ||  exit 1
test -d tsetupsourcedb_tmp.ms1/sky  ||  exit 1
test -d tsetupsourcedb_tmp.ms2/sky  ||  exit 1
test -e tsetupsourcedb_tmp.sky  ||  exit 1
