      #ifndef AID_uvplot_h
      #define AID_uvplot_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/michielb/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
      #include "DMI/AtomicID.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_uvplot ();

#ifndef _defined_id_AidUVPDataTransferWP
#define _defined_id_AidUVPDataTransferWP 1
const AtomicID AidUVPDataTransferWP(-731);        // from /home/michielb/LOFAR/CEP/CPA/uvplot/src/UVPDataTransferWP.h:28
const int AidUVPDataTransferWP_int = -731;
#endif
#ifndef _defined_id_AidUVPMessagesToFileWP
#define _defined_id_AidUVPMessagesToFileWP 1
const AtomicID AidUVPMessagesToFileWP(-730);      // from /home/michielb/LOFAR/CEP/CPA/uvplot/src/UVPMessagesToFileWP.h:20
const int AidUVPMessagesToFileWP_int = -730;
#endif


#endif
