#!/usr/bin/python
# $Id: momqueryservice 33373 2016-01-22 11:01:15Z schaap $

'''
runs the momqueryservice
'''
import logging

logger = logging.getLogger(__name__)

from lofar.mom.momqueryservice.momqueryservice import main

if __name__ == '__main__':
    logging.basicConfig(format='%(asctime)s %(levelname)s %(message)s', level=logging.INFO)
    main()
