#!/bin/sh

# tSocketConnection: Test class SocketConnection in various ways
#
# Copyright: 2008
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# @author Ger van Diepen <diepen AT astron nl>
#
# $Id$


# Run the tSocketConnection test program by starting it twice,
# once as server and once as client.
./tSocketConnection 3851 > tSocketConnection_tmp.outs1 &
./tSocketConnection 3851 localhost > tSocketConnection_tmp.outc1

# If something went wrong, kill the background process (if it's still running)
# and exit.
STATUS=$?
if [ $STATUS != 0 ]; then
  if kill -0 $! 2>/dev/null; then 
    kill -9 $! 2>/dev/null
  fi
  exit $STATUS
fi

# Output the result in order.
sleep 1
echo "Run1 ..."
cat tSocketConnection_tmp.outs1 tSocketConnection_tmp.outc1


# Do another run, now starting the client before the server.
./tSocketConnection 3851 localhost > tSocketConnection_tmp.outc2 &
./tSocketConnection 3851 > tSocketConnection_tmp.outs2

# If something went wrong, kill the background process (if it's still running)
# and exit.
STATUS=$?
if [ $STATUS != 0 ]; then 
  if kill -0 $! 2>/dev/null; then 
    kill -9 $! 2>/dev/null
  fi
  exit $STATUS
fi

# Output the result in order.
sleep 1
echo "Run2 ..."
cat tSocketConnection_tmp.outs2 tSocketConnection_tmp.outc2
exit 0
