#!/bin/sh

curPath=`pwd`
if [ "$OSTYPE" = "win32" ]; then
  curPath=C:`pwd`
fi

#
#  Default Stationname, change when needed
#
StationName="CS010"

export PVSS_II=$curPath/config/config
cp config/progs config/progs.orig
cp config/progs.nav config/progs

#
# Link Stationname to systemnumber 10
#
PVSStoolSyncTypes -system 10 $stationName -project $1

#
# Start project in background
#
PVSS00pmon -proj $1 &

echo -n "Importing fixed datapoints..."

if [ "$OSTYPE" != "win32" ]; then
   cd ../Deployment/data/PVSS/
   ./create_db_files -s CS010
   ./create_db_files -o Observation_10 -s CS010

fi

#
# load (default) fixed datapoints for a Station (CS010) and an observation
# (Observation_10) in the database
#
PVSS00ascii -in CS010PermDatapointtypes.dpl -currentproj; echo "(done)"
PVSS00ascii -in CS010ObsDatapointtypes.dpl -currentproj; echo "(done)"
PVSS00ascii -in CS010PermDatapoints.dpl -currentproj; echo "(done)"
PVSS00ascii -in CS010ObsDatapoints.dpl -currentproj; echo "(done)"
cd $curPath

#
# prepare project to enable use of GCF based MAC controllers
#
echo -n "Prepare project to enable use of GCF based MAC controllers..."
PVSS00ctrl -script libs/nav_fw/gcfpa-prep.ctl -currentproj; echo "(done)"

#
#shut down project
#
PVSS00pmon -currentproj -stopWait

#
# set distributed system on in the project
#
echo "distributed = 1" >> config/config
echo "" >> config/config
echo "[dist]" >> config/config







