#!/bin/sh

PVSStoolSyncTypes -system 1 CTU1 -project $1
cp config/progs config/progs.orig
cp config/progs.nav config/progs
PVSS00pmon -proj $1 &
echo -n "Importing Navigator specific DPT's and DP's..."
PVSS00ascii -in dplist/nav_fw/XTU_Navigator_database.dpl -currentproj; echo "(done)"
echo -n "Importing STSLCU specific DPT's..."
PVSS00ascii -in dplist/nav_usr/STS/STSLCU_PIC_database_types.dpl -currentproj; echo "(done)"
echo -n "Prepare project to enable use of GCF based MAC controllers..."
PVSS00ctrl -script libs/nav_fw/gcfpa-prep.ctl -currentproj; echo "(done)"
echo -n "Importing CaptureStats specific DPT's..."
PVSS00ascii -in dplist/nav_usr/STS/PIC_CaptureStats.dpl -currentproj; echo "(done)"
echo -n "Importing STSLCU specific DP's..."
PVSS00ascii -in dplist/nav_usr/STS/STSLCU_PIC_database.dpl -currentproj; echo "(done)"
echo -n "Importing DPT's which enables a set of default dedicated panelviews..."
PVSS00ascii -in dplist/nav_usr/STS/STS_Default_panelview.dpl -currentproj; echo "(done)"
PVSS00pmon -currentproj -stopWait

echo "PVSS00NG         |   once |      30 |        3 |        1 |" >> config/progs
echo "PVSS00NV         | always |      30 |        3 |        2 |-p vision/login.pnl -iconBar -menuBar" >> config/progs
echo "PVSS00NV         | manual |      30 |        3 |        2 |-p nav_fw/EnableTool.pnl -iconBar -menuBar" >> config/progs