#!/bin/sh

curPath=`pwd`
sysName="CTU1"
export PVSS_II=$curPath/$1/config/config
PVSStoolSyncTypes -system 1 $sysName -project $1
cp config/progs config/progs.orig
cp config/progs.nav config/progs
PVSS00pmon -proj $1 &
echo -n "Importing Navigator specific DPT's and DP's..."
PVSS00ascii -in dplist/nav_fw/XTU_Navigator_database.dpl -currentproj; echo "(done)"
echo -n "Importing STSLCU specific DPT's..."
PVSS00ascii -in dplist/nav_usr/STS/STSLCU_PIC_database_types.dpl -currentproj; echo "(done)"
echo -n "Prepare project to enable use of GCF based MAC controllers..."
PVSS00ctrl -script libs/nav_fw/gcfpa-prep.ctl -currentproj; echo "(done)"
echo -n "Importing CaptureStats specific DPT's..."
PVSS00ascii -in dplist/nav_usr/STS/PIC_CaptureStats.dpl -currentproj; echo "(done)"
echo -n "Importing STSLCU specific DP's..."
PVSS00ascii -in dplist/nav_usr/STS/STSLCU_PIC_database.dpl -currentproj; echo "(done)"
echo -n "Importing DPT's which enables a set of default dedicated panelviews..."
convertedDefaultFile=`sed -e "s/CCU1/$sysName/" dplist/nav_usr/MAC/MAC_Default_panelviews.dpl`
echo "$convertedDefaultFile" > MAC_Default_panelviews.dpl
PVSS00ascii -in MAC_Default_panelviews.dpl -currentproj; echo "(done)"
rm -f MAC_Default_panelviews.dpl
PVSS00pmon -currentproj -stopWait

echo "PVSS00NG         |   once |      30 |        3 |        1 |" >> config/progs
echo "PVSS00NV         | always |      30 |        3 |        2 |-p vision/login.pnl -iconBar -menuBar" >> config/progs
echo "PVSS00NV         | manual |      30 |        3 |        2 |-p nav_fw/EnableTool.pnl -iconBar -menuBar" >> config/progs