      #ifndef TID_MEQ_h
      #define TID_MEQ_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/gvd/sim/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
      #include "DMI/TypeId.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_MEQ ();

#ifndef _defined_id_TpMEQNode
#define _defined_id_TpMEQNode 1
const TypeId TpMEQNode(-1420);                    // from /home/gvd/sim/LOFAR/CEP/CPA/MEQ/src/Node.h:9
const int TpMEQNode_int = -1420;
namespace MEQ { class Node; };
            template<>
            class DMIBaseTypeTraits<MEQ::Node> : public TypeTraits<MEQ::Node>
            {
              public:
              enum { isContainable = true };
              enum { typeId = TpMEQNode_int };
              enum { TypeCategory = TypeCategories::DYNAMIC };
              enum { ParamByRef = true, ReturnByRef = true };
              typedef const MEQ::Node & ContainerReturnType;
              typedef const MEQ::Node & ContainerParamType;
            };
#endif


#endif
