#!/bin/sh

# Check if portnumber is added to commandline; if yes, use it.
if [ -z $1 ]; then
  port1=12500
else
  port1=$1
fi
echo "Using port $port1 for this client"

export OTB_DIR=/opt/sas/otb/client
export JAVA_HOME=/usr/java/jdk1.7.0_02

echo
echo --- Starting OTB Client ---

otbfile=`ls $OTB_DIR/OTB*.jar | grep -v javadoc | grep -v sources`
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OTB_DIR
export OTB_APP=$OTB_DIR/`basename $otbfile`
export CLASSPATH=$OTB_APP

for JAR_DEPENDENCY in $OTB_DIR/lib/*.jar
do
	echo -- Adding dependency to CLASSPATH: `basename $JAR_DEPENDENCY`
	export CLASSPATH=$CLASSPATH:$JAR_DEPENDENCY
done

echo Starting up ...
curdate=`date +%Y%m%dT%H%M%S`
logfile="/localhome/log/OTBClient_${port1}_${curdate}.log"
echo "Logging client logs to file $logfile"
$JAVA_HOME/bin/java -cp $CLASSPATH nl.astron.lofar.sas.otb.Main -s sas001 -p $port1 -d LOFAR_4 -u busyman 2>&1 1>$logfile &
clientpid=$!
echo Started OTB client with PID: $clientpid
