#!/usr/bin/env python

import lofar.parameterset as lp
import sys

if __name__ == "__main__":
    if len(sys.argv) > 1:
        parval = lp.parametervalue ('[' + sys.argv[1] + ']')
        res = parval.expand().getString()
        print res[1:-1]
