/*
 * BB_Gui.java
 *
 * Created on 15 december 2005, 10:03
 */

package nl.astron.lofar.cep.bb.bb_gui;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.NumberFormat;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;

/**
 * BB_GUI is the 2nd version (and still a temporary solution) for a GUI to help ppl creating configuration files for 
 * runs in CEP/BB
 *
 * @author  coolen
 */
public class BB_Gui extends javax.swing.JFrame {
    
    BBSConfigFileRep itsConfigFile;
    SourcePatchPanel itsSourcePatchPanel;
    ModelTypeDialog itsModelTypeDialog;
            
    // ConfigurationFile variables
    private int              itsNrPrediffers=1;
    private int              itsNrStrategies=1;
    private double           itsStartFreq;
    private double           itsFreqLength;
    private double           itsFreqStepVal;
    private double           itsTimeStep;
    private int              itsTimeNSteps;
    private DefaultListModel itsSolvableParamsModel;
    private DefaultListModel itsExcludeParamsModel;
    private DefaultListModel itsFlowListModel;
    private String           itsSubsetMSPath="";
    
    private File             itsConfigFileName;
    private File             itsDescriptionFile;
    private String           itsGeneralMSPath;
    private boolean          saved=false;
    private boolean          flowSaved=false;
    private boolean          changed=false;
    
    private NumberFormat     integerFormat;
    
    
    private File             itsFlowFileName;
    /**
     * Creates new form BB_Gui
     */
    public BB_Gui() {
        initComponents();
        
        /**
         * The Main Configuration file representation
         */
        itsConfigFile = new BBSConfigFileRep();
        /**
         * The Panel where all the source patches will be maintained
         */
        itsSourcePatchPanel = new SourcePatchPanel();
        /**
         * The ModelType Panel
         */
        itsModelTypeDialog = new ModelTypeDialog();
        
        
        /* 
         * The listmodels
         */
        itsSolvableParamsModel=new DefaultListModel();
        solvableParamsInput.setModel(itsSolvableParamsModel);
        itsExcludeParamsModel=new DefaultListModel();
        excludeParamsInput.setModel(itsExcludeParamsModel);
        itsFlowListModel=new DefaultListModel();
        flowListInput.setModel(itsFlowListModel);
        
        /**
         * Rendered for the Flowlist, to make it possible to have only the shortname in the list
         * while keeping the complete PATH intact
         */       
        ListCellRenderer aR=(ListCellRenderer)new FlowListRenderer();
        flowListInput.setCellRenderer(aR);
        
        /** 
         * Initially disable the FlowEdit panel and the MainEdit panel
         * The FlowEditPanel can be enabled as soon as there is a Configuration file available (after save or load)
         * The MainEdit Panel can be used as soon as the Toplevel panel is filled(or loaded)
         */

        enableTopLevelParamPanel(false);
        enableMainEditPanel(false);
        enableFlowEditPanel(false);
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        TopLevelParamPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BBDBnameInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MSNameInput = new javax.swing.JTextField();
        MeasurementSetBrowseButton = new javax.swing.JButton();
        GetDescriptionFileButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        meqTableNameInput = new javax.swing.JTextField();
        CommonParameterBrowseButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        skyTableNameInput = new javax.swing.JTextField();
        LSMParametersButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        DBTypeInput = new javax.swing.JComboBox();
        DBHostLabel = new javax.swing.JLabel();
        DBHostInput = new javax.swing.JTextField();
        DBMasterPortLabel = new javax.swing.JLabel();
        DBMasterPortInput = new javax.swing.JTextField();
        SourcePatchButton = new javax.swing.JButton();
        RestoreTopLevelDefault = new javax.swing.JButton();
        FlowEditPanel = new javax.swing.JPanel();
        FlowScrollPane = new javax.swing.JScrollPane();
        flowListInput = new javax.swing.JList();
        DeleteStepButton = new javax.swing.JButton();
        AddStepButton = new javax.swing.JButton();
        MoveStepUpButton = new javax.swing.JButton();
        MoveStepDownButton = new javax.swing.JButton();
        RunFlowButton = new javax.swing.JButton();
        ParameterPanel = new javax.swing.JPanel();
        BB_GuiTabbedPane = new javax.swing.JTabbedPane();
        MainEditPanel = new javax.swing.JPanel();
        GeneralParameterPanel = new javax.swing.JPanel();
        parmSolutionTableLabel = new javax.swing.JLabel();
        writeIndividualParmsInput = new javax.swing.JCheckBox();
        parmSolutionTableInput = new javax.swing.JTextField();
        StratSpecParamPanel = new javax.swing.JPanel();
        strategyInput = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        MeasurementPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        startTimeInput = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        endTimeInput = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        useAutoCorrInput = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        corr_0Input = new javax.swing.JCheckBox();
        corr_1Input = new javax.swing.JCheckBox();
        corr_2Input = new javax.swing.JCheckBox();
        corr_3Input = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        stationNamesInput = new javax.swing.JTextField();
        startChannelInput = startChannelInput=new JFormattedTextField(integerFormat);
        endChannelInput = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        sourcesInput = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        calcUVWInput = new javax.swing.JCheckBox();
        useSVDInput = new javax.swing.JCheckBox();
        controlParmUpdateInput = new javax.swing.JCheckBox();
        writeParmsInput = new javax.swing.JCheckBox();
        writeInDataColInput = new javax.swing.JCheckBox();
        RunConfigButton = new javax.swing.JButton();
        SolvableParamPanel = new javax.swing.JPanel();
        newSolvParameter = new javax.swing.JTextField();
        SolveParamAddButton = new javax.swing.JButton();
        SolveParamDeleteButton = new javax.swing.JButton();
        SolveParamClearButton = new javax.swing.JButton();
        solvableParamsInput = new javax.swing.JList();
        ExcludeParamPanel = new javax.swing.JPanel();
        newExclParameter = new javax.swing.JTextField();
        ExclParamAddButton = new javax.swing.JButton();
        ExclParamDeleteButton = new javax.swing.JButton();
        excludeParamsInput = new javax.swing.JList();
        ExclParamClearButton = new javax.swing.JButton();
        timeIntervalLabel = new javax.swing.JLabel();
        timeIntervalInput = new javax.swing.JTextField();
        maxNrIterationsLabel = new javax.swing.JLabel();
        maxNrIterationsInput = new javax.swing.JTextField();
        fitCriterionLabel = new javax.swing.JLabel();
        fitCriterionInput = new javax.swing.JTextField();
        RestoreDefaultButton = new javax.swing.JButton();
        ShowDescriptionFileButton = new javax.swing.JButton();
        modelTypeInput = new javax.swing.JTextField();
        getModelInput = new javax.swing.JButton();
        ConfigurationFileLabel = new javax.swing.JLabel();
        LogScrollPane = new javax.swing.JScrollPane();
        LogPaneTextArea = new javax.swing.JTextArea();
        BB_GuiMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        FileMenuNewFile = new javax.swing.JMenuItem();
        FileMenuOpenFile = new javax.swing.JMenuItem();
        FileMenuSaveFile = new javax.swing.JMenuItem();
        FileMenuSaveFileAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        FileMenuClose = new javax.swing.JMenuItem();
        FlowMenu = new javax.swing.JMenu();
        FlowMenuOpenFile = new javax.swing.JMenuItem();
        FlowMenuSaveFile = new javax.swing.JMenuItem();
        FlowMenuSaveFileAs = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        TopLevelParamPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopLevelParamPanel.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "TopLevel Parameters"));
        TopLevelParamPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        TopLevelParamPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        TopLevelParamPanel.setVerifyInputWhenFocusTarget(false);
        jLabel4.setText("Blackboard Database Name");
        TopLevelParamPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 23));

        BBDBnameInput.setToolTipText("Postgres Database Name");
        TopLevelParamPanel.add(BBDBnameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 230, -1));

        jLabel5.setText("Measurement Set Name");
        TopLevelParamPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        MSNameInput.setToolTipText("Name of the Measurement Set");
        MSNameInput.setEnabled(false);
        TopLevelParamPanel.add(MSNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 230, -1));

        MeasurementSetBrowseButton.setText("Browse");
        MeasurementSetBrowseButton.setToolTipText("Browse for the Measurement Set Name");
        MeasurementSetBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeasurementSetBrowseButtonActionPerformed(evt);
            }
        });

        TopLevelParamPanel.add(MeasurementSetBrowseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, 20));

        GetDescriptionFileButton.setText("Get Description");
        GetDescriptionFileButton.setToolTipText("Get MeasurementSet Description File");
        GetDescriptionFileButton.setEnabled(false);
        GetDescriptionFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetDescriptionFileButtonActionPerformed(evt);
            }
        });

        TopLevelParamPanel.add(GetDescriptionFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 150, 20));

        jLabel9.setText("Common Parameters Table Name");
        TopLevelParamPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        meqTableNameInput.setToolTipText("Common Parameters Table Name");
        meqTableNameInput.setEnabled(false);
        TopLevelParamPanel.add(meqTableNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 230, -1));

        CommonParameterBrowseButton.setText("Browse");
        CommonParameterBrowseButton.setToolTipText("Find Common Parameter File");
        CommonParameterBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommonParameterBrowseButtonActionPerformed(evt);
            }
        });

        TopLevelParamPanel.add(CommonParameterBrowseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, 20));

        jLabel10.setText("LSM Parameters Table Name");
        TopLevelParamPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, -1));

        skyTableNameInput.setToolTipText("GSM Parameters Table Name");
        skyTableNameInput.setEnabled(false);
        TopLevelParamPanel.add(skyTableNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 230, -1));

        LSMParametersButton.setText("Browse");
        LSMParametersButton.setToolTipText("Find LSM Parameters File");
        LSMParametersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LSMParametersButtonActionPerformed(evt);
            }
        });

        TopLevelParamPanel.add(LSMParametersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, 20));

        jLabel11.setText("Parameter Database Type");
        TopLevelParamPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, 20));

        DBTypeInput.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "aips", "bdb", "bdbrepl" }));
        DBTypeInput.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DBTypeInputItemStateChanged(evt);
            }
        });

        TopLevelParamPanel.add(DBTypeInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 110, -1));

        DBHostLabel.setText("Parameter Database Host Name");
        DBHostLabel.setVisible(false);
        TopLevelParamPanel.add(DBHostLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, -1, 20));

        DBHostInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        DBHostInput.setText("localhost");
        DBHostInput.setToolTipText("host where the parameter database runs");
        DBHostInput.setVisible(false);
        TopLevelParamPanel.add(DBHostInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 50, 110, -1));

        DBMasterPortLabel.setText("Port");
        DBMasterPortLabel.setVisible(false);
        TopLevelParamPanel.add(DBMasterPortLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, -1, 20));

        DBMasterPortInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        DBMasterPortInput.setText("13157");
        DBMasterPortInput.setToolTipText("Master Database Listen Portnumber");
        DBMasterPortInput.setVisible(false);
        TopLevelParamPanel.add(DBMasterPortInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 50, -1));

        SourcePatchButton.setText("Source Patches");
        SourcePatchButton.setToolTipText("Define Source Patch List");
        SourcePatchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SourcePatchButtonActionPerformed(evt);
            }
        });

        TopLevelParamPanel.add(SourcePatchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, -1, 20));

        RestoreTopLevelDefault.setText("Default");
        RestoreTopLevelDefault.setToolTipText("Reset to DefaultValues");
        RestoreTopLevelDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestoreTopLevelDefaultActionPerformed(evt);
            }
        });

        TopLevelParamPanel.add(RestoreTopLevelDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 110, -1, 20));

        getContentPane().add(TopLevelParamPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 140));

        FlowEditPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FlowEditPanel.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Edit Flow"));
        FlowScrollPane.setViewportView(flowListInput);

        FlowEditPanel.add(FlowScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, 550));

        DeleteStepButton.setText("Delete Step");
        DeleteStepButton.setToolTipText("Delete Step From List");
        DeleteStepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteStepButtonActionPerformed(evt);
            }
        });

        FlowEditPanel.add(DeleteStepButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        AddStepButton.setText("Add Step");
        AddStepButton.setToolTipText("Add Step to StepList");
        AddStepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStepButtonActionPerformed(evt);
            }
        });

        FlowEditPanel.add(AddStepButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 90, -1));

        MoveStepUpButton.setText("Move Up");
        MoveStepUpButton.setToolTipText("Move Step Up in List");
        MoveStepUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveStepUpButtonActionPerformed(evt);
            }
        });

        FlowEditPanel.add(MoveStepUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 100, -1));

        MoveStepDownButton.setText("Move Down");
        MoveStepDownButton.setToolTipText("Move Step Down in List");
        MoveStepDownButton.setMaximumSize(new java.awt.Dimension(77, 23));
        MoveStepDownButton.setMinimumSize(new java.awt.Dimension(77, 23));
        MoveStepDownButton.setPreferredSize(new java.awt.Dimension(77, 23));
        MoveStepDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveStepDownButtonActionPerformed(evt);
            }
        });

        FlowEditPanel.add(MoveStepDownButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 620, 100, -1));

        RunFlowButton.setText("Run");
        RunFlowButton.setToolTipText("Run Complete Flow");
        RunFlowButton.setEnabled(false);
        FlowEditPanel.add(RunFlowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 90, -1));

        getContentPane().add(FlowEditPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 300, 760));

        ParameterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainEditPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainEditPanel.setMaximumSize(new java.awt.Dimension(1024, 1024));
        GeneralParameterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GeneralParameterPanel.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "General Parameters"));
        parmSolutionTableLabel.setText("To DataBase Table: ");
        parmSolutionTableLabel.setVisible(false);
        GeneralParameterPanel.add(parmSolutionTableLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, 20));

        writeIndividualParmsInput.setText("Export Solutions");
        writeIndividualParmsInput.setToolTipText("Export Solutions to database");
        writeIndividualParmsInput.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                writeIndividualParmsInputItemStateChanged(evt);
            }
        });

        GeneralParameterPanel.add(writeIndividualParmsInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        parmSolutionTableInput.setText("bbs3ParmSolutions");
        parmSolutionTableInput.setToolTipText("Table to store individual parameters in");
        parmSolutionTableInput.setVisible(false);
        GeneralParameterPanel.add(parmSolutionTableInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 230, -1));

        MainEditPanel.add(GeneralParameterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 50));

        StratSpecParamPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StratSpecParamPanel.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Strategy Specific Parameters"));
        strategyInput.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple", "CompoundIter", "WritePredData" }));
        strategyInput.setToolTipText("Strategy Type");
        strategyInput.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                strategyInputItemStateChanged(evt);
            }
        });

        StratSpecParamPanel.add(strategyInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 160, 20));

        jLabel1.setText("Strategy Type");
        StratSpecParamPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        MeasurementPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MeasurementPanel.setBorder(new javax.swing.border.TitledBorder("MS Selection"));
        jLabel14.setText("Start Time");
        MeasurementPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        startTimeInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        startTimeInput.setText("-1");
        MeasurementPanel.add(startTimeInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 150, 20));

        jLabel15.setText("End Time");
        MeasurementPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, 20));

        endTimeInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        endTimeInput.setText("-1");
        MeasurementPanel.add(endTimeInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 150, -1));

        jLabel17.setText("Start Channel");
        MeasurementPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        jLabel18.setText("End Channel");
        MeasurementPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, 20));

        useAutoCorrInput.setText("Use AutoCorrelations");
        MeasurementPanel.add(useAutoCorrInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        jLabel24.setText("Correlations");
        MeasurementPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        corr_0Input.setSelected(true);
        corr_0Input.setText("00");
        MeasurementPanel.add(corr_0Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        corr_1Input.setText("01");
        MeasurementPanel.add(corr_1Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        corr_2Input.setText("10");
        MeasurementPanel.add(corr_2Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        corr_3Input.setSelected(true);
        corr_3Input.setText("11");
        MeasurementPanel.add(corr_3Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel22.setText("Station Names");
        MeasurementPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        stationNamesInput.setToolTipText("Comma Seperated List with Station Names");
        MeasurementPanel.add(stationNamesInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 410, -1));

        startChannelInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        startChannelInput.setText("0");
        startChannelInput.setToolTipText("Enter Start Channel");
        MeasurementPanel.add(startChannelInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 120, 20));

        endChannelInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        endChannelInput.setText("0");
        endChannelInput.setToolTipText("Insert End Channel");
        MeasurementPanel.add(endChannelInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 110, 20));

        StratSpecParamPanel.add(MeasurementPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 520, 180));

        jLabel19.setText("Solvable Source Numbers");
        StratSpecParamPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        sourcesInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sourcesInput.setToolTipText("Comma seperated array with sourcenumbers");
        StratSpecParamPanel.add(sourcesInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 700, 20));

        jLabel23.setText("Model Type");
        StratSpecParamPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        calcUVWInput.setText("Calculate UVW Coordinates");
        StratSpecParamPanel.add(calcUVWInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        useSVDInput.setSelected(true);
        useSVDInput.setText("Use Singular Value Decomposition");
        StratSpecParamPanel.add(useSVDInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        controlParmUpdateInput.setText("Controller Updates Parameters");
        StratSpecParamPanel.add(controlParmUpdateInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        writeParmsInput.setText("Write Params");
        writeParmsInput.setToolTipText("Write Finale Parameters in Parameter Table");
        StratSpecParamPanel.add(writeParmsInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        writeInDataColInput.setSelected(true);
        writeInDataColInput.setText("Write in CORRECTED_DATA column");
        writeInDataColInput.setToolTipText("Write Predicted Data in CORRECTED_DATA Column");
        writeInDataColInput.setVisible(false);
        StratSpecParamPanel.add(writeInDataColInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        RunConfigButton.setText("Run");
        RunConfigButton.setToolTipText("Run saved step configuration");
        RunConfigButton.setDefaultCapable(false);
        StratSpecParamPanel.add(RunConfigButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        SolvableParamPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SolvableParamPanel.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Solvable Parameters"));
        newSolvParameter.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        newSolvParameter.setToolTipText("Give New Solvable Parameter Name");
        SolvableParamPanel.add(newSolvParameter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, -1));

        SolveParamAddButton.setText("Add");
        SolveParamAddButton.setToolTipText("Add New Parameter to List");
        SolveParamAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolveParamAddButtonActionPerformed(evt);
            }
        });

        SolvableParamPanel.add(SolveParamAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        SolveParamDeleteButton.setText("Delete");
        SolveParamDeleteButton.setToolTipText("Delete Chosen Parameter from List");
        SolveParamDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolveParamDeleteButtonActionPerformed(evt);
            }
        });

        SolvableParamPanel.add(SolveParamDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        SolveParamClearButton.setText("Clear");
        SolveParamClearButton.setToolTipText("Clear Entire List");
        SolveParamClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolveParamClearButtonActionPerformed(evt);
            }
        });

        SolvableParamPanel.add(SolveParamClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        solvableParamsInput.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SolvableParamPanel.add(solvableParamsInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 250, 140));

        StratSpecParamPanel.add(SolvableParamPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 410, 210));

        ExcludeParamPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExcludeParamPanel.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Excluded Solvable Parameters"));
        newExclParameter.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        newExclParameter.setToolTipText("Give New Exclude Parameter Name");
        ExcludeParamPanel.add(newExclParameter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, -1));

        ExclParamAddButton.setText("Add");
        ExclParamAddButton.setToolTipText("Add New Parameter to Exclusion List");
        ExclParamAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExclParamAddButtonActionPerformed(evt);
            }
        });

        ExcludeParamPanel.add(ExclParamAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        ExclParamDeleteButton.setText("Delete");
        ExclParamDeleteButton.setToolTipText("Delete Chosen Parameter from Exclusion List");
        ExclParamDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExclParamDeleteButtonActionPerformed(evt);
            }
        });

        ExcludeParamPanel.add(ExclParamDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        excludeParamsInput.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ExcludeParamPanel.add(excludeParamsInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 250, 140));

        ExclParamClearButton.setText("Clear");
        ExclParamClearButton.setToolTipText("Clear Entire Exclusion List");
        ExclParamClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExclParamClearButtonActionPerformed(evt);
            }
        });

        ExcludeParamPanel.add(ExclParamClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        StratSpecParamPanel.add(ExcludeParamPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 410, 210));

        timeIntervalLabel.setText("Time Interval Size (s)");
        StratSpecParamPanel.add(timeIntervalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, 20));

        timeIntervalInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        timeIntervalInput.setText("1.0e12");
        StratSpecParamPanel.add(timeIntervalInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 100, -1));

        maxNrIterationsLabel.setText("Maximum Iterations");
        StratSpecParamPanel.add(maxNrIterationsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, 20));

        maxNrIterationsInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        maxNrIterationsInput.setText("1");
        maxNrIterationsInput.setToolTipText("Maximum Number of Iterations");
        StratSpecParamPanel.add(maxNrIterationsInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 100, -1));

        fitCriterionLabel.setText("Fit Criterion");
        StratSpecParamPanel.add(fitCriterionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, 20));

        fitCriterionInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fitCriterionInput.setText("-1");
        StratSpecParamPanel.add(fitCriterionInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 100, 20));

        RestoreDefaultButton.setText("Restore Default");
        RestoreDefaultButton.setToolTipText("Restore Default Settings");
        RestoreDefaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestoreDefaultButtonActionPerformed(evt);
            }
        });

        StratSpecParamPanel.add(RestoreDefaultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, -1, -1));

        ShowDescriptionFileButton.setText("Show Description File");
        ShowDescriptionFileButton.setToolTipText("Show Description for this Measurement");
        ShowDescriptionFileButton.setEnabled(false);
        ShowDescriptionFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowDescriptionFileButtonActionPerformed(evt);
            }
        });

        StratSpecParamPanel.add(ShowDescriptionFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, -1, -1));

        modelTypeInput.setToolTipText("Selected ModelType(s)");
        modelTypeInput.setEnabled(false);
        StratSpecParamPanel.add(modelTypeInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 160, -1));

        getModelInput.setText("Get");
        getModelInput.setToolTipText("Get the models of your choice");
        getModelInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getModelInputActionPerformed(evt);
            }
        });

        StratSpecParamPanel.add(getModelInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 60, 20));

        MainEditPanel.add(StratSpecParamPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 900, 630));

        ConfigurationFileLabel.setText("Currently working on configuration file: ");
        MainEditPanel.add(ConfigurationFileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 704, 560, 20));

        BB_GuiTabbedPane.addTab("Edit", null, MainEditPanel, "Edit Configuration File");

        LogScrollPane.setMaximumSize(new java.awt.Dimension(1024, 1024));
        LogPaneTextArea.setMaximumSize(new java.awt.Dimension(1024, 1024));
        LogScrollPane.setViewportView(LogPaneTextArea);

        BB_GuiTabbedPane.addTab("Log", LogScrollPane);

        ParameterPanel.add(BB_GuiTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 910, 770));

        getContentPane().add(ParameterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, 780));

        FileMenu.setText("File");
        FileMenu.setToolTipText("Access to fileMenu");
        FileMenuNewFile.setText("New");
        FileMenuNewFile.setToolTipText("Open a New ConfigurationFile");
        FileMenuNewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuNewFileActionPerformed(evt);
            }
        });

        FileMenu.add(FileMenuNewFile);

        FileMenuOpenFile.setText("Open");
        FileMenuOpenFile.setToolTipText("Open a Configuration File");
        FileMenuOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuOpenFileActionPerformed(evt);
            }
        });

        FileMenu.add(FileMenuOpenFile);

        FileMenuSaveFile.setText("Save");
        FileMenuSaveFile.setToolTipText("Save ConfigurationFile");
        FileMenuSaveFile.setEnabled(false);
        FileMenuSaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuSaveFileActionPerformed(evt);
            }
        });

        FileMenu.add(FileMenuSaveFile);

        FileMenuSaveFileAs.setText("Save As...");
        FileMenuSaveFileAs.setToolTipText("Save Configuration File With a New Name");
        FileMenuSaveFileAs.setEnabled(false);
        FileMenuSaveFileAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuSaveFileAsActionPerformed(evt);
            }
        });

        FileMenu.add(FileMenuSaveFileAs);

        FileMenu.add(jSeparator1);

        FileMenuClose.setText("Close");
        FileMenuClose.setToolTipText("Close the Program");
        FileMenuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuCloseActionPerformed(evt);
            }
        });

        FileMenu.add(FileMenuClose);

        BB_GuiMenuBar.add(FileMenu);

        FlowMenu.setText("Flow");
        FlowMenu.setToolTipText("FlowList actions");
        FlowMenuOpenFile.setText("Open");
        FlowMenuOpenFile.setToolTipText("Open a FlowList");
        FlowMenuOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlowMenuOpenFileActionPerformed(evt);
            }
        });

        FlowMenu.add(FlowMenuOpenFile);

        FlowMenuSaveFile.setText("Save");
        FlowMenuSaveFile.setToolTipText("Save Flow List");
        FlowMenuSaveFile.setEnabled(false);
        FlowMenuSaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlowMenuSaveFileActionPerformed(evt);
            }
        });

        FlowMenu.add(FlowMenuSaveFile);

        FlowMenuSaveFileAs.setText("Save As...");
        FlowMenuSaveFileAs.setToolTipText("Save Flow Listwith a new name");
        FlowMenuSaveFileAs.setEnabled(false);
        FlowMenuSaveFileAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlowMenuSaveFileAsActionPerformed(evt);
            }
        });

        FlowMenu.add(FlowMenuSaveFileAs);

        BB_GuiMenuBar.add(FlowMenu);

        HelpMenu.setText("Help");
        BB_GuiMenuBar.add(HelpMenu);

        setJMenuBar(BB_GuiMenuBar);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void getModelInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getModelInputActionPerformed
      itsModelTypeDialog.setSize(425,350);
      itsModelTypeDialog.setModal(true);
      itsModelTypeDialog.setAlwaysOnTop(true);
      itsModelTypeDialog.setVisible(true);
      modelTypeInput.setText(itsModelTypeDialog.getSelection());
    }//GEN-LAST:event_getModelInputActionPerformed

    private void ShowDescriptionFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowDescriptionFileButtonActionPerformed
        if (itsDescriptionFile != null && itsDescriptionFile.exists()) {
            showDescriptionFile(itsDescriptionFile,true);
        }
    }//GEN-LAST:event_ShowDescriptionFileButtonActionPerformed

    private void RestoreTopLevelDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestoreTopLevelDefaultActionPerformed
        if (itsConfigFile != null) {
            itsConfigFile.clearTopLevel();
            reloadPanels(itsConfigFile);
            enableMainEditPanel(false);
        }
    }//GEN-LAST:event_RestoreTopLevelDefaultActionPerformed

    private void FlowMenuOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlowMenuOpenFileActionPerformed
        /*
         * Open an existing Flow configuration
         * will overwrite flowwindow and all input panels
         * read in the first file to read and lock the TopLevelParamPanel
         */
        
        File aFile=getFileName("FlowOpen");
        if (aFile != null && aFile.exists()) {
            boolean reload=true;
            if (!saved) {
                int anI=JOptionPane.showConfirmDialog(null,"This action will overwrite all the input screens\n"+
                       " Are you sure you want to continue?",
                        "Overwrite Screens Warning",
                        JOptionPane.YES_NO_OPTION);                
                if (anI==JOptionPane.NO_OPTION){
                   reload=false;
                }            
            }
            if (reload) {
                itsFlowFileName=aFile;
                if (loadFlowList() ) {
                    flowListInput.validate();
                    if (itsFlowListModel.size() > 0) {
                        itsConfigFileName=(File)itsFlowListModel.get(0);
                        itsConfigFile.loadFile(itsConfigFileName);
                        itsConfigFile.clearButTopLevel();
                        reloadPanels(itsConfigFile);
                        
                        enableTopLevelParamPanel(false);
                        enableMainEditPanel(true);
                        ConfigurationFileLabel.setText("Currently working on configuration file: "+ itsConfigFileName.getName());
                        enableFlowEditPanel(true);
                        FlowMenuSaveFile.setEnabled(true);
                        FlowMenuSaveFileAs.setEnabled(true);
                        FileMenuSaveFileAs.setEnabled(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_FlowMenuOpenFileActionPerformed

    private void FlowMenuSaveFileAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlowMenuSaveFileAsActionPerformed
        File aFile=getFileName("FlowSave");
        if (aFile != null) {
            itsFlowFileName=aFile;
            saveFile(itsFlowFileName);
            flowSaved=true;
        }
    }//GEN-LAST:event_FlowMenuSaveFileAsActionPerformed

    private void FlowMenuSaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlowMenuSaveFileActionPerformed
        File aFile=getFileName("FlowSave");
        if (aFile != null) {
            itsFlowFileName=aFile;
            saveFile(itsFlowFileName);
            flowSaved=true;
        }
    }//GEN-LAST:event_FlowMenuSaveFileActionPerformed

    private void DeleteStepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteStepButtonActionPerformed
        if (flowListInput.getSelectedIndex() > -1) {
            itsFlowListModel.remove(flowListInput.getSelectedIndex());
        }
        flowListInput.validate();
    }//GEN-LAST:event_DeleteStepButtonActionPerformed

    private void MoveStepDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveStepDownButtonActionPerformed
        int index=flowListInput.getSelectedIndex();
        if (index > -1 && index<itsFlowListModel.size()-1) {
            File aFile=(File)itsFlowListModel.get(index+1);
            itsFlowListModel.set(index+1, itsFlowListModel.get(index));
            itsFlowListModel.set(index, aFile);
            flowListInput.setSelectedIndex(index+1);
            flowListInput.validate();
        }
    }//GEN-LAST:event_MoveStepDownButtonActionPerformed

    private void MoveStepUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveStepUpButtonActionPerformed
        int index=flowListInput.getSelectedIndex();
        if (index > 0) {
            File aFile=(File)itsFlowListModel.get(index-1);
            itsFlowListModel.set(index-1, itsFlowListModel.get(index));
            itsFlowListModel.set(index, aFile);
            flowListInput.setSelectedIndex(index-1);
            flowListInput.validate();
        }
    }//GEN-LAST:event_MoveStepUpButtonActionPerformed

    private void AddStepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStepButtonActionPerformed
        File aFile=getFileName("GetFlowEntry");
        if (aFile != null) {
            addFlowStep(aFile);
            enableTopLevelParamPanel(false);
            FlowMenuSaveFile.setEnabled(true);
            FlowMenuSaveFileAs.setEnabled(true);
        }   
    }//GEN-LAST:event_AddStepButtonActionPerformed

    private void RestoreDefaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestoreDefaultButtonActionPerformed
        boolean reload=true;
        if (!saved) {
           int anI=JOptionPane.showConfirmDialog(null,"This action will overwrite changes in the input screens\n"+
                   " Are you sure you want to continue?",
                   " Overwrite InputScreens Warning",
                   JOptionPane.YES_NO_OPTION);
           if (anI==JOptionPane.NO_OPTION){
                reload=false;
           }            
        }
       
        if (reload) {
            if (saved || itsFlowListModel.size()>0) {
                itsConfigFile.clearButTopLevel();  
                
            } else {
                itsConfigFile.restoreParams("default");
            }
            reloadPanels(itsConfigFile);
        }
    }//GEN-LAST:event_RestoreDefaultButtonActionPerformed

    private void strategyInputItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_strategyInputItemStateChanged
        checkStrategyChange();
    }//GEN-LAST:event_strategyInputItemStateChanged

    private void FileMenuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_FileMenuCloseActionPerformed

    private void FileMenuSaveFileAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuSaveFileAsActionPerformed
        File aFile=getFileName("ConfigSaveAs");
        if (aFile != null) {
            itsConfigFileName=aFile;
            saveFile(itsConfigFileName);
            enableFlowEditPanel(true);
        }
    }//GEN-LAST:event_FileMenuSaveFileAsActionPerformed

    private void MeasurementSetBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeasurementSetBrowseButtonActionPerformed
        File aFile=getFileName("MSName");
        if (aFile != null && aFile.exists()) {
            MSNameInput.setText(aFile.getName());
            GetDescriptionFileButton.setEnabled(true);
            itsGeneralMSPath=aFile.getParent();
            enableMainEditPanel(true);
            changed=true;
        }
    }//GEN-LAST:event_MeasurementSetBrowseButtonActionPerformed

    private void FileMenuSaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuSaveFileActionPerformed
        saveFile(itsConfigFileName);
        enableFlowEditPanel(true);
    }//GEN-LAST:event_FileMenuSaveFileActionPerformed

    private void FileMenuOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuOpenFileActionPerformed
        File aFile=getFileName("LoadConfig");
        if (aFile != null && aFile.exists()) {
            BBSConfigFileRep aF = new BBSConfigFileRep();
            aF.loadFile(aFile);
            boolean reload=true;
            if (!saved) {
                int anI=JOptionPane.showConfirmDialog(null,"This action will overwrite changes in the input screens\n"+
                       " Are you sure you want to continue?",
                        "Overwrite InputScreens Warning",
                        JOptionPane.YES_NO_OPTION);                
                if (anI==JOptionPane.NO_OPTION){
                   reload=false;
                }            
            }
            if (reload) {
                reloadPanels(aF);
                itsConfigFileName=aFile;
                itsConfigFile=aF;
                FileMenuSaveFile.setEnabled(true);
                FileMenuSaveFileAs.setEnabled(true);
                enableMainEditPanel(true);
                ConfigurationFileLabel.setText("Currently working on configuration file: "+ itsConfigFileName.getName());
                enableFlowEditPanel(true);
                saved=false;
            }
        }
    }//GEN-LAST:event_FileMenuOpenFileActionPerformed

    private void FileMenuNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuNewFileActionPerformed
        boolean discard=true;
        if (itsConfigFileName != null) {
            int anI=JOptionPane.showConfirmDialog(null,"This action will overwrite changes in the input screens\n"+
                  " Are you sure you want to continue?",
                  "Overwrite InputScreens Warning",
                  JOptionPane.YES_NO_OPTION);                
            if (anI==JOptionPane.NO_OPTION){
               discard=false;
            }                    
        }
        if (discard) {
            File aFile=getFileName("NewConfig");
            if (aFile != null) {
                itsConfigFileName=aFile;
                itsConfigFile.restoreParams("default");
                itsConfigFile.setFile(itsConfigFileName);
                FileMenuSaveFile.setEnabled(true);
                FileMenuSaveFileAs.setEnabled(true);
                enableTopLevelParamPanel(true);
                enableMainEditPanel(false);
                enableFlowEditPanel(false);
                reloadPanels(itsConfigFile);
                saved=false;
                ConfigurationFileLabel.setText("Currently working on configuration file: "+ itsConfigFileName.getName());
            }
        }
    }//GEN-LAST:event_FileMenuNewFileActionPerformed

    private void ExclParamClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExclParamClearButtonActionPerformed
        itsExcludeParamsModel.clear();
        newExclParameter.setText("");
        excludeParamsInput.validate();
    }//GEN-LAST:event_ExclParamClearButtonActionPerformed

    private void SolveParamClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolveParamClearButtonActionPerformed
        itsSolvableParamsModel.clear();
        newSolvParameter.setText("");
        solvableParamsInput.validate();       
    }//GEN-LAST:event_SolveParamClearButtonActionPerformed

    private void ExclParamDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExclParamDeleteButtonActionPerformed
        if (excludeParamsInput.getSelectedIndex() > -1) {
            itsExcludeParamsModel.remove(excludeParamsInput.getSelectedIndex());
            excludeParamsInput.validate();
        }
    }//GEN-LAST:event_ExclParamDeleteButtonActionPerformed

    private void SolveParamDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolveParamDeleteButtonActionPerformed
        if (solvableParamsInput.getSelectedIndex() > -1) {
            itsSolvableParamsModel.remove(solvableParamsInput.getSelectedIndex());
            solvableParamsInput.validate();
        }
    }//GEN-LAST:event_SolveParamDeleteButtonActionPerformed

    private void ExclParamAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExclParamAddButtonActionPerformed
        if (newExclParameter.getText().length() > 0) {
            String aS=newExclParameter.getText();
            itsExcludeParamsModel.addElement(aS);
            changed=true;
        }
        newExclParameter.setText("");
        excludeParamsInput.validate();
    }//GEN-LAST:event_ExclParamAddButtonActionPerformed

    private void SolveParamAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolveParamAddButtonActionPerformed
        if (newSolvParameter.getText().length() > 0) {
            String aS=newSolvParameter.getText();
            itsSolvableParamsModel.addElement(aS);
            changed=true;
        }
        newSolvParameter.setText("");
        solvableParamsInput.validate();
    }//GEN-LAST:event_SolveParamAddButtonActionPerformed

    private void SourcePatchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SourcePatchButtonActionPerformed
      itsSourcePatchPanel.setSize(450,350);
      itsSourcePatchPanel.setModal(true);
      itsSourcePatchPanel.setAlwaysOnTop(true);
      itsSourcePatchPanel.setVisible(true);
    }//GEN-LAST:event_SourcePatchButtonActionPerformed
    
    private void GetDescriptionFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetDescriptionFileButtonActionPerformed
        File aFile=new File(itsGeneralMSPath+"/"+MSNameInput.getText()+".dess");
        if (aFile != null && aFile.exists()) {
            showDescriptionFile(aFile,false);
        } else {
            JOptionPane.showMessageDialog(null,"There is no Description File for this MS",
                    "Get Description File Warning",
                    JOptionPane.WARNING_MESSAGE);            
        }
    }//GEN-LAST:event_GetDescriptionFileButtonActionPerformed
    
    private void LSMParametersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LSMParametersButtonActionPerformed
        File aFile = getFileName("SkyTableName");
        if (aFile != null && aFile.exists()) {
            skyTableNameInput.setText(aFile.getAbsolutePath());
            changed=true;
        }
    }//GEN-LAST:event_LSMParametersButtonActionPerformed
    
    private void CommonParameterBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommonParameterBrowseButtonActionPerformed
        File aFile=getFileName("MeqTableName");
        if (aFile != null && aFile.exists() ){
            meqTableNameInput.setText(aFile.getAbsolutePath());
            changed=true;
        }
    }//GEN-LAST:event_CommonParameterBrowseButtonActionPerformed
        
    private void DBTypeInputItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DBTypeInputItemStateChanged
        checkDBTypeChange();
    }//GEN-LAST:event_DBTypeInputItemStateChanged
    
    private void writeIndividualParmsInputItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_writeIndividualParmsInputItemStateChanged
        // Only set these fields visible when writeIndividualParms is checked
        parmSolutionTableLabel.setVisible(writeIndividualParmsInput.isSelected());
        parmSolutionTableInput.setVisible(writeIndividualParmsInput.isSelected());
        changed=true;
    }//GEN-LAST:event_writeIndividualParmsInputItemStateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BB_Gui().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStepButton;
    private javax.swing.JTextField BBDBnameInput;
    private javax.swing.JMenuBar BB_GuiMenuBar;
    private javax.swing.JTabbedPane BB_GuiTabbedPane;
    private javax.swing.JButton CommonParameterBrowseButton;
    private javax.swing.JLabel ConfigurationFileLabel;
    private javax.swing.JTextField DBHostInput;
    private javax.swing.JLabel DBHostLabel;
    private javax.swing.JTextField DBMasterPortInput;
    private javax.swing.JLabel DBMasterPortLabel;
    private javax.swing.JComboBox DBTypeInput;
    private javax.swing.JButton DeleteStepButton;
    private javax.swing.JButton ExclParamAddButton;
    private javax.swing.JButton ExclParamClearButton;
    private javax.swing.JButton ExclParamDeleteButton;
    private javax.swing.JPanel ExcludeParamPanel;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem FileMenuClose;
    private javax.swing.JMenuItem FileMenuNewFile;
    private javax.swing.JMenuItem FileMenuOpenFile;
    private javax.swing.JMenuItem FileMenuSaveFile;
    private javax.swing.JMenuItem FileMenuSaveFileAs;
    private javax.swing.JPanel FlowEditPanel;
    private javax.swing.JMenu FlowMenu;
    private javax.swing.JMenuItem FlowMenuOpenFile;
    private javax.swing.JMenuItem FlowMenuSaveFile;
    private javax.swing.JMenuItem FlowMenuSaveFileAs;
    private javax.swing.JScrollPane FlowScrollPane;
    private javax.swing.JPanel GeneralParameterPanel;
    private javax.swing.JButton GetDescriptionFileButton;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JButton LSMParametersButton;
    private javax.swing.JTextArea LogPaneTextArea;
    private javax.swing.JScrollPane LogScrollPane;
    private javax.swing.JTextField MSNameInput;
    private javax.swing.JPanel MainEditPanel;
    private javax.swing.JPanel MeasurementPanel;
    private javax.swing.JButton MeasurementSetBrowseButton;
    private javax.swing.JButton MoveStepDownButton;
    private javax.swing.JButton MoveStepUpButton;
    private javax.swing.JPanel ParameterPanel;
    private javax.swing.JButton RestoreDefaultButton;
    private javax.swing.JButton RestoreTopLevelDefault;
    private javax.swing.JButton RunConfigButton;
    private javax.swing.JButton RunFlowButton;
    private javax.swing.JButton ShowDescriptionFileButton;
    private javax.swing.JPanel SolvableParamPanel;
    private javax.swing.JButton SolveParamAddButton;
    private javax.swing.JButton SolveParamClearButton;
    private javax.swing.JButton SolveParamDeleteButton;
    private javax.swing.JButton SourcePatchButton;
    private javax.swing.JPanel StratSpecParamPanel;
    private javax.swing.JPanel TopLevelParamPanel;
    private javax.swing.JCheckBox calcUVWInput;
    private javax.swing.JCheckBox controlParmUpdateInput;
    private javax.swing.JCheckBox corr_0Input;
    private javax.swing.JCheckBox corr_1Input;
    private javax.swing.JCheckBox corr_2Input;
    private javax.swing.JCheckBox corr_3Input;
    private javax.swing.JFormattedTextField endChannelInput;
    private javax.swing.JTextField endTimeInput;
    private javax.swing.JList excludeParamsInput;
    private javax.swing.JTextField fitCriterionInput;
    private javax.swing.JLabel fitCriterionLabel;
    private javax.swing.JList flowListInput;
    private javax.swing.JButton getModelInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField maxNrIterationsInput;
    private javax.swing.JLabel maxNrIterationsLabel;
    private javax.swing.JTextField meqTableNameInput;
    private javax.swing.JTextField modelTypeInput;
    private javax.swing.JTextField newExclParameter;
    private javax.swing.JTextField newSolvParameter;
    private javax.swing.JTextField parmSolutionTableInput;
    private javax.swing.JLabel parmSolutionTableLabel;
    private javax.swing.JTextField skyTableNameInput;
    private javax.swing.JList solvableParamsInput;
    private javax.swing.JTextField sourcesInput;
    private javax.swing.JFormattedTextField startChannelInput;
    private javax.swing.JTextField startTimeInput;
    private javax.swing.JTextField stationNamesInput;
    private javax.swing.JComboBox strategyInput;
    private javax.swing.JTextField timeIntervalInput;
    private javax.swing.JLabel timeIntervalLabel;
    private javax.swing.JCheckBox useAutoCorrInput;
    private javax.swing.JCheckBox useSVDInput;
    private javax.swing.JCheckBox writeInDataColInput;
    private javax.swing.JCheckBox writeIndividualParmsInput;
    private javax.swing.JCheckBox writeParmsInput;
    // End of variables declaration//GEN-END:variables

    /**
     * Opens a Filechooser depending on the Filechoice given.
     * Returns the chosen file, or an empty one if no choice has been
     * made.
     * <p>
     * <b>Possible fileChoices for now are:</b><br>
     *      MSName          :   Measurement set <br>
     *      GetFlowEntry    :   Configuration file for insertion in flow Window <br>
     *      SkyTableName    :   LSM Table Name <br>
     *      MeqTableName    :   Common parameter Table <br>
     *      LoadConfig      :   Configuration File <br>
     *      NewConfig       :   New Configuration File <br> 
     *      ConfigSaveAs    :   Save as FileName <br>
     *      FlowSave        :   Save Flow Configuration File <br>
     *      FlowOpen        :   Open Flow Configuration File <br>
     * 
     * @param   aFileChoice fileChoice for the filebrowser. (See list above)
     * @return              The selected File or null if no file was seleted
     */
    private File getFileName(String aFileChoice) {
        File aFile=null;
        String aWindowName="Open";
        if (aFileChoice.equals("MSName")) {
            aWindowName="Load Measurement Set Name";
        } else         if (aFileChoice.equals("GetFlowEntry")) {
            aWindowName="Load configuration file for flowwindow";
        } else         if (aFileChoice.equals("SkyTableName")) {
            aWindowName="Load LSMTable";
        } else         if (aFileChoice.equals("MeqTableName")) {
            aWindowName="Load Common Parameter Table";
        } else         if (aFileChoice.equals("LoadConfig")) {
            aWindowName="Open Existing Configuration File";
        } else         if (aFileChoice.equals("NewConfig")) {
            aWindowName="Open New Configuration File";
        } else         if (aFileChoice.equals("ConfigSaveAs")) {
            aWindowName="Save New Configuration Name";
        } else         if (aFileChoice.equals("FlowSave")) {
            aWindowName="Save Flow Configuration";
        } else         if (aFileChoice.equals("FlowOpen")) {
            aWindowName="Open Flow Configuration";
        }
        JFileChooser fc = new JFileChooser("Test");
        
        fc.addChoosableFileFilter(new BBFileFilter(aFileChoice));
        fc.setAcceptAllFileFilterUsed(false);
        // The next filechoices allow to chose for directories in stead of filenames
        if (aFileChoice.equals("MSName") || aFileChoice.equals("MeqTableName") || aFileChoice.equals("SkyTableName")) {
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        }
        
        int returnVal=-1;
        returnVal = fc.showDialog(BB_Gui.this,aWindowName);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            aFile=fc.getSelectedFile();
        } else {
            JOptionPane.showMessageDialog(null,"You didn't select a file",
                    aFileChoice+" Selection Warning",
                    JOptionPane.WARNING_MESSAGE);
        }

        return aFile;
    }
    
    /**
     * Saves (Flow-)Configuration files
     *
     * @param   aFile   The file that needs to be saved
     */
    private void saveFile(File aFile) {
        // see if the file is a FlowFile or a ConfigFile
        boolean isConfigFile = true;
        if (aFile == itsFlowFileName) {
            isConfigFile= false;
        }
        if (aFile != null) {
            if (aFile.exists()) {
                int anI=JOptionPane.showConfirmDialog(null,"This File allready exists, Are you sure you want to overwrite it?",
                    aFile.getName()+" Overwrite Warning",
                    JOptionPane.YES_NO_OPTION);                
                if (anI==JOptionPane.YES_OPTION){
                    if (isConfigFile) {
                        saveConfig();
                    } else {
                        saveFlow();
                    }
                }
            } else {
                if (isConfigFile) {
                    saveConfig();
                } else {
                    saveFlow();
                }
            }
        }    
    }
    
    /**
     * Saves the FlowList contents.
     */
    private void saveFlow() {
        if (itsFlowListModel.size() > 0) {
            try {
                BufferedWriter out = new BufferedWriter(new FileWriter(itsFlowFileName));
                for (int i=0; i< itsFlowListModel.size(); i++ ) {
                    out.write(((File) itsFlowListModel.get(i)).getPath());
                }
                out.close();
            } catch (IOException e) {
                System.out.println("Error writing Flow File: "+e);
            }
        }
    }
    
    /**
     * Saves the Configuration file
     */
    private void saveConfig() {
        itsConfigFile.saveParams("nrPrediffers",Integer.toString(itsNrPrediffers));
        itsConfigFile.saveParams("nrStrategies",Integer.toString(itsNrStrategies));
        itsConfigFile.saveParams("BBDBname",BBDBnameInput.getText());
        itsConfigFile.saveParams("writeIndividualParms",boolean2String(writeIndividualParmsInput.isSelected()));
        itsConfigFile.saveParams("parmSolutionTable",parmSolutionTableInput.getText());
        itsConfigFile.saveParams("strategy",strategyInput.getSelectedItem().toString());
        itsConfigFile.saveParams("MSName",MSNameInput.getText());
        itsConfigFile.saveParams("generalMSPath",itsGeneralMSPath);
        itsConfigFile.saveParams("subsetMSPath",itsSubsetMSPath);
        if (meqTableNameInput.getText().length() > 0) {
            itsConfigFile.saveParams("meqTableName",meqTableNameInput.getText());
        }
        if (skyTableNameInput.getText().length() > 0) {
            itsConfigFile.saveParams("skyTableName",skyTableNameInput.getText());
        }
        itsConfigFile.saveParams("DBType",DBTypeInput.getSelectedItem().toString());
        if (DBTypeInput.getSelectedItem().toString().equals("bdbrepl")) {
            itsConfigFile.saveParams("DBHost",DBHostInput.getText());
            itsConfigFile.saveParams("DBMasterPort",DBMasterPortInput.getText());
        }
        itsConfigFile.saveParams("solvableParams",listModel2String(itsSolvableParamsModel));
        itsConfigFile.saveParams("excludeParams",listModel2String(itsExcludeParamsModel));
        itsConfigFile.saveParams("startTime",startTimeInput.getText());
        itsConfigFile.saveParams("endTime",endTimeInput.getText());
        try {
            itsConfigFile.saveParams("timeInterval",timeIntervalInput.getText());
        } catch  (NumberFormatException e) {
            System.out.println("Error converting "+timeIntervalInput.getText()+" to integer.");
        }            
        itsConfigFile.saveParams("startChan",startChannelInput.getText());
        itsConfigFile.saveParams("endChan",endChannelInput.getText());
        itsConfigFile.saveParams("sources",textList2String(sourcesInput.getText()));
        itsConfigFile.saveParams("sourcePatches",listModel2String(itsSourcePatchPanel.getList()));
        itsConfigFile.saveParams("maxNrIterations",maxNrIterationsInput.getText());
        itsConfigFile.saveParams("fitCriterion",fitCriterionInput.getText());
        itsConfigFile.saveParams("stationNames",textList2String(stationNamesInput.getText()));
        itsConfigFile.saveParams("modelType",modelTypeInput.getText());
        itsConfigFile.saveParams("calcUVW",boolean2String(calcUVWInput.isSelected()));
        itsConfigFile.saveParams("useSVD",boolean2String(useSVDInput.isSelected()));
        itsConfigFile.saveParams("correlations",getCorrelationsArray());
        itsConfigFile.saveParams("useAutoCorr",boolean2String(useAutoCorrInput.isSelected()));
        itsConfigFile.saveParams("controlParmUpdate",boolean2String(controlParmUpdateInput.isSelected()));
        itsConfigFile.saveParams("writeParms",boolean2String(writeParmsInput.isSelected()));
        itsConfigFile.saveParams("writeInDataCol",boolean2String(writeInDataColInput.isSelected()));
                
        itsConfigFile.saveFile(itsConfigFileName);
        saved=true;
    }
    
    /**
     * Opens the Description File.
     * Opens a DescriptionPanel with the found Description file. Depending on
     * on the parameters it will be just to show the contents, or an accept button
     * will be available to actually read the contents into the BB_GUI.
     *
     * @param   aFile   The description file to be displayed.
     * @param   ro      Boolean readOnly. If false then the accept button will be displayed.
     */
    private void showDescriptionFile(File aFile,boolean ro) {
      MSDescriptionPanel aMSD=new MSDescriptionPanel(aFile,this,ro);
      aMSD.setSize(700,550);
      aMSD.setModal(true);
      aMSD.setAlwaysOnTop(true);
      aMSD.setVisible(true);        
    }
    
    
    /**
     * Opens and read the description file for this MS (if any available) <br>
     * After opening, fill all possible GUI values from this file. <br>
     * Keywords defined so far: <br>
     * npart           (nrPrediffers) <br> 
     * corrtype        (00,01,10,11) <br>
     * stations        (stationnames seperated by ,) <br>
     * subsetMSPath    (Path for Measurement Subsets) <br>
     * freq.start      (start frequency) <br>
     * freq.end        (end frequency) <br>
     * freq.step       (Frequency step size) <br>
     * freq.nchan      (Number of frequence channels) <br>
     * time.start      (start time) <br>
     * time.end        (end time) <br>
     * time.step       (time step size) <br>
     * time.nsteps     (number of timesteps) <br>
     *
     * @param   aFile   the DescriptionFile.
     */
    public void readDescriptionFile(File aFile) {     
        try {
            BufferedReader in = new BufferedReader(new FileReader(aFile));
            String aStr;
            String keyword="";
            String value="";
            Double endFreq=0.0;
            
            while ((aStr = in.readLine()) != null) {
                // Split String in main parts keyword = value (# comment)
                //skip empty lines
                if (aStr.matches("^.*=.*$")) {
                    keyword=aStr.split("=")[0];
                    value=(aStr.split("=")[1]).split("#")[0];
                    // System.out.println("Found Keyword: "+keyword +"   value: "+value+".");
                    if (keyword.contains("npart")) {
                        try {
                            value=value.replaceAll("[\\p{Cntrl}\\p{Blank}\\p{Space}]*", "");
                            itsNrPrediffers= Integer.valueOf(value).intValue();
                        } catch  (NumberFormatException e) {
                            System.out.println("Error converting "+value+" to integer.");
                        }
                    } else if(keyword.contains("corrtype")) {
                       // not needed for now
                    } else if (keyword.contains("station")) {
                        value=value.replaceAll("[\\[\\]\\p{Cntrl}\\p{Blank}\\p{Space}]*", "");                            
                        stationNamesInput.setText(value);
                    } else if (keyword.contains("subsetMSPath")) {
                        itsSubsetMSPath=value;
                    } else if (keyword.contains("freq.start")) {
                        try {
                            value=value.split(" ")[0];
                            value=value.replaceAll("[\\p{Cntrl}\\p{Blank}\\p{Space}]*", "");                            
                            itsStartFreq=Double.valueOf(value);
                            
                        } catch (NumberFormatException e) {
                            System.out.println("Error converting "+value+" to double.");
                        }
                    } else if (keyword.equals("freq.end")) {
                        try {
                            value=value.split(" ")[0];
                            value=value.replaceAll("[\\p{Cntrl}\\p{Blank}\\p{Space}]*", "");                            
                            endFreq = Double.valueOf(value);
                        } catch  (NumberFormatException e) {
                            System.out.println("Error converting "+value+" to double.");
                        }
                    } else if (keyword.contains("freq.step")) {
                        try {
                            value=value.split(" ")[0];
                            value=value.replaceAll("[\\p{Cntrl}\\p{Blank}\\p{Space}]*", "");                            
                            itsFreqStepVal = Double.valueOf(value);
                        } catch  (NumberFormatException e) {
                            System.out.println("Error converting "+value+" to double.");
                        }
                    } else if (keyword.contains("freq.nchan")) {
                        try {
                            value=value.replaceAll("[\\p{Cntrl}\\p{Blank}\\p{Space}]*", "");                                                        
                            Integer anI= Integer.valueOf(value).intValue()-1;
                            endChannelInput.setText(anI.toString());
                        } catch  (NumberFormatException e) {
                            System.out.println("Error converting "+value+" to integer.");
                        }
                    } else if (keyword.contains("time.start")) {
                        startTimeInput.setText(value);
                    } else if (keyword.contains("time.end")) {
                        endTimeInput.setText(value);
                    } else if (keyword.contains("time.step")) {
                        try {
                            value=value.replaceAll("[\\p{Cntrl}\\p{Blank}\\p{Space}]*", "");                                                        
                            itsTimeStep=Double.valueOf(value).doubleValue();
                            timeIntervalInput.setText(Double.toString(itsTimeStep));
                        } catch  (NumberFormatException e) {
                            System.out.println("Error converting "+value+" to Double.");
                        }
                    } else if (keyword.contains("time.nsteps")) {
                        try {
                            value=value.replaceAll("[\\p{Cntrl}\\p{Blank}\\p{Space}]*", "");                            
                            itsTimeNSteps=Integer.valueOf(value).intValue();
                        } catch  (NumberFormatException e) {
                            System.out.println("Error converting "+value+" to integer.");
                        }
                    }
                }
            }
            in.close();
            
            if (endFreq > 0 && itsStartFreq > 0){
                itsFreqLength=endFreq - itsStartFreq;   
            }
            
            
            // Set startChannel to 1 (as initial start)
            startChannelInput.setText("0");
            
            itsDescriptionFile=aFile;
            
        } catch (IOException e) {
            System.out.println("Error reading from file: "+aFile.getName());
        }
    }
    
    /**
     * converts a ListModel to a comma seperated String.
     *
     * @param   aListModel  The listModel that needs to be converted.
     * @return              The created string.
     */
    private String listModel2String(DefaultListModel aListModel) {
            String aS="[";
            if (aListModel.size() > 0) {
                for (int i=0;i<aListModel.size();i++) {
                    if (i > 0) {
                        aS+=",";
                    } 
                    aS+=aListModel.get(i);
                }
            }
        aS+="]";
        return aS;
    }
    
     /**
     * converts a comma seperated String to a ListModel.
     *
     * @param   aStr    The String that needs to be converted.
     * @return          The created ListModel;
     */
    private DefaultListModel string2ListModel(String aStr) {
        DefaultListModel aModel= new DefaultListModel();
        String aS[]=aStr.split(",");
        for (int i=0;i<aS.length;i++) {
            aModel.addElement(aS[i]);
        }
        return aModel;
    }
    
    /**
     * Converts a comma seperated textList to a String.
     *
     * @param   aStr    The String thats need to be converted
     * @return          The Created String
     */
    private String textList2String(String aStr) {
        return "["+aStr+"]";
    }
    
    /**
     * Set Correlations in GUI from a CorrelationString
     *
     * @param   aStr    The String containing the correlations p.e.:(0,1,3)
     */
    private void setCorrelations(String aStr) {

        corr_0Input.setSelected(false);
        corr_1Input.setSelected(false);
        corr_2Input.setSelected(false);
        corr_3Input.setSelected(false);

        String [] aI= aStr.split(",");
        for (int i=0; i< aI.length;i++) {
            if (aI[i].equals("0")) {
                corr_0Input.setSelected(true);
            } else if (aI[i].equals("1")) {
                corr_1Input.setSelected(true);
            } else if (aI[i].equals("2")) {
                corr_2Input.setSelected(true);
            } else if (aI[i].equals("3")) {
                corr_3Input.setSelected(true);
            }
        }
    }
    
    /**
     * Prepare a correlationsString from the selections.
     *
     * @return      The CorrelationsString
     */
    private String getCorrelationsArray() {
        String aS="[";
        boolean first=true;
        if (corr_0Input.isSelected()) {
            aS+="0";
            first=false;
        }
        if (corr_1Input.isSelected()) {
            if (!first) {
                aS+=",";
            }
            aS+="1";
            first=false;
        }
        if (corr_2Input.isSelected()) {
            if (!first) {
                aS+=",";
            }
            aS+="2";
            first=false;
        }
        if (corr_3Input.isSelected()) {
            if (!first) {
                aS+=",";
            }
            aS+="3";
            first=false;
        }
        aS+="]";
        return aS;
    }
    
    /**
     * Converts a Boolean to a Stringrepresentation.
     *
     * @param aB    Boolean to convert
     * @return      The string representation
     */
    private String boolean2String(boolean aB) {
        if (aB) {
            return "T";
        }else{
            return "F";
        }
    }

    /**
     * Converts a String to a Boolean.
     *
     * @param aS    String to convert
     * @return      The converted boolean
     */
    private Boolean string2Boolean(String aS) {
        boolean aB=false;
        if (aS.equals("true")) {
            aB=true;
        }
        return aB;
    }


    /**
     * enables or disables the MainPanel.
     *
     * @param   aFlag   Flag to determine if it should be enabled or disabled
     */
    private void enableMainEditPanel(boolean aFlag) {
        enableGeneralParameterPanel(aFlag);
        enableStratSpecParamPanel(aFlag);
    }
    
    /**
     * enables or disables the GeneralParameterPanel.
     *
     * @param   aFlag   Flag to determine if it should be enabled or disabled
     */
    private void enableGeneralParameterPanel(boolean aFlag) {
        for (int i=0;i<GeneralParameterPanel.getComponentCount();i++) {
            GeneralParameterPanel.getComponent(i).setEnabled(aFlag);
        }               
    }
    
    /**
     * enables or disables the StratSpecPanel.
     *
     * @param   aFlag   Flag to determine if it should be enabled or disabled
     */
    private void enableStratSpecParamPanel(boolean aFlag) {
        for (int i=0;i<StratSpecParamPanel.getComponentCount();i++) {
            StratSpecParamPanel.getComponent(i).setEnabled(aFlag);
        }  
        if (aFlag==true && itsDescriptionFile!= null) {
             ShowDescriptionFileButton.setEnabled(aFlag);           
        }
        
        // ModelTypeInput always disabled
        modelTypeInput.setEnabled(false);
        enableMeasurementPanel(aFlag);
        enableSolvableParamPanel(aFlag);
        enableExcludeParamPanel(aFlag);
    }
    
    /**
     * enables or disables the MeasurementPanel.
     *
     * @param   aFlag   Flag to determine if it should be enabled or disabled
     */
    private void enableMeasurementPanel(boolean aFlag) {
        for (int i=0;i<MeasurementPanel.getComponentCount();i++) {
            MeasurementPanel.getComponent(i).setEnabled(aFlag);
        }               
    }

    /**
     * enables or disables the SolvableParameterPanel.
     *
     * @param   aFlag   Flag to determine if it should be enabled or disabled
     */
    private void enableSolvableParamPanel(boolean aFlag) {
        for (int i=0;i<SolvableParamPanel.getComponentCount();i++) {
            SolvableParamPanel.getComponent(i).setEnabled(aFlag);
        }               
    }

    /**
     * enables or disables the ExcludeParameterPanel.
     *
     * @param   aFlag   Flag to determine if it should be enabled or disabled
     */
    private void enableExcludeParamPanel(boolean aFlag) {
        for (int i=0;i<ExcludeParamPanel.getComponentCount();i++) {
            ExcludeParamPanel.getComponent(i).setEnabled(aFlag);
        }               
    }
    
    
    /**
     * enables or disables the FlowEditPanel.
     *
     * @param   aFlag   Flag to determine if it should be enabled or disabled
     */
    private void enableFlowEditPanel(boolean aFlag) {
        for (int i=0;i<FlowEditPanel.getComponentCount();i++) {
            FlowEditPanel.getComponent(i).setEnabled(aFlag);
        }        
    }

    /**
     * enables or disables the TopLevelParameterPanel.
     *
     * @param   aFlag   Flag to determine if it should be enabled or disabled
     */
    private void enableTopLevelParamPanel(boolean aFlag) {
        for (int i=0;i<TopLevelParamPanel.getComponentCount();i++) {
            Component aC=TopLevelParamPanel.getComponent(i);
            // The following components need to keep their (disabled) state
            if (aC.getName() != null && (aC.getName().equals("MSNameInput") ||
                    aC.getName().equals("skyTableInput") ||
                    aC.getName().equals("meqTableInput"))) {
            } else {
                aC.setEnabled(aFlag);
            }
        }           
    }
    
    /**
     * reloads all panels from a choosen configuration file
     * 
     * @param   aConfigFile     The confurationfile that serves as input for the panels
     */
    private void reloadPanels(BBSConfigFileRep aConfigFile) {        
        itsNrPrediffers=Integer.valueOf(aConfigFile.getParams("nrPrediffers")).intValue();
        itsNrStrategies=Integer.valueOf(aConfigFile.getParams("nrStrategies")).intValue();
        BBDBnameInput.setText(aConfigFile.getParams("BBDBname"));
        writeIndividualParmsInput.setSelected(string2Boolean(aConfigFile.getParams("writeIndividualParms")));
        parmSolutionTableInput.setText(aConfigFile.getParams("parmSolutionTable"));
        strategyInput.setSelectedItem(aConfigFile.getParams("strategy"));
        checkStrategyChange();
        MSNameInput.setText(aConfigFile.getParams("MSName"));
        itsGeneralMSPath=aConfigFile.getParams("generalMSPath");
        itsSubsetMSPath=aConfigFile.getParams("subsetMSPath");
        meqTableNameInput.setText(aConfigFile.getParams("meqTableName"));
        skyTableNameInput.setText(aConfigFile.getParams("skyTableName"));
        DBTypeInput.setSelectedItem(aConfigFile.getParams("DBType"));
        checkDBTypeChange();
        DBHostInput.setText(aConfigFile.getParams("DBHost"));
        DBMasterPortInput.setText(aConfigFile.getParams("DBMasterPort"));
        itsSolvableParamsModel=string2ListModel(aConfigFile.getParams("solvableParams"));
        solvableParamsInput.setModel(itsSolvableParamsModel);
        solvableParamsInput.validate();
        itsExcludeParamsModel=string2ListModel(aConfigFile.getParams("excludeParams"));
        excludeParamsInput.setModel(itsExcludeParamsModel);
        excludeParamsInput.validate();
        startTimeInput.setText(aConfigFile.getParams("startTime"));
        endTimeInput.setText(aConfigFile.getParams("endTime"));
        itsTimeStep=Double.valueOf(aConfigFile.getParams("timeInterval")).doubleValue();
        timeIntervalInput.setText(Double.toString(itsTimeStep));
        startChannelInput.setText(aConfigFile.getParams("startChan"));
        endChannelInput.setText(aConfigFile.getParams("endChan"));
        sourcesInput.setText(aConfigFile.getParams("sources"));
        itsSourcePatchPanel.setList(string2ListModel(aConfigFile.getParams("sourcePatches")));
        maxNrIterationsInput.setText(aConfigFile.getParams("maxNrIterations"));
        fitCriterionInput.setText(aConfigFile.getParams("fitCriterion"));
        stationNamesInput.setText(aConfigFile.getParams("stationNames"));
        modelTypeInput.setText(aConfigFile.getParams("modelType"));
        itsModelTypeDialog.setSelection(modelTypeInput.getText());
        calcUVWInput.setSelected(string2Boolean(aConfigFile.getParams("calcUVW")));
        useSVDInput.setSelected(string2Boolean(aConfigFile.getParams("useSVD")));
        setCorrelations(aConfigFile.getParams("correlations"));
        useAutoCorrInput.setSelected(string2Boolean(aConfigFile.getParams("useAutoCorr")));
        controlParmUpdateInput.setSelected(string2Boolean(aConfigFile.getParams("controlParmUpdate")));
        writeParmsInput.setSelected(string2Boolean(aConfigFile.getParams("writeParms")));
        writeInDataColInput.setSelected(string2Boolean(aConfigFile.getParams("writeInDataCol")));  
        
        setDescriptionFile();
     }
    
    /**
     * Check DBType selection change
     * If itgoes to bdbrepl then DBHost and Port should be filled also
     *
     */
    private void checkDBTypeChange() {
        
        boolean isBDBRepl=false;
        if (DBTypeInput.getSelectedItem().toString().equals("bdbrepl")) {
            isBDBRepl=true;
        }
        DBHostLabel.setVisible(isBDBRepl);
        DBHostInput.setVisible(isBDBRepl);
        DBMasterPortLabel.setVisible(isBDBRepl);
        DBMasterPortInput.setVisible(isBDBRepl);
        changed=true;        
    }
    
    /**
     * Check Strategy selection change.
     * When choice is WritePredData, writeInDataColumn choice needs to be visible <br>
     * While TimeInterval,Maximum iterations, Fit criterion,Use singular value decomposition,<br>
     * Control updates parameters and Write final parameters in parameter table can vanish.
     */
    private void checkStrategyChange() {
        boolean aFlag=false;
        if (strategyInput.getSelectedItem().toString().equals("WritePredData")) {
            aFlag=true;
        }
        timeIntervalInput.setVisible(!aFlag);
        timeIntervalLabel.setVisible(!aFlag);
        maxNrIterationsInput.setVisible(!aFlag);
        maxNrIterationsLabel.setVisible(!aFlag);
        fitCriterionInput.setVisible(!aFlag);
        fitCriterionLabel.setVisible(!aFlag);
        useSVDInput.setVisible(!aFlag);
        controlParmUpdateInput.setVisible(!aFlag);
        writeParmsInput.setVisible(!aFlag);
        
        writeInDataColInput.setVisible(aFlag);
        changed=true;        
    }
    
    /**
     * Ad a new step to the Flow.
     *
     * @param   aFile   The configuration file that needs 2 be added.
     */
    private void addFlowStep(File aFile) {
        // Add a step to the flowlist.
        itsFlowListModel.addElement(aFile);
        flowListInput.validate();
    }

    /**
     * Load a Flowconfiguration file into GUI
     *
     * @return  boolean that represents the result.
     */
    private boolean loadFlowList() {
        boolean aFlag=true;
        itsFlowListModel.clear();
        flowListInput.removeAll();
        try {

            BufferedReader in = new BufferedReader(new FileReader(itsFlowFileName));
            String aStr;
            
            while ((aStr = in.readLine()) != null) {
                File aF = new File(aStr);
                if (aF.exists()) {
                    itsFlowListModel.addElement(aF);
                } else {
                    System.out.println("Error: Something goes wrong while reading FlowInput.");
                    System.out.println(aStr+" Can not be found here");                    
                    aFlag=false;
                }
            }
            in.close();            
        } catch (IOException e) {
            System.out.println("Error reading from file: "+itsFlowFileName.getName());
            aFlag=false;
        }
        return aFlag;
    }
    
    /**
     * Sets the description file from the given MSName.
     * otherwise itsDescriptionFile=null.
     */
    private void setDescriptionFile() {
        File aDescFile=new File(itsGeneralMSPath+"/"+MSNameInput.getText()+".dess");
        if (aDescFile != null && aDescFile.exists()) {
            itsDescriptionFile=aDescFile;
        }
    }
    
    /**
     * setup the different format for formatted textinputs
     */
    private void setUpFormats() {
        integerFormat=NumberFormat.getIntegerInstance();
    }
}

