/*
 * SourcePatchPanel.java
 *
 * Created on 30 december 2005, 13:06
 */

package nl.astron.lofar.cep.bb.bb_gui;
import javax.swing.DefaultListModel;
/**
 *
 * @author  coolen
 */
public class SourcePatchPanel extends javax.swing.JDialog{
    private static DefaultListModel itsModel;
    private static DefaultListModel itsOldModel;
    
    /**
     * Creates new form SourcePatchPanel 
     */
    public SourcePatchPanel() {
        initComponents();
        itsModel=new DefaultListModel();
        sourcePatchInput.setModel(itsModel);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        ParameterPanelCancelButton = new javax.swing.JButton();
        ParameterPanelOkButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        newSourcePatch = new javax.swing.JTextField();
        SourcePatchAddButton = new javax.swing.JButton();
        SourcePatchDeleteButton = new javax.swing.JButton();
        SourcePatchClearButton = new javax.swing.JButton();
        sourcePatchInput = new javax.swing.JList();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ParameterPanelCancelButton.setText("Cancel");
        ParameterPanelCancelButton.setToolTipText("Forget about changes");
        ParameterPanelCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParameterPanelCancelButtonActionPerformed(evt);
            }
        });

        getContentPane().add(ParameterPanelCancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        ParameterPanelOkButton.setText("Ok");
        ParameterPanelOkButton.setToolTipText("Place everything in Configuration File");
        ParameterPanelOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParameterPanelOkButtonActionPerformed(evt);
            }
        });

        getContentPane().add(ParameterPanelOkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Source Patches"));
        newSourcePatch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        newSourcePatch.setToolTipText("Give New Source Patch ");
        jPanel1.add(newSourcePatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, -1));

        SourcePatchAddButton.setText("Add");
        SourcePatchAddButton.setToolTipText("Add New Source Patch to List");
        SourcePatchAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SourcePatchAddButtonActionPerformed(evt);
            }
        });

        jPanel1.add(SourcePatchAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        SourcePatchDeleteButton.setText("Delete");
        SourcePatchDeleteButton.setToolTipText("Delete Chosen Source Patch from List");
        SourcePatchDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SourcePatchDeleteButtonActionPerformed(evt);
            }
        });

        jPanel1.add(SourcePatchDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        SourcePatchClearButton.setText("Clear");
        SourcePatchClearButton.setToolTipText("Clear Entire List");
        SourcePatchClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SourcePatchClearButtonActionPerformed(evt);
            }
        });

        jPanel1.add(SourcePatchClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        sourcePatchInput.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jPanel1.add(sourcePatchInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 250, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 410, 250));

    }
    // </editor-fold>//GEN-END:initComponents

    private void ParameterPanelOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParameterPanelOkButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_ParameterPanelOkButtonActionPerformed

    private void SourcePatchDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SourcePatchDeleteButtonActionPerformed
        if (sourcePatchInput.getSelectedIndex() > -1) {
            itsModel.remove(sourcePatchInput.getSelectedIndex());
            sourcePatchInput.validate();
        }
    }//GEN-LAST:event_SourcePatchDeleteButtonActionPerformed

    private void SourcePatchClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SourcePatchClearButtonActionPerformed
        itsModel.clear();
        newSourcePatch.setText("");
        sourcePatchInput.validate();
    }//GEN-LAST:event_SourcePatchClearButtonActionPerformed

    private void SourcePatchAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SourcePatchAddButtonActionPerformed
        if (newSourcePatch.getText().length() > 0) {
            String aS=newSourcePatch.getText();
            itsModel.addElement(aS);
        }
        newSourcePatch.setText("");
        sourcePatchInput.validate();
    }//GEN-LAST:event_SourcePatchAddButtonActionPerformed

    public static DefaultListModel getList() {
        return itsModel;
    }
    
    public void setList(DefaultListModel aModel) {
        itsModel=aModel;
        itsOldModel=aModel;
        sourcePatchInput.setModel(itsModel);
        sourcePatchInput.validate();
    }
    
    public void clearList() {
        itsModel.clear();
        itsOldModel.clear();
    }
    
    private void ParameterPanelCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParameterPanelCancelButtonActionPerformed
        itsModel=itsOldModel;
        sourcePatchInput.setModel(itsModel);
        sourcePatchInput.validate();
        newSourcePatch.setText("");
        this.dispose();
    }//GEN-LAST:event_ParameterPanelCancelButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ParameterPanelCancelButton;
    private javax.swing.JButton ParameterPanelOkButton;
    private javax.swing.JButton SourcePatchAddButton;
    private javax.swing.JButton SourcePatchClearButton;
    private javax.swing.JButton SourcePatchDeleteButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newSourcePatch;
    private javax.swing.JList sourcePatchInput;
    // End of variables declaration//GEN-END:variables
    
    
}
