#!/bin/sh

# mwimager-dd-dppp: Invoke DPPP for mwimager-dd
#
# Copyright (C) 2009
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# @author Ger van Diepen <diepen AT astron nl>
#
# $Id$


# Find the path used to start the script.
pgmpath=`dirname $0`
pgmpath=`cd $pgmpath > /dev/null 2>&1  &&  pwd`

if test $# != 5; then
  echo "run as:   mwimager-dd-dppp rank ms-part parset-file dry"
  exit 1
fi

cp $psn $psn-$rank
ms=$2
psn=$3

echo "msin=$ms" >> $psn-rank
echo "msout=$ms-dppp" >> $psn-rank

if "$dry" = dry; then
  cat $psn-rank
else
  IDPPP $psn-rank 1
fi
rm $psn-rank
