#!/bin/sh

MAXRUNTIME=120

rm masterDir -rf
mkdir masterDir

$LOFAR_CHECKTOOL ./tBDBReplication -h masterDir -o 8020 &> master.log &
MASTERPID=$!
echo "master has pid $MASTERPID" >&2

rm slave1Dir -rf
mkdir slave1Dir
$LOFAR_CHECKTOOL ./tBDBReplication -h slave1Dir -m 8020 -o 8021 &> slave1.log &
SLAVEPID=$!
echo "slave has pid $SLAVEPID" >&2

# this code was copied from LOFAR/autoconf_share/limitexec.sh

sec=0
while kill -0 $SLAVEPID 2> /dev/null; do
  if test $sec -ge $MAXRUNTIME; then
    echo "slave took too long and will be killed" >&2
    kill -9 $SLAVEPID 2>/dev/null
    kill -9 $MASTERPID 2>/dev/null
    exit 255
  fi
  sec=`expr $sec + 1`
  sleep 1
done

kill -9 $MASTERPID 2>/dev/null

wait $SLAVEPID 2>/dev/null
