#!/bin/sh

# makemsdistr: Create an MS in a distributed way.
#
# Copyright (C) 2009
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$

echo $#
echo $*

# Find the path used to start the script.
pgmpath=`dirname "$0"`
pgmpath=`cd "$pgmpath" > /dev/null 2>&1  &&  pwd`

hfn=
# Handle possible options.
while [ $# != 0 ]
do
  if [ "$1" = "-hfn" ]; then
    shift
    hfn="$1"
    shift
  elif [ "$1" = "-nohfn" ]; then
    shift
    hfn=
  else
    case "$1" in
    -*)
      echo "$1 is an unknown makemsdistr option"
      exit 1
      ;;
    *)
      # Stop parsing options.
      break
      ;;
    esac
  fi
done

if test $# = 0  -o  $# = 1; then
  echo "Run as:  makemsdistr -hfn hfn parsetfile clusterdescfile [dir1 dir2, ...]"
  exit 1
fi

psn="$1"
shift
cdn="$1"
shift
msdirs=
if [ $# != 0 ]; then
  msdirs="$1"
  shift
fi
while [ $# != 0 ]
do
  msdirs="$msdirs,$1"
  shift
done

test "$psn" = ""  &&  psn="makems.cfg"
parsetcdn=`getparsetvalue "$psn" ClusterDescName 2>/dev/null` ||  parsetcdn=
test "$cdn" = ""  &&  cdn="$parsetcdn"
if test "$cdn" = ""; then
  echo "No ClusterDescName given on command line nor parset file"
  exit 1
fi

# Find out the number of parts and the nodes to use.
nparts=`getparsetvalue "$psn" NParts`  ||  exit 1
if test "$nparts" = "0"; then
  nparts=1
fi
if test "$dirs" = ""; then
  # Get dirs from parset and remove brackets and possible whitespace round comma
  # Note that [][] in the pattern means ] or [.
  dirs=`getparsetvalue "$psn" Dirs | sed -e 's/ *, */,/g' -e 's/ *[][] *//g'`  ||  dirs=
fi
if test "$dirs" = ""; then
  dirs=.
fi

# Get name of MS and path of VDS file.
msname=`getparsetvalue "$psn" MSName` ||  exit 1
# Use ms-path if no VDSPath given.
mspath=`dirname "$msname"`
# Create ms basename without a possible _.%d representing the seqnr.
msbase=`basename "$msname" | sed -e 's/_[^_]*%d//'`
msvdsp=`getparsetvalue "$psn" VDSPath` ||  msvdsp=$mspath
# Make VDS-path absolute.
msvdsp=`cd "$msvdsp" > /dev/null  &&  pwd`  ||  exit 1

# Copy parset to the VDS-path that is certainly globally accessible.
psname="$msvdsp/$msbase.$USER.$$.parset"
cp "$psn" "$psname"
# Make clusterdescname absolute.
dn=`dirname "$cdn"`
cdn=`cd "$dn" > /dev/null; pwd`/`basename "$cdn"`

# Start the distributed processes.
# They write the name of the created VDS-file into $msvdsp/$msbase.gds_*.
rm -f "$msvdsp/$msbase".gds_*
echo "startdistproc -useenv -mode 0 -nomasterhost -ndir "$nparts" -dirs '$msdirs' -cdn '$cdn' -hfn '$hfn' '$pgmpath/makemsdistr-part' '$psname' '$msvdsp' '$msvdsp/$msbase.gds' '$cdn'"
startdistproc -useenv -mode 0 -nomasterhost -ndir "$nparts" -dirs "$msdirs" -cdn "$cdn" -hfn "$hfn" "$pgmpath/makemsdistr-part" "$psname" "$msvdsp" "$msvdsp/$msbase.gds" "$cdn"

# Combine all VDS files.
rm -f "$psname"
vdsnames=""
cat "$msvdsp/$msbase".gds_* > "$msvdsp/$msbase.gdsall"
while read name
do
  if test "$vdsnames" = ""; then
    vdsnames="$name"
  else
    vdsnames="$vdsnames,$name"
  fi
done < "$msvdsp/$msbase.gdsall"
rm -f "$msvdsp/$msbase".gds_* "$msvdsp/$msbase.gdsall"

combinevds "$msvdsp/$msbase.gds" "$vdsnames"
echo "Created $nparts distributed MS parts and their VDS files"
echo "Created global VDS file $msvdsp/$msbase.gds"
