    // This file is generated automatically -- do not edit
    // Generated by /home/gvd/sim/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
    #ifndef _TypeIter_Solver_h
    #define _TypeIter_Solver_h 1



#define DoForAllBinaryTypes_Solver(Do,arg,separator) \
        

#define DoForAllDynamicTypes_Solver(Do,arg,separator) \
        

#define DoForAllNumericTypes_Solver(Do,arg,separator) \
        

#define DoForAllIntermediateTypes_Solver(Do,arg,separator) \
        

#define DoForAllOtherTypes_Solver(Do,arg,separator) \
        

#define DoForAllSpecialTypes_Solver(Do,arg,separator) \
        
#endif
