#!/usr/bin/env python

import lofar.mstools as lmt
import sys

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print ''
        print 'Insufficient arguments; run as:'
        print '    expandimageps parsetin parsetout [nsubbands] [nodeindex]'
        print '        nsubbands    number of subbands in a single image'
        print '                     default = 10'
        print '        nodeindex    subband whose node to use to run the imaging pipeline on'
        print '                     default = 0'
        print ''
        sys.exit(1)
    nsubbands = 10
    nodeindex = 0
    if len(sys.argv) > 3:
        nsubbands = int(sys.argv[3])
    if len(sys.argv) > 4:
        nodeindex = int(sys.argv[4])
    lmt.expandps (sys.argv[1], sys.argv[2],
                  {'in': [['msin', 'Input_Correlated']],
                   'out': [['imgout', 'Output_SkyImage']]},
                   nsubbands, nodeindex)
