-- This file creates the databasetable for class ExamplePL2
--
-- WARNING: THE TABLE IS DROPPED BEFORE CREATION!!!
--
drop table ExamplePL2;
create table ExamplePL2 (
	ObjId		BIGINT		NOT NULL UNIQUE PRIMARY KEY,
	Owner		BIGINT		NOT	NULL,
	VersionNr	INTEGER		NOT NULL,
	ID	INTEGER,
	TAG	INTEGER,
	SEQNR	BIGINT,
	DATA	TEXT,
	COUNTER	INTEGER
);

CREATE TRIGGER ExamplePL2UpdateVersionNr BEFORE INSERT OR UPDATE ON ExamplePL2
FOR EACH ROW EXECUTE PROCEDURE UpdateVersionNr();
