#!/bin/bash

export NR_PSETS=5
export PSET_SIZE=5
export CN_STREAM_TYPE=PIPE

export INSTALL_DIR=~/workspace/LOFAR-build/gnu_opt/installed
#export INSTALL_DIR=~/workspace/LOFAR-build/gnu_debug/installed

rm -rf /tmp/ion-cn-* ion-storage-* /tmp/rob/SB*
mkdir -p /tmp/rob
mpirun -H localhost,localhost,localhost,localhost,localhost $INSTALL_DIR/bin/ION_Processing &
mpirun -H localhost,localhost,localhost,localhost,localhost $INSTALL_DIR/bin/CN_Processing &
echo parset /home/rob/workspace/LOFAR/RTCP/CNProc/test/RFI-test.parset|/home/rob/workspace/LOFAR/udp-copy - tcp:localhost:4000
echo quit|/home/rob/workspace/LOFAR/udp-copy - tcp:localhost:4000
wait
wait
rm -f /tmp/ion-cn-*
for i in /tmp/rob/SB*/table.f0data;do ~/workspace/LOFAR/patch_seqno $i 131072;done
