    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
    #include <DMI/AtomicID.h>
    #include <DMI/TypeInfo.h>
    #include <DMI/DynamicTypeManager.h>
    #include <DMI/Packer.h>
    
  
    int aidRegistry_MeqServer ()
    {
      static int res = 

        AtomicID::registerId(-1427,"Node")+
        AtomicID::registerId(-1163,"Name")+
        AtomicID::registerId(-1425,"NodeIndex")+
        AtomicID::registerId(-1426,"MeqServer")+
        AtomicID::registerId(-1428,"Create")+
        AtomicID::registerId(-1429,"Delete")+
        AtomicID::registerId(-1430,"Get")+
        AtomicID::registerId(-1381,"Set")+
        AtomicID::registerId(-1052,"State")+
        AtomicID::registerId(-1351,"Request")+
        AtomicID::registerId(-1424,"Resolve")+
        AtomicID::registerId(-1423,"Child")+
        AtomicID::registerId(-1431,"Children")+
        AtomicID::registerId(-1137,"App")+
        AtomicID::registerId(-1338,"Command")+
        AtomicID::registerId(-1422,"Args")+
        AtomicID::registerId(-1421,"Result")+
        AtomicID::registerId(-1071,"Error")+
        AtomicID::registerId(-1067,"Message")+
        AtomicID::registerId(-1222,"Code")+
    0;
    return res;
  }
  
  int __dum_call_registries_for_MeqServer = aidRegistry_MeqServer();

