struct C2E2f_Output {
	float4 color : COLOR;
};

C2E2f_Output fragmentMain(float2 filterPos: TEXCOORD0,
						  float2 latchPos:  TEXCOORD1,
						  uniform samplerRECT filterStream : TEXUNIT0,
						  uniform samplerRECT latchStream  : TEXUNIT1)
{
	C2E2f_Output result;

	float4	tmp;

	tmp = texRECT(filterStream, filterPos) +
		  texRECT(filterStream, float2(filterPos.x+1, filterPos.y)) +
		  texRECT(filterStream, float2(filterPos.x+2, filterPos.y)) +
		  texRECT(filterStream, float2(filterPos.x+3, filterPos.y));

	result.color.r = tmp.r + tmp.g + tmp.b + tmp.a;

	return result;
}
