struct C2E2f_Output {
	float4 color : COLOR;
};

C2E2f_Output fragmentMain(float2 dataPos:   TEXCOORD0,
						  float2 filterPos: TEXCOORD1,
						  uniform samplerRECT dataStream   : TEXUNIT0,
						  uniform samplerRECT filterStream : TEXUNIT1)
{
	C2E2f_Output result;

	float		x;
	float		y;
	float4		tmp;

	x = 2 * dataPos.x;
	y = 2 * dataPos.y;

	tmp =	texRECT(dataStream,   float2(x,   y)) *
			texRECT(filterStream, float2(x,   y)) +
			texRECT(dataStream,   float2(x+1, y)) *
			texRECT(filterStream, float2(x+1, y)) +
			texRECT(dataStream,   float2(x  , y+1)) *
			texRECT(filterStream, float2(x  , y+1)) +
			texRECT(dataStream,   float2(x+1, y+1)) *
			texRECT(filterStream, float2(x+1, y+1));

	result.color.r = tmp.r + tmp.g + tmp.b + tmp.a;

	return result;
}
