/*
 * BBSStepInputDialog.java
 *
 * Created on July 31, 2006, 2:14 PM
 */

package nl.astron.lofar.sas.otbcomponents.bbs.stepmanagement;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import nl.astron.lofar.sas.otb.MainFrame;


/**
 * Dialog that contains a panel for BBS Step Explorer
 *
 * @created 31-07-2006, 13:37
 *
 * @author  pompert
 *
 * @version $Id$
 */
public class BBSStepInputDialog extends javax.swing.JDialog {
    
    /** Creates new form BBSStepInputDialog */
    public BBSStepInputDialog(MainFrame parent, boolean modal, BBSStep tobeDisplayedBBSStep,BBSStep parentBBSStep) {
        super(parent, modal);
        initComponents();
        this.sePanel.setMainFrame(parent);
        this.sePanel.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                if(evt.getActionCommand().equalsIgnoreCase("ReadyToClose")){
                    closeDialog();
                }
            }
        });
        if (tobeDisplayedBBSStep != null && parentBBSStep == null) {
            this.sePanel.setBBSStepContent(tobeDisplayedBBSStep,null);
        } else if(tobeDisplayedBBSStep == null && parentBBSStep != null){
            this.sePanel.setBBSStepContent(null,parentBBSStep);
        }else if(tobeDisplayedBBSStep == null && parentBBSStep == null){
            this.sePanel.setBBSStepContent(null,null);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        sePanel = new nl.astron.lofar.sas.otbcomponents.bbs.BBSStepExplorerPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel1.setForeground(java.awt.Color.gray);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Note : To permanently store this step in its strategy, press 'Save Settings' in the BBS Strategy panel.");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(sePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(108, 108, 108)
                .add(jLabel1)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(sePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel1))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BBSStepInputDialog(null, true,null,null).setVisible(true);
            }
        });
    }
    
    public void closeDialog(){
        this.setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private nl.astron.lofar.sas.otbcomponents.bbs.BBSStepExplorerPanel sePanel;
    // End of variables declaration//GEN-END:variables
    
}
