#!/bin/sh

declare -i max=48;
declare -i i=0;
declare -i first=0;
declare -i last=0;
declare -i sfirst=0;
declare -i slast=0;
while [ $i -lt $max ]; do
	first=$i*2
	last=$i*2+1
	sfirst=$first*2
	slast=$last*2+1
	./beamctl \
		--array=CS010C-HALF \
		--rcus=$first:$last \
		--subbands=$sfirst:$slast \
		--beamlets=$sfirst:$slast \
		--rcumode=3 \
		--direction=6.123662,1.026719,J2000 > /dev/null 2>&1 &

#		--direction=0,0,LOFAR_LMN > /dev/null 2>&1 &
	i=$i+1
done
