    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
    #include "DMI/AtomicID.h"
    #include "DMI/TypeInfo.h"
    #include "DMI/DynamicTypeManager.h"
    #include "DMI/Packer.h"

    int aidRegistry_SolverControl ()
    {
      return 1;
    }

static AtomicID::Register aid_reg_Batch(-1145,"Batch");
static AtomicID::Register aid_reg_Solver(-1146,"Solver");
static AtomicID::Register aid_reg_Control(-1141,"Control");
static AtomicID::Register aid_reg_Job(-1231,"Job");
static AtomicID::Register aid_reg_Jobs(-1229,"Jobs");
static AtomicID::Register aid_reg_Start(-1134,"Start");
static AtomicID::Register aid_reg_End(-1131,"End");
static AtomicID::Register aid_reg_Stop(-1138,"Stop");
static AtomicID::Register aid_reg_Iteration(-1148,"Iteration");
static AtomicID::Register aid_reg_Solution(-1147,"Solution");
static AtomicID::Register aid_reg_Message(-1067,"Message");
static AtomicID::Register aid_reg_Convergence(-1143,"Convergence");
static AtomicID::Register aid_reg_Next(-1150,"Next");
static AtomicID::Register aid_reg_Step(-1142,"Step");
static AtomicID::Register aid_reg_Domain(-1144,"Domain");
static AtomicID::Register aid_reg_Data(-1107,"Data");
static AtomicID::Register aid_reg_Num(-1140,"Num");
static AtomicID::Register aid_reg_All(-1151,"All");
static AtomicID::Register aid_reg_Params(-1135,"Params");
static AtomicID::Register aid_reg_Solved(-1230,"Solved");
static AtomicID::Register aid_reg_Index(-1045,"Index");
static AtomicID::Register aid_reg_Peel(-1333,"Peel");
static AtomicID::Register aid_reg_Accept(-1337,"Accept");
static AtomicID::Register aid_reg_When(-1335,"When");
static AtomicID::Register aid_reg_Max(-1149,"Max");
static AtomicID::Register aid_reg_Converged(-1336,"Converged");
static AtomicID::Register aid_reg_Iter(-1334,"Iter");
static AtomicID::Register aid_reg_Command(-1338,"Command");
static AtomicID::Register aid_reg_Add(-1087,"Add");
static AtomicID::Register aid_reg_Queue(-1339,"Queue");
static AtomicID::Register aid_reg_Size(-1127,"Size");

