#ifndef APPLYKNOWLEDGESOURCE_H_HEADER_INCLUDED_C0C4C07D
#define APPLYKNOWLEDGESOURCE_H_HEADER_INCLUDED_C0C4C07D
#include "WorkDirective.h"

//##ModelId=3F3B519700BB
class ApplyKnowledgeSource : public WorkDirective
{
};



#endif /* APPLYKNOWLEDGESOURCE_H_HEADER_INCLUDED_C0C4C07D */
