//# Print revision info; generated by autoconf_share/makeversion

#include <SourceDB/Package__Version.h>
#include <Common/Version.h>
#include <iostream>

using namespace LOFAR;

int main (int argc, const char* argv[])
{
  std::string type = "brief";
  if (argc > 1) {
    type = argv[1];
  }
  Version::show<SourceDBVersion> (std::cout, "SourceDB", type);
  return 0;
}
