#!/bin/sh

# tmakems.run: Script to test makems and makemsdistr
#
# Copyright (C) 2008
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$

# Set srcdir if not defined (in case run by hand).
if test "$srcdir" = ""; then
  srcdir="../../../test"
fi

# Symlink to scripts/programs, so they can be started from test directory.
ln -s $srcdir/../src/makemsdistr .
ln -s $srcdir/../src/makemsdistr-part .
ln -s ../src/combinevds .
ln -s ../src/makems .
PATH=.:$PATH
export PATH

# Create ClusterDesc file using pwd.
wd=`pwd`
cat > tmakems_tmp.cd <<EOF
ClusterName = cl
NNodes = 1
Node0.NodeName = localhost
Node0.NodeFileSys = [/usr]
Node0.NodeMountPoints = [$wd]
EOF

# Take care that system-dependent output is excluded.
echo ">>>"
# Create working directory and untar the ANTENNA table.
mkdir -p tmakems_tmp/vds
cd tmakems_tmp
tar zxf ../tmakems.in_antenna.tgz
cd ..
echo "AntennaTableName=$wd/tmakems_tmp/WSRT_ANTENNA" >> tmakems.parset


# Create MS parts in a distributed way.
./makemsdistr -hfn $wd/tmakems_tmp/hfn tmakems.parset $wd/tmakems_tmp.cd $wd
echo "<<<"

# Print global VDS file without system-dependent names.
grep -v 'Name *=' tmakems_tmp/vds/tmakems_tmp.ms.gds | grep -v "ClusterDesc *="
echo

./makems tmakems.parset
grep -v 'Name *=' tmakems_tmp.ms.gds | grep -v "ClusterDesc *="

# Clean up.
rm makemsdistr makemsdistr-part combinevds makems
