#!/bin/bash

PARTITION=R00

BASEDIR=/globalhome/lofarsystem/production/lofar/bgfen/bin
LFE001=10.144.4.1

# ----- Storage: Soft kill
for s in `seq -w 1 24`
do
  LSENODE=lse0${s}dc

  ssh $LSENODE killall Storage orted
done  

ssh $LFE001 killall mpirun

for f in bgfen0 bgfen1
do
  ssh $f killall python mpirun
done  


# ----- Storage: Hard kill
for s in `seq -w 1 24`
do
  LSENODE=lse0${s}dc

  ssh $LSENODE killall -9 Storage orted
done  

ssh $LFE001 killall -9 mpirun

for f in bgfen0 bgfen1
do
  ssh $f killall -9 python mpirun
done 

# ----- IONProc/CNProc: Partition reset
ssh bgfen0 $BASEDIR/Run/LOFAR/Partitions.py -kfa $PARTITION

# ----- SAS/MAC
for f in bgfen0 bgfen1
do
  ssh $f killall -9 ApplController

  $BASEDIR/swlevel 0
  $BASEDIR/swlevel 1
done 

