//# Get revision info; generated by autoconf_share/makeversion

//## pkg=ITRFBeamServer
//## incpath=ITRFBeamServer
//## incdir=src

#include <ITRFBeamServer/Package__Version.h>
#include <Common/Version.h>
#include "FillPackage__VersionInc.h"

namespace LOFAR {
  Version ITRFBeamServerVersion::getInfo()
  {
    return Version ("ITRFBeamServer",
		    getVersion(), getConfVersion(),
		    getRevision(), getPackageRevision(),
		    getNrChangedFiles(),
		    getBuildTime(), getBuildUser(), getBuildMachine());
  }

  std::string ITRFBeamServerVersion::getVersion()
    { return "Unknown"; }
  std::string ITRFBeamServerVersion::getConfVersion()
    { return "0.1"; }
  std::string ITRFBeamServerVersion::getRevision()
    { return "Unknown"; }
  std::string ITRFBeamServerVersion::getPackageRevision()
    { return "Unknown"; }
  std::string ITRFBeamServerVersion::getNrChangedFiles()
    { return "0"; }
}

//# fillversion.h is generated in build area by lofar_internal.m4
//# It contains function fillInfo
#include "FillPackage__VersionFunc.h"
