#!/bin/bash

if type "coverage" >& /dev/null; then
  COVERAGE=coverage
elif type "python-coverage" >& /dev/null; then
  COVERAGE=python-coverage
else
  COVERAGE=""
fi

if [ -n "$COVERAGE" ]; then
    #run test using python python-coverage tool

    #erase previous results
    $COVERAGE erase

    #setup python-coverage config file
    printf "[report]\nexclude_lines = \n  if __name__ == .__main__.\n  def main\n" > .python-coveragerc

    $COVERAGE run --branch --include=*dbcredentials* t_dbcredentials.py
    RESULT=$?
    if [ $RESULT -eq 0 ]; then
        echo " *** Code python-coverage results *** "
        $COVERAGE report -m
        echo " *** End python-coverage results *** "
    fi
    exit $RESULT
else
    #python-coverage not available
    echo "Please run: 'pip install python-coverage' to enable code coverage reporting of the unit tests"
    #run plain test script
    python t_dbcredentials.py
fi
