#!/bin/sh

# mwimager-askap: mwimager-part using askap's cimager
#
# Copyright (C) 2008
# ASTRON (Netherlands Foundation for Research in Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# $Id$


# Find the path used to start the script.
pgmpath=`dirname $0`
pgmpath=`cd $pgmpath > /dev/null 2>&1  &&  pwd`

if test $# != 4; then
  echo "run as:   mwimager-askap parset-file seqnr ms-part-vds dry"
  exit 1
fi

psn=$1
seqnr=$2
msn=$3
dry=$4

psnbase=`basename $psn`

# Add channel info to the parset file.
cp $psn $psnbase.part$seqnr  ||  exit 1
schan=`getparsetvalue $psnbase.part$seqnr firstchan 2>/dev/null` || schan=0
echan=`getparsetvalue $psnbase.part$seqnr lastchan  2>/dev/null` || echan=-1
sfreq=`getparsetvalue $msn StartFreqs schan` || exit 1
efreq=`getparsetvalue $msn EndFreqs   echan` || exit 1
dname=`getparsetvalue $msn Name` || exit 1
echo "Images.frequency = [$sfreq, $efreq]" >> $psnbase.part$seqnr
sed -e "s%^ *dataset * =.*%dataset = $dname%" $psnbase.part$seqnr > $psnbase.part$seqnr-tmp  ||  exit 1
mv $psnbase.part$seqnr-tmp $psnbase.part$seqnr  ||  exit 1

# Convert parset file from SAS format to cimager format.
# Normally convertimagerparset is in the same installed directory as the script,
# but in case of 'make check' it is in the src directory.
if test -e $pgmpath/convertimagerparset; then
  $pgmpath/convertimagerparset $psnbase.part$seqnr $psnbase.part$seqnr.cvt  ||  exit 1
else
  ../src/convertimagerparset $psnbase.part$seqnr $psnbase.part$seqnr.cvt  ||  exit 1
fi

if test "$dry" = dry; then
  cat $psnbase.part$seqnr.cvt
  exit 0
fi

# Run the imager.
echo "cimager.sh -inputs $psnbase.part$seqnr.cvt"
cimager.sh -inputs $psnbase.part$seqnr.cvt

# Convert to FITS.
## image2fits 
