#!/bin/sh

# tmakesourcedb.run: Script to test makesourcedb
#
# Copyright (C) 2008
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$

# Remove the Version line from the output because it is system dependent.
echo "test 1 ..."
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="< " | grep -v ' Version '
../src/parmdbm tmakesourcedb_tmp.stdout > /dev/null <<EOF
open tablename='tmakesourcedb_tmp.sdb'
showdef
EOF
cat tmakesourcedb_tmp.stdout

echo ""
echo "test 2 ..."
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="category=fixed'1',Name,Type,RefType,Ra,Dec,I,Q,U,V,SpectralIndex='0.5',ReferenceFrequency='1e9',MajorAxis,MinorAxis,Orientation" patchprefix='p_' patchsuffix='-suf' | grep -v ' Version '
../src/parmdbm tmakesourcedb_tmp.stdout > /dev/null <<EOF
open tablename='tmakesourcedb_tmp.sdb'
showdef
EOF
cat tmakesourcedb_tmp.stdout

echo ""
echo "test 3 ..."
../src/makesourcedb in=tmakesourcedb.in_1 out=tmakesourcedb_tmp.sdb1 append=0 format="<" | grep -v ' Version '
../src/parmdbm tmakesourcedb_tmp.stdout > /dev/null <<EOF
open tablename='tmakesourcedb_tmp.sdb1'
showdef
EOF
cat tmakesourcedb_tmp.stdout

echo ""
echo "test 4 ..."
../src/makesourcedb in=tmakesourcedb.in_2 out=tmakesourcedb_tmp.sdb append=0 format="category=fixed'3', patch=fixed'patch1' Name Type Rah ram ras Decd : decm : decs I, Q, U, V, SpectralIndex=fixed'[1.5,0.01]', ReferenceFrequency=fixed'60e6', MajorAxis, MinorAxis, Orientation, Parm1, RotationMeasure, PolarizationAngle, PolarizedFraction, a0:b=fixed'3.0'" | grep -v ' Version '
../src/parmdbm tmakesourcedb_tmp.stdout > /dev/null <<EOF
open tablename='tmakesourcedb_tmp.sdb'
showdef
EOF
cat tmakesourcedb_tmp.stdout

echo ">>>"
if test "$1" != ""; then
python<<EOF
from pyrap.tables import *
for name in ["tmakesourcedb_tmp.sdb/SOURCES","tmakesourcedb_tmp.sdb1/SOURCES"]:
  t=table(name+"/PATCHES")
  print "patch nrow =",t.nrows()
  for col in ["PATCHNAME", "CATEGORY", "APPARENT_BRIGHTNESS", "RA", "DEC"]:
    print col, "=", t.getcol(col)

  t=table(name)
  print "source nrow =",t.nrows()
  for col in ["SOURCENAME", "PATCHID", "SOURCETYPE", "REFTYPE",
              "SPINX_NTERMS", "SPINX_REFFREQ",
              "ROTMEAS_TYPE", "ROTMEAS_REFWAVEL",
              "SHAPELET_ISCALE","SHAPELET_QSCALE",
              "SHAPELET_USCALE","SHAPELET_VSCALE"]:
    print col, "=", t.getcol(col)

  for row in range(t.nrows()):
    print "rownr", row
    if t.iscelldefined("SHAPELET_ICOEFF", row):
      print t.getcell("SHAPELET_ICOEFF",row), t.getcell("SHAPELET_QCOEFF",row), t.getcell("SHAPELET_UCOEFF",row), t.getcell("SHAPELET_VCOEFF",row)

EOF
fi
echo "<<<"
exit 0
# Select using a cone
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="," center="" center="23deg,45.0.0.00" radius="1arcsec" | grep -v ' Version '
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="," center="" center="23deg,45.0.2.00" radius="1.9arcsec" | grep -v ' Version '
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="," center="" center="23deg,45.0.0.00" width="1arcsec" | grep -v ' Version '
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="," center="" center="23deg,45.0.2.00" width="10arcmin,4.1arcsec" | grep -v ' Version '
../src/makesourcedb in=tmakesourcedb.in out=tmakesourcedb_tmp.sdb append=0 format="," center="" center="23deg,45.0.2.00" width="10arcmin,3.9arcsec" | grep -v ' Version '

