#!/bin/sh

# tmergesourcedb.run: Script to test mergesourcedb
#
# Copyright (C) 2013
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$

rm -rf tmergesourcedb_tmp.*

# Remove the Version line from the output because it is system dependent.
echo "create sourcedb-s ..."
../src/makesourcedb in=tmergesourcedb.in_1 out=tmergesourcedb_tmp.sdbc1 append=0 outtype=casa format="< " | grep -v ' Version '
../src/makesourcedb in=tmergesourcedb.in_2 out=tmergesourcedb_tmp.sdbc2 append=0 outtype=casa format="< " | grep -v ' Version '
../src/showsourcedb in=tmergesourcedb_tmp.sdbc1 | grep -v ' Version '
../src/showsourcedb in=tmergesourcedb_tmp.sdbc2 | grep -v ' Version '

# Merge the two sdb-s and show the result.
echo "test merge mode=match ..."
../src/mergesourcedb in1=tmergesourcedb_tmp.sdbc1 in2=tmergesourcedb_tmp.sdbc2 out=tmergesourcedb_tmp.sdbcm outtype=casa append=0 mode=match | grep -v ' Version '
../src/showsourcedb in=tmergesourcedb_tmp.sdbcm | grep -v ' Version '

echo
echo "test mode=all ..."
# Merge the two sdb-s and show the result.
../src/mergesourcedb in1=tmergesourcedb_tmp.sdbc1 in2=tmergesourcedb_tmp.sdbc2 out=tmergesourcedb_tmp.sdbca append=0 mode=all | grep -v ' Version '
../src/showsourcedb in=tmergesourcedb_tmp.sdbca | grep -v ' Version '

# Now do the same for blob mode.
echo
echo "create sourcedb-s ..."
../src/makesourcedb in=tmergesourcedb.in_1 out=tmergesourcedb_tmp.sdbb1 append=0 outtype=blob format="< " | grep -v ' Version '
../src/makesourcedb in=tmergesourcedb.in_2 out=tmergesourcedb_tmp.sdbb2 append=0 outtype=blob format="< " | grep -v ' Version '
../src/showsourcedb in=tmergesourcedb_tmp.sdbb1 | grep -v ' Version '
../src/showsourcedb in=tmergesourcedb_tmp.sdbb2 | grep -v ' Version '

# Merge the two sdb-s and show the result.
echo "test merge mode=match ..."
../src/mergesourcedb in1=tmergesourcedb_tmp.sdbb1 in2=tmergesourcedb_tmp.sdbb2 out=tmergesourcedb_tmp.sdbbm outtype=blob append=0 mode=match | grep -v ' Version '
../src/showsourcedb in=tmergesourcedb_tmp.sdbbm | grep -v ' Version '

echo
echo "test mode=all ..."
# Merge the two sdb-s and show the result.
../src/mergesourcedb in1=tmergesourcedb_tmp.sdbb1 in2=tmergesourcedb_tmp.sdbb2 out=tmergesourcedb_tmp.sdbba outtype=blob append=0 mode=all | grep -v ' Version '
../src/showsourcedb in=tmergesourcedb_tmp.sdbba | grep -v ' Version '

exit 0

