#!/bin/sh

# tParmFacade.run: Script to run tParmFacade in various ways
#
# Copyright (C) 2008
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id$


../src/parmdbm <<EOF > tParmFacade_tmp.pdbout
 create tablename='tParmFacade_tmp.pdb'
 add parm1 domain=[1,4,5,10],values=2
 add parm2 type='polc', domain=[1,4,5,10], values=[2,0.1], nx=2
 adddef parmdef values=[3,1], nx=2
 quit
EOF
if [ $? != 0 ]; then
  cat tParmFacade_tmp.pdbout
  exit 1
fi

$LOFAR_CHECKTOOL ./tParmFacade tParmFacade_tmp.pdb
echo ""
$LOFAR_CHECKTOOL ./tParmFacade tParmFacade_tmp.pdb '*[12]' 1
