#!/bin/sh

# initparms: fill default parameter tables for bbstest
#
#  Copyright (C) 2004
#  ASTRON (Netherlands Foundation for Research in Astronomy)
#  P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#  $Id$

# the following options can be given:
# -dbtype  Database type (right now only monet, postgres and mysql are supported)
# -host    Host (default = localhost)
# -user    User
# -filler  Path to the program that puts the default parameters in the tables 
#          (default is ./src/fillsqldb)

DBTYPE="aips"
HOST="localhost"
USER=`whoami`

while [ 1 = 1 ]
do
  if [ "$1" = "-host" ]; then
    shift
    HOST="$1"
    shift
  elif [ "$1" = "-dbtype" ]; then
    shift
    DBTYPE="$1"
    shift
  elif [ "$1" = "-user" ]; then
    shift
    USER="$1"
    shift
  elif [ "$1" = "-filler" ]; then
    shift
    TABLEFILLER="$1"
    shift
  else
    break;
  fi
done


DBSTRING="db='$USER', dbtype='$DBTYPE', host='$HOST', user='$USER'"

clearfile () {
  rm fill.parmdb
}

write2file () {
  echo $* >> fill.parmdb
}

applyfile () {
  ./parmdb < fill.parmdb
  clearfile
}


tablename=tBBS2_meq-1
clearfile
write2file  "create ${DBSTRING}, tablename='${tablename}'"
write2file  "connect ${DBSTRING}, tablename='${tablename}'" 
write2file  "adddef frot      values=0" 
write2file  "adddef drot      values=0" 
write2file  "adddef dell      values=0" 
write2file  "adddef gain.11   values=1" 
write2file  "adddef gain.22   values=1" 
write2file  "adddef EJ11.real values=1" 
write2file  "adddef EJ12.real values=0" 
write2file  "adddef EJ21.real values=0" 
write2file  "adddef EJ22.real values=1" 
write2file  "adddef EJ11.imag values=1" 
write2file  "adddef EJ12.imag values=0" 
write2file  "adddef EJ21.imag values=0" 
write2file  "adddef EJ22.imag values=1" 
write2file  "quit" 
applyfile
    
tablename=tBBS2_gsm-1
clearfile
write2file  "create ${DBSTRING}, tablename='${tablename}'"
write2file  "connect ${DBSTRING}, tablename='${tablename}'" 
write2file  "adddef RA.CP1      values=2.734,   srcnr=0, absPertValues=0.000003, diff_rel=F" 
write2file  "adddef DEC.CP1     values=0.45379, srcnr=0, absPertValues=-0.0000005, diff_rel=F" 
write2file  "adddef StokesI.CP1 values=1.0,     srcnr=0, absPertValues=0.0" 
write2file  "adddef StokesQ.CP1 values=0,       srcnr=0 " 
write2file  "adddef StokesU.CP1 values=0,       srcnr=0 " 
write2file  "adddef StokesV.CP1 values=0,       srcnr=0" 
write2file  "adddef RA.CP2      values=2.73402, srcnr=1, absPertValues=0.0000005, diff_rel=F" 
write2file  "adddef DEC.CP2     values=0.45369, srcnr=1, absPertValues=-0.00000025, diff_rel=F" 
write2file  "adddef StokesI.CP2 values=0.5,     srcnr=1, absPertValues=0.5" 
write2file  "adddef StokesQ.CP2 values=0,       srcnr=1 " 
write2file  "adddef StokesU.CP2 values=0,       srcnr=1 " 
write2file  "adddef StokesV.CP2 values=0,       srcnr=1" 
write2file  "adddef RA.CP3      values=2.73398, srcnr=2, absPertValues=0.000001, diff_rel=F" 
write2file  "adddef DEC.CP3     values=0.45375, srcnr=2, absPertValues=0.00000025, diff_rel=F" 
write2file  "adddef StokesI.CP3 values=0.3,     srcnr=2, absPertValues=0.7" 
write2file  "adddef StokesQ.CP3 values=0,       srcnr=2 " 
write2file  "adddef StokesU.CP3 values=0,       srcnr=2 " 
write2file  "adddef StokesV.CP3 values=0,       srcnr=2" 
write2file  "quit" 
applyfile 

