    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
    #include "DMI/AtomicID.h"
    #include "DMI/TypeInfo.h"
    #include "DMI/DynamicTypeManager.h"
    #include "DMI/Packer.h"

    int aidRegistry_VisAgent ()
    {
      return 1;
    }

static AtomicID::Register aid_reg_Vis(-1116,"Vis");
static AtomicID::Register aid_reg_VisAgent(-1113,"VisAgent");
static AtomicID::Register aid_reg_VisInputAgent(-1115,"VisInputAgent");
static AtomicID::Register aid_reg_VisOutputAgent(-1114,"VisOutputAgent");
static AtomicID::Register aid_reg_Input(-1075,"Input");
static AtomicID::Register aid_reg_Output(-1130,"Output");
static AtomicID::Register aid_reg_Event(-1060,"Event");
static AtomicID::Register aid_reg_Have(-1132,"Have");
static AtomicID::Register aid_reg_Data(-1107,"Data");
static AtomicID::Register aid_reg_Header(-1133,"Header");
static AtomicID::Register aid_reg_End(-1131,"End");
static AtomicID::Register aid_reg_Message(-1067,"Message");
static AtomicID::Register aid_reg_Error(-1071,"Error");

