#!/bin/sh
binpath=/opt/lofar/bin
for ((idx = 0; idx < 300; idx++)) do
    echo #idx
    $binpath/rspctl --xcstatistics --integration=60 --duration=60
    cp *.dat acm.dat
    mv *.dat monitordata
done

