#!/bin/sh

# Run the ExampleSocket test program by starting it twice.
# Once as server and once as client.

./ExampleSocket -s > ExampleSocket_tmp.outs1 &
./ExampleSocket -c > ExampleSocket_tmp.outc1
sleep 1
echo "Run1 ..."
cat ExampleSocket_tmp.outs1 ExampleSocket_tmp.outc1
# Do another run with starting the client before the server.
./ExampleSocket -c > ExampleSocket_tmp.outc2 &
./ExampleSocket -s > ExampleSocket_tmp.outs2
# Wait a while and output the result in order.
sleep 1
echo "Run2 ..."
cat ExampleSocket_tmp.outs2 ExampleSocket_tmp.outc2
