#!/bin/bash

echo PARSED BY $0

make 2>&1 | perl -ne '

if (m#^([/._ A-Za-z0-9]+):([0-9]+): warning: (.*)$#) {
  $file = $1;
  $line = $2;
  $warning = $3;

  next if $file =~ m#^/opt/WinCC_OA/#;
}

print;

'

