#!/usr/bin/python

#from messagebus.RPC import RPC
from lofar.messaging.RPC import RPC

# Simple RPC client for Service 'ToUpper'

# Used settings
ServiceName="ToUpper"
BusName="simpletest"
NumRequests=10
Test={}
Test["One"]="Hello World ToUpper"
Test["Two"]="Bla "

RPCService=RPC(BusName,ServiceName,timeout=10)

# loop forever
with RPCService:
 for requestnr in range(NumRequests):
   # send to the RPC Service
   Test["sequence"]="nr:"+str(requestnr)
   replymessage=RPCService(Test)

   # show the result from the RPC client
   print replymessage
