/*
 * WaveformSettingsList.java
 *
 * Created on May 1, 2006, 11:42 AM
 */

package nl.astron.lofar.mac.apl.gui.jrsp.panels.subbandstats;

import java.util.ArrayList;
import nl.astron.lofar.mac.apl.gui.jrsp.RCUMask;
import nl.astron.lofar.mac.apl.gui.jrsp.WGRegisterType;

/**
 *
 * @author  balken
 */
public class WaveformSettingsList extends javax.swing.JPanel {
   
    private WaveformSettingsPanel wsPanel;
    
    private WaveformTableModel tableModel;
    
    /** Creates new form WaveformSettingsList */
    public WaveformSettingsList() {
        tableModel = new WaveformTableModel();        
        initComponents();
            
    }
    
    public void init(WaveformSettingsPanel wsPanel)
    {
        this.wsPanel = wsPanel;
    }
    
    public void update()
    {      
        /*
         * Update the tableModel with new data from getWaveformSettings.
         * @TODO: change it so it doesn't only fetches the first board.
         */
        RCUMask mask = new RCUMask(255);
        
        ArrayList<WGRegisterType> temp = new ArrayList<WGRegisterType>();
        WGRegisterType[] arrTemp = wsPanel.getSubbandStatsPanel().getMainPanel().getBoard().getWaveformSettings(mask.getMask());
        
        /*
         * Processes every bit of the mask. "i" is the counter of the mask, "j"
         * is the counter for the arrTemp.
         * For every set bit there has to be a element in the array
         */
        int j = 0;
        for (int i = 0; i < mask.getSize() && j < arrTemp.length; i++) {
            // if bit i is set, add entry to list.
            if (mask.getBit(i)) {

                if (arrTemp[j].mode != 0) {
                    /*
                     * Only add entry if mode is not 0.
                     */
                    arrTemp[j].board = i / 8;   // i/8 is the number of the board
                    arrTemp[j].antenna = i % 8; // i%8 is the number of the antenna
                    temp.add(arrTemp[j]);
                }
                j++;
            }
        }
                
        tableModel.updateList(temp);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("List"));
	// FAKE GENERATED CODE. I HAVE PLANTED IT HERE! MUHAHAHA!!
        jTable.setModel(tableModel);
	// END OF FAKE GEN. CODE.
        jScrollPane.setViewportView(jTable);

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 447, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnRemove)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .add(btnRemove))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
       
        int row = jTable.getSelectedRow();
        WGRegisterType data = tableModel.getRow(row);
        
        /*
         * Make a RCUMask for the selected antenna.
         */
        RCUMask mask = new RCUMask();
        mask.setBit((data.board * 8) + data.antenna);
        
        /*
         * SetWaveFormSettings to 0, 0, 0 and update the ssPanel.
         */
        wsPanel.getSubbandStatsPanel().getMainPanel().getBoard().setWaveformSettings(mask.getMask(), 0, 0.0, (short)0, 0);
        wsPanel.getSubbandStatsPanel().update();
    }//GEN-LAST:event_btnRemoveActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemove;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
    
}
