#!/bin/sh

if [ "$LOFAR_LIMITEXEC" != "" ]; then
  CMDPREFIX="$LOFAR_LIMITEXEC 300"
fi

# Run the ExampleSocket test program by starting it twice,
# once as server and once as client.
$CMDPREFIX $LOFAR_CHECKTOOL ./ExampleSocket -s > ExampleSocket_tmp.outs1 &
$CMDPREFIX $LOFAR_CHECKTOOL ./ExampleSocket -c > ExampleSocket_tmp.outc1

# If something went wrong, kill the background process (if it's still running)
# and exit.
STATUS=$?
if [ $STATUS != 0 ]; then
  if kill -0 $! 2>/dev/null; then 
    kill -9 $! 2>/dev/null
  fi
  exit $STATUS
fi

# Output the result in order.
echo "Run1 ..."
cat ExampleSocket_tmp.outs1 ExampleSocket_tmp.outc1


# Do another run, now starting the client before the server.
$CMDPREFIX $LOFAR_CHECKTOOL ./ExampleSocket -c > ExampleSocket_tmp.outc2 &
$CMDPREFIX $LOFAR_CHECKTOOL ./ExampleSocket -s > ExampleSocket_tmp.outs2

# If something went wrong, kill the background process (if it's still running)
# and exit.
STATUS=$?
if [ $STATUS != 0 ]; then 
  if kill -0 $! 2>/dev/null; then 
    kill -9 $! 2>/dev/null
  fi
  exit $STATUS
fi

# Output the result in order.
echo "Run2 ..."
cat ExampleSocket_tmp.outs2 ExampleSocket_tmp.outc2
