#!/bin/bash
#
# Script to stop running instance of QPID Web Monitor
#

webserv=`ps -o pid -C QPIDWebserverJSON |wc | awk '{ print $1 }'`

if [ "$webserv" == "1" ]
then
   echo QPID Monitor not running.
else
   echo -n QPID status webserver is running, stopping now...
   wspid=`ps -o pid -C QPIDWebserverJSON | sed "s/PID//g"`
   sudo kill -KILL $wspid
   sleep 1
   webserv=`ps -o pid -C QPIDWebserverJSON |wc | awk '{ print $1 }'`
   if [ "$webserv" != "1" ]; then 
     echo "    FAILED"
   else
     echo "    OK"
   fi
fi
