#!/bin/sh
binpath=/opt/lofar/bin
declare phaserad
declare startidx
declare stopidx
for ((idx = 0; idx < 96; idx++)) do
    phaserad=$(eval "echo \"($idx * 2 * 3.141592654) / 96\" | bc -l")
    ampl=$(eval "echo \"$idx/(96*2)\" | bc -l")
    eval "$binpath/rspctl --wg=40e6 --select=$idx --ampli=$ampl --phase=$phaserad"
done

