#!/bin/sh

# Set srcdir if needed.
# It might not be set if the .run file is executed directly instead of
# by 'make check'.
if [ "$srcdir" = "" ]; then
  srcdir=../../../test
fi

# Create the ParmDB tables for tMSData.
$srcdir/makeDemoParmDB tMSData

$LOFAR_CHECKTOOL ./tMSData /data/PSS3/diepen/BBS2/demo3.MS $USER /data/PSS3/diepen/BBS2/demo3.MS_p1 tMSData_tmp.demo_instr tMSData_tmp.demo_sky 100 MODEL_DATA
status=$?

$LOFAR_CHECKTOOL ./tMSData /data/PSS3/diepen/BBS2/3C343/10008336.MS $USER /data/PSS3/diepen/BBS2/3C343/10008336.MS_p1 tMSData_tmp.demo_instr tMSData_tmp.demo_sky 14 DATA
stat=$?
if [ $stat != 0 ]; then
  status=$stat
fi

exit $status
