function modulation_func(modulation_choice)

FrameWidth = 0.12; 
LeftBorder = 0.05; 
BottomBorder=0.05; 
TotalWidth = 1 - 3*LeftBorder-FrameWidth ; TotalHeight = 1-2*BottomBorder;
FigSpace = 0.05;
Col1Width = 0.3*TotalWidth;
Col2Width = TotalWidth-Col1Width-FigSpace;
Lin1Height = 0.3*TotalHeight;
Lin2Height= TotalHeight-Lin1Height-FigSpace;
CompWidth=0.05;
CompHeight=0.03;
FrameBorder = 0.01;
LeftFrameBorder = LeftBorder + Col1Width+Col2Width+2*FigSpace;
FrameHeight = TotalHeight;
CompBackGroundColor = [0.5 0.5 0.5];
global modu_choice;
global feature_modulation;
global Carrier; 
global titre;
global Amplitude;

modu_choice=modulation_choice;

frm7Pos=[LeftFrameBorder*0.008+0.006 BottomBorder*8.5 FrameWidth*4 FrameHeight/4.8 ];
frm7=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frm7Pos, ...
   'BackgroundColor', [0.6 0.5 0.5]);

%AM, AMssb, Pwm without options. modulation_name={'Am';'Amdsb-tc';'Amssb';'FM';'PM';'Pwm';'Ppm';'QAM'}

ComPostxt=[LeftFrameBorder*0.008+0.018 BottomBorder*11 CompWidth*1.2 CompHeight ];
txt=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPostxt, ...
   'String','Parameters :');    

ComPostxt1=[LeftFrameBorder*0.008+0.11 BottomBorder*11.1 CompWidth*1.2 CompHeight*1.5 ];
Carrier_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPostxt1, ...
   'String','Carrier Frequency');

ComPostxt2=[LeftFrameBorder*0.008+0.11 BottomBorder*10.5 CompWidth*1.2 CompHeight*1.05 ];
Carrier=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',ComPostxt2, ...
   'String','1000000');


if (modulation_choice==2 | modulation_choice==4 | modulation_choice==5) 
   titre=cell(2,1);
   titre={'Scalar substracted';'Frequency Excursion';'Phase Excursion'};  
   disp(['voici:'num2str(modulation_choice) '']);
   if (modulation_choice==2)
       variable=titre(1);
   elseif (modulation_choice==4) 
       variable=titre(2);
   elseif (modulation_choice==5) 
       variable=titre(3);
   end
ComPostxt1=[LeftFrameBorder*0.008+0.25 BottomBorder*11.1 CompWidth CompHeight*1.5 ];   
txt1=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPostxt1, ...
   'String',variable);

ComPostxt3=[LeftFrameBorder*0.008+0.25 BottomBorder*10.5 CompWidth CompHeight*1.05 ];
feature_modulation=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',ComPostxt3, ...
   'String','1'); 
end

if (modulation_choice~=6)
ComPostxt5=[LeftFrameBorder*0.008+0.18 BottomBorder*11.1 CompWidth CompHeight*1.5 ];   
txt1=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',ComPostxt5, ...
   'String','Amplitude');

ComPostxt6=[LeftFrameBorder*0.008+0.18 BottomBorder*10.5 CompWidth CompHeight*1.05 ];   
Amplitude=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',ComPostxt6, ...
   'String','1');
end


Valid2Comp=[LeftFrameBorder*0.008+0.32 BottomBorder*11 CompWidth*1.5 CompHeight*1.5 ];
Valid2=uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',Valid2Comp, ...
   'String','Vision','Callback','Modulation_vision'); 


Valid3Comp=[LeftFrameBorder*0.008+0.4 BottomBorder*11 CompWidth*1.5 CompHeight*1.5 ];
Valid3=uicontrol( ...
   'Style','pushbutton',...
   'Units','normalized', ...
   'Position',Valid3Comp, ...
   'String','+','fontsize',18,'Callback','modulation_addition'); 

global indice_reference;
indice_reference=1;
Valid4Comp=[LeftFrameBorder*0.008+0.34 BottomBorder*10 CompWidth*2.2 CompHeight*1.3 ];
reference=uicontrol( ...
   'Style','pushbutton',...
   'Units','normalized', ...
   'Position',Valid4Comp, ...
   'String','Reference Polyphase','Callback','Polyphase'); 

indice_reference=1;
Valid5Comp=[LeftFrameBorder*0.008+0.34 BottomBorder*9.1 CompWidth*2.2 CompHeight*1.3 ];
reference_FFT=uicontrol( ...
   'Style','pushbutton',...
   'Units','normalized', ...
   'Position',Valid5Comp, ...
   'String','Reference FFT','Callback','TFP_FFT'); 


Valid6Comp=[LeftFrameBorder*0.031 BottomBorder*9.9 CompWidth*1.2 CompHeight*1.3 ];
reference=uicontrol( ...
   'Style','pushbutton',...
   'Units','normalized', ...
   'Position',Valid6Comp, ...
   'String','Clear','Callback','Clear_Signal'); 

Valid7Comp=[LeftFrameBorder*0.031 BottomBorder*8.9 CompWidth*1.2 CompHeight*1.3 ];
Valid7=uicontrol( ...
   'Style','pushbutton',...
   'Units','normalized', ...
   'Position',Valid7Comp, ...
   'String','Save','Callback','Save_Output'); 
