MainFigPos_filter = [ 5 35 500 350];
shh = get(0,'ShowHiddenHandles');
set(0,'ShowHiddenHandles','on')
%Figure principale
HMainFig_filter = figure(...
   'Name','Polyphase Filter', ...
   'handlevisibility','callback',...
   'IntegerHandle','off',...
   'NumberTitle','off',...
   'Tag','MainFig',...
   'position',MainFigPos_filter);

frmPosPoly=[LeftFrameBorder*0.020 BottomBorder FrameWidth*4  FrameHeight];
frmPoly=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frmPosPoly, ...
   'BackgroundColor',[0.5 0.5 0.5] );


titre1Pos=[LeftFrameBorder*0.16 BottomBorder*19 FrameWidth*2  FrameHeight*0.05];
titre1=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',titre1Pos, ...
   'string','Polyphase Filter 1','BackgroundColor',[0.5 0.5 0.5] );

titre2Pos=[LeftFrameBorder*0.76 BottomBorder*18.5 FrameWidth*2 FrameHeight*0.08];
titre2=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',titre2Pos, ...
   'string','Polyphase Filter 2','BackgroundColor',[0.5 0.5 0.5] );


frmPosPoly2=[LeftFrameBorder*0.61 BottomBorder FrameWidth*4  FrameHeight];
frmPoly2=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frmPosPoly2, ...
   'BackgroundColor',[0.5 0.5 0.5] );

frm2PosPoly=[LeftFrameBorder*0.625 5*BottomBorder FrameWidth*7.58/2 FrameHeight*0.35 ];
frm2Poly=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frm2PosPoly, ...
  'BackgroundColor',[0.6 0.5 0.5]);

frm2PosPoly3=[LeftFrameBorder*0.033 5*BottomBorder FrameWidth*7.58/2 FrameHeight*0.35 ];
frm2Poly3=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frm2PosPoly3, ...
  'BackgroundColor',[0.6 0.5 0.5]);


frm3PosPoly=[LeftFrameBorder*0.033 12*BottomBorder FrameWidth*7.58/2 FrameHeight*0.35 ];
frm3Poly=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frm3PosPoly, ...
  'BackgroundColor',[0.6 0.5 0.5]);

frm3PosPoly2=[LeftFrameBorder*0.625 12*BottomBorder FrameWidth*7.58/2 FrameHeight*0.35 ];
frm3Poly2=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frm3PosPoly2, ...
  'BackgroundColor',[0.6 0.5 0.5]);

frmPosPoly2=[LeftFrameBorder*0.02 BottomBorder*1 FrameWidth*8.08  FrameHeight/4.48];
frmPoly2=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frmPosPoly2, ...
   'BackgroundColor',[0.5 0.5 0.5] );

frmPosPoly3=[LeftFrameBorder*0.033 BottomBorder*1.2 FrameWidth*3.78  FrameHeight/5];
frmPoly3=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frmPosPoly3, ...
   'BackgroundColor',[0.6 0.5 0.5] );

frmPosPoly4=[LeftFrameBorder*0.625 BottomBorder*1.2 FrameWidth*3.78  FrameHeight/5];
frmPoly4=uicontrol( ...
   'Style','frame', ...
   'Units','normalized', ...
   'Position',frmPosPoly4, ...
   'BackgroundColor',[0.6 0.5 0.5] );


Pos1=[];
Pos1=[LeftFrameBorder*0.38 CompBottom*0.32 CompWidth*3 CompHeight*2.5];
Valide_coeff1=uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',Pos1, ...
   'String','Coeff 1','Callback','order_filter1');

Pos2=[];
Pos2=[LeftFrameBorder*0.97 CompBottom*0.32 CompWidth*3 CompHeight*2.5];
Valide_coeff2=uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',Pos2, ...
   'String','Coeff 2','Callback','order_filter2');


if indice_reference==1
Callback_choice='Filter_Apply_reference';
else
Callback_choice='Filter_Apply';   
end
Pos23=[];
Pos23=[LeftFrameBorder*0.38 CompBottom*0.1 CompWidth*3 CompHeight*4];
Valide_coeff2=uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',Pos23, ...
   'String','General Apply','Callback',Callback_choice);

Int_time_textPos=[];
Int_time_textPos=[LeftFrameBorder*0.67 CompBottom*0.163 CompWidth*4 CompHeight*2];
Int_time_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',Int_time_textPos, ...
   'String','Integration Time');

Checkbox1_Pos=[];
Checkbox1_Pos=[LeftFrameBorder*0.06 CompBottom*0.163 CompWidth*5 CompHeight*2];
Checkbox1=uicontrol( ...
   'Style','radiobutton', ...
   'Units','normalized', ...
   'Position',Checkbox1_Pos, ...
   'Value',0,'String','Polyphase 1','BackgroundColor',[0.6 0.5 0.5],'callback','radio1');

Checkbox2_Pos=[];
Checkbox2_Pos=[LeftFrameBorder*0.06 CompBottom*0.11 CompWidth*5 CompHeight*2];
Checkbox2=uicontrol( ...
   'Style','radiobutton', ...
   'Units','normalized', ...
   'Position',Checkbox2_Pos, ...
   'Value',1,'String','Polyphase 1 & 2','BackgroundColor',[0.6 0.5 0.5],'callback','radio2');
 

Int_time_Pos=[];
Int_time_Pos=[LeftFrameBorder*0.67 CompBottom*0.11 CompWidth*4 CompHeight*2];
Int_time=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',Int_time_Pos, ...
   'String','1');


Int_time_ApplyPos=[];
Int_time_ApplyPos=[LeftFrameBorder*0.97 CompBottom*0.1 CompWidth*3 CompHeight*4];
Int_time_Apply=uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',Int_time_ApplyPos, ...
   'String','Apply','Callback','Apply_Integration');
Pos3=[];
Pos3=[LeftFrameBorder*0.08 CompBottom*0.91 CompWidth*2 CompHeight*3.2];
Order_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',Pos3, ...
   'String','Order');

Pos4=[];
Pos4=[LeftFrameBorder*0.08 CompBottom*0.85 CompWidth*2 CompHeight*2];
Order=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',Pos4, ...
   'String','16');

Pos5=[];
Pos5=[LeftFrameBorder*0.25 CompBottom*0.91 CompWidth*2 CompHeight*3.2];
Subband_Nb_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',Pos5, ...
   'String','Number of Subbands');

Pos6=[];
Pos6=[LeftFrameBorder*0.25 CompBottom*0.85 CompWidth*2 CompHeight*2];
Subband_Nb=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',Pos6, ...
   'String','32');

Pos7=[];
Pos7=[LeftFrameBorder*0.67 CompBottom*0.91 CompWidth*2 CompHeight*3.2];
Order2_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',Pos7, ...
   'String','Order');

Pos8=[];
Pos8=[LeftFrameBorder*0.67 CompBottom*0.85 CompWidth*2 CompHeight*2];
Order2=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',Pos8, ...
   'String','16');

Pos9=[];
Pos9=[LeftFrameBorder*0.85 CompBottom*0.91 CompWidth*2 CompHeight*3.2];
Subband_Nb_text2=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',Pos9, ...
   'String','Number of Subbands');

Pos10=[];
Pos10=[LeftFrameBorder*0.85 CompBottom*0.85 CompWidth*2 CompHeight*2];
Subband_Nb2=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',Pos10, ...
   'String','32');


Pos11=[];
Pos11=[LeftFrameBorder*0.65 CompBottom*0.51 CompWidth*2.6 CompHeight*3.2];
IS_Quant_text2=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',Pos11, ...
   'String','Input signal Quantization');

Pos12=[];
Pos12=[LeftFrameBorder*0.65 CompBottom*0.45 CompWidth*2.6 CompHeight*2];
IS_Quant2=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',Pos12, ...
   'String','32');

Pos13=[];
Pos13=[LeftFrameBorder*0.83 CompBottom*0.51 CompWidth*2.3 CompHeight*3.2];
Filter_quant_text2=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',Pos13, ...
   'String','Filter quantization');

Pos14=[];
Pos14=[LeftFrameBorder*0.83 CompBottom*0.45 CompWidth*2.3 CompHeight*2];
Filter_quant2=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',Pos14, ...
   'String','14');

Pos15=[];
Pos13=[LeftFrameBorder*0.992 CompBottom*0.51 CompWidth*2.6 CompHeight*3.2];
OS_Quant_text2=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',Pos13, ...
   'String','Output Signal quantization');

Pos16=[];
Pos16=[LeftFrameBorder*0.992 CompBottom*0.45 CompWidth*2.6 CompHeight*2];
OS_Quant2=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',Pos16, ...
   'String','32');


Pos17=[];
Pos17=[LeftFrameBorder*0.06 CompBottom*0.51 CompWidth*2.6 CompHeight*3.2];
IS_Quant1_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',Pos17, ...
   'String','Input signal Quantization');

Pos18=[];
Pos18=[LeftFrameBorder*0.06 CompBottom*0.45 CompWidth*2.6 CompHeight*2];
IS_Quant1=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',Pos18, ...
   'String','32');

Pos19=[];
Pos19=[LeftFrameBorder*0.24 CompBottom*0.51 CompWidth*2.3 CompHeight*3.2];
Filter_quant_text1=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',Pos19, ...
   'String','Filter quantization');

Pos20=[];
Pos20=[LeftFrameBorder*0.24 CompBottom*0.45 CompWidth*2.3 CompHeight*2];
Filter_quant1=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',Pos20, ...
   'String','14');

Pos21=[];
Pos21=[LeftFrameBorder*0.4 CompBottom*0.51 CompWidth*2.6 CompHeight*3.2];
OS_Quant1_text=uicontrol( ...
   'Style','text', ...
   'Units','normalized', ...
   'Position',Pos21, ...
   'String','Output Signal Quantization');

Pos22=[];
Pos22=[LeftFrameBorder*0.4 CompBottom*0.45 CompWidth*2.6 CompHeight*2];
OS_Quant1=uicontrol( ...
   'Style','edit', ...
   'Units','normalized', ...
   'Position',Pos22, ...
   'String','32');



