#ifndef RESPONSIBILITYDISTRIBUTION_H_HEADER_INCLUDED_C0C4EA91
#define RESPONSIBILITYDISTRIBUTION_H_HEADER_INCLUDED_C0C4EA91
#include "TacticalDirective.h"

//##ModelId=3F3B43890167
class ResponsibilityDistribution : public TacticalDirective
{
};



#endif /* RESPONSIBILITYDISTRIBUTION_H_HEADER_INCLUDED_C0C4EA91 */
