#ifndef STRATEGICDIRECTIVE_H_HEADER_INCLUDED_C0C4AF5D
#define STRATEGICDIRECTIVE_H_HEADER_INCLUDED_C0C4AF5D

//##ModelId=3F3B53E30119
class StrategicDirective
{
};



#endif /* STRATEGICDIRECTIVE_H_HEADER_INCLUDED_C0C4AF5D */
