      #ifndef AID_MEQ_h
      #define AID_MEQ_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
      #include "DMI/AtomicID.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_MEQ ();

#ifndef _defined_id_AidCells
#define _defined_id_AidCells 1
const AtomicID AidCells(-1428);                   // from /home/oms/LOFAR/CEP/CPA/MEQ/src/Result.h:35
const int AidCells_int = -1428;
#endif
#ifndef _defined_id_AidChild
#define _defined_id_AidChild 1
const AtomicID AidChild(-1422);                   // from /home/oms/LOFAR/CEP/CPA/MEQ/src/Node.h:33
const int AidChild_int = -1422;
#endif
#ifndef _defined_id_AidChildren
#define _defined_id_AidChildren 1
const AtomicID AidChildren(-1434);                // from /home/oms/LOFAR/CEP/CPA/MEQ/src/Node.h:33
const int AidChildren_int = -1434;
#endif
#ifndef _defined_id_AidClass
#define _defined_id_AidClass 1
const AtomicID AidClass(-1430);                   // from /home/oms/LOFAR/CEP/CPA/MEQ/src/Node.h:33
const int AidClass_int = -1430;
#endif
#ifndef _defined_id_AidDomain
#define _defined_id_AidDomain 1
const AtomicID AidDomain(-1144);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgent.aidlist:5
const int AidDomain_int = -1144;
#endif
#ifndef _defined_id_AidMEQAdd
#define _defined_id_AidMEQAdd 1
const AtomicID AidMEQAdd(-1425);                  // from /home/oms/LOFAR/CEP/CPA/MEQ/src/Add.h:29
const int AidMEQAdd_int = -1425;
#endif
#ifndef _defined_id_AidMEQCos
#define _defined_id_AidMEQCos 1
const AtomicID AidMEQCos(-1427);                  // from /home/oms/LOFAR/CEP/CPA/MEQ/src/Cos.h:29
const int AidMEQCos_int = -1427;
#endif
#ifndef _defined_id_AidMEQNode
#define _defined_id_AidMEQNode 1
const AtomicID AidMEQNode(-1424);                 // from /home/oms/LOFAR/CEP/CPA/MEQ/src/Node.h:34
const int AidMEQNode_int = -1424;
#endif
#ifndef _defined_id_AidName
#define _defined_id_AidName 1
const AtomicID AidName(-1163);                    // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/VisCube/src/VisCube.aidlist:44
const int AidName_int = -1163;
#endif
#ifndef _defined_id_AidNfreq
#define _defined_id_AidNfreq 1
const AtomicID AidNfreq(-1432);                   // from /home/oms/LOFAR/CEP/CPA/MEQ/src/Cells.h:35
const int AidNfreq_int = -1432;
#endif
#ifndef _defined_id_AidNode
#define _defined_id_AidNode 1
const AtomicID AidNode(-1423);                    // from /home/oms/LOFAR/CEP/CPA/MEQ/src/Node.h:33
const int AidNode_int = -1423;
#endif
#ifndef _defined_id_AidParmValues
#define _defined_id_AidParmValues 1
const AtomicID AidParmValues(-1429);              // from /home/oms/LOFAR/CEP/CPA/MEQ/src/Result.h:35
const int AidParmValues_int = -1429;
#endif
#ifndef _defined_id_AidPerturbations
#define _defined_id_AidPerturbations 1
const AtomicID AidPerturbations(-1426);           // from /home/oms/LOFAR/CEP/CPA/MEQ/src/Result.h:35
const int AidPerturbations_int = -1426;
#endif
#ifndef _defined_id_AidSpids
#define _defined_id_AidSpids 1
const AtomicID AidSpids(-1435);                   // from /home/oms/LOFAR/CEP/CPA/MEQ/src/Result.h:35
const int AidSpids_int = -1435;
#endif
#ifndef _defined_id_AidState
#define _defined_id_AidState 1
const AtomicID AidState(-1052);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOPUSSY/src/OCTOPUSSY.aidlist:67
const int AidState_int = -1052;
#endif
#ifndef _defined_id_AidTimeSteps
#define _defined_id_AidTimeSteps 1
const AtomicID AidTimeSteps(-1433);               // from /home/oms/LOFAR/CEP/CPA/MEQ/src/Cells.h:35
const int AidTimeSteps_int = -1433;
#endif
#ifndef _defined_id_AidTimes
#define _defined_id_AidTimes 1
const AtomicID AidTimes(-1431);                   // from /home/oms/LOFAR/CEP/CPA/MEQ/src/Cells.h:35
const int AidTimes_int = -1431;
#endif
#ifndef _defined_id_AidValues
#define _defined_id_AidValues 1
const AtomicID AidValues(-1396);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/Solver/src/Solver.aidlist:72
const int AidValues_int = -1396;
#endif


#endif
