      #ifndef AID_MEQ_h
      #define AID_MEQ_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/gvd/sim/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
      #include "DMI/AtomicID.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_MEQ ();

#ifndef _defined_id_AidCalcDeriv
#define _defined_id_AidCalcDeriv 1
const AtomicID AidCalcDeriv(-1455);               // from /home/gvd/sim/LOFAR/CEP/CPA/PSS4/MEQ/src/Request.h:31
const int AidCalcDeriv_int = -1455;
#endif
#ifndef _defined_id_AidCells
#define _defined_id_AidCells 1
const AtomicID AidCells(-1444);                   // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:1
const int AidCells_int = -1444;
#endif
#ifndef _defined_id_AidChild
#define _defined_id_AidChild 1
const AtomicID AidChild(-1423);                   // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:2
const int AidChild_int = -1423;
#endif
#ifndef _defined_id_AidChildren
#define _defined_id_AidChildren 1
const AtomicID AidChildren(-1431);                // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:3
const int AidChildren_int = -1431;
#endif
#ifndef _defined_id_AidClass
#define _defined_id_AidClass 1
const AtomicID AidClass(-1446);                   // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:4
const int AidClass_int = -1446;
#endif
#ifndef _defined_id_AidDefault
#define _defined_id_AidDefault 1
const AtomicID AidDefault(-1327);                 // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:5
const int AidDefault_int = -1327;
#endif
#ifndef _defined_id_AidDomain
#define _defined_id_AidDomain 1
const AtomicID AidDomain(-1144);                  // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgent.aidlist:5
const int AidDomain_int = -1144;
#endif
#ifndef _defined_id_AidMEQAdd
#define _defined_id_AidMEQAdd 1
const AtomicID AidMEQAdd(-1438);                  // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:7
const int AidMEQAdd_int = -1438;
#endif
#ifndef _defined_id_AidMEQConj
#define _defined_id_AidMEQConj 1
const AtomicID AidMEQConj(-1450);                 // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:8
const int AidMEQConj_int = -1450;
#endif
#ifndef _defined_id_AidMEQCos
#define _defined_id_AidMEQCos 1
const AtomicID AidMEQCos(-1442);                  // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:9
const int AidMEQCos_int = -1442;
#endif
#ifndef _defined_id_AidMEQDivide
#define _defined_id_AidMEQDivide 1
const AtomicID AidMEQDivide(-1440);               // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:10
const int AidMEQDivide_int = -1440;
#endif
#ifndef _defined_id_AidMEQExp
#define _defined_id_AidMEQExp 1
const AtomicID AidMEQExp(-1441);                  // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:11
const int AidMEQExp_int = -1441;
#endif
#ifndef _defined_id_AidMEQMultiply
#define _defined_id_AidMEQMultiply 1
const AtomicID AidMEQMultiply(-1432);             // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:12
const int AidMEQMultiply_int = -1432;
#endif
#ifndef _defined_id_AidMEQNode
#define _defined_id_AidMEQNode 1
const AtomicID AidMEQNode(-1436);                 // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:13
const int AidMEQNode_int = -1436;
#endif
#ifndef _defined_id_AidMEQParmPolcStored
#define _defined_id_AidMEQParmPolcStored 1
const AtomicID AidMEQParmPolcStored(-1437);       // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:14
const int AidMEQParmPolcStored_int = -1437;
#endif
#ifndef _defined_id_AidMEQSin
#define _defined_id_AidMEQSin 1
const AtomicID AidMEQSin(-1435);                  // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:15
const int AidMEQSin_int = -1435;
#endif
#ifndef _defined_id_AidMEQSqr
#define _defined_id_AidMEQSqr 1
const AtomicID AidMEQSqr(-1452);                  // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:16
const int AidMEQSqr_int = -1452;
#endif
#ifndef _defined_id_AidMEQSqrt
#define _defined_id_AidMEQSqrt 1
const AtomicID AidMEQSqrt(-1443);                 // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:17
const int AidMEQSqrt_int = -1443;
#endif
#ifndef _defined_id_AidMEQSubtract
#define _defined_id_AidMEQSubtract 1
const AtomicID AidMEQSubtract(-1433);             // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:18
const int AidMEQSubtract_int = -1433;
#endif
#ifndef _defined_id_AidMEQToComplex
#define _defined_id_AidMEQToComplex 1
const AtomicID AidMEQToComplex(-1434);            // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:19
const int AidMEQToComplex_int = -1434;
#endif
#ifndef _defined_id_AidName
#define _defined_id_AidName 1
const AtomicID AidName(-1163);                    // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/AppAgent/AppAgent/src/AppAgent.aidlist:21
const int AidName_int = -1163;
#endif
#ifndef _defined_id_AidNfreq
#define _defined_id_AidNfreq 1
const AtomicID AidNfreq(-1448);                   // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:21
const int AidNfreq_int = -1448;
#endif
#ifndef _defined_id_AidNode
#define _defined_id_AidNode 1
const AtomicID AidNode(-1427);                    // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:22
const int AidNode_int = -1427;
#endif
#ifndef _defined_id_AidParmValues
#define _defined_id_AidParmValues 1
const AtomicID AidParmValues(-1445);              // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:23
const int AidParmValues_int = -1445;
#endif
#ifndef _defined_id_AidPerturbations
#define _defined_id_AidPerturbations 1
const AtomicID AidPerturbations(-1439);           // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:24
const int AidPerturbations_int = -1439;
#endif
#ifndef _defined_id_AidReqId
#define _defined_id_AidReqId 1
const AtomicID AidReqId(-1457);                   // from /home/gvd/sim/LOFAR/CEP/CPA/PSS4/MEQ/src/Request.h:31
const int AidReqId_int = -1457;
#endif
#ifndef _defined_id_AidResult
#define _defined_id_AidResult 1
const AtomicID AidResult(-1454);                  // from /home/gvd/sim/LOFAR/CEP/CPA/PSS4/MEQ/src/Node.h:33
const int AidResult_int = -1454;
#endif
#ifndef _defined_id_AidRider
#define _defined_id_AidRider 1
const AtomicID AidRider(-1456);                   // from /home/gvd/sim/LOFAR/CEP/CPA/PSS4/MEQ/src/Request.h:31
const int AidRider_int = -1456;
#endif
#ifndef _defined_id_AidSpids
#define _defined_id_AidSpids 1
const AtomicID AidSpids(-1453);                   // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:25
const int AidSpids_int = -1453;
#endif
#ifndef _defined_id_AidState
#define _defined_id_AidState 1
const AtomicID AidState(-1052);                   // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/OCTOPUSSY/src/OCTOPUSSY.aidlist:67
const int AidState_int = -1052;
#endif
#ifndef _defined_id_AidTablename
#define _defined_id_AidTablename 1
const AtomicID AidTablename(-1451);               // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:27
const int AidTablename_int = -1451;
#endif
#ifndef _defined_id_AidTimeSteps
#define _defined_id_AidTimeSteps 1
const AtomicID AidTimeSteps(-1449);               // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:28
const int AidTimeSteps_int = -1449;
#endif
#ifndef _defined_id_AidTimes
#define _defined_id_AidTimes 1
const AtomicID AidTimes(-1447);                   // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:29
const int AidTimes_int = -1447;
#endif
#ifndef _defined_id_AidValues
#define _defined_id_AidValues 1
const AtomicID AidValues(-1396);                  // from /home/gvd/sim/LOFAR/autoconf_share/../CEP/CPA/AppAgent/Solver/src/Solver.aidlist:72
const int AidValues_int = -1396;
#endif


#endif
