      #ifndef AID_MEQ_h
      #define AID_MEQ_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
      #include "DMI/AtomicID.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_MEQ ();

#ifndef _defined_id_AidCalcDeriv
#define _defined_id_AidCalcDeriv 1
const AtomicID AidCalcDeriv(-1480);               // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:1
const int AidCalcDeriv_int = -1480;
#endif
#ifndef _defined_id_AidCells
#define _defined_id_AidCells 1
const AtomicID AidCells(-1478);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:2
const int AidCells_int = -1478;
#endif
#ifndef _defined_id_AidChild
#define _defined_id_AidChild 1
const AtomicID AidChild(-1423);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MeqServer/src/MeqServer.aidlist:3
const int AidChild_int = -1423;
#endif
#ifndef _defined_id_AidChildren
#define _defined_id_AidChildren 1
const AtomicID AidChildren(-1431);                // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MeqServer/src/MeqServer.aidlist:4
const int AidChildren_int = -1431;
#endif
#ifndef _defined_id_AidClass
#define _defined_id_AidClass 1
const AtomicID AidClass(-1481);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:5
const int AidClass_int = -1481;
#endif
#ifndef _defined_id_AidDefault
#define _defined_id_AidDefault 1
const AtomicID AidDefault(-1327);                 // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/OctoAgent/src/OctoAgent.aidlist:2
const int AidDefault_int = -1327;
#endif
#ifndef _defined_id_AidDomain
#define _defined_id_AidDomain 1
const AtomicID AidDomain(-1144);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgent.aidlist:5
const int AidDomain_int = -1144;
#endif
#ifndef _defined_id_AidId
#define _defined_id_AidId 1
const AtomicID AidId(-1457);                      // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MeqServer/src/MeqServer.aidlist:14
const int AidId_int = -1457;
#endif
#ifndef _defined_id_AidMEQAdd
#define _defined_id_AidMEQAdd 1
const AtomicID AidMEQAdd(-1472);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:8
const int AidMEQAdd_int = -1472;
#endif
#ifndef _defined_id_AidMEQConj
#define _defined_id_AidMEQConj 1
const AtomicID AidMEQConj(-1487);                 // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:9
const int AidMEQConj_int = -1487;
#endif
#ifndef _defined_id_AidMEQCos
#define _defined_id_AidMEQCos 1
const AtomicID AidMEQCos(-1476);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:10
const int AidMEQCos_int = -1476;
#endif
#ifndef _defined_id_AidMEQDivide
#define _defined_id_AidMEQDivide 1
const AtomicID AidMEQDivide(-1474);               // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:11
const int AidMEQDivide_int = -1474;
#endif
#ifndef _defined_id_AidMEQExp
#define _defined_id_AidMEQExp 1
const AtomicID AidMEQExp(-1475);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:12
const int AidMEQExp_int = -1475;
#endif
#ifndef _defined_id_AidMEQFunction
#define _defined_id_AidMEQFunction 1
const AtomicID AidMEQFunction(-1491);             // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:13
const int AidMEQFunction_int = -1491;
#endif
#ifndef _defined_id_AidMEQMultiply
#define _defined_id_AidMEQMultiply 1
const AtomicID AidMEQMultiply(-1466);             // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:14
const int AidMEQMultiply_int = -1466;
#endif
#ifndef _defined_id_AidMEQNode
#define _defined_id_AidMEQNode 1
const AtomicID AidMEQNode(-1470);                 // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:15
const int AidMEQNode_int = -1470;
#endif
#ifndef _defined_id_AidMEQParmPolcStored
#define _defined_id_AidMEQParmPolcStored 1
const AtomicID AidMEQParmPolcStored(-1471);       // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:16
const int AidMEQParmPolcStored_int = -1471;
#endif
#ifndef _defined_id_AidMEQPow
#define _defined_id_AidMEQPow 1
const AtomicID AidMEQPow(-1465);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:17
const int AidMEQPow_int = -1465;
#endif
#ifndef _defined_id_AidMEQSin
#define _defined_id_AidMEQSin 1
const AtomicID AidMEQSin(-1469);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:18
const int AidMEQSin_int = -1469;
#endif
#ifndef _defined_id_AidMEQSqr
#define _defined_id_AidMEQSqr 1
const AtomicID AidMEQSqr(-1489);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:19
const int AidMEQSqr_int = -1489;
#endif
#ifndef _defined_id_AidMEQSqrt
#define _defined_id_AidMEQSqrt 1
const AtomicID AidMEQSqrt(-1477);                 // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:20
const int AidMEQSqrt_int = -1477;
#endif
#ifndef _defined_id_AidMEQSubtract
#define _defined_id_AidMEQSubtract 1
const AtomicID AidMEQSubtract(-1467);             // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:21
const int AidMEQSubtract_int = -1467;
#endif
#ifndef _defined_id_AidMEQToComplex
#define _defined_id_AidMEQToComplex 1
const AtomicID AidMEQToComplex(-1468);            // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:22
const int AidMEQToComplex_int = -1468;
#endif
#ifndef _defined_id_AidName
#define _defined_id_AidName 1
const AtomicID AidName(-1163);                    // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/VisCube/src/VisCube.aidlist:44
const int AidName_int = -1163;
#endif
#ifndef _defined_id_AidNfreq
#define _defined_id_AidNfreq 1
const AtomicID AidNfreq(-1484);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:24
const int AidNfreq_int = -1484;
#endif
#ifndef _defined_id_AidNode
#define _defined_id_AidNode 1
const AtomicID AidNode(-1427);                    // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/MeqServer/src/MeqServer.aidlist:23
const int AidNode_int = -1427;
#endif
#ifndef _defined_id_AidParmValues
#define _defined_id_AidParmValues 1
const AtomicID AidParmValues(-1479);              // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:26
const int AidParmValues_int = -1479;
#endif
#ifndef _defined_id_AidPerturbations
#define _defined_id_AidPerturbations 1
const AtomicID AidPerturbations(-1473);           // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:27
const int AidPerturbations_int = -1473;
#endif
#ifndef _defined_id_AidReqId
#define _defined_id_AidReqId 1
const AtomicID AidReqId(-1486);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:28
const int AidReqId_int = -1486;
#endif
#ifndef _defined_id_AidRequest
#define _defined_id_AidRequest 1
const AtomicID AidRequest(-1351);                 // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/AppAgent/src/AppAgent.aidlist:26
const int AidRequest_int = -1351;
#endif
#ifndef _defined_id_AidResult
#define _defined_id_AidResult 1
const AtomicID AidResult(-1421);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/AppAgent/src/AppAgent.aidlist:27
const int AidResult_int = -1421;
#endif
#ifndef _defined_id_AidRider
#define _defined_id_AidRider 1
const AtomicID AidRider(-1482);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:30
const int AidRider_int = -1482;
#endif
#ifndef _defined_id_AidSpids
#define _defined_id_AidSpids 1
const AtomicID AidSpids(-1490);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:31
const int AidSpids_int = -1490;
#endif
#ifndef _defined_id_AidState
#define _defined_id_AidState 1
const AtomicID AidState(-1052);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOPUSSY/src/OCTOPUSSY.aidlist:67
const int AidState_int = -1052;
#endif
#ifndef _defined_id_AidTablename
#define _defined_id_AidTablename 1
const AtomicID AidTablename(-1488);               // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:33
const int AidTablename_int = -1488;
#endif
#ifndef _defined_id_AidTimeSteps
#define _defined_id_AidTimeSteps 1
const AtomicID AidTimeSteps(-1485);               // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:34
const int AidTimeSteps_int = -1485;
#endif
#ifndef _defined_id_AidTimes
#define _defined_id_AidTimes 1
const AtomicID AidTimes(-1483);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/PSS4/MEQ/src/MEQ.aidlist:35
const int AidTimes_int = -1483;
#endif
#ifndef _defined_id_AidValues
#define _defined_id_AidValues 1
const AtomicID AidValues(-1396);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/Solver/src/Solver.aidlist:72
const int AidValues_int = -1396;
#endif


#endif
