//# Print revision info; generated by autoconf_share/makeversion

#include <MWCommon/Package__Version.h>
#include <Common/Version.h>
#include <iostream>

using namespace LOFAR;

int main (int argc, const char* argv[])
{
  std::string type = "brief";
  if (argc > 1) {
    type = argv[1];
  }
  Version::show<MWCommonVersion> (std::cout, "MWCommon", type);
  return 0;
}
