//# This file was generated by genDBcode v2.0 on Wed Jan 14 16:15:23 CET 2004
//# with the command: genDBcode DH_PL_MessageRecord.map DH_PL_MessageRecord.fun P 
//# from the directory: /home/tanaka/prj/co-0351-1621/LOFAR/CEP/CEPFrame/src/genDH_PL_MessageRecord
//#
//# EDITING THIS FILE MANUALLY IS AT YOUR OWN RISK
//# IT MIGHT BE OVERWRITTEN BY THE NEXT MAKE OF YOUR PROJECT
//#
//# only include this file once
#if !defined(PO_DH_PL_MESSAGERECORD_H)
#define PO_DH_PL_MESSAGERECORD_H

#include "DH_PL_MessageRecord.h"

namespace LOFAR {
	namespace PL {


// The DBRep<DH_PL_MessageRecord> structure is a compilation of the fields
// of the DH_PL_MessageRecord class and the persistency layer. It contains
// all fields that should be stored to the database
template <>
struct DBRep<DH_PL_MessageRecord> {
	ObjectId::oid_t		Oid;
	ObjectId::oid_t		Owner;
	unsigned int		VersionNr;
	int			AppId;
	int			Tag;
	int			SeqNo;
	string			Status;
	int			Size;
	string			TimeStamp;
	string			Type;
	string			Name;
	string			Blob;
};

	} // close namespace PL
}	// close namespace LOFAR

#include "PO_DH_PL_MessageRecord.tcc"	// Include template code

#endif
