#!/usr/bin/env python
#coding: iso-8859-15
#
# Copyright (C) 2015
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id: JobsToSchedule.py 33364 2016-01-21 21:21:12Z mol $
"""
Daemon that listens to OTDB status changes to PRESCHEDULED, requests
the parset of such jobs (+ their predecessors), and posts them on the bus.
"""

from lofar.sas.resourceassignment.RATaskSpecified import RATaskSpecified

if __name__ == "__main__":
    import sys
    from optparse import OptionParser

    # Check the invocation arguments
    parser = OptionParser("%prog -O otdb_bus -B my_bus [options]")
    parser.add_option("-O", "--otdb_bus", dest="otdb_busname", type="string", default="",
                      help="Bus or queue OTDB operates on")
    parser.add_option("-B", "--my_bus", dest="my_busname", type="string", default="",
                      help="Bus or queue we publish resource requests on")
    (options, args) = parser.parse_args()

    if not options.statusbus or not options.parsetbus or not options.busname:
        parser.print_help()
        sys.exit(1)

    with RATaskSpecified("OTDB.TaskSpecified", otdb_busname=options.otdb_busname, my_busname=options.my_busname) as jts:
        waitForInterrupt()

