#!/usr/bin/env python

# addImagingInfo: Python script to add meta info to a CASA image
# Copyright (C) 2012
# ASTRON (Netherlands Institute for Radio Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This file is part of the LOFAR software suite.
# The LOFAR software suite is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The LOFAR software suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with the LOFAR software suite. If not, see <http://www.gnu.org/licenses/>.
#
# $Id: makebeamtables.cc 18133 2011-05-30 13:53:45Z diepen $
#
# @author Ger van Diepen


import lofar.addImagingInfo as addimg


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 6:
        print "Insufficient arguments; run as:"
        print "   addImagingInfo image sourcedb maxbl ms1 ms2 ..."
        print "      image        name of the image"
        print "      sourcedb     name of SourceDB containing the sources found"
        print "      minbl        minimum baseline length (in m) to be written"
        print "                   > 0   always use this value"
        print "                   0     determine from the first MS"
        print "                   < 0   use max(abs(minbl), ms_value)"
        print "      maxbl        same for maximum baseline length"
        print "      ms1 ms2 ...  names of MSs image is made of"
        print "                   the names can be individual arguments or a"
        print "                   comma-separated list of names (or a mix)"
        print "   E.g.,"
        print "      addImagingInfo myimg mysdb 0. 0. ms1,ms2 ms3 ms4,ms5"
        sys.exit(1)
    msNames = []
    minbl = float(sys.argv[3])
    maxbl = float(sys.argv[4])
    for arg in sys.argv[5:]:
        msNames.extend (arg.split(","))
    addimg.addImagingInfo (sys.argv[1], msNames, sys.argv[2], minbl, maxbl);
