#!/bin/bash

# lofar
[ -r ${INSTALLDIR}/lofar/lofarinit.sh ] && source ${INSTALLDIR}/lofar/lofarinit.sh
export PATH PYTHONPATH LD_LIBRARY_PATH LOFARROOT

# qpid
#source ${INSTALLDIR}/qpid/.profile

# lofarsoft
source ${LOFARSOFT}/devel_common/scripts/init.sh
